### ISSUE TITLE
"Learn more" link needs a / prefix

### ISSUE THREAD

**Issue by groovecoder** [mozilla-mobile/mozilla-vpn-client#10]
STR:

1. Open the app
1. Click the "Learn more" link

Expected results:
Open a real "Learn more" page on vpn.mozilla.org

Actual results:
Opens https://fpn.firefox.comlearnmore/

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-191)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been opened in error by the data sync.
