### ISSUE TITLE
this is not a bug, but how to work with what you have developed, the one that have created the README.MD should use ai more or should get more braincells

### ISSUE THREAD

**Issue by fahiid33** [mozilla-mobile/mozilla-vpn-client#10126]
**Describe the bug**

**VPN version:**
  <Please fill this in>

**Affected Platforms:**
  <Please fill this in>

**Prerequisites:**
  <Optional: Any special steps taken not related to the app to trigger the bug>

**Steps to reproduce:**
   <Please fill this in>

**Expected result:**
  <Please fill this in>

**Actual result:**
  <Please fill this in>

**Additional notes:**
  <Optional: Any Screenshots, Videos, Logs>

**Comment by strseb** [comment]
https://www.mozilla.org/en-US/about/governance/policies/participation/
