### ISSUE TITLE
Twin-Devices Are Handled Like One Device

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1013]
"I have registered two LGE LM-G900 smartphones for Mozilla VPN. The app was successfully installed on both devices. However, it seems that the devices in the login directory are not correctly recognised and differentiated. On the smartphones only 3 of 5 devices are displayed, but there should be four.
I can never activate the two smartphones at the same time. "

**Comment by mossroy** [comment]
I face the same issue. We have the same (Android) smartphone model for several members of my family, and only one can use the VPN.

The VN app considers all phones of the same model as the same device, with the same display name. When I disconnect on the app of one, I'm also disconnected from the other phones.
After disconnecting the phones, and reconnecting only one, the vpn works again on it.

I have reported this issue to the support. Their answer was that they were working on it : 

> Thank you for reporting this to us, our engineering team is already working on resolving this duplicate device issue and once we have a solution, you will be notified. Unfortunately, we don't have an exact time for the issue to be resolved, but rest assured that we are doing everything to fix it the fastest way possible.
