### ISSUE TITLE
“X” red banner at sign out from VPN client

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1021]
#### VPN version:
- 2.3.0 (2.202105131130);

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Open VPN app;
2. Sign in to VPN app;
3. Sign out from the VPN app;
4. See the red disconnection banner;

#### Expected result:
- There is a red banner displayed, informing the user that he disconnected.

#### Actual result:
- There is only the end of the banner displayed - “X”.

#### Notes:
- Not reproducing using the last builds on Windows, Android or iOS.
- Might be related with https://github.com/mozilla-mobile/mozilla-vpn-client/issues/780

![image](https://user-images.githubusercontent.com/15685960/118134355-8214b580-b40a-11eb-934d-64c1b38720ff.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on Linux Ubuntu 20.04 while using VPN v. 2.3.0 (2.202105131702);
At sign out the correct/complete red banner is displayed.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been opened in error by the data sync.
