### ISSUE TITLE
Spanish is not present as a language option anymore

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1029]
#### VPN version:
- 2.3.0 (2.202105131703);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;
- The user is signed in the VPN app;

#### Steps to reproduce:
1. Open the VPN app;
2. Go to Settings;
3. Go to Language;
4. Find Español in the language list;

#### Expected result:
- Español should be present in the list;

#### Actual result:
- Español is not found there;

#### Notes:
- Varieties of Español (i.e. Mexico, Argentina) can be found in the list, but they don’t fulfill the same functionality as Español. 

![image](https://user-images.githubusercontent.com/15685960/118285572-45b08a80-b4da-11eb-9257-56b23c11ab61.png)

**Comment by flodolo** [comment]
> Español should be present in the list;

Why should it be present? There's no requirement on supported languages beyond French and German, and Spanish (es-ES) was never requested by the community.

**Comment by ValentinaPC** [comment]
@flodolo I was just assuming that Spanish was the most "important" (because it is es-ES) and all the rest are dialects. Was just an assumption.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 builds across platforms.
The es-ES language is present.
![image](https://user-images.githubusercontent.com/15685960/126787578-b2768ed6-4e5f-4aa7-a820-02db007ee7b6.png)
