### ISSUE TITLE
Clicking on the “Get Help” link does nothing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1030]
#### VPN version:
- 2.3.0 (2.202105131703);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;
- The user is signed in the VPN app;

#### Steps to reproduce:
1. Open the VPN app;
2. Go to Settings;
3. Scroll down to the bottom of the app;
4. Click on the “Get Help” link;

#### Expected result:
- The user should be brought to the “Get Help’ section;

#### Actual result:
- Clicking on the “Get Help” link does nothing.;

#### Notes:
- The link was working in the previous build (from May 13);
- The "Get Help" link from "Get Started" screen is working;

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN stage build (2.202105180844) while using Windows 10.
Clicking on the “Get Help” link brings up the respective page.
![VPN gethelp postfix](https://user-images.githubusercontent.com/15685960/118766660-66cffd00-b885-11eb-83ea-a88f794920ed.gif)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
