### ISSUE TITLE
Small overlay passing the right margin of the window

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1046]
#### **Affected versions:**
* 2.3.0 (2.202105180844);

**Affected Platforms:**

* Windows 10;

**Prerequisites:**

* Have a FxA account with an active subscription for Mozilla VPN;
* Have VPN installed;

#### **Steps to reproduce:**
1. Open the VPN app;
1. Observe the right side of the app window;

**Expected result:**

* No display issues;

#### **Actual result:**
* There is a small overlay passed the right margin of the window;

![width=200,height=183](https://user-images.githubusercontent.com/15685441/118639556-b7414f00-b7e0-11eb-926b-f21328f2ec48.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-52)

**Comment by lesleyjanenorton** [comment]
Thanks @ValentinaPC! Is this happening on an external display?

**Comment by madalincm** [comment]
> Thanks @ValentinaPC! Is this happening on an external display?

Hello! I am reproducing this when the vpn app is opened on a second monitor (not the one from the laptop)

**Comment by ValentinaPC** [comment]
Will this go out with 2.4? Thanks!

**Comment by lesleyjanenorton** [comment]
@ValentinaPC  @madalincm I'm not longer able to reproduce this on Windows. Are you still seeing this?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Tried to reproduce the issue on Mozilla VPN 2.7.0 (2.202112131208) and it is no longer reproducible.

!image-20211215-124207.png|width=410,height=591!

Closing the ticket and we will reopen in case the issue reappears.

Thank you

CC: Madalin Cotetiu Valentina Virlics
