### ISSUE TITLE
Error message displayed in the last step of the installation process

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1047]
#### Affected versions:
- 2.3.0 (2.202105180844);
 
#### Affected Platforms:
- MacOS 10.15.7

#### Steps to reproduce:
1. Run the latest MacOS staging package to install Mozilla VPN;
2. Continue the installation flow until the last step; 
 
#### Expected result:
- No errors are displayed;

#### Actual result:
- The app is installed but an installation failed message is displayed:

![Screenshot 2021-05-18 at 14 15 35](https://user-images.githubusercontent.com/15685441/118642340-e60cf480-b7e3-11eb-8937-69c8451828d1.png)

**Comment by ValentinaPC** [comment]
Verified this as fixed on Mac OS VPN build 2.3.0 (2.202105201517)
No errors displayed during app installation.
![Screenshot 2021-05-21 at 13 08 08](https://user-images.githubusercontent.com/15685960/119127427-fd92ea00-ba3c-11eb-958c-fb51f9d62cc7.png)
