### ISSUE TITLE
Issues at sign in for the VPN client accross platforms

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1049]
#### VPN version:
- stage build 2.3.0;

#### Affected Platforms:
- iOS 14.4;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Open VPN app;
2. Tap the “Get Started” 

#### Expected result:
- User is redirected to the fxa-stage page to log in.

#### Actual result:
- An error is displayed.

#### Notes:
- this is happening also on Android and Linux but there are different errors displayed.
- attaching logs from Windows;

![20210518_135155](https://user-images.githubusercontent.com/15685960/118645695-eb6c3e00-b7e7-11eb-9f95-a9cd544d814e.jpg)

https://user-images.githubusercontent.com/15685960/118645859-25d5db00-b7e8-11eb-909e-a2db6766e757.mp4

![Screenshot from 2021-05-18 14-16-37 (1)](https://user-images.githubusercontent.com/15685960/118645865-27070800-b7e8-11eb-8676-65c7697c758d.png)

[mozillavpn-2021-5-18.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6501367/mozillavpn-2021-5-18.txt)

**Comment by bakulf** [comment]
This should be fixed now. Can you please retry?

**Comment by ValentinaPC** [comment]
Verified as fixed on all platforms mentioned above.
User ca sign in via VPN app.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
