### ISSUE TITLE
In app survey - Rotating surveys

### ISSUE THREAD

**Issue by dianahorn** [mozilla-mobile/mozilla-vpn-client#1053]
UXR, PM, and Marketing to determine the list of surveys to rotate

The surveys are triggered in 2 ways:
- Give Feeback option in the Client Settings
- Banner in the Client

We have full control of what the link points to because the surveys are managed by the guardian-website component. Their URLs are not written in the client. 

We need to update the surveys (current surveys are noted in the working document linked below).

Rotate the survey link between: 
- Usability Mozilla [VPN SUPR-Q](https://docs.google.com/document/d/19I0FNmuxNwq_xZNWhKAHi-AdPyKCtfZDEwiEmiBnVnw/edit?usp=sharing)
- Marketing
- Support
- Future Roadmap
- New Customer (Day 7)

[Working document](https://docs.google.com/document/d/1Urcxqbzp_yujQa7Obh-_RaXpqtVsKlvqC9ifrAbUOTk/edit?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-53)

**Comment by dianahorn** [comment]
Brian and I are working on a single localized survey for this release. We will update this ticket when it is ready. 

In the meantime, keep the current surveys links running until we have the updated survey link. 

I am creating the survey today 5/19. Brian submit for translation/localization on Thursday, 5/20.

**Comment by jess-cook03** [comment]
@bakulf @rbillings 
I wanted to make sure you both have seen this update ^^^
cc @bfyee

**Comment by dianahorn** [comment]
The following two surveys have been created for the In App Survey and Give Feedback:

Mac, Window, Linux: 
- [Mozilla VPN - Customer Benchmarks - Q2'21](https://survey.alchemer.com/collab/6332395/Mozilla-VPN-SUPRQ-Q2-21-Draft)

iOS and Andriod
- [Mozilla VPN - Customer Benchmarks - Mobile - Q2'21](https://survey.alchemer.com/collab/6353593/Mozilla-VPN-Customer-Benchmarks-Mobile-Q2-21)

@bfyee to submit the surveys to be localized and

Once we have the translations are uploaded a final URL will be published.

**Comment by ValentinaPC** [comment]
Verified above links and in both of them we list "Chromebook" as an OS supported by our VPN - but is not yet.
![image](https://user-images.githubusercontent.com/15685960/119088685-ba6f5180-ba11-11eb-986b-fc4966c4c049.png).
Maybe we should consider hiding it for now.

**Comment by dianahorn** [comment]
@ValentinaPC @bfyee I removed Chromebook from the surveys

**Comment by jess-cook03** [comment]
@lesleyjanenorton can we confirm that this will be solved/go out in v2.5? The changes that needed to be made re: @dianahorn follow up on slack ??? Thanks!

**Comment by lesleyjanenorton** [comment]
Closing this since I refiled it in the Guardian repo https://github.com/mozilla-services/guardian-website/issues/1255 on 07/29. 

@jess-cook03 I just removed myself from the assignee list as this will likely need to be done with someone more familiar with the Guardian codebase.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/11 . Changing it back to Done.

Thank you.
