### ISSUE TITLE
"Data collection and use" screen is displayed either before or after authentication

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1055]
#### VPN version:
* 2.3.0 (2.202105180844);

#### Affected Platforms:
* Windows 10;

#### Prerequisites:
* Have one FxA account with subscription;

#### Steps to reproduce:
1. Open the VPN app;
1. Click on “Get Started” and sign in with the FxA account;
1. Sign out of the app;
1. Repeat steps 2 and 3;
1. Observe the “Data collection and use” page;

#### Expected result:
The page should appear after clicking on the “Get Started” button and before being redirected to the sign in page in the browser;

#### Actual result:
The page doesn’t always appear at the right step, but randomly appears after signing in;

#### Notes:
-not reproducing each time;

* might be related to allow/not allow options (form Settings);

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-54)
┆author: Data Sync

**Comment by ValentinaPC** [comment]
Was able to reproduce this on Android also.
Attaching logs.
[p3EyHyrx.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6508362/p3EyHyrx.txt)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Can we close this issue? It seems to be fixed.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed while using the last 2.11 Mozilla VPN builds across platforms.

The data collection screen is always displayed after log in.
