### ISSUE TITLE
[Intermitent] Connection information screen does not displayed the location IP

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1062]
#### VPN version:
- 2.3.0 (2.202105190913);
- 2.3.0 (2.202105190912);

#### Affected Platforms:
- Windows 10, Linux Ubuntu 20.04, Android 10;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Install the VPN app;
2. Open the VPN app;
3. Turn ON the VPN;
4. Enter the Connection Information screen;
5. Observe the IP at the top of the page;

#### Expected result:
- There is a valid IP displayed (i.e. “IP:94.198.43.90”);

#### Actual result:
- There is an invalid IP displayed (i.e. “IP:2a00:1dc0:2925:10::a01e”);

#### Notes:
- Does not reproduce every time, and sometimes it appears randomly without a clear cause, therefore it might need repeating the steps until it happens;
![Screenshot_20210524-154320](https://user-images.githubusercontent.com/15685960/119349458-de979080-bca6-11eb-8cab-34eb888933e7.png)

**Comment by bakulf** [comment]
“IP:2a00:1dc0:2925:10::a01e” this is a valid IPv6 address. This bug is invalid. But there is a underlying question: do we want to show ipv4 addresses only or even ipv6 ones?
I wrote a PR that retrieves ipv4 and ipv6 addresses. Only ipv4 is shown for now but we should show both. See #1095.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 builds across platforms.
Both IPv4 and IPv6 are displayed in CI.
![image](https://user-images.githubusercontent.com/15685960/126786565-1f944b2e-2c4b-46fd-ab89-45df0b53bf99.png)
