### ISSUE TITLE
Captive portal not working on MacOS

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1066]
#### Affected versions:
- 2.3.0 (2.202105181120);
 
#### Affected Platforms:
- MacOS 10.15.7;

 
#### Prerequisites:
- Have a FxA account with an active subscription for Mozilla VPN;
- Have VPN installed;

#### Steps to reproduce:
1. Connect to a regular wifi network (it should not have captive protal set up on this network);
2. Turn on the VPN; 
3. While VPN is on connect to a network that is using captive portal;
 
#### Expected result:
- The captive portal notification is displayed;

#### Actual result:
- The notification is not displayed. The No signal label is displayed inside the vpn app;

#### Logs:
[macosLogs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6513525/macosLogs.txt)

**Comment by strseb** [comment]
Hello! Looking at the logs, the ping tools only report success e.g:
```
[20.05.2021 09:41:39.315] (macos|networking - MacOSPingSendWorker) MacOSPingSendWorker - sending ping to: 10.64.0.1 from: 10.64.76.143
[20.05.2021 09:41:39.315] (macos|networking - MacOSPingSendWorker) Ping sent
[20.05.2021 09:41:39.358] (macos|networking - MacOSPingSendWorker) Ping reply received
[20.05.2021 09:41:39.358] (networking - PingSender) PingSender - Ping Succeeded 
```
Ping Succeeded in this case means that the vpn connection is working and not blocked, which means there is no reason to look out for a captive portal. Maybe the test device is still logged into the portal?

**Comment by punster-moz** [comment]
Would it possible the router block on UDP ?

**Comment by strseb** [comment]
It's unlikely that this router (at least for this logging-session) was blocking UDP traffic. As the PingSendWorker was able to send pings through the wireguard tunnel (which uses udp) to mullvad and got a response.

**Comment by ValentinaPC** [comment]
We used the same router on Windows, and Captive Portal worked as expected.

**Comment by strseb** [comment]
@ValentinaPC @madalincm - Is it possible to recheck this, and again post the logs for me :) ?
Because from the current set of logs this looks fine to me, as in from what i can read there shouldn't have been the captive portal prompt.

**Comment by ValentinaPC** [comment]
Rechecked above scenario while using the last VPN build (2.202105241233) on Mac OS 10.15.
The following things happen:
1. VPN ON - Captive Portal checked - connected to a network with CP -> CP notification is displayed -> click on the notification -> nothing happens at click; (this might happen because the VPN does not finalize connection until the user clicks on the notification)
2. VPN ON - Captive Portal checked - connected to a network with CP -> CP notification is displayed -> click on the notification -> VPN is turned OFF - nothing happens after;
Attaching logs after both actions.

[mozillavpn-2021-5-24_2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6532744/mozillavpn-2021-5-24_2.txt)

**Comment by strseb** [comment]
Thank you for the logs! So i've created a PR to solve Sub-Issue nr 1. 

Sadly for the Noted issue Nr 2 there is nothing we can do here. Once the Tunnel has Turned-Off, we rely that the Operating System itself finds the Captive Portal. We can't trigger this search by ourselves (at least on mac) - so for now this is probably a wontfix :(

**Comment by ValentinaPC** [comment]
Verified this on Mac OS 10.15 using the VPN build 2.3.0 (2.202105260933)

The following things happen:
- VPN ON (with CP on) -> connect to a network with captive portal -> first notification is shown -> click on the notification -> VPN is turned OFF -> disconnect from the captive portal network -> reconnect to the captive portal network (this time VPN is already off) -> second notification is shown -> click on the notification -> VPN is turned ON.

Not sure if this is the correct behavior, @strseb @bakulf what do you think?

**Comment by bakulf** [comment]
Yes. For 2.3 sometimes, mac is unable to detect the captive-portal by itself. We have ideas about what we can do more for 2.4.
Thank you for verifying this issue!
