### ISSUE TITLE
Layout issues on mobile while switching from landscape to portrait mode

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1067]
#### VPN version:
* 2.3.0 (16214150);

#### Affected Platforms:
* Android 10; (Google Pixel 4)

#### Prerequisites:
* Have one FxA account with subscription;
* Use the mobile device in landscape mode;

#### Steps to reproduce:
1. Open VPN app;
1. Tap the “Get Started” 
1. Sign in successfully;
1. Switch device view back to portrait;

#### Expected result:
* There are no layout issues in the activation VPN screen.

#### Actual result:
* There are some layout issues in the activation VPN screen.

#### Notes:
* Switching back and forth between landscape and portrait either triggers or not the layout issue.
* The Settings page is incomplete in landscape mode.
![Screenshot](https://user-images.githubusercontent.com/15685960/118943488-576fb300-b95c-11eb-8c32-1eba4f93228d.png)UNITO-UNDERSCORE!20210520-105008!
![Screenshot](https://user-images.githubusercontent.com/15685960/118943490-58084980-b95c-11eb-889d-3c11cc52b147.png)UNITO-UNDERSCORE!20210520-095011!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-55)

**Comment by lesleyjanenorton** [comment]
I think the fix here is actually to restrict landscape mode on Android devices since we don't support landscape mode on iPhones. @jess-cook03 what do you think?
