### ISSUE TITLE
IP address is not changed at server location switch

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1069]
#### VPN version:
- 2.3.0 (16214150);

#### Affected Platforms:
- Android 10; (Google Pixel 4)
- Android 11; (Samsung S10)

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Open VPN app and turn it on;
2. Check device IP address;
3. Tap “Select location” and switch the location;
4. Check device IP address;

#### Expected result:
- The IP address of the new location is displayed.

#### Actual result:
- The old location IP address is displayed.

#### Notes:
- this gets fixed if we turn OFF/ON the VPN.
- not reproducing on iOS;

**Comment by bakulf** [comment]
@ValentinaPC  Was the IPv6 on or off? And the IP shown is in v4 or v6?

**Comment by ValentinaPC** [comment]
So, the IPv6 was ON.
The following occur:
- IPv6 ON => Connection info screen displays the IPv4;
- IPv6 OFF => Connection info screen displays the IPv6;

**Comment by ValentinaPC** [comment]
Re-verified this on the last build received (2.3.0-162185200)
The IPv4 of the location before the switch is displayed in both VPN app or in a specific web page. (IP address one)

**Comment by ValentinaPC** [comment]
Verified this as fixed on Android 10 while using the VPN build 2.3.0 (16218860).
The correct IP is displayed for the selected location. (no matter if ipv6 is checked or not)
