### ISSUE TITLE
Telemetry screen scrolling a bit redundant

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1070]
#### VPN version:
- 2.3.0 (2.202105191459);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have the app installed on the machine;

#### Steps to reproduce:
1. Open the app;
2. Click on the “Get started” blue button;
3. Scroll up and down in the Telemetry page;

#### Expected result:
- The page should fit in the app screen;

#### Actual result:
- The scrolling happens as there is half of a line that’s not displayed in the initial position of the page;

#### Notes:
- The page doesn’t contain that much content as to need this much scrolling, instead it just needs a bit of repositioning. A user presented with the page correctly fitted will take in the information easier;
![telemetrry scroll](https://user-images.githubusercontent.com/15685960/118956918-b63b2980-b968-11eb-8449-b23529d3121e.png)

**Comment by jess-cook03** [comment]
@lesleyjanenorton @ValentinaPC 
This is expected with the design -- scrolling is ok -- with the amount of text + space etc we need to clearly communicate I think its fine -- plus this design being cross platform and different devices (mobile) sometimes it will scroll and other times it won't. 
I would mark this as complete/ OK and no further action on this for now.
