### ISSUE TITLE
qrc:/ui/settings/ViewSettingsMenu.qml:42:5: QML VPNPanel: Binding loop detected for property "height" (ViewSettingsMenu.qml:42)

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1073]
It could be that this issue has already been fixed. I found this in a log sent by a user.

**Comment by lesleyjanenorton** [comment]
Closing as I'm fairly certain this has been fixed. I don't _think_ this would be device specific but just in case, do you recall what kind of device they were on?
