### ISSUE TITLE
[L10n] Incomplete locatization issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1079]
#### VPN version:
- 2.3.0 (2.202105201515);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;
- Have the VPN app language set to French;

#### Steps to reproduce:
1. Open the VPN app;
2. Click on the “Démarrer” blue button;
3. Observe the Telemetry page;

#### Expected result:
- The Telemetry page should be translated into French;

#### Actual result:
- The Telemetry page is partially translated to French, only the title being in French;

#### Notes:
- Reproduces in other French dialects as well;
![telemetry french 1 0](https://user-images.githubusercontent.com/15685960/119115025-5fe4ee00-ba2f-11eb-8e8f-4395b74cfdb0.png)

**Comment by ValentinaPC** [comment]
Survey banner not translated in all VPN languages. See screenshot below.
![image](https://user-images.githubusercontent.com/15685960/119115565-fb765e80-ba2f-11eb-9d1b-b473791526e8.png)

**Comment by bakulf** [comment]
I close this bug. Let's open a new one for 2.4 and 2.3.2 if needed.
