### ISSUE TITLE
System language feature does not work on Mac

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1081]
#### VPN version:
- 2.3.0 (2.202105201517);

#### Affected Platforms:
- Mac OS 10.15;

#### Prerequisites:
- Have one FxA account with subscription;
- Have the system language set to French or German;
- Have the system language option inside the VPN app, turned on;

#### Steps to reproduce:
1. Open VPN app and turn it ON;
2. Check app language;

#### Expected result:
- VPN uses system language.

#### Actual result:
- The VPN is in English.

#### Notes:
- used French and German (no dialects);
![Bildschirmfoto 2021-05-21 um 15 45 49](https://user-images.githubusercontent.com/15685960/119139579-dabc0200-ba4b-11eb-8e7e-0c759be65bc2.png)
![Bildschirmfoto 2021-05-21 um 15 48 14](https://user-images.githubusercontent.com/15685960/119139817-1e167080-ba4c-11eb-8621-adaec42ade10.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on Mac OS 10.15 using the last VPN build (2.202105230622).
System language VPN feature works as expected.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
