### ISSUE TITLE
“Unable to connect Try Again” red banner always appears when opening the app with the VPN off

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1082]
#### VPN version:
- 2.3.0 (2.202105201515);

#### Affected Platforms:
- across platform;

#### Prerequisites:
- Have one FxA account with subscription;
- The user is signed in the VPN app;
- The VPN app is closed;

#### Steps to reproduce:
1. Open the app;
2. Wait for 13-14 seconds;
3. Observe the activation page of the VPN app;

#### Expected result:
- Everything is in order;

#### Actual result:
- A confusing red banner always appears after 13-14 seconds with the text “Unable to connect Try Again” in the top part of the VPN app;

#### Notes:
- Reproducible 5/5;
- Doesn’t break anything, but might confuse the user;
![image](https://user-images.githubusercontent.com/15685960/119142367-16a49680-ba4f-11eb-880a-e2672853adf5.png)

**Comment by bakulf** [comment]
Can you provide a log please?

**Comment by ValentinaPC** [comment]
[mozillavpn-2021-5-21.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6523204/mozillavpn-2021-5-21.txt)

**Comment by bakulf** [comment]
Thanks! Fixed!

**Comment by ValentinaPC** [comment]
Verified this issue while using Windows 10/Mac OS and Android 10 and the latest VPN build (2.202105230619).
There is no red banner appearing.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
