### ISSUE TITLE
[macOS] cmd+w completely quits the app

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#1086]
Running the last staging app on macOS (`2.3.0 (2.202105211512)`): closing the window with my mouse keeps the app running, but pressing cmd+W completely quits, while it should only close the window.

**Comment by bakulf** [comment]
Let's bring this topic at the next design meeting. We should also check the UI/UX apple guide-line to see if they suggest something better.

**Comment by jess-cook03** [comment]
@peterbenvenuto Maybe this is something you can look into? I would imagine this is a minor bug like tweak on our end -- could we see what the best treatment is here for macOS

**Comment by peterbenvenuto** [comment]
@jess-cook03 @bakulf According to [Apple Support](https://support.apple.com/en-us/HT201236) Cmd-W should only close the front window, but it should stay active and running. Cmd - Q should disconnect and quit the app (which is currently already does).
