### ISSUE TITLE
[macOS] Mozilla VPN menu is not localized

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#1087]
<img width="251" alt="Schermata 2021-05-21 alle 17 55 59" src="https://user-images.githubusercontent.com/3644868/119165493-d26cc280-ba5d-11eb-83b3-496425522871.png">

The other two menus are correctly localized.

**Comment by bakulf** [comment]
That menu cannot be localized by the app because it's "owned" by the operative system. If you change language, at the system level, you should see that menu in the selected language.

**Comment by flodolo** [comment]
> That menu cannot be localized by the app because it's "owned" by the operative system. If you change language, at the system level, you should see that menu in the selected language.

That is incorrect, take a look at Firefox

<img width="263" alt="Schermata 2021-05-23 alle 10 15 32" src="https://user-images.githubusercontent.com/3644868/119253103-dad51280-bbaf-11eb-90cf-20fe32962cfd.png">

**Comment by flodolo** [comment]
Here's the only thing I've found about it (apparently translations would come from existing qt packages)
https://doc.qt.io/qt-5/macos-issues.html#translating-the-application-menu-and-native-dialogs

**Comment by bfyee** [comment]
Agree that app menus should also be localized.  As a premium product offered in multiple languages,  we should do what we can to ensure that users feel like Mozilla VPN was built for them.

**Comment by flodolo** [comment]
@bakulf 
I'm testing 2.4.0 (2.202107201556) but it still doesn't look localized. Is it expected?

**Comment by bakulf** [comment]
Even after a restart of the app?

**Comment by flodolo** [comment]
> Even after a restart of the app?

Yes, it's always in English. I tried also switching from use system language and pick another one (Spanish), but that doesn't change. Note that this is the staging version, but I don't think that's relevant.

**Comment by flodolo** [comment]
For what it's worth, I see a file in `Contents/Resources/it.lproj/locversion.plist`, for example

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>LprojCompatibleVersion</key>
    <string>123</string>
    <key>LprojLocale</key>
    <string>it</string>
    <key>LprojRevisionLevel</key>
    <string>1</string>
    <key>LprojVersion</key>
    <string>123</string>
</dict>
</plist>
```
