### ISSUE TITLE
Show both ipv4 and ipv6 addresses in the connection info

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1095]
If ipv6 is enabled, the device should/could have 2 IP addresses. We should show them both in the connection-info view.
Right now we show only the IPv4 one.

**Comment by jess-cook03** [comment]
@lesleyjanenorton (myself) -- + team can take a look at this for v2.4
^ can you provide a screenshot of the current treatment and then we can work to refine from there?
- Perhaps we can address the data/graph screen while we look at this design?
- Also look at the settings for this as well
- Also user friendly copy to help them understand the value of this info

**Comment by bakulf** [comment]
Done!
