### ISSUE TITLE
UI issue for IPv6 while in CI screen

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1097]
#### VPN version:
- 2.3.0 (2.202105230622)

#### Affected Platforms:
- Android 10;
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have one FxA account with subscription;
- Have the IPv6 option unchecked;

#### Steps to reproduce:
1. Open VPN app;
2. Click “Get Started”;
3. Finalize login;
4. Turn ON VPN;
5. Check CI screen;

#### Expected result:
- There are no display or layout issue while the IPv6 is displayed;

#### Actual result:
- There is a layout issue while IPv6 is displayed;
![image](https://user-images.githubusercontent.com/15685960/119351777-8ada7680-bca9-11eb-844b-98475ebe8d4a.png)

**Comment by bakulf** [comment]
Fixed for 2.4

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 builds, across platforms.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/126783613-9bea3912-f35a-4af6-8bc5-e53385011c9c.png)
