### ISSUE TITLE
active subscribers asked to Re-subscribe on sign-in

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#1116]
When opening the VPN app and trying to sign in, the user enters their Firefox account information that is associated with an active subscription but is redirected to purchase a subscription instead and enter their payment information.

 Device version Samsung Galaxy S20
* FX product Mozilla VPN
* FX version 2.2.0
* Operating systems affected: Android, iOS

**Steps to Reproduce**
1. Download/install Mozilla VPN
2. Open VPN
3. click on "Get started"
4. enter Firefox account email/password in sign in page
5. VPN recognizes info and completes setup

**Actual Results**
- when entering Firefox account email/password the user is directed to payment screen and asked to enter payment information.

**Expected Results**
- After entering fxa information, the VPN is ready to be used and connect

Users affected as of 05/26/2021 - 12
No logs collected as of yet.

**Comment by bakulf** [comment]
it would be great if we can have the email address of their FxA accounts.

**Comment by rbillings** [comment]
Closing as this is moving to the integration repo.

**Comment by birdsarah** [comment]
Moved to https://jira.mozilla.com/browse/PSP-32

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
