### ISSUE TITLE
Unsecured network notifications sent for secured networks

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1121]
#### VPN version:
- 2.3.0 (2.202105270956);

#### Affected Platforms:
- Linux Ubuntu 18.04;

#### Prerequisites:
- Have an FxA account with subscription;
- The user is signed in the VPN app;
- The VPN is OFF;
- Have the “Unsecured network alert”, from the VPN “Notifications”, turned on;

#### Steps to reproduce:
1. Connect to a secured network;
2. Observe the notification received;

#### Expected result:
- No notification is received;

#### Actual result:
- The user receives a notification for connecting to an unsecured network;

#### Notes:
- the "Oiegas" network is secured;
- the "one e1001" network is not secured;

[mozillavpn-2021-5-27 (1).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6555224/mozillavpn-2021-5-27.1.txt)

**Comment by mariaberlinger** [comment]
Hello,
This is verified fixed on VPN 2.4.0 (2.202107230654) using Ubuntu 20.04, the user doesn’t receive a notification for connecting to an unsecured network when the network connection is secured.
