### ISSUE TITLE
Clean up SystemTrayHandler

### ISSUE THREAD

**Issue by mbirghan** [mozilla-mobile/mozilla-vpn-client#1123]
Currently the `SystemTrayHandler` handles the system tray and the notification. It would make more sense to handle the notifications in the `SystemTrayNotificatioHandler` which currently only calls functions from `SystemTrayHandler`.

Together with that it would make sense to get rid of the `SystemTrayHandler` for mobile devices since they do not have a system tray but need notifications.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-65)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this using the latest Mozilla VPN 2.6 build on Windows 10, Mac OS and Linux Ubuntu 20.04.

There are a few things that were tracked in https://mozilla-hub.atlassian.net/browse/VPN-1287 ( https://mozilla-hub.atlassian.net/browse/VPN-1287|smart-link ) .

We can mark this as verified.
