### ISSUE TITLE
System tray icon squished when on secondary display

### ISSUE THREAD

**Issue by mbirghan** [mozilla-mobile/mozilla-vpn-client#1134]
On Mac when a display is not the active display the system tray icon gets sqashed. 

![](https://user-images.githubusercontent.com/32091959/120286891-039b8d00-c2bf-11eb-96a6-dd3081fb9b69.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-68)

**Comment by jess-cook03** [comment]
@peterbenvenuto delivered optimized PNGs to @lesleyjanenorton to solve this
✅ marking this as complete from design side for v2.4

**Comment by lesleyjanenorton** [comment]
Unfortunately this is a known Qt bug and not something that can be solved by an image change (although the improved images did fix a number of other issues). Here is the bug report regarding the squishing effect:
https://bugreports.qt.io/browse/QTBUG-88600

Looks like there may be a workaround though!

**Comment by jess-cook03** [comment]
My bad -- keeping this open -- marked 'Done' from Jira from design side apologies --- need to work through this github/jira syncing process....

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Verified this as fixed on Mozilla VPN 2.6.0 (2.202109201913), while using MacOS Big Sur 11.6. 

When the second display is not the active the system tray icon doesn't get  squashed. See the attached screenshot.

!image_2021_09_21T09_03_57_156Z.png|width=348,height=28!
