### ISSUE TITLE
Update via Play Store is not possible if the VPN is ON

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1139]
#### VPN version:
- 2.3.0 (2.16221090)

#### Affected Platforms:
- Android 10;

#### Affected device:
- Google Pixel 4;

#### Prerequisites:
- Have one FxA account with subscription;
- Have 2.2.0 VPN version installed and VPN on;
- Have your account enrolled for beta testing;

#### Steps to reproduce:
1. Search the Mozilla VPN app in the Play Store;
2. Tap the “Update” button for the Mozilla VPN;

#### Expected result:
- The update is made with success. The VPN remains ON after the update.

#### Actual result:
- The update is not made.

#### Notes:
- If we turn OFF the VPN and try the update after, the update is finalized with success.
- Verified on other devices (Samsung Galaxy s20, Android 11) and **update is made with success**, but the **VPN app appears turned OFF after the update**.

**Comment by rbillings** [comment]
Seems like there are 2 issues here- one where the update doesn't happen and the other that it appears off. @ValentinaPC would you please clarify what you mean by "the VPN app appears turned off after the update". It is expected that the VPN would be off after an update, just wasn't sure about appearing off vs being off.

**Comment by rbillings** [comment]
@ValentinaPC would you please comment?

**Comment by ValentinaPC** [comment]
@rbillings sure:
- first thing was: VPN ON -> go to Play Store -> see "Update" button for the Mozilla VPN -> click it -> wait that the app to be updated => nothings happens.
- second thing was: tried the above flow on other device (see notes section from above) and the update was made with success, exept the fact that the VPN app was turned OFF after.
Sorry for any confusion.

Note: I no longer reproduce this. I'll close it and reopen if happens again.
