### ISSUE TITLE
Change the strings in the macos installer

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1146]
Probably this issue is a dup but I would suggest the following:
1. no need for a backup. Nobody knows how to backup data before removing the client...
2. no need to run the app manually. The app starts automatically.

@jess-cook03 can you help here to define new strings?

**Comment by jess-cook03** [comment]
Connect with @chrisrooneys for content :) thanks!

**Comment by jess-cook03** [comment]
This also seems like a duplicate of #781

**Comment by chrisrooneys** [comment]
@bakulf these strings were addressed in #781—do you need anything else from me?

**Comment by jess-cook03** [comment]
Lets close this as its a duplicate of #781 and we have already provided the updates there, thanks!
