### ISSUE TITLE
Consider adding in-app release notes...

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1147]
We should think about the "post-update experience" and consider adding something like in-app release notes to:
- Announce newly added features, explain why they're great, and explain how they help our customers (instead of just adding them silently and hoping customers who've already installed the app just discover them)
- Describe feature improvements and how they help customers
- Possibly provide new feature "guided walking tours" for non-techies (but with great big bail out buttons for people who find these irritating)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-45)

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Final designs for this feature are completed and can be found in this figma file ( https://www.figma.com/file/SjWR5U9aqEiUnmrkuS74O5/What-s-new-Release-notes?node-id=133%3A4471 ). Let Jessica Cook or I know if you have any other questions!

CC Brian Yee Lesley Norton

**Comment by lesleyjanenorton** [comment]
Closing this as done since we took this into consideration and will be moving forward with this feature in 2.5 :)
