### ISSUE TITLE
Can releases be tagged?

### ISSUE THREAD

**Issue by tavianator** [mozilla-mobile/mozilla-vpn-client#1152]
Hi, I'm packaging mozillavpn for the AUR and it would be convenient if the recent releases (2.2, 2.3) were tagged in git.  Right now I'm getting the source from https://launchpad.net/~mozillacorp/+archive/ubuntu/mozillavpn/+packages but I'd prefer to get it from here (or some other upstream source).

**Comment by bakulf** [comment]
Thanks! Done!
