### ISSUE TITLE
Mixed casing in Settings

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#1154]
![Screenshot_20210607-234513.png](https://user-images.githubusercontent.com/17863082/121129652-7db1a180-c7ea-11eb-8765-7ddfd10e7d24.png)

Some sections have sentence casing while others have title casing. This looks a bit weird -- I'd say settle on one and stick with it. :)

I'd suggest sentence casing since it looks more casual/friendly and is used on the bigger platforms (Android, Windows) while title casing is really only a thing on Apple platforms. It's also what Mozilla VPN started with.

**Comment by chrisrooneys** [comment]
@lolrepeatlol thanks for opening this; I prefer sentence casing as well, except for in iOS as you mentioned. I'm discussing with Firefox content design team quickly and then will update on Monday.

**Comment by chrisrooneys** [comment]
@lolrepeatlol just getting to this now, but yes, let's switch these to sentence case. So, it'd read like this:

- Network settings
- Language
- App permissions
- About us
- Give feedback
- Get help
- Privacy & security

**Comment by jess-cook03** [comment]
@lesleyjanenorton @bakulf 
These updated lines have been provided for v2.4 --- can we confirm that this will be changed? or if this won't land until 2.5? Looking for update here, thanks!

**Comment by bakulf** [comment]
@jess-cook03 @chrisrooneys All good! But I have a question: "Get help" is shown in multiple places in the app. Do you want to have lowercase "help" everywhere or just in the settings?

**Comment by jess-cook03** [comment]
@bakulf @chrisrooneys I would say have the lowercase 'help' everywhere
