### ISSUE TITLE
Odd ordering of sections in Settings 

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#1155]
![Screenshot_20210607-234513.png](https://user-images.githubusercontent.com/17863082/121129876-d2551c80-c7ea-11eb-9f94-6d27bba187c7.png)

Maybe it's just me, but I find the order of sections a bit odd here.

I'd personally order it like this:

1. Privacy & security
2. Network settings
3. App permissions
4. Language
5. Get help
6. About us
7. Give feedback

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-42)

**Comment by bakulf** [comment]
@chrisrooneys @jess-cook03 what do you think about this bug? I would like to close/fix it together with #1154

**Comment by jess-cook03** [comment]
@chrisrooneys do you have any thoughts on this?

This is something we ideally can also tackle within our issue #921 ---- however based on looking at competitors and common patterns of ordering app settings UI in various apps I would recommend this:

- Network settings
- Privacy & security 
- App permissions
- Notifications
- Get help
- Language
- Give feedback
- About us

Thoughts?
cc @bakulf

**Comment by flozia** [comment]
Did we already agree on the order of the sections or should this better wait for #921 @jess-cook03?

**Comment by jess-cook03** [comment]
@flozia  I would say we are updating this order and redesigning the settings for v2.5 and I would say lets hold on this change as it will be fullfilled by this issue #921

**Comment by jess-cook03** [comment]
@lesleyjanenorton @flozia Hi there!
This issue will be fullfilled by the completion of #921 --- I wanted to assign and mark labels as such so we make sure this gets collected in v2.5 release.

**Comment by jess-cook03** [comment]
Closing this as it will be solved when completing the issue #921 --- lets continue tracking progress there in that open issue for v2.5 as discussed with @punster-moz

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/11 . Changing it back to Done.

Thank you.
