### ISSUE TITLE
Privacy Nutrition Label in App Store is now incorrect

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#1156]
![Screenshot_20210607-235536.png](https://user-images.githubusercontent.com/17863082/121130639-f1a07980-c7eb-11eb-9db8-2093f668c596.png)

Now that Glean has been added, Mozilla must state that the data is collected in the App Store description in order to continue complying w/ guidelines.

**Comment by bfyee** [comment]
This can only be changed by users with access level:  Account Holder or Admin in appstore connect,  so assuming @MihaiTabara  and team own release_appleagent@mozilla.com ?

**Comment by MihaiTabara** [comment]
@bfyee I can help with this, @bhearsum just showed me how. Let's coordinate privately and tackle it together.

**Comment by MihaiTabara** [comment]
I pinged @bfyee on this, we'll need to do it together as I may need some input while I'm clicking around.

**Comment by MihaiTabara** [comment]
This is now done.
