### ISSUE TITLE
Matrix chat?

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#1157]
Not exactly an issue but it would be nice if Mozilla had a Matrix channel for Mozilla VPN. There's already an official homeserver for the Mozilla community and there are channels like #fx-desktop-community:mozilla.org, so one like #vpn:mozilla.org would be great to have as well.

**Comment by strseb** [comment]
We have #mozilla-vpn:mozilla.org :)

**Comment by lolrepeatlol** [comment]
haha, thanks! not sure if it's just me though, but i can't join :(
