### ISSUE TITLE
Show the selected city when opening the server list

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#116]
A few issues here:
1. Right now, when I open the list of servers, I don't see the selected city by default. Would be great to open the country and show the 'blue' selected city immediately.
2. If the city is not visible because we need to scroll, the app should scroll by default to the right place.

@lesleyjanenorton thoughts?

**Comment by ValentinaPC** [comment]
Verified this on the lastest cross-plat VPN build on Android, Mac OS, iOS and Linux.
When selecting any region except **Australia** => everything woks as expected.
- When selecting Melbourne => we have a cut "Melbourne" option in the servers list.
- When selecting Sydney => the servers list starts from Austria, and Australia is completely hidden.
See screenshots bellow for clarifications. Reopening.
![image](https://user-images.githubusercontent.com/15685960/100873015-5e3c6380-34ab-11eb-98b8-40ca4c5fd505.png)
![image](https://user-images.githubusercontent.com/15685960/100873041-672d3500-34ab-11eb-9d2b-a7f543ebe336.png)

**Comment by lesleyjanenorton** [comment]
Fixed via #388

**Comment by ValentinaPC** [comment]
Verified as fixed on all platforms using the last VPN build.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/103998496-bfd7a800-51a4-11eb-8528-c73bd5d70863.png)
