### ISSUE TITLE
Mozilla VPN uninstall breaks Firefox Browser with vcruntime140.1.dll error

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#1162]
**Description**
Users are unable to use Firefox after uninstalling the Mozilla VPN. Firefox appears but does not respond (does not link to the internet, requests remain unanswered. In the top right corner, a "warning" panel appears which delivers the message "account disconnected". When trying to reinstall Firefox they get an error "impossible to execute the code because vcruntime140_1.dll is not found. reinstalling the program can correct this problem"

**Technical Information**

* Device version Windows 10
* FX product: Firefox browser
* FX version 
* Any other additional info

**Steps to Reproduce**

1. Uninstall Mozilla VPN
2. Open Firefox browser
3. Firefox not responding
4. reinstalling Firefox gives vcruntime error

**Support Info**

Tag: [fxa-browser-blank] 
12 tickets inbound with this issue as of 06/09

**Comment by jr-johnson-support** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1691782
![Firefox_borwser_error](https://user-images.githubusercontent.com/58608126/121363158-4a5f3780-c8fc-11eb-9c4f-34414e8235c7.jpeg)

![Capture_Refus_de_réinstaller_Firefox](https://user-images.githubusercontent.com/58608126/121363091-3ddadf00-c8fc-11eb-9e39-668bcf3b3f19.JPG)

**Comment by rbillings** [comment]
Moving discussion to Firefox.

**Comment by data-sync-user** [comment]
➤ Nma-Sie-Anyene Davenport commented:

Moved the discussion to Firefox group
