### ISSUE TITLE
Linux unsecure-network notification doesn't work

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1176]
In 2.4 (current main branch), I see a notification when connected to a WPA/WPA2 wifi.
@oskirby do you mind taking a look? The fix needs to land to 2.3.1

**Comment by bakulf** [comment]
Fixed!

**Comment by AOiegas** [comment]
Verified this issue while using Ubuntu 18.04 and the latest VPN build.
The problem is no longer reproducing, the notification is not displayed while connecting to a secured network. Also the notifications are shown when connecting to an unsecured network.
