### ISSUE TITLE
VPN cannot be turned ON if we enable the "Always on" feature while app is off

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1179]
#### VPN version:
* 2.3.0 (2.3.1 - 16233300);

#### Affected Platforms:
* Android 10;

#### Prerequisites:
* Have one FxA account with subscription;
* Have the VPN open and OFF;

#### Steps to reproduce:
1. Open the VPN app, but do not turn it ON;
1. Go to device Setting-> VPN-> Mozilla VPN;
1. Enable the “Always on” VPN feature;
1. Go back to VPN and try to turn it ON;

#### Expected result:
* VPN is turned on with success.

#### Actual result:
* The app remains in “Connecting...” state.

#### Notes:
* this does not happen if the VPN is ON while enabling the feature from device settings;
* this does not happen if we swipe kill the app after step 1;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-39)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Verified as fixed on Mozilla VPN 2.6.0 (16321650), while using Android 10. 

The VPN is turned on automatically with success after enabling the “Always on” feature.

Thank you.
