### ISSUE TITLE
Notification/Network settings "VPN must be off" messages are incoherent with the options

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#119]
#### Affected versions:
- 1.202010191546;

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Sign in using the account from prerequisites;
3. Turn on the VPN
4. Go to Settings;
5. Access Notifications/Network settings option;
6. Observe the “VPN must be off...” messages;

#### Expected result:
-  If the options are disabled, the message listed is: “VPN must me off before enabling”;
-  If the options are enabled, the message listed is: “VPN must me off before disabling”;

#### Actual result:
- No matter if the options are enabled or disabled the message is always: “VPN must me off before disabling”;

#### Notes:
- Also, in “Network setting:s the message should be written under each option.
![must](https://user-images.githubusercontent.com/15685960/97414990-5702c280-190d-11eb-8775-9280004d7c01.png)

**Comment by tduzan** [comment]
@bakulf: Does this affect more than Linux?  I see it's labeled cross-platform but the bug report says only Linux is affected.

**Comment by ValentinaPC** [comment]
@tduzan When I've logged the issue, the Android cross-platform build was not available. 
Now, that it is, the issue is also reproducible on Android.
![msg](https://user-images.githubusercontent.com/15685960/99380043-1c6bc480-28d2-11eb-84cb-25ad84d535ec.png)

**Comment by bakulf** [comment]
Yes, this is a cross-platform issue. We need to change the string.

**Comment by lesleyjanenorton** [comment]
What do we think about changing this string to "VPN must be off before changing these settings"

**Comment by jess-cook03** [comment]
@lesleyjanenorton 
@bakulf 
I agree we could use what Lesley mentioned above or even something like:
"VPN must be off in order to edit these settings"
Either way can work!
.... I was trying to get a lesser character count if possible to avoid the message having to be 2 lines vs one

**Comment by ValentinaPC** [comment]
Verified as fixed while using the last cross-plat VPN build on Android 10, Linux, iOS and Mac OS.
The new message is displayed and coherent with the options.
![image](https://user-images.githubusercontent.com/15685960/100980953-baa48f00-354e-11eb-8085-cecb46b9606e.png)
