### ISSUE TITLE
IP leak after an “Always ON” double switch

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1194]
#### VPN version:
- 2.3.1 - 16233300;

#### Affected Platforms:
- Android 11;

#### Affected device:
- Samsung S10;

#### Prerequisites:
- Have one FxA account with subscription;
- Have the “Always on” VPN feature disabled;

#### Steps to reproduce:
1. Open the VPN app;
2. Turn it ON;
3. Swipe kill the app;
4. Go to device Setting-> VPN-> Mozilla VPN;
5. Enable/Disable/Enable the “Always on” VPN feature;
6. Go back to VPN app;
7. Check Connection information screen;
8. See the IP displayed;

#### Expected result:
- The IP displayed is the one corresponding to the connected server.

#### Actual result:
- Real IP is displayed.

#### Notes:
- The issue is fixed if we turn OFF/ON the VPN app.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 build.
The VPN does not show the real IP in CI screen after a "Always on" double switch.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
