### ISSUE TITLE
VPN is unusably slow in VirtualBox guest

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1200]
When running the VPN in a VirtualBox guest VM, the client becomes unusably slow whenever the main view is visible, regardless of whether the VPN is connected or not. A quick examination of the CPU load shows that the VPN client is consuming all of the CPU time available. While switching away from the main view reduces the CPU load to only a few percent.

I suspect that the problem is related to software rendering of the animated rings on a virtual GPU.

My typical testing setup for VirtualBox is to enable 2 cores with 4GB of memory and no CPU execution cap.

![Screenshot from 2021-06-15 08-34-23](https://user-images.githubusercontent.com/7256630/122082820-2ba5e880-cdb5-11eb-9007-f37251bf9424.png)
![Screenshot from 2021-06-15 08-43-23](https://user-images.githubusercontent.com/7256630/122083488-c6062c00-cdb5-11eb-844a-b71b57194c5b.png)

**Comment by strseb** [comment]
That sounds most likely like the rings but they should not consume paint calls when the vpn is off :/

**Comment by oskirby** [comment]
I can explain why the CPU load is high when not connected. I found this while testing the 2.3.1 release builds and it seems that the globe image is using a QML Canvas to produce a gradient effect that wants to eat all the available CPU. This issue was fixed in main by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1108

However, when the VPN is connected, my installation of VirtualBox just isn't fast enough to render the animated rings in realtime.

**Comment by ValentinaPC** [comment]
Verified as fixed while using an Oracle VM with a Linux Hirsute installed on it.
After installing the VPN 2.5 (2.202108180705) seems like only little CPU resources are used while VPN is OFF and around 20% with the app ON.
![image](https://user-images.githubusercontent.com/15685960/129890412-5439f0d2-ba1b-43d1-a8f8-4eb216e0f344.png)
