### ISSUE TITLE
VPN acting up/posix collation implementation?

### ISSUE THREAD

**Issue by Haleymiranda79** [mozilla-mobile/mozilla-vpn-client#1208]
Found this in logs:

Only C and default locale supported with posix collation implementation. (PostgreSQL)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-34)

**Comment by oskirby** [comment]
Would you be able to share the logs with us so we can identify some more information about the platform you are experiencing this issue on?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Dup of VPN-942
