### ISSUE TITLE
[Linux] "Recycle-bin" device removal icon has layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#121]
#### Affected versions:
* 1.202010191546;

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;
* Be connected to VPN on 2 devices;

#### Steps to reproduce:
1. Open the VPN app;
1. Sign in using the account from prerequisites;
1. Go to ”My devices”;
1. Observe the removing recycle-bin icon from the second device;

#### Expected result:
* There are no display or layout issues.

#### Actual result:
* The recycle bin icon is too on the right side.

![rb](https://user-images.githubusercontent.com/15685960/97417355-4142cc80-1910-11eb-8248-29d8dd878331.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-257)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
