### ISSUE TITLE
No signal/unstable connection when the VPN is running more than 10 minutes

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1215]
#### Affected versions:
- Mozilla VPN 2.4.0 (2.202106162202);

#### Affected Platforms:
* Windows 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device.

#### Steps to reproduce:
1. Open Mozilla VPN and login with the account from prerequisite;
2. Select a location and turn on the VPN;
3. Let the VPN running for about 10 minutes;
4. Observe the VPN status in the activation screen.

#### Expected result:
- The screen displays the following text: “Secure and private” and the period of time since the VPN is running. The user is able to navigate on the internet.

#### Actual result:
- A “No Signal/Unstable - Check Connection” message is displayed and the user is not able to navigate on the internet. 

#### Notes:
- Reproducing constantly on WIndows, no matter of the selected location;
- Not reproducing on Mac OS;

#### Logs:
[mozillavpn-2021-6-18.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6676975/mozillavpn-2021-6-18.txt)

**Comment by oskirby** [comment]
Unfortunately, the attached log file doesn't appear to be demonstrating the issue you have described.

**Comment by oskirby** [comment]
With a bit of experimenting, I've been able to get the VPN client into a state where it seems to shows that the connection is unstable, and under the hood it seems that something is going badly with the captive portal notification and the connection health checker. However, I haven't observed any loss of network connectivity through the VPN when this occurs.

My steps to reproduce the issue are as follows:
1. Connect to any server of your choosing.
2. Open www.speedtest.net and run the test to load up your network connection.
3. If the speedtest was successful, and there was no reports of instability. Disconnect the VPN and go back to step 1.
4. Eventually, at some point a connection health ping will get lost which seems to trigger a silent server switch.
5. The silent server switch triggers a captive portal check, which gets stuck in an endless failure loop with `Network error: 99`
 
Some oddities of note:
- I think captive portal detection is broken once the VPN is on. Attempting to ping the captive portal address from a command prompt using `ping 34.107.221.82` just prints out `General failure.`
- The log is full of message about `PingSender - Ping failed` but oddly enough it seems that the connection health checks are generally working and reporting reasonable round trip times.

Attempting the same procedure on the 2.3.0 release shows the same oddities, but the server switch is successful and the errors clear themselves up fairly quickly.

[mozillavpn-connection-unstable.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6681116/mozillavpn-connection-unstable.txt)

**Comment by oskirby** [comment]
The problem seems to begin with the genuine loss of a single ICMP ping, which snowballs into a positive feedback loop. The root of the problem is that the `IcmpSendEcho2Ex()` method will stall the ping worker thread for 10 seconds until a timeout occurs, which is much longer than the length of time it takes for the connection health checker to report a problem. This means that the windows implementation is brittle in the face of packet loss.

If this happens to trigger a server switch, we are likely to loose even more packets during the connection negotiation, which causes the whole cycle to start again.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been opened in error by the data sync.
