### ISSUE TITLE
mozillavpn inside a docker container

### ISSUE THREAD

**Issue by Davidian1024** [mozilla-mobile/mozilla-vpn-client#1218]
Hello,

I wanted to try running mozillavpn inside a docker container.  I got it installed inside an Ubuntu 20.04 container.  But, when I try to run it, it crashed during the part when I think it would try to do the authentication bit.

I decided to try to work around that by generating a ~/.config/mozilla/vpn.moz file outside of the container and then copying that into the container and then running mozillavpn activate.

Running mozillavpn with strace I can see it open the file I copied in, but then it gets hung.

Any suggestions?

Thanks,
Dave

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-32)

**Comment by bakulf** [comment]
Can you tell us more about your container? Can you share a Dockerfile? I would like to reproduce the issue locally.

mozillavpn implements a CLI. Does it work for you? See https://github.com/mozilla-mobile/mozilla-vpn-client/wiki/Command-line-interface

**Comment by Davidian1024** [comment]
Sure, here's the Dockerfile I've been using:

`
FROM ubuntu

RUN apt-get update

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:mozillacorp/mozillavpn
RUN apt-get update
RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
RUN apt-get install -y mozillavpn
`

Not sure what more there is to tell you about it.  Other than that running mozillavpn locally does work.  That's how I created that vpn.moz file that I copied into the container.

I've tried running it with and without that externally generated vpn.moz file.  If I try to do the activate from inside the container mozillavpn will crash with a core dump.  That's what made me think to try using that file.

**Comment by devanubis** [comment]
I've been trying to use the mozillavpn cli in a container as well, with the hope of routing some other containers and host traffic through it.

[devanubis/mozilla-vpn-docker](https://github.com/devanubis/mozilla-vpn-docker)

So far not much success.

I've tried:

## `ubuntu:focal` with versions (from the PPA):
###   `2.7.0` 
*   `login -p` ✅
    *   Able to log in with my mozilla account credentials, new ubuntu device shows up on my android phone ✅
*   `servers` ✅
*   `select <server>` ✅
*   `status` ✅
    *   Shows selected server, shows other devices, shows this device, shows
*   `device` ✅
    *   Successfully removed a device (another previous docker session not that it matters)
*   `activate` ❌ 
    *   Doesn't appear to actually connect, container shows no outbound traffic and external IP address from inside the container is unchanged.
```
[06.05.2022 22:37:38.303] Info: (main - Command) MozillaVPN 2.7.0
[06.05.2022 22:37:38.303] Info: (main - Command) User-Agent: MozillaVPN/2.7.0 (sys:ubuntu 20.04)
```
* `linuxdaemon` ❌
```
root@51481e674579:/# mozillavpn linuxdaemon   
[06.05.2022 22:45:58.952] Info: (main - Command) MozillaVPN 2.7.0
[06.05.2022 22:45:58.952] Info: (main - Command) User-Agent: MozillaVPN/2.7.0 (sys:ubuntu 20.04)
[06.05.2022 22:45:58.957] Error: (linux - PidTracker) Failed to send netlink message: Connection refused
[06.05.2022 22:45:58.957] Error: (linux - main) Connection failed - name: org.freedesktop.DBus.Error.Disconnected message: Not connected to D-Bus server
```
### `2.8.0`
*   `login -p` ❌
```
root@bbf4568a7677:/# mozillavpn -v
mozillavpn 2.8.0
root@bbf4568a7677:/# mozillavpn login -p
[06.05.2022 23:52:29.017] Info: (main - Command) MozillaVPN 2.8.0
[06.05.2022 23:52:29.018] Info: (main - Command) User-Agent: MozillaVPN/2.8.0 (sys:ubuntu 20.04)
[06.05.2022 23:52:29.021] Warning: could not connect to display 
[06.05.2022 23:52:29.021] Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
[06.05.2022 23:52:29.021] Error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

Aborted (core dumped)
```
## `ubuntu:jammy`
### `2.8.0`
*   `login -p`
    *   Same Qt errors as `focal` above.
##`debian:bookworm`
### `2.2.0`
From the [debian repositories](https://packages.debian.org/bookworm/mozillavpn)
    *   `login -p` ❌
        *   `Aborted (core dumped)` with no other logs, presumably a similar Qt issue but who really cares this package is not maintained right now.
---


I don't suppose it's possible to compile from source _without_ Qt is it?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

This does not appear to be feasible without significant refactoring as we require too many permissions to manipulate the network interfaces and routing table to make the VPN work within a docker container.
