### ISSUE TITLE
Windows VPN client is not listed on Linux if user activates first the VPN Linux client and not vice versa

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#122]
#### Affected versions:
- 1.202010191546;

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app on Linux and sign in using the account from prerequisites;
2.  Open the VPN app on Win and sign in using the same account;
3. Observe the list of devices on Linux;

#### Expected result:
- 2 devices - Win and Linux are listed under “My devices” section on both Linux and Windows clients.

#### Actual result:
- 1 device - only Linux (current device) is listed under “My devices” section on Linux client, and 2 devices are listed in Windows client.

#### Notes:
- If we switch step 1 with step 2, both devices are listed for both VPN clients.

**Comment by ValentinaPC** [comment]
Verified as fixed on Linux Ubuntu 20.04 while using the last VPN version 2.202011200942.
The Win client is added in the Linux client list, even if activated last, when accessing the "My devices" page.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
