### ISSUE TITLE
Drop down menu from Select Location not displayed in Spanish

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1227]
#### Affected versions:
- Mozilla VPN 2.3.2 (2.202106171827);

#### Affected Platforms:
- MacOS Big Sur 11.4;
- Windows 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device;
- Have the system language set to Spanish;

#### Steps to reproduce:
1. Open Mozilla VPN app and login with the account from prerequisite;
2. Navigate to Select Location/Elegir obicación menu;
3. Observe the options displayed.

#### Expected result:
- The options from the drop down menu are displayed in Spanish;

#### Actual result:
- The options from the drop down menu are displayed in English.

#### Notes:
- Reproducible even if the language Spanish is selected from the Language menu and the “Use system language” is not on.

**Comment by ValentinaPC** [comment]
Verified this on Mozilla VPN 2.3.2 (2.202106232304) - prod build while using iOS 14.4.2 and stage build 2.3.2 (16244660) while using Android 10;
**Android:**
- In app language setting: the list of the cities are translated in es-es locale. The list of the countries is not;
- Device language setting: the locations, both cities and countries, are not translated in Spanish;
**iOS:**
- In app language setting: the list of the cities are translated in es-es locale. The list of the countries is not;
- Device language setting: the entire app is not translated in Spanish;

**Comment by bakulf** [comment]
@ValentinaPC has confirmed that now the countries are corrected localised. Closing the bug.
