### ISSUE TITLE
Download and Upload strings not translated in Italian

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1228]
#### Affected versions:
- Mozilla VPN 2.3.2 (2.202106171827);

#### Affected Platforms:
- MacOS Big Sur 11.4;
- Windows 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device;
- Have the system language set to Italian;

#### Steps to reproduce:
1. Open Mozilla VPN app and login with the account from prerequisite;
2. Turn on the VPN;
3. Click on the information icon from the top-left corner of the window;
3. Observe the Download and Upload strings.

#### Expected result:
- The Download and Upload strings are translated to Italian;

#### Actual result:
- The Download and Upload strings are not translated to Italian;

#### Notes:
- The Download and Upload strings are also displayed in English when the application has the language set to Deutsch and Netherlands.

**Comment by bakulf** [comment]
In italian we use "upload" and "download". We use English words.

**Comment by madalincm** [comment]
> In italian we use "upload" and "download". We use English words.

This is reproducible for other languages too: Deutsch, Netherlands, Frysk, Slovak and Portuguese. (see Notes from above)
