### ISSUE TITLE
User is not logged out from a removed device 

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1235]
#### Affected versions:
- Mozilla VPN 2.3.2 (2.202106171826);

#### Affected Platforms:
- MacOS Big Sur 11.4;
- Windows 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed at least on 2 devices;

#### Steps to reproduce:
1. Open Mozilla VPN app and login with the account from prerequisite at least on 2 or more devices;
2. Click on My devices from the bottom of the window from the first device that you are using;
3. On the same device click the trash button for the second device from the list  and select the "Remove" button.
4. Check the second device to see if the user is logged out.

#### Expected result:
- The user is logged out;

#### Actual result:
- The user is not logged out until it navigates to My devices list.

#### Notes:
- The user is able to access all the options from the VPN Mozilla application, except the My Device list;
- Even if the user is not logged out instantly, on the VPN screen, “Unstable connection” is displayed and the web pages are not loading.

**Comment by bakulf** [comment]
This is a known issue. There are already registered issues. Unfortunately we do not have a solution yet. We do not have a way to synchronise clients yet.

**Comment by bakulf** [comment]
See https://github.com/mozilla-mobile/mozilla-vpn-client/issues/189 https://github.com/mozilla-mobile/mozilla-vpn-client/issues/183

**Comment by rbillings** [comment]
Closing as a duplicate.
