### ISSUE TITLE
Updates should be allowed to happen while connected to VPN

### ISSUE THREAD

**Issue by KelleyCook** [mozilla-mobile/mozilla-vpn-client#1239]
A corporate nanny firewall installed on my laptop blocks the Mozilla update servers, so I regularly get prompted to update my VPN version, but have been unable to do so.

An obvious solution would be to be able to download and begin installation of the update while we are connected through the Mozilla VPN.

As a note I just manually did this while connected through Mozilla VPN by directing Firefox to https://vpn.mozilla.org/downloads/vpn/windows/v2.3.0/MozillaVPN.msi 

It worked perfectly, including offering to shutdown the service and restarting again for me after the installation.

[mozillavpn-2021-6-24_2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6711868/mozillavpn-2021-6-24_2.txt)

**Comment by rbillings** [comment]
Typically trying to update will close VPN and start the update, however this may be impacted by the network being used.

**Comment by KelleyCook** [comment]
Of course it disconnects during the installation of the update and then reconnects afterwards.  But the point is that I am unable to download the VPN update when I am not connected to the VPN.  There needs to be a user friendly solution.
