### ISSUE TITLE
[Linux] Long display name causes layout issue in Settings page of the VPN app

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#124]
#### Affected versions:
* 1.202010191546;

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;
* Have a LONG display name set to your FxA account;

#### Steps to reproduce:
1. Open the VPN app;
1. Click settings gear icon;
1. Observe the account info section;

#### Expected result:
* There are no display or layout issues. The LONG account display name is wrapped.

#### Actual result:
* There are some layout issues.

#### Notes:
* If no display name is set, a default “VPN user” display name is assigned in the VPN app.
* This is also happening on iOS;
![displayn](https://user-images.githubusercontent.com/15685960/97456113-35233300-1941-11eb-8105-471b2ba0a6f0.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-260)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
