### ISSUE TITLE
Users losing internet connection after turning VPN on.

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#1246]
**Description**

Users on Windows10 are losing internet connectivity when the VPN is turned on.

**Technical Information**

* Device version: Windows10
* FX product Mozilla VPN 2.3.0
* FX version 
* Any other additional info

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. ... 

**Actual Results**

* The users internet connection stops completely when turning on the VPN. Internet connectivity is restored when the VPN is turned off.

**Expected Results**

* After turning the Mozilla VPN, the user's internet connection should not be affected. 

**Support Info**

Tag: [vpn-windows2.3-blocksinternet] 
[mozillavpn-2021-6-16.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6717327/mozillavpn-2021-6-16.txt)

**Comment by jr-johnson-support** [comment]
10 Users affected over the last week

**Comment by oskirby** [comment]
Unfortunately there doesn't appear to be a connection attempt being made in the provided logs, so it's hard to know what area of the code the problem could be related to.

**Comment by bakulf** [comment]
#1236 dup.
