### ISSUE TITLE
[Mac] Top menu bar icon is invisible in dark mode

### ISSUE THREAD

**Issue by groovecoder** [mozilla-mobile/mozilla-vpn-client#125]
The latest build seems to have regressed the menu bar icon in dark mode. See https://bugzilla.mozilla.org/show_bug.cgi?id=1671456 for more details.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-261)

**Comment by ValentinaPC** [comment]
Verified as fixed while using MacOS 10.15.7 and VPN v. 2.202011200952.
Postfix screenshot below.
![Screenshot 2020-11-20 at 16 44 21](https://user-images.githubusercontent.com/15685960/99814413-9f4e8280-2b51-11eb-85fa-a64004210d30.png)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
