### ISSUE TITLE
make install step fails on Debian 10 (packaged go too old)

### ISSUE THREAD

**Issue by matthewhughes934** [mozilla-mobile/mozilla-vpn-client#1251]
Under Debian 10, the version of `go` from the `golang` package is:

```
$ /usr/bin/go version
go version go1.11.6 linux/amd64
```

Following the instructions to install on Debian (notably the line: `sudo apt install clang llvm golang`) causes `make install` to fail with

```
Building ../linux/netfilter/netfilter.go
runtime/cgo
github.com/mdlayher/socket
# github.com/mdlayher/socket
vendor/github.com/mdlayher/socket/conn.go:187:14: f.SyscallConn undefined (type *os.File has no field or method SyscallConn)
net
make[1]: *** [Makefile:1692: ../linux/netfilter/netfilter.a] Error 2
make[1]: Leaving directory '/home/mjh/src/mozilla-vpn-client/src'
make: *** [Makefile:60: sub-src-install_subtargets] Error 2
```

Because `os.File.SyscallConn` was added in go 1.12, docs: https://golang.org/pkg/os/#File.SyscallConn

Uninstalling the packaged Go and installing Go 1.16 from https://golang.org/ allowed install to complete succesfully. Although Debian does provide packages for specific versions of go e.g. 1.14 https://packages.debian.org/buster-backports/golang-1.14 which would probably also work.

Not sure if this issue really needs addressing, but thought I'd open it in case someone else were to encounter the same problem.

**Comment by oskirby** [comment]
I believe that the minimum version of Go we can support would be 1.13, which is where a bunch of changes were made to aid in how modules are packaged, so you should be able to get yourself unstuck by enabling the buster-backports suite.
