### ISSUE TITLE
Update recommended screen isn’t displayed  

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1254]
#### VPN version:
- 2.3.2 (2.202106231537);

#### Affected Platforms:
- Windows 10x64;

#### Steps to reproduce:

1. Access http://localhost:8766/ 
2. Enter force_update_check 1.5 command

#### Expected result:
- The Update Recommended screen is displayed

#### Actual result:
- Nothing happens

#### Notes:
- If you introduce first the force_update_check 1 command and then the force_update_check 1.5 command the update recommended screen is displayed

**Comment by bakulf** [comment]
Can I see the logs, please?

**Comment by bakulf** [comment]
The reason why it doesn't work is that the balrog 1.5 configuration points to version 2.3.0 which is lower than 2.3.2.
This is a balrog misconfiguration. Closing this issue.

**Comment by oskirby** [comment]
I believe there is actually a bug here. When using an inspector command to trigger an update, we actually force the version comparison to whatever version is provided as an argument. So the command `force_update_check 2.2.0` ought to trigger an update alert even though the current version is `2.3.2`

**Comment by mariaberlinger** [comment]
Hello,
This is verified fixed on VPN 2.4.0 (2.202107231555) using Windows 10.
