### ISSUE TITLE
Unable to install Mozilla VPN, getting Windows Installer Error Message: The installation package could not be opened. Contact the application vendor to verify that this a valid Windows Installer Package.

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#1255]
**Description**
Users on Windows 10 are getting an error message preventing them from installing the Mozilla VPN to their device.

**Technical Information**

* Device version Windows 10
* FX product: Mozilla VPN
* FX version 
* Any other additional info

**Steps to Reproduce**

1. Go to vpn.mozilla.org
1. Log in with Firefox account
1. Download Windows 10 VPN file
1. run .msi file to complete installation

**Actual Results**

* when running .msi file an error appears **Windows Installer Error Message: The installation package could not be opened. Contact the application vendor to verify that this a valid Windows Installer Package.**

**Expected Results**

* Running the download file should execute the Windows installer and install the VPN app

**Support Info**

Tag: [vpn-windows-2.3installfailure] 

Response to Users:

* confirm users are on Windows 10
* have users redownload the VPN file again
* confirm device time and date settings are set to automatic

Screenshot shared by a user of the VPN download file properties are missing some information and tabs like the digital signature

![image](https://user-images.githubusercontent.com/72564534/124784135-dfa51a00-df02-11eb-871a-36ec443d64f2.png)

![image](https://user-images.githubusercontent.com/72564534/124784319-0b280480-df03-11eb-9951-929c02d53501.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-684)
┆Reporter: Data Sync

**Comment by jr-johnson-support** [comment]
@JKingZapata WE have been using a tag for this. Can you check how many tickets we have with this issue thus far and add that as a comment?

**Comment by JKingZapata** [comment]
11 tickets reported in Zendesk so far

**Comment by rbillings** [comment]
Possibly the file was corrupted during download. Need more info from users. Confirmed this happens on 64bit. Sending a link to a direct download did not help. If the user could upload the installer they used that would be helpful.

**Comment by rbillings** [comment]
Next steps are that Support will try to get the info from users and report back.

**Comment by dlmchugh1212** [comment]
Having same problem, same actual result

**Comment by rbillings** [comment]
Currently we have 24 users with this issue. We are unable to receive the files from the users via email.

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

JR Johnson  Do you know if this issue persists? It may be possible that this was fixed with a more recent version.  Please advise.

**Comment by jr-johnson-support** [comment]
@JKingZapata Can you provide an update here? I was trying to also ping Joe, but I do not know his Github handle.

**Comment by data-sync-user** [comment]
➤ JR Johnson commented:

Adrienne Davenport  I pinged Juan our support technical lead to provide a follow up here. Joe Cuevas and Juan Zapata would be the contacts to ping for updates on these issues in the future as they are close to the source.

**Comment by JKingZapata** [comment]
@jr-johnson-support I found a couple of tickets for this issue still happening on 2.4

**Comment by data-sync-user** [comment]
➤ JR Johnson commented:

Thanks @JKingZapata I know we stuggled with this last time, but I wonder if we are able to grab install files at all for this?

**Comment by strseb** [comment]
@JKingZapata  - If we could get hands on such a corrupted file that would be great! 
Otherwise, getting a hash of their broken installer file would already help too. They can do this here, super easy :) https://md5file.com/calculator
- While at it, can we ask them if they are using any type of antivirus & firewall software?

**Comment by JKingZapata** [comment]
@strseb we have issues with the users attaching the installer file to their email and so far none have been able to send us one. The users also confirmed they had no Antivirus or Firewall software (besides Windows defender). I haven't seen this issue recently in which the user is willing to troubleshoot, but I'll get them to send us the hash next time.

**Comment by data-sync-user** [comment]
➤ Basti (Sebastian) Streich commented:

Hi! Marking this as cancceled as we currently have no info whether this still happens and lack information on possible causes. 
Don't hesitate to reopen this once something comes up!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled
