### ISSUE TITLE
Tapping the Mozilla VPN notifications does not open the app

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1258]
#### Affected versions:
- Mozilla VPN 2.3.2 (16244660);

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your mobile device;
 
#### Steps to reproduce:
1. Open Mozilla VPN and login with the account from prerequisite;
2. Select a location and turn on the VPN;
3. Hide the app in background and drag down the notification menu from the bar;
4. Observe the notification from the Mozilla VPN app and tap on it;
5. Observe the screen.

#### Expected result:
- The activation screen of the Mozilla VPN should be displayed.

#### Actual result:
- Nothing happens when tapping on the notification.

#### Notes:
- Not reproducible on iOS;
- See the attached video.

https://user-images.githubusercontent.com/15685441/124490663-0d7f4700-ddbb-11eb-8b77-39075ee5fa04.mp4

**Comment by strseb** [comment]
Fix landed for 2.4 :)
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1132

**Comment by madalincm** [comment]
Verified this on Mozilla VPN 2.4.0 (16270230), while using Android 10 and the activation screen of the Mozilla VPN is now displayed.
