### ISSUE TITLE
Update Glean.js to v0.21.0

### ISSUE THREAD

**Issue by brizental** [mozilla-mobile/mozilla-vpn-client#1262]
Hey folks, the new release of Glean.js is out ([v0.16.0](https://github.com/mozilla/glean.js/releases/tag/v0.16.0)) and has many big changes regarding QML. Here are the highlights and suggestions on how to adress them:

#### 1. Glean.js now provides a default `httpClient` for QML
This means it is not mandatory to add a custom `httpClient`, as [the VPN app has right now](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/20db046b7de8f2613fffe26c2d4f2e4902fb2f49/src/ui/main.qml#L70-L90). The provided default client [uses XHR]() just like the custom one provided by the app right now, so I suggest you simply drop the custom one and use the default.

#### 2. Glean.js will now gzip pings upon submission
This only requires action in case you decide to continue using a custom uploader / want to implement another one.

Implementing the gzipping required that we change the signature of the `Uploader.post` function to accept both a `String` and `UInt8Array`. That means any custom uploader implementation will need to be updated to support the enhanced signature. Note that for XHR specifically it is necessary to change the request depending on the type we are sending over the wire. See [default uploader implementation](https://github.com/mozilla/glean.js/blob/main/glean/src/platform/qt/uploader.ts#L52-L56) for specifics.

#### 3. Glean.js now has persistent storage for QML
Prior to this version Glean.js did not persist metrics and pings throughout sessions, which meant data not sent in a single session were lost and most importantly meant that every new run generated a new client id.

That is not the case from v0.16.0 onwards. This changes dramatically the shape of the data you will get from now on. An approach here is, after update, to bisect data based on the [`telemetry_sdk_build` metric](https://mozilla.github.io/glean/book/user/pings/index.html?highlight=telemetry_sdk#the-client_info-section), which contains a string with the Glean version a ping was built on. Another approach, if possible, is to wipe all data coming from versions prior to v0.16.0, since it will be nearly impossible to correlate data from before and after this version.

Anyways, for this one I cannot really recommend what would be the best approach. I am available for discussion and questions whenever necessary :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-687)

**Comment by birdsarah** [comment]
v0.16 will also let us have a unique independent client id that will let us properly analyze the telemetry data.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Updated title as we will be upgrading to v0.21 which will be out shortly after I’ve confirmed bug fixes with brizental.

**Comment by birdsarah** [comment]
This issue was not closed by #1911 but will be in an upcoming PR.
