### ISSUE TITLE
VPN timer does not display the correct uptime

### ISSUE THREAD

**Issue by AOiegas** [mozilla-mobile/mozilla-vpn-client#1263]
#### Platforms:
- Android 9, iOS;

#### Prerequisites:
- The user has a VPN account with an active subscription;
- The VPN app is installed;

#### Steps to reproduce:
1. Open the VPN app;
2. Turn on the VPN to any location;
3. Close the phone’s display and take note at what time you do this;
4. Wait for 5-10 minutes;
5. Open your phone and reopen the VPN app;
6. Check the VPN timer;

#### Expected result:
- The timer should display the correct time passed;

#### Actual result:
- The timer shows that less time has passed;

#### Notes:
- Might need a few tries as it doesn’t always reproduce;
- Kill swiping the app and reopening it fixes the timer;
![14 45](https://user-images.githubusercontent.com/85748693/124627342-23a70900-de88-11eb-90b6-5ffa5b9b9df7.JPEG)
![15 00](https://user-images.githubusercontent.com/85748693/124627361-27d32680-de88-11eb-9240-9bfcddcff4e7.JPEG)
![15 30](https://user-images.githubusercontent.com/85748693/124627372-299cea00-de88-11eb-9eb2-252cbcfab7a4.JPEG)

**Comment by bakulf** [comment]
This is kind-of expected. We use the ellipsed-timer. So, when the app is 'frozen', the timer is suspected.
@jess-cook03 does it seem reasonable to you?

**Comment by AOiegas** [comment]
it seems that this issue, or at least something very similar, came up a while ago.
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/753

**Comment by mbirghan** [comment]
@bakulf wouldn't it be better to store the time we connected and then display the elapsed time since then instead of using a timer?

**Comment by bakulf** [comment]
@mbirghan please! Let me know how the implementation goes :) Thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 build across platforms.
The timer does not stop while the app works in background or the device is in stand by, or it is swipe killed, etc.
