### ISSUE TITLE
Logs overwhelmed with ShaderEffectSource warning when compiled for debug

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1268]
When the VPN client is compiled for debugging on Windows and MacOS platforms and the main view is visible, the logs quickly get overwhelmed with warning messages complaining about recursive rendering in the `ShaderEffectSource` class. These messages appear sporadically when while disconnected but are generated around 90 times a second as soon as the animated rings begin.

```
[07.07.2021 22:19:51.984] Warning: ShaderEffectSource: 'recursive' must be set to true when rendering recursively. (scenegraph\qsgopengllayer.cpp:165, void __cdecl QSGOpenGLLayer::bind(void))
```

When compiled without `CONFIG+=debug` no such messages are printed to the logs, so this is merely an annoyance that hinders debugging.

[mozillavpn-2021-7-7_3.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6781048/mozillavpn-2021-7-7_3.txt)

**Comment by lesleyjanenorton** [comment]
Fixed in #1475
