### ISSUE TITLE
Several lists in the UI do not scroll when traversed with the keyboard.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#128]
Scrolling with keyboard seems to work for lists that are interactive (see Server location list), however there are a number of lists that still need to be fixed:

* `settingsList` in `ViewSettingsMenu`
* a list in `ViewLanguage`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-264)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
