### ISSUE TITLE
Add a padding above “VPN must be off to edit these settings” option from Network settings

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1288]
#### VPN version:
- 2.4.0 (2.202107110548);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Go to VPN -> Settings->Network settings;
2. Check the “Use Local DNS” option;
3. Go in VPN activation screen;
4. Turn on the VPN;
5. Go back to Settings->Network settings;
6. Observe the edit red note;

#### Expected result:
- There are no display or layout issues;

#### Actual result:
- There is no space between the DNS field and the note;
![image](https://user-images.githubusercontent.com/15685960/125262687-0d2b0280-e30b-11eb-929c-c19055c2cd6b.png)

**Comment by lesleyjanenorton** [comment]
Fixed via #1301

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 build across platforms.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/126766393-065645c4-8099-4747-afe6-1c4023ebd32a.png)
