### ISSUE TITLE
Move “Done” button from In App Feedback “Thank you” page to the bottom

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1291]
#### VPN version:
* 2.4.0 (2.202107110548);

#### Affected Platforms:
* Windows 10;

#### Prerequisites:
* Have one FxA account with subscription;

#### Steps to reproduce:
1. Go to VPN ~~> Settings~~>Give feedback;
1. Select a rating option;
1. Fill all mandatory fields and submit your feedback;
1. Observe the “Thank you” screen;

#### Expected result:
* The screen layout is as available in the [mock-ups](https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=149%3A0);

#### Actual result:
* The “Done” button is in the middle of the screen;

![image](https://user-images.githubusercontent.com/15685960/125277973-d230cb00-e31a-11eb-8044-a8c6e1e0cb5b.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-706)

**Comment by lesleyjanenorton** [comment]
This is actually the correct button placement for the desktop implementation. 
https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=137%3A4004


801- spec for desktop
![Screen Shot 2021-07-14 at 11 23 38 AM](https://user-images.githubusercontent.com/22355127/125657609-cb50f4b3-21b9-4d00-83ac-5f5b9f73735c.png)

838- spec for mobile
![Screen Shot 2021-07-14 at 11 24 09 AM](https://user-images.githubusercontent.com/22355127/125657707-26259b1e-17d4-4a0e-826a-9aefa0fd063b.png)

**Comment by ValentinaPC** [comment]
Verified this on Android 10 using VPN v.2.4.0 (16267140).
The "Done" button was moved to the bottom.
Postfix screenshot below.
![Screenshot_20210720-123516](https://user-images.githubusercontent.com/15685960/126300270-0883bcf1-58aa-4c96-9eaf-7339a25e162c.png)
