### ISSUE TITLE
The “Give us 5 stars” screen isn’t displayed on mobile devices

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1294]
#### VPN version:
* 2.4.0 (16259820);
* 2.4.0 (2.202106211609);

#### Prerequisites:
* Have Mozilla VPN installed on your mobile device;
* Have an FxA account with subscription;

#### Affected Platforms:
* Android 10;
* iOS 14.4.2;

#### Steps to reproduce:
1. Open Mozilla VPN;
1. Log in with the account from Prerequisites (do not turn it ON);
1. Go to Settings -> Give feedback;
1. Choose the “Excellent” rating face;

#### Expected result:
* The “Give us 5 stars” screen is displayed;

#### Actual result:
* The “Thank you” screen is displayed;

#### Notes:
* See [figma ](https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=149%3A0)doc;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-707)

**Comment by bakulf** [comment]
I'm not sure we want to have that screen for 2.4. @lesleyjanenorton, what do you think?

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Designs are complete for this additional UX and can be found here in this figma file: https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=149%3A3224 ( https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=149%3A3224|smart-link ) 
In the file we have highlighted with the GTM 2.5 label and you will see the ‘give us 5 stars’ screen and then the flow to push them out to the app store.
Please let us know if you have questions! cc Peter Benvenuto

**Comment by ValentinaPC** [comment]
Verified this on VPN 2.5 (16297900) while using Android 10.
After clicking on "Excellent" I am redirected to the "Give us 5 stars" and when I click the "Leave a review" I am not redirected to Play Store, but to "Thank you" page, is this expected? @bakulf 

https://user-images.githubusercontent.com/15685960/130606916-8c4a52e6-dc4d-4c3c-b7d1-4ce590a1f79a.mp4

Note: we should also consider moving the Leave a review and Skip buttons at the bottom. @jess-cook03

**Comment by bakulf** [comment]
This is expected because out apk packages are not connected to the Google play store. Let's keep this issue open and, when the builds will be signed and available through the store, we will test it again.

**Comment by bakulf** [comment]
This is now fixed.

**Comment by ValentinaPC** [comment]
Yes, the Leave a review screen is displayed, but clicking on the button, does nothing. Shouldn't leave this open until does work? @bakulf 
![Screenshot_20210909-172749](https://user-images.githubusercontent.com/15685960/132704825-abed689b-70c1-4d64-8697-61b3ac9480ad.png)

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified as fixed on Mozilla VPN 2.5.0 (16313840), while using Android 10. After choosing the "Excellent" rating the “Give us 5 stars” screen is displayed. The "Give us 5 stars" button redirects the user to the Play Store. Closing this.
