### ISSUE TITLE
Confusing status indicators when the connection is unstable/lost

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1295]
![Screen Shot 2021-07-09 at 12 26 59 PM](https://user-images.githubusercontent.com/22355127/125303545-7fdbb400-e2f2-11eb-834e-9e6d51b9f64e.png)

It's hard to interpret what is being communicated here. The status indicators (the green circle with shield, and the unstable warning symbol) seem to be at odds with each other. When the internet connection is unstable or lost, we should consider changing or updating the shield icon to also reflect this - or maybe adding a tooltip that says something along the lines of "VPN is on, but your _internet_ connection is unstable."

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-709)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Checked this on Windows 10, using the latest built from the main branch (2.7.0 (2.202111182105)).

While the icons are displayed correctly for each of the states, when returning from Unstable or No Signal to the regular ON state, the Globe turns pink and the shield goes blank (as seen in the below screenshot and video). Is this intended?

!image-20211119-120302.png|width=557,height=540!

!2021-11-19_13h44_27.mp4|width=404,height=586!

Thank you.

CC: Valentina Virlics Madalin Cotetiu

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Florian Zia tested this on the latest build from main branch, VPN v. 2.7.0 (2.202111242330) and the fix seems to no longer be present or not working. The icons no longer change according to the connection status.

!2021-11-25_13h40_40.mp4|width=424,height=622!

Could you please take a look?

Thank you.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Verified as Fixed on Windows 10, using the latest build from the main branch - 2.7.0 (2.202112060044).

The icons are displayed correctly for each of the states, and when returning from Unstable or No Signal to the regular ON state, the correct icon is displayed.

Please see attached video”

!2021-12-06_15h21_50.mp4|width=412,height=600!
