### ISSUE TITLE
The “Give Feedback” text for the “Good” rating is not correct 

### ISSUE THREAD

**Issue by LuminitaB** [mozilla-mobile/mozilla-vpn-client#1304]
#### VPN version:
- 2.4.0 (2.202107110547);

#### Affected Platforms:
- MacOS Catalina 10.15.7;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Go to VPN -> Settings->Give feedback;
2. Select the “Good” rating and click Continue;
3. Take a look at the message displayed on the form page;

#### Expected result:
- The message specific to the “Good” rating is displayed:
 "We're glad you're enjoying Mozilla VPN! Please let us know how we can make your experience better.";

#### Actual result:
- The message specific to the “Average” rating is displayed:
"We'd love to know what we can do to improve Mozilla VPN. Please share any specific feedback here.";

#### Notes:
- See Figma mockups;
<img width="463" alt="Message for the Good rating" src="https://user-images.githubusercontent.com/52028275/125424617-986c5341-eadd-43bc-b8f8-28d99dd85973.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-710)

**Comment by bakulf** [comment]
@peterbenvenuto we have just 2 strings. Do we want to have more of them? What do you think about this bug?

**Comment by peterbenvenuto** [comment]
@bakulf We're missing a string. The "Good" rating has a different response than the "Average" rating. Is it possible to add the 3rd string because users having a good experience are still different than users having an average experience.

**Comment by lesleyjanenorton** [comment]
Fixed in #1318 but we will wait to land this string until after the 2.4 release and go live with it in 2.5.

**Comment by lesleyjanenorton** [comment]
Closing as fixed in #1318

**Comment by LuminitaB** [comment]
The fix has **Passed** testing

Tested on the Staging environment;
Tests run on:
- Win 10 x64,  GitHub build #1809, Mozilla VPN version 2.5.0 (2.202108190648)
- iMac, macOS Catalina v. 10.15.7, GitHub build #2150, Mozilla VPN version 2.5.0 (2.202108191038)

Thank you.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.
