### ISSUE TITLE
UX/UI for Customer Support workflow

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#1312]
**v2.5 major feature**

**Goal**
Getting help even if we can’t recognize your FXA account as having a subscription (post purchase). Particulary our IAP users have the most difficult ways of contacting support. We want to explore moving our contact support form inside of the client.

**UX Subtasks**

* Document current support workflows
* Highlights areas for opportunity improvement post purchase experience
* Explore UX/Ui design solutions that can improve over experience
* Explore designs for moving the contact support form inside of the app/client

**P1**
Timeline based on a sprint cadence 

* First round feedback: July 19-20th
* Sprint 1 design delivery: July 23rd
* Second round feedback: July 26-27th
* Sprint 2 design delivery: July 30th
* Finalization bumper period (for feedback, last changes): July 30th - Aug 4th
* Design + content freeze: August 4th

**Linked issues (if applicable)**
Please list any other GitHub issues that are constrained by or dependent on this feature here:
#702

**Deliverable:**

[https://www.figma.com/file/eX7DaXmHUzCLeonwXka14D/Support-Workflow-InApp?node-id=54%3A2821](https://www.figma.com/file/eX7DaXmHUzCLeonwXka14D/Support-Workflow-InApp?node-id=54%3A2821|smart-link) - Specs + Content (direct page link)
User flow architecture (direct page link): [https://www.figma.com/file/eX7DaXmHUzCLeonwXka14D/Support-Workflow-InApp?node-id=164%3A4944](https://www.figma.com/file/eX7DaXmHUzCLeonwXka14D/Support-Workflow-InApp?node-id=164%3A4944|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-715)

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

* Change icon in settings to be ❓ Get help

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Closing as this is UX only

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/25 . Changing it back to Done.

Thank you.
