### ISSUE TITLE
Update banner is no longer displayed after performing any action in the VPN app 

### ISSUE THREAD

**Issue by LuminitaB** [mozilla-mobile/mozilla-vpn-client#1315]
#### VPN version:
- 2.3.0 (2.202105270956);
- 2.3.2 (2.202107091528);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription;

#### Steps to reproduce:
1. Install an older version of the Mozilla VPN (in this case 2.3.0);
2. Log in with the account mentioned in the Prerequisites;
3. Perform any action in the VPN app (leave the main screen, change location);

#### Expected result:
- The Update banner is displayed on the screen until the user either updates the app or dismisses the banner;

#### Actual result:
- The Update banner is no longer displayed on the screen after performing any action, even though the user did not update the app or dismiss the banner;
- To trigger the update banner once more, the user needs to sign out and back in;

**NOTE:** After performing the update, reinstalling the older version once more, does not trigger the update message, unless the user signs out and back in;

![Update banner](https://user-images.githubusercontent.com/52028275/125609294-b94a102c-7564-4276-a337-104751db7000.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-717)

**Comment by data-sync-user** [comment]
➤ Pun Lam commented:

if the app is exited, and re-enter, does the update banner show again ?

**Comment by ValentinaPC** [comment]
>     * To trigger the update banner once more, the user needs to sign out and back in;

As Lulu mentioned in the issue description, under Notes, yes, the update banner is displayed again after a reauth.

**Comment by jess-cook03** [comment]
I can confirm that even after signing out then back it on MacOS I was not prompted with the banner to update either. I needed to reinstall the client from our website to get the latest.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

!Mozilla_VPN_2022-01-11_15-54-09_AdobeCreativeCloudExpress.gif|width=160,height=231!

Hi Valentina Virlics - Can you recheck this on Windows ? Given that this was reported on 2.3 this might be fixed, I can’t reproduce it.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sebastian Streich This is no longer reproducible. Quite opposite is happening in 2.7 😃 - https://mozilla-hub.atlassian.net/browse/VPN-1503 ( https://mozilla-hub.atlassian.net/browse/VPN-1503|smart-link )
