### ISSUE TITLE
VPN 2.4 is broken when trying to access the “App permissions” option

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1317]
#### VPN version:
- 2.4.0 (2.202107140750)

#### Prerequisites:
- Have Mozilla VPN installed on your device;
- Have an FxA account with subscription;

#### Affected Platforms:
- Ubuntu 20.04

#### Steps to reproduce:
1. Open Mozilla VPN;
2. Log in with the account from Prerequisites (do not turn it ON);
3. Go to Settings -> App Permissions;

#### Expected result:
- The “App Permissions” screen is displayed;

#### Actual result:
- Choosing the “App Permissions” option doesn’t to anything;

#### Notes:
- When you try to access other option from the list it’s overlaid them
![Screenshot from 2021-07-14 15-04-41](https://user-images.githubusercontent.com/54393305/125620513-bb01d4dd-e62f-4021-80b8-d72988b3986f.png)

**Comment by bakulf** [comment]
Fixed by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1320

**Comment by mariaberlinger** [comment]
Hello,
This is verified fixed on VPN 2.4.0 (2.202107230654) using Ubuntu 20.04.
