### ISSUE TITLE
Layout suggestions for IAP VPP on iOS 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1319]
#### VPN version:
- 2.4.0 (2.202107131636);

#### Affected Platforms:
- iOS 14.4;

#### Prerequisites:
- Have one FxA account without subscription;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Observe the VPP screen;

#### Expected result:
- savings percent is displayed for both 6-months and 12-months plans;
- saving percent for both plans is correct;
- “30-day money-back guarantee”/Refund policy link is displayed;
- Subscribe now/ToS/PN and Sign out options are at the bottom of the page;
- There is a space between app details and pricing plans;
- Tapping on each plan should display that plan as selected and the “Subscribe now” button should be mandatory - there is the chance that the user is tapping a bit higher that the plan he wants and ends up with the wrong plan;

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-719)

**Comment by jess-cook03** [comment]
@ValentinaPC can you provide an imagine or video of what you are seeing?
Thank you!

**Comment by ValentinaPC** [comment]
@jess-cook03 This is what I see on the last 2.4 VPN version, on iOS 14.4.
![image](https://user-images.githubusercontent.com/15685960/125746519-51d8ff94-d117-41f5-a793-10a43c4db116.png)

**Comment by lesleyjanenorton** [comment]
I've unassigned myself from this issue since there isn't anything actionable to do here yet for engineering.

**Comment by jess-cook03** [comment]
@lesleyjanenorton this has been resolved from the front end, correct? This is something we can either close or put into 2.5 if not already merged/addressed?

**Comment by jess-cook03** [comment]
These is the treatment as expected I am going to close this issue.
