### ISSUE TITLE
ListView does not render all delegates.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#132]
It looks like ListView only renders visible delegates + a couple more delegates out of view within each scroll direction. This is a problem for accessibility because assistive technologies will incorrectly report the size of the list and the position within the list. There needs to be a way to always force ListViews to render all their delegates.

**Comment by bakulf** [comment]
@lesleyjanenorton is this bug fixed now?

**Comment by lesleyjanenorton** [comment]
closed in #293

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
