### ISSUE TITLE
Reimplement the ring-animation as a C++ QtQuick item

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1322]
We must improve the ring animation because it consumes too much CPU. There are many options:
- change the ring-animation with a less "complex" thing
- reimplement it in C++ to see if it consumes less CPU.

Maybe, a good first step can be to reimplement the component in C++.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-720)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Florian Zia Checking that the ring animation does not increase CPU usage, show be enough while verifying this? Thanks!

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Valentina Virlics In addition to CPU usage it would be good to check if the animation looks consistent across platforms. Thank you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on VPN 2.5.0 (2.202108310209), across platforms.

The new ring animation looks consistent on desktop and the CPU usage is under 10%.

On Android, they seem a bit flattened.

!rings.png|width=535,height=449!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

I just received the last 2.5 iOS build, and the rings look flatted there too.

!20210907_141418.jpg|width=3024,height=4032!

iPad Air iOS 14.02.

**Comment by flozia** [comment]
Thank you for reporting this. This issue — the rings stretching for certain aspect ratios — will be fixed with PR #1738.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the lat builds on both Android and iOS v 2.5.0 (2.202109091821). The ring animations look very good.

Postfix screenshot below.

!image-20210910-082612.png|width=453,height=362!

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
