### ISSUE TITLE
Controls with no visible text alternative must provide a tooltip.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#133]
Controls such as `VPNIconButtom` must provide a tooltip for when they are hovered over or are focused. This is primarily because accessible name is only available to screen readers and thus non screen reader users might not always be able to discern what the control icon implies. A quick fix lie this will do the trick in `VPNIconButtom` for example:
```
ToolTip.text: accessibleName
ToolTip.visible: mouseArea.containsMouse || activeFocus
ToolTip.delay: 2000
```
I believe tooltip visuals can also be customized if necessary.

**Comment by lesleyjanenorton** [comment]
Fixed in #231 and #147
