### ISSUE TITLE
[Android] Search filters not working properly on Language menu

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1336]
#### Affected versions:
- Mozilla VPN 2.4.0 (16262900);

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have a FxA account and have an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your mobile device;
 
#### Steps to reproduce:
1. Open Mozilla VPN and login with the account from prerequisites;
2. Go to Settings - Language and disable “Use system language” feature;
3. Start typing “Spanish” in the Search field;
4. Observe the behavior;

#### Expected result:
- Search filtering is working as expected. Correct suggestions are displayed while typing chars in the field.

#### Actual result:
- The list is displayed with no filters. 

#### Notes:
- specific options displayed for the entered chars are displayed ONLY when you tap the magnifying glass;
- if the cursor is in front of the typed chars, the search filters are removed again;
- Not reproducible on iOS;
- See the attached video.

https://user-images.githubusercontent.com/15685441/125919900-26f67383-708d-415a-ade1-e317cee45e1a.mp4

**Comment by madalincm** [comment]
Verified this on Android 10 platform using Mozilla VPN 2.4.0 (16262900) build. The search filters are applied as expected but there is a small glitch while clicking on the magnifier. See below video of the issue. Reopening.


https://user-images.githubusercontent.com/15685441/126187717-3f6065e4-f00c-4c3d-8c24-73877bb66c60.mp4

**Comment by bakulf** [comment]
Can we open a separate issue for this glitch? It seems related to the virtual keyboard. Am I right?

**Comment by madalincm** [comment]
Indeed, it seems related with the virtual keyboard. We can close this issue as verified on Mozilla VPN 2.4.0 (16267140), while using Android 10. For the glitch issue we logged the issue #1367. Closing.
