### ISSUE TITLE
Devices from local network (router) are reachable with “local network access” disabled and VPN ON

### ISSUE THREAD

**Issue by LuminitaB** [mozilla-mobile/mozilla-vpn-client#1337]
#### VPN version:
* 2.4.0 (2.202107141914);

#### Affected Platforms:
* MacOS Catalina 10.15.7;

#### Prerequisites:
* Have one FxA account with subscription;
* Have the VPN app installed on machine;

#### Steps to reproduce:
1. Access a device from local network and confirm that it works (for example connect to your router);
1. Open Mozilla VPN app and log in with the account mentioned in the Prerequisites;
1. Go to Settings > Network settings and make sure the “Local network access” option is disabled;
1. Turn on the VPN;
1. Try to access a device from the local network once more;

#### Expected result:
* The user is no longer able to access the device from local network;

#### Actual result:
* The device from Local Network is still reachable, even though the “Local network access” is disabled;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-736)

**Comment by ValentinaPC** [comment]
We can close this based on the fact that this feature is OS dependent. If **LNA is off you could or could not access local devices**. With LNA on, you should always be able to access local devices.
