### ISSUE TITLE
Casing issues still not resolved

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#1346]
![Screenshot_20210717-133616.png](https://user-images.githubusercontent.com/17863082/126045356-1bf1e733-b478-44d7-9b57-6c835951866b.png)

Here, "Privacy & Security" should be "Privacy & security." "Launch VPN app on Startup" should be "Launch VPN app on startup." "Sign Out" should also be "Sign out."

![Screenshot_20210717-133636.png](https://user-images.githubusercontent.com/17863082/126045388-61278dce-4119-46e8-a6f1-cd306466ce5c.png)

"Advanced DNS Settings" should be "Advanced DNS settings."

![Screenshot_20210717-133645.png](https://user-images.githubusercontent.com/17863082/126045404-8f9696f7-ce2c-4a53-ae87-a19d8a6329f8.png)

Same with the last two tickboxes here.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 07/19 . Changing it back to Done.

Thank you.
