### ISSUE TITLE
[Windows] VPN cannot be turned ON

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1350]
#### VPN version:
* 2.4.0 (2.202107170646);

#### Affected Platforms:
* Win 10;

#### Prerequisites:
* Have one FxA account without subscription;
* Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
1. Turn ON the app;

#### Expected result:
* VPN is turned ON with success;

#### Actual result:
* VPN cannot be turned on and internet is not working on device;

#### Notes:
* there were cases when VPN started working, but after making some changes in the “Network settings” section from app Settings, it could not be turned back ON and the results regarding internet were the same.
* Internet starts working ONLY after VPN uninstall;
[mozillavpn-2021-7-19_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6841646/mozillavpn-2021-7-19_1.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-744)

**Comment by bakulf** [comment]
@oskirby can this be a regression of your PRs?

**Comment by oskirby** [comment]
I'll take a look into it

**Comment by oskirby** [comment]
Looking through the logs, and based on the build date, I think this was actually fixed by #1347. I think the bug was that `fromIPAddressList()` was outputting an IPv6 address and calling it IPv4, which eventually causes the daemon to try and produce bogus routing table entries.

I do not seem to be able to reproduce the issue on builds off the `main` branch after that fix.

**Comment by ValentinaPC** [comment]
Verified as fixed on VPN v. 2.4.0 (2.202107191712) build, while using Windows.
The VPN can be turned ON and works as expected. Same for the internet.
![image](https://user-images.githubusercontent.com/15685960/126291608-3895e9cc-ee92-4cf2-887e-692616999e2d.png)
