### ISSUE TITLE
[Linux] "Connecting..." state while trying to turn ON the VPN

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1352]
#### VPN version:
- 2.4.0 (2.202107170644);

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have one FxA account without subscription;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Go to Settings-> Network settings;
3. Uncheck the iPv6 option;
4. Turn ON the VPN;

#### Expected result:
- VPN is turned ON with success;

#### Actual result:
- VPN cannot be turned ON;
- VPN remains in the “Connecting…” state; 

#### Notes:
- after few seconds it can be turned OFF;
[mozillavpn-2021-7-19_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6841908/mozillavpn-2021-7-19_1.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-745)

**Comment by bakulf** [comment]
This seems fixed after a killall -9 mozillavpn. It seems that an old version of the daemon was running.

**Comment by ValentinaPC** [comment]
Verified as fixed on VPN v. 2.4.0 (2.202107191711) while using Linux Ubuntu 20.04.
The VPN is turned on even if the ipv6 option is unchecked.

**Comment by ValentinaPC** [comment]
@bakulf This is now happening on Bionic.
Running the killall -9 command does not fix it, neither checking/unchecking app network settings.
Here are the logs.
[mozillavpn-2021-7-26.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6878202/mozillavpn-2021-7-26.txt)

**Comment by ValentinaPC** [comment]
Verified this while using the last Linux Ubuntu - Bionic production build.
The VPN app is connecting and can be turned ON, but **crashes** after.
See attached logs and screenshot;
[mozillavpn-2021-7-27.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6885141/mozillavpn-2021-7-27.txt)
![Screenshot from 2021-07-27 14-51-05](https://user-images.githubusercontent.com/15685960/127149348-045085e0-915b-43f8-949f-abcd73a5ead9.png)

**Comment by oskirby** [comment]
I am able to reproduce the issue on Ubuntu Bionic in a VM.

**Comment by ValentinaPC** [comment]
Verified as fixed on VPN v. 2.4.0 (2.202107272146) while using Linux Ubuntu - Bionic.
The VPN is turned ON and there are no other issues.
