### ISSUE TITLE
[Linux] "Background service error" message is displayed at VPN activation if IPV6 option is checked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1353]
#### VPN version:
* 2.4.0 (2.202107170644);

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have one FxA account without subscription;
* Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
1. Go to Settings-> Network settings;
1. Have the iPv6 option checked;
1. Turn ON the VPN;

#### Expected result:
* VPN is turned ON with success;

#### Actual result:
* A "background server error" message is displayed; VPN cannot be turned on;

[mozillavpn-2021-7-19_2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6842155/mozillavpn-2021-7-19_2.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-746)

**Comment by bakulf** [comment]
This seems fixed after a `killall -9 mozillavpn`. It seems that an old version of the daemon was running.

**Comment by ValentinaPC** [comment]
[mozillavpn-2021-7-19_3.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6842249/mozillavpn-2021-7-19_3.txt)
The killall command only fixes the issue if the ipv6 is unchecked.

**Comment by oskirby** [comment]
I ran into this bug while hacking on the tests this weekend, it should be fixed by #1347, specifically in the commit about `fromIPAddressList()`

That being said, we don't clean up the interface correctly after a failure, which is what causes the hang until a `'killall -9 mozillavpn`. So we could still handle this better.

**Comment by bakulf** [comment]
@oskirby , can we close this bug?

**Comment by oskirby** [comment]
Yes, I think so.

**Comment by ValentinaPC** [comment]
Verified as fixed on VPN v.2.4.0 (2.202107191711) while using Linux Ubuntu 20.04.
There is no error displayed while iPV6 option is checked.
