### ISSUE TITLE
Add search bar to server list

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1358]
To support the new UI for ✨Multi-Hop✨, we need to add a search bar to the server list so that it is filterable by country name. For now, we will not support filtering by city name. Examples of previously implemented search bars can be found in the [languages view](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/5619fe2be8b663ffbce29508dc36752e32af8755/src/ui/settings/ViewLanguage.qml) and [app permissions view](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/fe9f17de28c70b4aeeeec22a1d9f08a40b6876a2/src/ui/components/VPNExpandableAppList.qml).

Search bar:
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/ui/components/forms/VPNSearchBar.qml

Server list: 
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/ui/components/views/ViewServerList.qml

Figma:
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9089

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-748)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/04 . Changing it back to Done.

Thank you.
