### ISSUE TITLE
[Android] Error message not displayed when entering random chars in the custom field from “Use local DNS” option

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1359]
#### Affected versions:
- Mozilla VPN 2.4.0 (16267140);

#### Affected Platforms:
- HUAWEI P30 - ELE-L29 - Android 10; 

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your mobile device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - Network settings - Advanced DNS Settings;
2. Tap on “Use local DNS” option;
3. Enter some random chars in the custom field and press the “Enter” button from the keyboard;
4. Observe the behaviour;

#### Expected result:
- “Invalid IP address” error message is displayed under the custom field.

#### Actual result:
- The error message is not displayed under the custom field.

#### Notes:
- If you tap anywhere on the screen, the error message is displayed, but if you tap again on the custom field and then press “Enter”, the error message disappears.
- Not reproducing on Google Pixel 4 - Android 10;
- See the attached video. 

https://user-images.githubusercontent.com/15685441/126294079-1b893577-aa83-44e3-be45-762b181396e1.mp4

**Comment by bakulf** [comment]
This is similar to the other input field for android. I take this bug.

**Comment by madalincm** [comment]
Verified this on Mozilla VPN 2.4.0 (16270230), while using Android 10 and now the error message is displayed under the custom field when pressing the "Enter" button from the keyboard.
