### ISSUE TITLE
Default text from Give Feedback form is not removed when typing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1363]
#### VPN version:
* 2.4.0 (2.16267140);

#### Affected Platforms:
* google Pixel 4 - Android 10;

#### Prerequisites:
* Have one FxA account without subscription;
* Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
1. Go to Settings-> Give Feedback;
1. Select an emoji;
1. Click “Continue”;
1. Type something in the text field;

#### Expected result:
* default “Enter feedback...” text is replaced with the enterded text;

#### Actual result:
* Entered text overlaps the default one.

#### Notes:
* not reproducing on Android 11;
![image](https://user-images.githubusercontent.com/15685960/126310117-41b576ae-5e8e-4f5f-8139-890d3408c367.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-751)

**Comment by lesleyjanenorton** [comment]
I can't reproduce this on any emulator unfortunately so I'm not sure how to fix/test. We recently changed the functionality of this placeholder text and I suppose we could revert that change.

**Comment by flozia** [comment]
@lesleyjanenorton  I’m not able to reproduce this on a Pixel 4 (Android 10) as well with version `2.5.0`. Is this still happening for you @ValentinaPC?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Florian Zia We tried reproducing this on an HUAWEI P30 - ELE-L29 - Android 10, using VPN 2.4.0 (16270230) and cannot reproduce the issue.

It might be device specific. Maybe Valentina can check when she gets back.

Thank you.

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

Cannot be reproduced by QA nor Engineering.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the latest VPN 2.6 (16330740) while using Android 10 and Google Pixel IV device.

The default text is removed while typing something in the field.

!Screenshot_20211001-143157.png|width=1080,height=1920!
