### ISSUE TITLE
[Android] The Language screen is glitching when clicking on the magnifying glass from the Search field

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1367]
#### Affected versions:
* Mozilla VPN 2.4.0 (16267140);

#### Affected Platforms:
* Android 10;

#### Prerequisites:
* Have a FxA account and have an active subscription for Mozilla VPN;
* Have Mozilla VPN app installed on your mobile device;

      1. Steps to reproduce:

1. Open Mozilla VPN and login with the account from prerequisites;
1. Go to Settings - Language and disable “Use system language” feature;
1. Enter some chars in the Search field;
1. Tap on the magnifying glass;
1. Observe the behavior;

#### Expected result:
* The virtual keyboard disappears from the screen when clicking on the magnifying glass.

#### Actual result:
* The virtual keyboard does not disappear, and a glitch is displayed on the screen.

#### Notes:
* this happens if you tap anywhere in the Search field.
* See the attached video.

https://user-images.githubusercontent.com/15685441/126329771-43813778-689f-47ff-91a9-5c9f9b085bd8.mp4

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-755)
┆Reporter: Data Sync

**Comment by madalincm** [comment]
This is reproducible on each text field on Mozilla VPN 2.5.0 (16300130) while using Android 10. See the attached video. 


https://user-images.githubusercontent.com/15685441/131312866-e02c24aa-f91c-41c6-bde7-a925405cc93f.mp4

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on Android 10, while using Mozilla VPN 2.15.0 (2.202304131916) build.

While typing something in a search filed the search is made automatically and the results are filtered instantly. If we click anywhere in the field, the keyboard is not dismissed nor glitchy.

We can mark is as fixed and close it.
