### ISSUE TITLE
Windows: WFP Allow rule for v6

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1370]
WindowsFirewall::allowDHCPTraffic and allowTrafficTo is currently v4 only :c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-756)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/11 . Changing it back to Done.

Thank you.
