### ISSUE TITLE
“Use local DNS” option does not require an IP address 

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1371]
#### Affected versions:
- Mozilla VPN 2.4.0 (16267140);
- Mozilla VPN 2.4.0 (2.202107191900);
- Mozilla VPN 2.4.0 (2.202107191712);

#### Affected Platforms:
- HUAWEI P30 - ELE-L29 - Android 10; 
- MacOS Big Sur 11.4;
- Windows 10;

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your mobile device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - Network settings - Advanced DNS Settings;
2. Check the  “Use local DNS” option and leave the text field blank;
3. Go back to the activation screen and turn the VPN on;
4. Observe the behaviour;

#### Expected result:
- “Use local DNS” option requires an IP address.

#### Actual result:
- “Use local DNS” option does not require an IP address and VPN can be turned ON.

#### Notes:
- In this case, both options behave the same;

**Comment by bakulf** [comment]
This is expected. If the user doesn't insert a valid IP address (an empty string is an invalid IP address), the default DNS setting is used.

**Comment by bakulf** [comment]
@peterbenvenuto do you think what I'm describing is the acceptable behavior? or do you suggest changes?

**Comment by peterbenvenuto** [comment]
I think this behavior is normal, if the user doesn't input anything into the text field, it's as if they opted to not use the feature and the UI reverts back to it's original state.

**Comment by bakulf** [comment]
OK! I close this bug. @peterbenvenuto thanks!
