### ISSUE TITLE
VPN client freezes when changing language

### ISSUE THREAD

**Issue by tcinotto** [mozilla-mobile/mozilla-vpn-client#1374]
When I change the language on the VPN client it becomes unresponsive. I have to close the VPN client and reopen for the language change to work and the VPN to become responsive again.  (I also waited over 4 minutes to see if it was just taking awhile to load but client remained unresponsive) 

Client: Mac
Release version: 2.3.2 (2.202107091527)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-759)

**Comment by mbirghan** [comment]
Did you have the window on an external monitor?
This sounds similar to #1226

**Comment by tcinotto** [comment]
@mbirghan Yep I do. Just tried changing it not on an external monitor and works perfectly. so seems like this is a dupe of #1226

**Comment by mbirghan** [comment]
Ok then I will close this as a duplicate
