### ISSUE TITLE
“Add Application” for App Permissions is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1382]
#### VPN version:
- 2.4.0 (2.202107201434)

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account without subscription;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Go to Settings-> App Permissions;
3. Disable the feature;
4. Click “+Add application” blue button;
5. Go to app directory and select an .exe file for an app that is not yet added to the list;

#### Expected result:
App is added in VPN App Permissions list.

#### Actual result:
App is not added.

#### Notes:
- If we install the app normally, sign out from VPN and sign back in, the app is automatically added to the list.

**Comment by madalincm** [comment]
@strseb ,do you think it could be possible to move down the "+Add Application" button on the bottom of the screen? There is some empty space under the button (see the attached screenshot). 

![image_2021_07_21T12_09_49_238Z](https://user-images.githubusercontent.com/15685441/126487752-409c5caf-9bf5-476c-add7-24103799b7ee.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on Windows 10 VPN 2.4.0 (2.4.0 (2.202107220713)).
The app is automatically added to the list.

There is a thing, though.... the app can be added using the .exe file, even if she is not yet installed on the computer. Is there a way to remove it from the list? @strseb

**Comment by strseb** [comment]
Well any *.exe can be splitted, that is intended. 
For example you have the chrome_installer.exe and want that this does not use the vpn :)
Currently the only way to get rid of it is to move it to a diffrent location/delete/ or rename it. The client will show an added .exe as long as it's there :) 
Maybe we should also have an option to remove added "missing apps" from the applist? 
cc @peterbenvenuto

**Comment by peterbenvenuto** [comment]
After speaking with @strseb -- adding a remove button seems counter productive to what the user would want from this list. I think we're fine to leave it as is. In the case of any missing apps in the list the warning toast will appear informing the user of any missing apps in the list.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last 2.4 VPN build.
"Add Application" button works as expected.
