### ISSUE TITLE
Applications from exclusion list on App Permissions menu should be unchecked by default

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1386]
#### Affected versions:
- Mozilla VPN 2.4.0 (2.202107210216);

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - App permissions;
2. Turn off the “Protect all apps with VPN” feature;
3. Observe the list displayed on the screen;

#### Expected result:
- The checkboxes placed in front of the applications are unchecked by default.

#### Actual result:
- The checkboxes placed in front of the applications are checked by default.

#### Notes:
- If the user wants to exclude only one application, he needs to uncheck manually all the applications installed on the device. It would be much easier for the user to have all the applications unchecked by default when the feature is off, and to check only the application he wants to exclude.
- On Windows and Android the apps are unchecked by default.

**Comment by bakulf** [comment]
This was a wrong configuration file generated before we "swap" the selected vs unselected app policy.

**Comment by ValentinaPC** [comment]
Verified as fixed on 2.4.0 (2.202107220713) Linux Ubuntu 20.04. The list of the apps is unchecked.
