### ISSUE TITLE
"Choose a Category" should be "Choose a category"

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1390]
"Choose a Category" should be "Choose a category" in ViewGiveFeedback.qml.
<img width="361" alt="Screen Shot 2021-07-21 at 10 33 03 AM" src="https://user-images.githubusercontent.com/22355127/126516933-8c49f0f7-64b3-471d-be5a-7436617fdcf1.png">

**Comment by lesleyjanenorton** [comment]
Fixed in #1493

**Comment by ValentinaPC** [comment]
Verified this as fixed on the last VPN build 2.5.0 (2.202109022353).
The string was updated.
![image](https://user-images.githubusercontent.com/15685960/131965614-76a78873-9c2f-40c4-b79d-f9bb0c9c7d06.png)
