### ISSUE TITLE
LAN option blocks VPN from being turned ON

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1398]
#### VPN version:
- 2.4.0 (2.4.0 (2.202107220713)

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have one FxA account without subscription;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Login to VPN with the account from prerequisites;
2. Go to Settings-> Network settings;
3. Enable the “Local network access” option;
4. Try to turn on the VPN;
5. Disabled the “Local network access” option;
6. Try to turn on the VPN;
7. Quit the app and reopen it;
8. Run “Killall -9 mozillavpn” command and reopen the VPN;

#### Expected result:
- VPN can be turned ON no matter if LAN option is checked or unchecked without issues.

#### Actual result:
4 - “Background service error Restore” error is displayed.
6 - Same “Background service error Restore” error is displayed.
7 - VPN goes to No Signal state in 2 seconds;
8 - Things get back to normal;

#### Notes:
- lan option also blocks VPN to be turned on on Win, but the app behaves different;
- Attaching logs;
[mozillavpn-2021-7-22_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6861790/mozillavpn-2021-7-22_1.txt)

**Comment by bakulf** [comment]
This is fixed now in 2.4.0

**Comment by ValentinaPC** [comment]
Verified as fixed in VPN 2.4 last version on Linux Ubuntu 20.04.
The VPN can be turned ON.
