### ISSUE TITLE
VPN does not stay on while LAN option is enabled

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1399]
#### Affected versions:
- Mozilla VPN 2.4.0 (2.202107220713);

#### Affected Platforms:
- Windows;

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - Network settings;
2. Enable the option “Local network access”;
3. Go to the activation screen and turn the VPN on;

#### Expected result:
- The VPN is successfully connected. “VPN is on. Secure and private” description is displayed on the activation screen.

#### Actual result:
- The VPN can’t connect. “VPN is off. Turn on to protect your privacy” is displayed on the activation screen.

#### Notes:
- The VPN doesn’t stay on even if the LAN option is disabled;
- If you uncheck the LAN option, uninstall the application, reinstall the application and leave the LAN option disabled, the VPN can be turned on;
- See the attached logs.

[mozillavpn-2021-7-22.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6861958/mozillavpn-2021-7-22.txt)

**Comment by bakulf** [comment]
Fixed. @basti, confirm or reopen it. Thanks!

**Comment by madalincm** [comment]
Verified this on Mozilla VPN 2.4.0 (2.202107230655), while using Windows 10 and the VPN stays connected while the LAN option is enabled.
