### ISSUE TITLE
Layout audit

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#14]
Do a pass through the UI and adjust margins/spacing issues. For instance, there isn't enough space between the content of the first list item in both of these lists and the bottom border line of the nav bar. 
![](https://user-images.githubusercontent.com/22355127/91584582-7898fb00-e918-11ea-864d-0cf534b8a7c7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-275)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
