### ISSUE TITLE
App permissions feature is not working properly

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1400]
#### VPN version:
- 2.4.0 (2.202107220713)

#### Prerequisites:
- Have Mozilla VPN installed on your device;
- Have an FxA account with subscription;
- Have Chrome and Firefox opened;

#### Affected Platforms:
- Ubuntu 20.04;

#### Steps to reproduce:
1. Open Mozilla VPN;
2. Log in with the account from Prerequisites (do not turn it ON);
3. Go to Settings -> App Permissions;
4. Disable the feature;
5. Check Firefox browser to make it unprotected;
6. Turn ON the VPN;
7. Verify if selected application (Firefox) is unprotected;

#### Expected result:
-  Firefox browser displays the user real location.

#### Actual result:
-  Firefox browser displays VPN location.

#### Notes:
- same applies for Chrome, Chromium.
- not reproducing on other Ubuntu Focal;
- attaching logs;
[mozillavpn-2021-7-22.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6861941/mozillavpn-2021-7-22.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-775)

**Comment by oskirby** [comment]
This might have something to do with how Firefox was installed on your device. The logs show that the application list is finding the Firefox desktop file at `/home/mariaberlinger/.local/share/flatpak/app/org.mozilla.firefox/x86_64/stable/16b9ca7f1a98ec6fc26bbadffd23b2f29b153e36574e249cacc7628ecef750d3/export/share/applications/org.mozilla.firefox.desktop` but the firewall is finding Firefox being launched as `/home/mariaberlinger/.local/share/flatpak/exports/share/applications/org.mozilla.firefox.desktop`

Likewise, chrome is being found by the firewall as `/usr/share/applications/google-chrome.desktop` but the application list is finding both `/usr/share/applications/google-chrome.desktop` and also as `/home/mariaberlinger/.local/share/applications/chrome-fhbjgbiflinjbdggehcddcbncdddomop-Profile_2.desktop` Though, from the logs it seems like it is working...  though you should have two copies of Chrome in your application list.

My hunch is that there is some kind of symlink magic when applications are installed as a flatpak that is breaking the application launch and tracking mechanisms needed for split tunneling.

**Comment by oskirby** [comment]
After re-installing Firefox using a flatpak, I can reproduce the problem.

**Comment by mariaberlinger** [comment]
Hello,
On the Firefox Flatpak build I can still reproduce the issue. On Chrome and Chromium I can’t reproduce it with the latest build.
I’ll attach the log file.
[mozillavpn-2021-7-26.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6878356/mozillavpn-2021-7-26.txt)

**Comment by mariaberlinger** [comment]
Hello,
This is verified fixed on VPN 2.4.0 (2.202107270926) using Firefox Flatpak build on Ubuntu 20.04.
