### ISSUE TITLE
SplitTunnel View: Implement "Apps Missing Notification"

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1401]
The Figma File describes a Notification, in case an App Goes missing:
-> i.e it was splitted but now not found 
-> it was added by "missing" and is now missing again. 

We should add that! :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-777)

**Comment by ValentinaPC** [comment]
Verified this on VPN 2.5.0 (2.202108191038) while using Windows 10.
After adding an app manually a success banner is displayed, but immediately after a second one, that mentions to add the app manually. If we repeat the steps to add it manually, both banners are displayed again.
Reopening.
![addapp1](https://user-images.githubusercontent.com/15685960/130199946-8fccdb9f-44f2-450e-ad74-19d9b4872901.gif)

**Comment by strseb** [comment]
.msi is not an application. We should catch this but in the mean-time can you re-try with an .exe file?

**Comment by ValentinaPC** [comment]
Yes, verified the ".exe" file also in https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1402. All good for .exe.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
