### ISSUE TITLE
Banner not displayed when adding an application to the exclusion list from App Permissions menu 

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1402]
#### Affected versions:
- Mozilla VPN 2.4.0 (2.202107220713);

#### Affected Platforms:
- Windows;

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - App permissions;
2. Scroll down to the bottom of the screen and click on the “+Add Application” blue button;
3. Select an application that is not on the exclusion list and add it to the list;
4. Observe the screen.

#### Expected result:
- “Success! You added the app to this list.” green banner is displayed at the top of the screen. The added application is checked by default and highlighted.

#### Actual result:
- “Success! You added the app to this list.” green banner is not displayed at the top of the screen. The added application is not checked and is not highlighted. 

#### Notes:
- See the mock-ups for Split Tunneling feature: https://www.figma.com/file/k9gjzhdAisu1SHJwGX1U7j/Split-Tunneling_Settings?node-id=69%3A808.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-778)

**Comment by bakulf** [comment]
It's too late to add new strings. We move this to 2.5.

**Comment by bakulf** [comment]
Basti, you are working on #1401, can you work on this too? They are almost the same feature.

**Comment by ValentinaPC** [comment]
Verified this on VPN 2.5.0 (2.202108191038) while using Windows 10.
A success banner is displayed, but there are some small UI issues in it. Also the app is not added to the list if a .msi  file is used.
The app is added to the list if an .exe file is used.
![image](https://user-images.githubusercontent.com/15685960/130200612-0f7722cf-0f77-4968-971e-485e424bb388.png)

**Comment by strseb** [comment]
this is right. An msi should not be added as it is not an "application" in that sense :)

**Comment by ValentinaPC** [comment]
@strseb the "?" form before and after the app name is intended UI?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
