### ISSUE TITLE
“Mozilla VPN” application displayed in the exclusion list from App permissions

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#1419]
#### Affected versions:
- Mozilla VPN 2.4.0 (2.202107231555);

#### Affected Platforms:
- Windows;

#### Prerequisites:
- Have an FxA account with an active subscription for Mozilla VPN;
- Have Mozilla VPN app installed on your device and in off state;
 
#### Steps to reproduce:
1. Go to Settings - App permissions;
2. Disable the “Protect all apps with VPN” option;
3. Search for “Mozilla VPN” in the exclusion list;

#### Expected result:
- “Mozilla VPN” is not displayed in the exclusion list;

#### Actual result:
- “Mozilla VPN” is displayed in the exclusion list.

#### Notes:
- If “Mozilla VPN” is checked and the VPN is on, the information screen displays the real IP address and not the IP address of the server.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-795)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/02 . Changing it back to Done.

Thank you.
