### ISSUE TITLE
Implement a `ping` cmd fallback for linux

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1422]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-801)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 07/27 . Changing it back to Done.

Thank you.
