### ISSUE TITLE
In-App Feedback Form - Mobile Ergonomic Enhancement

### ISSUE THREAD

**Issue by peterbenvenuto** [mozilla-mobile/mozilla-vpn-client#1425]
I would like to move the icon selection of the in-app feedback form to the center of the screen on mobile. 

The tap radius being at the top and then moving to the bottom is not great ergonomically for the user, the proposed solution can be seen below: 

<img width="647" alt="Screen Shot 2021-07-26 at 10 22 15 AM" src="https://user-images.githubusercontent.com/83967259/127049516-cf4b1680-44af-4f2b-b411-fd029ace3295.png">

Here is a link to the [figma file](https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=515%3A6056) where you can find the changes.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-804)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 07/31 . Changing it back to Done.

Thank you.
