### ISSUE TITLE
Change Informational Blue colour in app to align with design system and colour palette

### ISSUE THREAD

**Issue by peterbenvenuto** [mozilla-mobile/mozilla-vpn-client#1426]
The blue we're currently using for focus states is aligned with firefox. 

We'd like to change the blue focus states and border to match the blue we currently have in our design system. 

This is the what the input field will look like with the design system colours: #0060DF for the thin border and #0060DF at 40% opacity for the thicker outline.

<img width="477" alt="Screen Shot 2021-07-26 at 4 47 32 PM" src="https://user-images.githubusercontent.com/83967259/127056952-06935834-4326-47ec-9165-a5edc1becbdc.png">

Here's the link to the [figma file](https://www.figma.com/file/cBaBmcPisqZ0QQX5LLzpjU/Nebula-Design-System-V1?node-id=202%3A110) which has the proposed colours.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-805)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/04 . Changing it back to Done.

Thank you.
