### ISSUE TITLE
[Linux]Update recommended screen isn’t displayed

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1429]
#### VPN version:
- 2.4.0 (2.202107270926);

#### Affected Platforms:
- Ubuntu 20.04;

#### Steps to reproduce:

1. Access http://localhost:8766/ 
2. Enter force_update_check 1.5 command

#### Expected result:
- The Update Recommended screen is displayed

#### Actual result:
- The Update Required screen is displayed

#### Notes:
- See the logs
[mozillavpn-2021-7-27.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6885766/mozillavpn-2021-7-27.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-809)

**Comment by strseb** [comment]
This is the right screen, 1.x Clients are now required to update
See:
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/813#issuecomment-880044395

**Comment by ValentinaPC** [comment]
@strseb In the past, for the force_update_check command, we used 1.0 to trigger the "required" update and 1.5 for the "recommended" one. This still applies on Windows, for example. Is there another argument for the recommended update on Linux? Thanks!
