### ISSUE TITLE
Android IAP Client

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1432]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-741)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Most of the above scenarios have been verified while running the Android IAP test suites, that can be found here ( https://testrail.stage.mozaws.net/index.php?/plans/view/47508 ) .

The scenarios that have not been validated are the ones with the Google play store purchases listed as Yes - Unacked  a purchase was made but still needs to be acknowledged, because we had no way of controlling the acknowledgement side of things.

Since the QA signoff for Android IAP has been sent, we can consider this closed. Let us know if there is anything else to consider here.

Thank you.

CC: Valentina Virlics Rebecca Billings

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

This was completed in v2.5 should not have been re-opened. cc James Dirks

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Pun Lam Adrienne Davenport this is ridiculous. i keep putting this into done and data sync has moved it out multiple times now.

**Comment by birdsarah** [comment]
Closing here too as jira sync is busted.
