### ISSUE TITLE
Missing space in update notification, after period ("New version is available.Update now")

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/mozilla-vpn-client#1455]
I just launched Mozilla VPN on my macbook pro and got an update notification, and I noticed that there's a missing space in the notification text (in "available.Update").  See attached screenshot.

I was running version 2.1.0 -- that's the version where I saw this issue. Now I'm on version 2.3.2 (after accepting the update), and I can't know for sure if it's already been fixed or not; I can't tell until a new update is offered, of course. :)  So it's possible this has already been fixed -- I don't know.

<img width="354" alt="Screen Shot 2021-07-28 at 3 42 18 PM" src="https://user-images.githubusercontent.com/426803/127405739-dc9859b8-75ba-4d51-af65-d25558aaab57.png">

┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-832)

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN signed build 2.5.0 (2.202109111821) on Windows 10.
![image](https://user-images.githubusercontent.com/15685960/133227409-ffc4d137-545b-4622-aed7-0f1bd91808c4.png)
