### ISSUE TITLE
No Support If You Subscribe Via In-App Purchase On iOS

### ISSUE THREAD

**Issue by nobody63** [mozilla-mobile/mozilla-vpn-client#1458]
I'm really sorry I have to bother you here, but sadly as discussed in #702 there is no way to contact support if you can't sign in or if the support website doesn't detect the subscription. 
I subscribed via an in-app purchase on iOS (Apple Pay) and when I sign in with the same account at vpn.mozilla.org it actually detects my subscription just fine and allows me to download the VPN apps. 
Now the issue is that if I click on my profile picture on the top right and go to "manage subscription" and, more importantly, "contact", I always get redirected to my Firefox account profile and not to my subscription nor the contact form.

So there is clearly something wrong going on here, and yes I double checked.. it's the same account as in my iOS app showing my subscription, I can also connect to the VPN on Windows just fine (not on iOS because of iOS 15 which is why I tried to contact support).

Of course I'd love to get in contact with support somehow, but I'd actually appreciate it more if you could just fix this for everyone or actually implement an option for people to contact support if you can't sign in.. as you can see, there are use cases for this and I kinda feel lost atm which can't really be what you want if someone just paid for your service.

.. and I don't really want to create a new Firefox account, pay for the service directly at mozilla.org just so it's finally possible for me to get in contact about my first account.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-833)

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Closing this as it is resolved now with completion of github #1341 (in app support work)
