### ISSUE TITLE
[Linux] “Switched from X, to Y” location notification is incorrect

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#146]
#### Affected versions:
* 1.202011021112;

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
1. Click the “Select locations” option;
1. Pick a different location that your actual;
1. Observe the system notifications;

#### Expected result:
* The notification mentions: “Switched from X, to Y”, where X is the actual location and Y the one selected at step 3.

#### Actual result:
* The notification mentions: “Switched from Y, to X”, where X is the actual location and Y the one selected at step 3.

#### Notes:
* the final notification about the new actual location is correct.
![sw](https://user-images.githubusercontent.com/15685960/97877244-8b1f1e80-1d25-11eb-8e58-1d34820f7159.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-278)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
