### ISSUE TITLE
Add new VPNCollapsibleCard component 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1472]
We need to build a new collapsible card component to support the UI for Multi-Hop. 

The component should:
- Take in an icon, and two text elements (a title, and body copy)
- Use VPNIconButton to expand and collapse the card
- Be able to support text wrapping of the title text element as this is almost sure to happen in some locales

**Figma**
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9172
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9160

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-837)

**Comment by lesleyjanenorton** [comment]
Fixed in #1515

**Comment by ValentinaPC** [comment]
Verified this across platform while using the last VPN 2.5 version (2.5.0 (2.202108310209)).
The collapsible Multi-hop component is displayed and works as expected.

@lesleyjanenorton There is a vertical scroll button available for few seconds.
See image below.
![image](https://user-images.githubusercontent.com/15685960/131471479-03437120-9cff-4e53-a230-533585cfa399.png)

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Also, “This may slow down your connection” text from the collapsible Multi-hop component is not bold, as presented in the Figma files: https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=286%3A10518. ( https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=286%3A10518.|smart-link )  

See the attached screenshots.

!Screenshot 2021-09-01 at 12.33.11.png|width=358,height=550!

!Screenshot 2021-09-01 at 12.34.18.png|width=375,height=572!
