### ISSUE TITLE
Add new VPNTabbedNavigation component 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1473]
To support the new UI for Multi-Hop and Advanced DNS Settings, we need to create a VPNTabbedNavigation{} component.

The component should switch views based on the selected tab button. For now, the component only needs to accommodate two tabs but it would be major extra credit to build this in such a way that it could just as easily support any number of tabs.  We can probably make use of this Qt.Quick [TabBar](https://doc.qt.io/qt-5/qml-qtquick-controls2-tabbar.html) control https://doc.qt.io/qt-5/qml-qtquick-controls2-tabbar.html.

Figma: 
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A8972
https://www.figma.com/file/If64AyDRUKkGIkxNP0LBG3/DNS-Settings?node-id=203%3A2257

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-838)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync. Is there something the QA team needs to do for this ticket or can it be closed once more?

Thank you.
