### ISSUE TITLE
[Linux] Keyboard navigation is not entirely possible in “Select locations” and “Settings” pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#148]
#### Affected versions:
* 1.202011021112;

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;
* Use only keyboard navigation;

#### Steps to reproduce:
1. Open the VPN app;
1. Access using the keyboard the “Select locations” option;
1. Navigate until Finland (or any location that is listed last in that screen)
1. Hit “enter” to expand the list;

#### Expected result:
* The list is expanded. The page is scrolled.

#### Actual result:
* The page is not scrolled down while using the keyboard.

#### Notes:
* In Settings page keyboard nav is possible through the Notifications/Network/Lang/About us/Give feedback options.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-279)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
