### ISSUE TITLE
Create new component to show entry and exit nodes

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1480]
To support the new multi-hop UI, we need to build a new component that shows both an entry node and an exit node when Multi-hop is enabled, and only an exit node when Single-hop is enabled. This component could also possibly be used in the server list.
This component will handle server location and flag only. We don't need to worry about trying to build in additional functionality (chevrons, toggles, etc) or even about making it a clickable thing since it will need to be nested inside so many other components. 

<img width="300" src="https://user-images.githubusercontent.com/22355127/127917683-bf899776-8b3b-4d3c-9b2c-f90b5471ebe5.png">
<img width="300" src="https://user-images.githubusercontent.com/22355127/127917775-447b1914-5ca6-4fe5-babc-581a539badfe.png">
<img width="300" src="https://user-images.githubusercontent.com/22355127/127917921-d93a1c37-c91b-4f29-943b-1ff332fa5ac5.png">
<img width="300" src="https://user-images.githubusercontent.com/22355127/127918020-66d9ab71-519f-49c0-ae0e-b22ad8e3fe05.png">

Relevant Figma specs:

With Single-hop enabled:
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9229

With Multi-hop enabled:
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9234
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A9196

Server list items:
https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=339%3A8972

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-839)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this across platforms while using the last builds.

The Multi-Hop feature works as expected.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
