### ISSUE TITLE
Stuck after subscription expiration

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1482]
Steps to reproduce:

1. have a subscription and a connection to vpn
1. let subscription expire
1. open laptop and connect to vpn

Result:

I can't connect to VPN because my subscription has expired so first I get stuck in VPN "connecting" screen.
If I force quit the VPN then my internet doesn't work becaues my DNS is set to the wireguard DNS.
Restarting the client did not restore my DNS....but I also had a hard time force quitting, and ended up rebooting machine. So if this isn't reproducible let me know.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-841)
┆author: Data Sync

**Comment by punster-moz** [comment]
MacOS specific.

**Comment by bakulf** [comment]
The main issue here is that the client doesn't know when the current subscription is about to expire.
Let's assume we have the expiration date from the account endpoint, we can inform the user when their subscription is about to expire, disconnect the client, show a proper error page.
This is something that cannot be done for 2.5 but we can definitely do something for 2.6.

@birdsarah if you like this plan, we could extend the account endpoint to expose the expiration date.
@jess-cook03 we also need to define the correct UX. I would like to see the following:

- if the VPN is connected when the subscription is about to expire, we inform the user with a notification (tomorrow your subscription expires!  or... in 10 minutes your VPN tunnel will disconnect).
- We can also show a notification banner (similar to the alert red banners?) to inform the user. And we can have a subscription-needed view too.
- When the subscription expires, we go back to the authentication view
@jess-cook03 what do you think?

**Comment by jess-cook03** [comment]
@peterbenvenuto we have done some design exploration around this already -- can you address the questions at hand? Thanks!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closing in favor of VPN-2168

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Will be tracked in another ticket

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back from Cancelled
