### ISSUE TITLE
VPP screen does not display correct monthly prices

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1483]
Shows $8.00 and $5.00 per month, not $7.99 and $4.99

![049E4AF5-C90E-4D84-8032-8D84EEEAE6ED](https://user-images.githubusercontent.com/1796208/127942555-75793149-1858-40d2-94df-ab9e09892c85.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-840)

**Comment by birdsarah** [comment]
@bfyee @tcinotto - I've written that monthly prices are displayed incorrectly. But the problem is actually the 47.99 and the 59.99. The $7.99 * 6 = $47.94 and $4.99 * 12 = $59.88. So, can you can confirm that you're okay with the $8 and $5 per month - if so we should change the VPN landing page. Or can we update the total prices to be accurate?

**Comment by bfyee** [comment]
The Apple app store only allows us to choose specific prices.   Up to $30 it's $x.49 and $x.99,  above $30 it's only $x.99.  As such we can't do the $47.94 and $59.88 to match with our website.

**Comment by bakulf** [comment]
The monthly price is computed by the app. It seems that we round the value too much...

**Comment by birdsarah** [comment]
The value is rounded mathematically correctly @bakulf.

`59.99 / 12 = 4.9991`

@bfyee would you like us to force the $4.99 or are you happy with the more accurate $5.00?

**Comment by birdsarah** [comment]
Next step @tcinotto talk to stakeholders.

**Comment by bfyee** [comment]
Am okay leaving it at $5 and $8.  We would be undercharging them by a penny which is better than looking like we are overcharging them by 5 for 11 cents.

**Comment by birdsarah** [comment]
Then @tcinotto you can close this issue if you want to skip talking to stakeholders.

**Comment by birdsarah** [comment]
Closing as everyone agrees this is acceptable.
