### ISSUE TITLE
Logviewer: Add a share button

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1494]
On Mobile where we use the copy button to share the logs. This means the application to paste needs to be able to handle this much text in the input. (e.g. Slack fails here and crashes)
We should use the Share functionalities of the mobile os'ses to pass the logfile directly to other apps, e.g the mail app. :)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-844)

**Comment by bakulf** [comment]
This is a great idea. Right now we register crashes on iOS because, if the logs are too many, we allocate too much memory and we crash. Plus, showing the logs is not really useful. Sharing it is definitely better.
