### ISSUE TITLE
VPNToolTip does not show up on keyboard focus.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#150]
See https://github.com/mozilla-mobile/mozilla-vpn-client/pull/147#issuecomment-721158127 for more detail

`activefocus` should be checked on the control that actually gets focus, which in most cases is tooltip's parent.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-280)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
