### ISSUE TITLE
Change "Get help" icon in settings menu

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1508]
We need to update the icon for 'Get help' in the settings menu 
![](https://user-images.githubusercontent.com/22355127/128569805-fc983acf-3153-4718-891e-74df90a55aa5.png)

The new icon can be exported from this Figma spec:
https://www.figma.com/file/SjWR5U9aqEiUnmrkuS74O5/What's-new%3F-(Release-notes)?node-id=69%3A2931

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-850)

**Comment by strseb** [comment]
cancelled
