### ISSUE TITLE
Support Flow - Guardian

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1511]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-722)

**Comment by data-sync-user** [comment]
➤ Nma-Sie-Anyene Davenport commented:

No work needed for Guardian

**Comment by birdsarah** [comment]
Turns out work is needed on guardian for this. Related guardian issue: https://github.com/mozilla-services/guardian-website/issues/1276

@bakulf and @mbirghan to help spec this, probably @lloan to implement

**Comment by birdsarah** [comment]
Closed via https://github.com/mozilla-services/guardian-website/pull/1302

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sarah Bird Could you provide some steps for QA to check this? Thank you!

**Comment by birdsarah** [comment]
cc @mbirghan @bakulf @lloan

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

The Contact Us ticket does not longer returns an error at submit. But for some reason the tickets are not listed in the Zendesk dashboard where QA has access. Joseph Anthony Cuevas

**Comment by birdsarah** [comment]
Is there a seperate zendesk environment for the staging environment? that is a question for fxa team. i wouldn't expect that these tickets end up in prooduction zendesk.

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Valentina Virlics Sarah Bird This is resolved. There was a routing issue where the test tickets weren’t sorted into the appropriate group. The tickets are visible for Valentina now.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Yes, I confirm that the QA test tickets are there and are correct.
