### ISSUE TITLE
Implement mock server entries to simulate errors

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1523]
In debug/staging build, it would be great if we can have some extra countries/cities to trigger errors or unexpected behaviours. In this way, the QA team can check what it happens when the servers are down.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-853)
┆author: Data Sync

**Comment by oskirby** [comment]
I recently wrote an API proxy that allows us to mock features on the staging server. At present it's being used to perform the functional tests in parallel by mocking the devices API, but it could be extended to manipulate the server list as well for testing like this (sources here: [tests/proxy/wsgi.py](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/tests/proxy/wsgi.py))

Though, it would probably be less cumbersome for the QA team if this were something that was built into the client and/or guardian.
