### ISSUE TITLE
Eliminate the use of WgQuickProcess

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1526]
Presently, we make use of the `WgQuickProcess` to build a `wg-quick` compatible configuration file, which is then passed into `Daemon::run()` to handle anything that isn't provided by `WireguardUtils`, `IPUtils` or `DNSUtils`. When used to bring up the interface, this includes the user's private key in plaintext, which could be exposed to other users on the system with admin access.

After the refactoring necessary for multihop in PR #1376, this config file is now only used for:

* DNS configuration (MacOS and Windows).
* ifup and address configuration on Windows.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-854)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Owen Kirby do you think we can close this bug?

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Yeah, we can close this. Even though we still have the WgQuickProcess class kicking around, the reason for removing it is no longer applicable as we don’t have to write the config file to disk anymore.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

We no longer write the wireguard config file to disk when starting the tunnel service on Windows, so the security risk posed by this issue no longer exists.
