### ISSUE TITLE
menu bar icons are broken on macOS

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#153]

**Comment by jess-cook03** [comment]
@lesleyjanenorton to investigate and report back with how easy or not this fix is -- then @jess-cook03 to evaluate svg if need be or we backlog this issue and remove the check and stick with just the animation for now.

**Comment by ValentinaPC** [comment]
@bakulf Could you please add some UI docs or something to help us identify more easily the changes?
Thanks!
