### ISSUE TITLE
Add a generic error to handle when a server location is down

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla-mobile/mozilla-vpn-client#1532]
#### VPN version:
* 2.5.0;

#### Affected Platforms:
* All;

#### Preconditions:
* Have VPN installed;
* Have an account with subscription;

#### Steps to reproduce:
1. Open the VPN and sign in with the account from prerequisites; 
1. Enable the multi-hop feature;
1. Turn the VPN on;

#### Expected result:
* If one of the servers is down a specific error message is displayed;

#### Actual result:
* The connection status jumps to “Connecting…” state or “No signal”;

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-858)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Link to Figma spec for this work:

https://www.figma.com/file/ziJ5tGCqhfst4svjtKJlbr/2.7--Feature-Enhancements?node-id=206%3A5300 ( https://www.figma.com/file/ziJ5tGCqhfst4svjtKJlbr/2.7--Feature-Enhancements?node-id=206%3A5300|smart-link )

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

All dependent issues that have details or a way to be checked, were marked as qa-verified. 

Please add a specific label or a comment for the rest. Thanks!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

All dependent issues have a qa-not-actionable or a qa-verified label.

Closing this.
