### ISSUE TITLE
No internet connection with VPN turned On

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#1536]
Users on Windows 10 are losing internet connectivity when the VPN is turned on.

* Device version: Windows10
* FX product Mozilla VPN 2.4

**Steps to Reproduce**

1. Sign up for Mozilla VPN
1. Download/install VPN client
1. Flip switch to connect to VPN

**Actual Results**

* The users' internet connection stops completely when turning on the VPN. Internet connectivity is restored when the VPN is turned off.

We've confirmed with users that their Windows Firewall settings are set to allow the VPN 
[mozillavpn-2021-8-6 (7).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6969584/mozillavpn-2021-8-6.7.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-859)

**Comment by bakulf** [comment]
Completely unrelated, reading the log, I see that the captive-portal detection fails in a loop. We should have a max number of retries if possible.

**Comment by JKingZapata** [comment]
Users are also seeing an "Unstable" and "No signal" message in the VPN
![image](https://user-images.githubusercontent.com/72564534/129421377-d1ecabbb-1360-435f-8db7-75f5c6f31f71.png)
![image](https://user-images.githubusercontent.com/72564534/129421391-201884e0-9496-465a-a335-d94c8cb50047.png)

**Comment by JKingZapata** [comment]
[mozillavpn-2021.08.24.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7048544/mozillavpn-2021.08.24.txt)

**Comment by JKingZapata** [comment]
Still getting this issue after updating to 2.6

[mozillavpn-2021-11-17.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7596946/mozillavpn-2021-11-17.txt)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

In the most recent log from version 2.6, it appears that the Daemon is connecting successfully to the Wireguard server (as seen from messages like [17.11.2021 18:16:38.527] Info: (windows - tunnel.dll) [TUN] [MozillaVPN] peer(uC0C?LiQM) - Received handshake response) but the problem appears to be caused by the connection health check failing and leading to constant server switching.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This should be done now. Please check it again.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last VPN 2.7.0 (2.202112170222) build on Windows 10.

Internet is working as expected while VPN is turned on.
