### ISSUE TITLE
Android IAP - attach FxA UID to purchase with setObfuscatedAccountId.

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1537]
This will be used by FXA to verify the purchase.

We need to:

* setup guardian to return the FxA UID (not just the email address) to client
* add this to the client models/user.cpp
* use this value from the model in the play billing request with `setObfuscatedAccountId`

This work will have:

* [ ] PR on guardian-website (owner @lloan / @birdsarah) 
* [ ] PR for client (owner @birdsarah)
* [ ] PR on fxa (owner @bbangert)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-860)

**Comment by birdsarah** [comment]
Update after discussing with @bbangert, we are using FxA email in `setObfuscatedAccountId` property

**Comment by birdsarah** [comment]
After trying to implement I've read the docs more closely and seen that storing a plain text identifier is not an option: https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setObfuscatedAccountId(java.lang.String)

```
Specifies an optional obfuscated string that is uniquely associated with the user's account in your app.

If you pass this value, Google Play can use it to detect irregular activity, such as many devices making purchases on the same account in a short period of time. Do not use this field to store any Personally Identifiable Information (PII) such as emails in cleartext. Attempting to store PII in this field will result in purchases being blocked. Google Play recommends that you use either encryption or a one-way hash to generate an obfuscated identifier to send to Google Play.

You can also retrieve this identifier via the Purchase object.

This identifier is limited to 64 characters.

Optional:

    To buy in-app item
    To create a new subscription
    To replace an old subscription 
```

This will have to wait until we agree on a new plan.

**Comment by birdsarah** [comment]
Code that did it though is here: 312f14a81251a5071ccf1ca1b9111a944b429bf2

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Why are you assigning me this work Pun Lam? We haven’t planned when this will be done.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Adrienne Davenport this is a small task that would be a good addition to improve security for 2.6.
