### ISSUE TITLE
[Intermittent] iOS crashes with black bar on the side

### ISSUE THREAD

**Issue by mbirghan** [mozilla-mobile/mozilla-vpn-client#1539]
If you have the VPN open on the iPad in landscape mode the VPN crashes intermittently before rotating. 

It is not clear if this is iPad specific or not and if this has anything to do with the landscape mode.

![IMG](https://user-images.githubusercontent.com/32091959/129091533-587eee9a-ca5e-448b-b60f-e0042eb81e9a.PNG)UNITO-UNDERSCORE!0010!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-862)

**Comment by lesleyjanenorton** [comment]
@mbirghan is this happening with landscape mode disabled?

**Comment by mbirghan** [comment]
I was not able to reproduce it without landscape mode.

Maybe @birdsarah has?

**Comment by lesleyjanenorton** [comment]
For now, let's disable landscape mode on iOS if it isn't already disabled.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Can I still this bug?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is no longer reproducible using the last VPN 2.7 version on iOS, as landscape mode is no longer active while inside the VPN app.
