### ISSUE TITLE
iOS crashes in staging mode

### ISSUE THREAD

**Issue by mbirghan** [mozilla-mobile/mozilla-vpn-client#1540]
After the combination of staging and production builds the VPN client crashes when in staging mode.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-861)

**Comment by ValentinaPC** [comment]
@mbirghan I receive an "Authentication error. Try again" multiple times on all platforms while changing from prod to stage. After a while it works.
I have logs from Android, maybe helps.
[Y2hv7N01.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6975672/Y2hv7N01.txt)

**Comment by mbirghan** [comment]
I am not sure if the two issues are connected or caused by the same this. They might be but I think for now it would be better to file a second issue for the Authentication error. 

@ValentinaPC do you want to do it or should I?

**Comment by ValentinaPC** [comment]
I can do it! @mbirghan

**Comment by bakulf** [comment]
Fixed.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

We have not been able to reproduce this issue on our side, so we can consider it closed. If the issue reproduces again, we will reopen this ticket.

Thank you.

CC: Valentina Virlics
