### ISSUE TITLE
Default DNS leak

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#1546]
#### VPN version:
- 2.5.0 (2.202108091724);

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have one FxA account with subscription for Mozilla VPN;
- Have the VPN installed on your machine;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Settings->Network settings -> Advanced DNS Settings;
3. Enable the “Use default DNS” option.
4. Turn ON the VPN;
5. Access the  https://mullvad.net/en/check/ page

#### Expected result:
- There is no DNS leak.

#### Actual result:
- User default DNS is leaked.
![image](https://user-images.githubusercontent.com/15685960/129225593-571853c8-45a5-4e56-a194-0c58471aca33.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-864)

**Comment by oskirby** [comment]
Out of curiosity, what browser are you using for the DNS leak check? If it's Firefox can you check to see if DNS-over-HTTP has been enabled? We have some known issues with regards to DNS leaking via DoH (#892)

**Comment by ValentinaPC** [comment]
@oskirby Yes, Firefox. I know about that, but that option is not enabled. Though, I've tried both ways => same results.
![image](https://user-images.githubusercontent.com/15685960/129318681-27e34d2c-7ad6-4ffb-8d37-87e82d9d6ab2.png)

**Comment by ValentinaPC** [comment]
Verified this as fixed on Windows 10 and Linux Ubuntu 20.04 using VPN 2.5.0 (2.202108240733);
There are no leaks in the Mullvad site if the default DNS option is checked.
![image](https://user-images.githubusercontent.com/15685960/130608177-cc00fe3e-5356-4861-8a7b-083bdc3a275d.png)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
