### ISSUE TITLE
Missing WireguardGo logs when tunnel daemon fails to start

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1548]
When an error prevents the windows tunnel daemon from starting, we find ourselves in a position where there are no logs being reported to the backend that might explain the failure. This is caused by starting the log monitor thread only after the tunnel daemon has started successfully. The lack of visibility into the tunnel daemon and its Go code makes it very difficult to debug when things go wrong as a result.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-865)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it does not need QA.

Thank you.
