### ISSUE TITLE
Android IAP Edge Case 2 - "item already owned"

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1550]
Steps to reproduce (you can't really repro this as the feature is in development, this is for UX's benefit):
* Get on your android device, get Mozilla VPN, sign in using FxA account "A", and get a subscription with the play store
* Uninstall the app
* Reinstall the app
* When you're asked to sign in by Mozilla VPN use a different FxA account "B"
* You'll then be prompted to in app subscribe (because guardian / fxa doesn't have a link between your existing play store account and this new FxA account "B")
* When you try and subscribe at the back end we get an error message "ITEM_ALREADY_OWNED"

This UI/UX request is for a message to display to the user.

It should explaining that their play store already has an active VPN subscription, but it is likely associated with a different FxA account, and they probably need to try logging in with a different FxA account.

Of course there could be other wierdness that I haven't realized for how a user could get in this state so the help message should be appropriately non-committal or open-ended.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-866)

**Comment by bakulf** [comment]
A similar issue can happen on iOS too.

**Comment by bakulf** [comment]
For iOS we show this view: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/ui/states/StateSubscriptionBlocked.qml
@lesleyjanenorton can we use the same UI component for both iOS and android?
We can expose different strings for android, but all the rest should be the same. Am I right?

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Sharing the UX documentation here for each edge case: https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740 ( https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740|smart-link )

**Comment by birdsarah** [comment]
Just discussed with baku we can use the remedy for this edge case to pre-empt people getting to the subscribe screen if they've already purchased - as opposed to letting them try and pick a plan. Because if they try and pick a plan they might pick a different time frame and be allowed to purchase twice.

**Comment by birdsarah** [comment]
Completed in #1541.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been verified as fixed on Mozilla VPN 2.5.0 (16303750) using an Android 9 Samsung Galaxy S10 Plus.

The user is not taken to the subscription screen and prompted to in app subscribe. Instead, they are taken directly to the below error screen:

!image-20210903-121116.png|width=401,height=871!

Sarah Bird please let us know if the above scenario is not correct, as it is not exactly as you described. Otherwise, we can consider this issue fixed/closed.

Thank you

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.
