### ISSUE TITLE
Android IAP Edge Case 3 - "Purchase validation" or "Purchase acknowledgment" fails

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1551]
Hoping that we can solve two error scenarios with one string, but maybe two are needed:

### Purchase validation fails

There is a failure scenario where, for a variety of possible reasons we are unable to "verify a purchase token."

Here's what happens:
* We load the subscribe page
* The user picks a plan and hits subscribe
* The native payment dialog loads and the user pays
* The payment is successful at this step and we receive a purchaseToken

The way google in app purchases work, after receiving a purchaseToken we send it to the server (fxa via guardian) and then that purchase token is validated / verified. This helps prevent fraud makes, sure everything lines up, and is how we tell FxA that a purchase has been made etc.

If all goes well, we get a `tokenValid = true` and we acknowledge the purchase and we're good to go (or see below).
But, if guardian / fxa are down or, more likely, they're functional but the result is `tokenValid = false` we need to display an error message.

Please see final section "what the user sees" before coming to conclusions.

### Purchase acknowledgment fails

All the above steps happen, and we get as far as `tokenValid = true`. So we tell Google "we acknowledge the purchase." This step can fail too. I'm not sure why / how it would fail - but I'm sure it could.

Please see final section "what the user sees" before coming to conclusions.

### What the user sees

In these two cases the user will get an initial email from Google telling them that they're subscribed.

The test version of this email looks like this:

----
<h5>Test: Your Google Play Order Receipt from Aug 12, 2021</h5>

<div style="margin: 20px 0px;font-size: 30px;line-height: 30px;text-align:left">
Thank you</div>
<div style="text-align:left">
This is a test subscription. It will recur according to <a href="https://notifications.google.com/g/p/AD-FnExMfKcylUYmIU_L0-7riZCnKbcCQZiAGmSiaOv2HkojVlqz8eIyIhfbRWLK-OIp9o5hCjtZhxKAAUNWFvTQlwCy8IbIkLf_B0Dq34XpLhi7f39JUxzIi12maJ69c5bUgIYoIIcPC_rGGnRYbupT6OBKm0moV6H0aAQvIHwSAsH3hw">this schedule</a>. You have not been charged. <br>
<br>
<div>
You've made a subscription purchase from <span dir="ltr"></span> on Google Play. Your subscription will <b>automatically renew on Aug 12, 2021, 8:08 PM CDT</b> unless you cancel before then. You can cancel at any time. <a href="">Manage your subscriptions</a>.
</div>
<br>
<div style="margin-bottom: 20px;text-align:left">
<b>
Order number: </b> GPA.3344-2583-5432-22046<br>
<b>
Order date: </b> Aug 12, 2021 8:03:24 PM CDT <br><b>Your account:</b> sarahmoztest@gmail.com
</div>

Item | Price
Test: Sarah's VPN Monthly (org.mozilla.sarah.vpn (unreviewed)) | $9.99/5 min
Auto-renewing subscription |  -

----

**If we fail to acknowledge the purchase** which could happen for either of the two reasons above, then Google will automatically cancel the subscription and the user should receive an email. I'm not exactly sure what that'll be. This is the test email I've been getting:

---
<h5>Test: Your Google Play Order Cancellation Receipt from Aug 12, 2021</h5>

This test purchase was cancelled because it was not acknowledged. You 
should ensure all purchases are acknowledged so they are not subject to 
refunds. For more information see <a href="https://notifications.google.com/g/p/AD-FnEzBY75IUYj4Kv6sSWkocaIVXGvzFsnGl_cLmd9Mz5OhmnlEE517h1U8FvxJioGSSz8FhhVM2d-gx1I51T6K5_vEPkxhVfr8eSgpop-u5wq46SB60YvAg5rOHrQw8dM-8TcegSTEDwU">https://developer.android.com/google/play/billing/integrate#process</a>. <br>
<div style="margin-bottom: 30px;">
</div>
<div style="margin-bottom: 20px;text-align:left">
<b>
Order number: </b> GPA.3344-2583-5432-22046<br>
<b>
Order date: </b> Aug 12, 2021 8:03:24 PM CDT

Item | Price
Test: Sarah's VPN Monthly (org.mozilla.sarah.vpn (unreviewed)) | $9.99/5 min
Payment method: | Test card, always approves

---

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-867)

**Comment by bakulf** [comment]
This can happen on iOS too. On iOS, we are able to retrieve the "receipt" and send it back to the guardian-website. Then, the flow continues as normal. Can we do something similar on android too?

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Sharing the UX documentation here for each edge case: https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740 ( https://www.figma.com/file/fXfxErqwSeqQzA65jcvwuZ/IAP-Android-iOS_Variable-Pricing?node-id=153%3A6740|smart-link )

**Comment by birdsarah** [comment]
Work done in #1541.

> This can happen on iOS too. On iOS, we are able to retrieve the "receipt" and send it back to the guardian-website. Then, the flow continues as normal. Can we do something similar on android too?

@bakulf - I have implemented logic to retry acknowledgement

@jess-cook03 - I used the existing reusable error screen. On it, the "Get Help" link is at the top right on the re-usable error screen so the text that was committed for string freeze that says "visit our help center below" is a little off.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

This is in QA column. But I’m not sure how QA can test this error state. Maybe through license tester options. But not sure.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Closing as not testable
