### ISSUE TITLE
Avoid duplicate object creation

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1553]
In our codebase, I see this pattern a few times:

```
const char *buffer = something();
QString foo = QString(buffer);
```

We do it with QString and with QByteArray, and probably elsewhere. This is not great because we end up creating 2 QString objects. Instead, we can simply write:

```
const char *buffer = something();
QString foo(buffer);
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-869)
┆Reporter: Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Gela Malek Pour maybe this is relevant for you misc thoughts about using clang tidy. But closing for now as progress has been made.
Closed during bug squashing.
