### ISSUE TITLE
Testing webapp (WASM) is broken

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#1560]
Reported by localizer: after selecting the language, this error appears

```
Application exit (To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking)
```

CC @bakulf

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-872)

**Comment by Patriccollu** [comment]
The problem appears as soon as **VPN connection is activated**.
