### ISSUE TITLE
Max-limit devices view  doesn't scroll on android

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#157]

**Comment by lesleyjanenorton** [comment]
@bakulf Is this happening in one of the emulators or on a physical device? And are you still able to reproduce? I just tried on a few emulators (Pixel 2, 3, and Nexus One) and was able to scroll on all.

**Comment by ValentinaPC** [comment]
I verified this on a real Android 10 device, while using last version of VPN, and the scroll option is working as expected.
Below you can see a video.
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/15685960/99515204-54880b80-2995-11eb-9aa8-84af0fb5fe90.gif)

**Comment by lesleyjanenorton** [comment]
Ok great - thank you @ValentinaPC ! I am going to close this in that case.
