### ISSUE TITLE
MultiHop: Add Settings infrastructure and The Bits™ to support Recent Connections

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1570]
To support [Multi-Hop UI](https://www.figma.com/file/3ro5ivHWvcQZFbRWGQbUoS/Multi-Hop-Feature?node-id=286%3A10518) the frontend needs:
- A list of Recent Connections. Each recent connection should consist of 1-2 server locations with a country code and localized city name for each location.
- A function to call when one of the Recent Connections options is clicked that updates the server location(s) accordingly (or maybe this can be achieved with existing functionality + the output of #1569 ?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-874)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync. Is there something the QA team needs to do for this ticket or can it be closed once more?

Thank you.
