### ISSUE TITLE
VPN using too many GPU resources on Windows

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#1579]
**Description**
VPN (version 2.4.1) is using high amount of GPU on Windows while the application is turned ON.

**Technical Information**
* Device version Windows 10
* FX product Mozilla VPN 2.4

![image](https://user-images.githubusercontent.com/72564534/129904282-a3d8034c-f877-4f8c-8ac3-f2dbc68af2ec.png)

Similar to Issue #846

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-877)

**Comment by strseb** [comment]
This will be Solved with the next release :) @flozia fixed this in 
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1545

**Comment by ValentinaPC** [comment]
Verified as fixed on 2.5.0 (2.202108191038), Windows 10, while VPN ON.
![image](https://user-images.githubusercontent.com/15685960/130208311-1ddcb13c-a203-417b-bcd5-9b9caa898c49.png)
