### ISSUE TITLE
Layout issue (truncated text) during connection

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#159]
![](https://user-images.githubusercontent.com/3644868/98379267-61c50200-2047-11eb-9cb8-94a659d62771.png)

The Italian translation is quite longer than English, so the text is cut and not completely readable during one of the screens in the connection phase.

Might be worth making the text wrap, and accounting for at least a couple of rows of text, so that the toggle doesn't move in most cases?

Version 2.202011051210 on macOS 10.15.7 (19H2)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-285)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
