### ISSUE TITLE
Add a certificate chain validation between guardian and the VPN client

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1601]
Right now, the client "trusts" the guardian-website endpoint. Maybe we should add extra security and validate the HTTPS certificates as we do for balrog.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-883)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

We're ok relying on https.
Closed during bug squashing.
