### ISSUE TITLE
5 star rating window doesn't show if not signed into app store

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1605]
Similar to IAP Edge Case 1 (#1528), but much less critical.

Steps to reproduce:

* Make sure android device is signed out of play store
* Go to leave review and press 5 stars.

https://user-images.githubusercontent.com/1796208/130331993-1aac96c3-e934-4361-b2e7-c65c891f5d7d.mp4

Video below with sign in to play store and it then working (sorry for the slow start while i fumble to find my password).

https://user-images.githubusercontent.com/1796208/130332034-5d3dc47a-9c8a-4791-9023-2baa3ffdd0ea.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-884)
┆Reporter: Data Sync

**Comment by bakulf** [comment]
We should check the log and see if the api returns an usable error code. Then we can "attach" the component used for AIP edge 1.
