### ISSUE TITLE
qml error - don't know if it's a problem

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1606]
I see this error a lot:
```
 Warning: qrc:/ui/components/VPNFocusOutline.qml:14:5: Unable to assign [undefined] to QColor (VPNFocusOutline.qml:14)
```

Maybe it's not a problem. Just flagging for @flozia @lesleyjanenorton.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-885)

**Comment by lesleyjanenorton** [comment]
Adding this to 2.5 as there is also an accessibility issue here. Somehow the visual focus changes got goofed up after a recent merge. Thanks for flagging.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Please add some steps for QA to check this. Lesley Norton Thanks!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics There is nothing to QA for this issue - thank you!
