### ISSUE TITLE
Systray menu on macOS shows identifiers instead of labels

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#161]
Not sure if they're identifiers, but they're definitely not labels. Currently using the Italian translation.

![](https://user-images.githubusercontent.com/3644868/98380041-56260b00-2048-11eb-8a21-2d22a889e60e.png)

Version 2.202011051210 on macOS 10.15.7 (19H2)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-287)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
