### ISSUE TITLE
Resolve DNS lookups through the VPN tunnel

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1610]
This is currently not possible in production. We need to run tests in staging. This issue is needed to have a reference in the code.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-887)

**Comment by data-sync-user** [comment]
➤ Basti (Sebastian) Streich commented:

closed by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1695 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1695|smart-link )
