### ISSUE TITLE
Clicking on a radiobox/checkbox label should enable/disable the input field.

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1615]
Currently, only the checkbox/radiobox graphical objects are clickable. Maybe we should include the label in the MouseArea. @lesleyjanenorton what do you think?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-889)
┆author: Data Sync

**Comment by lesleyjanenorton** [comment]
I agree - we'd just need to make sure there wasn't a conflict with scrolling on touch devices. CCing @peterbenvenuto @jess-cook03

**Comment by peterbenvenuto** [comment]
@lesleyjanenorton @jess-cook03 @bakulf Jess and I agree as well -- I think the label should be clickable (but not the description if there is one)

I also think we should not include any hover states when the user hovers over the label -- Material UI has a good example of this with their radio buttons/check boxes https://material-ui.com/components/radio-buttons/

**Comment by MattLichtenstein** [comment]
FWIW, our `VPNRadioButtonDelegate` component already does this, so this change just needs to be made to VPNCheckBoxRow + some tweaks to some of the views

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on Mozilla VPN 2.9.0 (2.202204012343) build from Main branch, and observed the following:

  * In Languages list the description is also clickable (see ss below);
  * The clickable area is until the end of the row (see ss below);
  * Buttons like “Cancel“ or “Sign out“ have the clickable area larger than the label;

!clickarea.png|width=869,height=434!

Based on these observation, I’ll reopen the issue.

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Betty Fleming I believe some of the fixes made it into 2.8, but the issues that Valentina Virlics mentioned in the comment above ( https://mozilla-hub.atlassian.net/browse/VPN-889?focusedCommentId=531475 ) are still in code review. What do we do in this scenario to ensure that this is tracked correctly? Make a new bug with the outstanding issues? Comment this bug defining what parts are in 2.8 vs 2.9?

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

yes, should be 2.9. Thanks!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last 2.9.0 (2.202205041856) Mozilla VPN build while using Windows 10.

Matt Lichtenstein Shouldn’t we reduce the clicking on label functionality only to the exact length of the label (string) and not use the entire row, as we currently do? Thanks!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Exactly, I just observed that 😛

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verifying this on Windows platform is blocked by https://mozilla-hub.atlassian.net/browse/VPN-2224 ( https://mozilla-hub.atlassian.net/browse/VPN-2224|smart-link )

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on the last VPN 2.9.0 (2.202205250346) build while using Windows 10.

Clicking on a radiobox/checkbox label enables/disables the input field.
