### ISSUE TITLE
Set up a google group email address for glean notification emails

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1619]
And then update `glean/metrics.yaml` so people can see archives and choose to subscribe if interested.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-891)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Sarah Bird I just noticed we have some metrics that include the email vpn@mozilla.com is that a real email? Is it the same thing you were talking about here. cc Adrienne Davenport may know the answer too.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Yes. It’s a real email. Support checks it. But we should set-up a new, proper one.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

vpn-telemetry@mozilla.com ( mailto:vpn-telemetry@mozilla.com ) has been created

Lesley Norton and Beatriz Rizental Machado have been set as owners of the google group.

You can see the group here: https://groups.google.com/a/mozilla.com/g/vpn-telemetry ( https://groups.google.com/a/mozilla.com/g/vpn-telemetry|smart-link )
