### ISSUE TITLE
After one cycle with new support form unwind storing support data in guardian

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1627]
For 2.5 we're storing the support form data in guardian db before forwarding on to zendesk via fxa.

If we can see that's going well then we should unwind storing the data as we're just holding it unecessary and we can let zendesk deal with it and it's just passing through guardian (and maybe in the future we can leave guardian out of this loop).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/PSP-187)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Adrienne Davenport can this go in guardian v1.19 epic? (https://mozilla-hub.atlassian.net/browse/VPN-1214 ( https://mozilla-hub.atlassian.net/browse/VPN-1214|smart-link ) ). I discussed this with Brian and this would be the right time to have given the data to settle. I’m going to add a subtask that we can put in the Guardian 1.18 epic the task to review the data to make sure we have not been seeing errors.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Changing priority to High after discussion with legal. This table contains PII and we don’t have deletion request support for it. So lets just make sure we actually get this deleted sooner rather than later.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

This was done by Jeremy Swinarton  in 1.22 and 1.23 releases.
