### ISSUE TITLE
Make signupsignin unit tests clean and matching guardian behavior

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1628]
There's been a lot of flakiness in the signupsignin unit tests. The current "fix" #1613 is a hack. This issue is to rework as necessary the signupsignin unit tests so they correctly work with the expected guardian and auth flow behavior.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-895)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

The unit-test is really stable in these days. Closing.
