### ISSUE TITLE
Remove 'get help' in top right of error screens 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1635]
!Screen Shot 2021-08-26 at 10.25.23 AM.png|thumbnail! 

Provided a screenshot of the UI spec --- I don't have an image of the current screen but going off of a note [~accountid:6047d245addbcd006ba913b3] made on these error screens having the link in the top right..... when we have the get help as the 2nd CTA below in the spec.

Just seeing how we can remedy this in the future.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-902)

**Comment by lesleyjanenorton** [comment]
Closing this as I think it was decided yesterday that "Get help" would stay in the upper right corner, following the pattern on other views.
