### ISSUE TITLE
After completing InApp purchase user gets Authentication Failure

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1641]
Steps to reproduce:
* Open android app
* Sign in with an account that does not have a subscription
* Complete in app purchase

Expected:
* User sees "please wait" screen
* User is take to main view to begin using vpn

Actual:
* User sees "please wait" screen
* User is taken back to main page with "Authentication error: Please try again"

This could be a client or a guardian bug.

Note: The in-app purchase has successfully worked though and they subscription can be viewed in the user's play store account and when they re-login with the same fxa account they will be able to use the app as normal. This is only an issue the first time after subscribing.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-906)

**Comment by birdsarah** [comment]
Fixed in guardian.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been verified as fixed on Mozilla VPN 2.5.0 (16303750) using an Android 9 Samsung Galaxy S10 Plus.
Thank you
