### ISSUE TITLE
Red border for email field after typing a correct email in Contact Support screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1654]
**VPN version:**

* 2.5.0 (2.202108251758);

**Affected Platforms:**

* Windows / Linux Focal;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;
* Have Developer options enabled for VPN;

**Steps to reproduce:**
1. Click “Get Help”-> “Developer options”;
2. Click “Feature list”
3. Enable the “unauthSupport” feature;
4. Restart the app;
5. Click “Get Help”-> “Contact us”;
6. Type a valid email in the first email field;

**Expected result:**

* The field border is blue;

**Actual result:**

* The field border is red even if the email entered is correct.

**Notes:**

* not reproducing for the second field.

!image-2021-08-30-17-24-45-223.png|width=200,height=183!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-915)

**Comment by ValentinaPC** [comment]
Verified this on the last VPN build.
The border of the first email field is blue after typing a correct email.
![image](https://user-images.githubusercontent.com/15685960/131972787-36e510b4-a091-4af3-b1d5-3ebbf2e984de.png)
