### ISSUE TITLE
“Submit” button is inactive for unauth Contact support option 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1655]
**VPN version:**

* 2.5.0 (2.202108251758);

**Affected Platforms:**

* Windows 10;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;
* Have Developer options enabled for VPN;
* Have the “unauthSupport” feature enabled;

**Steps to reproduce:**
1. Click “Get Help”-> “Contact us”;
2. Fill all mandatory fields and click “Submit”;

**Expected result:**

* Ticket is sent to support;

**Actual result:**

* “Submit” button is disabled;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-916)

**Comment by bakulf** [comment]
I'm unable to reproduce it. The mandatory fields are:
- email address
- confirmation email address
- category
- text content

basically the only optional field is the 'subject'.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last build 2.5.0 (2.202109022353).
The "Submit" button is active even if the email has an` xyz+eyz@domain.com` format.
