### ISSUE TITLE
If you enter too young an age when creating an FxA account you need to re-install to sign-up

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1657]
Steps to reproduce:
* Android, fresh install no existing account
* After hitting, Get Started, you are on the "enter your email" screen
* Put in an email address that doesn't have an existing FXA account
* On the "create a firefox account" page enter password and an age < 10 (I don't know what the cutoff is but <10 works for repro)

You get a "Cannot create account screen"

<img src="https://user-images.githubusercontent.com/1796208/131421344-0140309b-03ff-4bc4-9317-123780d1f3d1.png" width=100/>

If you click "x" and Get started to try again you are shown the same screen.

If you close the app and reopen you are shown the same screen. 

I was only able to try again by uninstalling and reinstalling.

This may be intentional, but it's good to be aware of the UX.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-917)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been verified as fixed on Mozilla VPN 2.5.0 (16306850) using an Android 9 Samsung Galaxy S10 Plus.

Validated both scenarios:

  * click "x" and Get started to try again you are shown the same screen.
  * close the app and reopen you are shown the same screen.

Thank you
