### ISSUE TITLE
Fix height for the What's new modal?

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1661]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-921)

**Comment by flozia** [comment]
@bakulf Having the the `next` button not move its position might be more user friendly. However, I’m not sure if this is possible without the risk of content being cut off. Right now we load the slides in the popup dynamically and can‘t determine the max height of the slides. We could change this, but then there is still the chance that shorter feature descriptions can lead to a lot of white space.

@peterbenvenuto What is you take on that?
