### ISSUE TITLE
Add accessibleName to VPNCollapsibleCard toggle

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1665]
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/336455944346cc9db1b4ea97592a863b29d77f53/src/ui/components/VPNCollapsibleCard.qml#L124-L125

We need to add an `accessibleName` here and potentially change it based on whether the card is open or closed. The `accessibleName` will also be used to populate the button's tooltip.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-923)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Matt Lichtenstein Could you please let us know what the QA needs to do on this one, if anything?

Thank you.

CC: Lesley Norton Madalin Cotetiu

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Absolutely Luminita Buruian,

  * Tooltip text when hovering over the chevron icon on the collapsible info card on the multi hop page should now say “Expand” when closed and “Collapse” when open
  * Screen readers should say “Expand” or “Collapse” depending on the state of the card when the chevron icon gains focus

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Thank you Matt Lichtenstein for your promp and helpfull response.

We will look into this as soon as possible, depending on priorities.

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Bianca Hidecuti - if I understand correctly, macOS is working as expected and the only problem is with generating strings for Windows? If so, can we move the status to “blocked” as that is what we are doing with other stories with the same issue (eg https://mozilla-hub.atlassian.net/browse/VPN-2270 ( https://mozilla-hub.atlassian.net/browse/VPN-2270|smart-link ))

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Matt Lichtenstein , yes, on MacOS this is working as expected. 

Moving this into “Blocked” status, as we are tracking the Windows issue here: https://mozilla-hub.atlassian.net/browse/VPN-2284 ( https://mozilla-hub.atlassian.net/browse/VPN-2284|smart-link ) 

Thank you.

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Linked https://mozilla-hub.atlassian.net/browse/VPN-2293 ( https://mozilla-hub.atlassian.net/browse/VPN-2293|smart-link ) as a blocker, as that bug should unblock this one
