### ISSUE TITLE
The What's New feature tour starts each time I restart the app

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1666]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-924)

**Comment by ValentinaPC** [comment]
Verified this on VPN 2.5.0 (2.202109011951) across platform.
The "What's new" tour is no longer triggered after each restart.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
