### ISSUE TITLE
Active server is not centered when going from ViewMain to the single hop server list when there are recent connections.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1670]
Active server is not centered when going from ViewMain to the single hop server list when there are recent connections.

Steps to reproduce: 
1.) Have at least one Single-hop recent connection
2.) Connected to the VPN via a Single-hop connection
3.) Click to the "Select location" button on the main view

Expected: 
The active server is vertically centered in the Single-hop server list view

Actual: 
The active server is offset by the height of the recent connections list. Strangely, this doesn't happen going from the Multi-hop tab back to the Single-hop tab. 

<img width="361" alt="Screen Shot 2021-08-31 at 9 53 01 AM" src="https://user-images.githubusercontent.com/22355127/131525382-86c56b3a-57bf-4bd4-b9e4-131fce814dab.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-927)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-927

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this while using the last build from 2.11 branch - 2.11.0 (2.202210270555).

The last location is still not centered while coming back from main screen.

Matt Lichtenstein If this is only fixed on 2.12, please update the Fix version. Thank you!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Yep, this is 2.12 - changed fix version and moving back to “Needs QA”

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed across platforms, while using the latest 2.12.

The previously selected server location is centered when going back to the location list.
