### ISSUE TITLE
Back tabbing from the server list to the tab bar is not possible.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1671]
The menu bar and tab bar become inaccessible by tabbing once you've tabbed into a server list.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-929)

**Comment by ValentinaPC** [comment]
Verified this across platform using VPN 2.5.0 (2.202109011951).
Keyboard navigation is possible through server list, back and forth.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
