### ISSUE TITLE
Linux Headless

### ISSUE THREAD

**Issue by lachesis** [mozilla-mobile/mozilla-vpn-client#1677]
I see that Qt5 is a dependency of this project. How can I run this VPN on a headless Linux server without X11?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-931)

**Comment by bakulf** [comment]
MozillaVPN works in command line mode too. See this documentation: https://github.com/mozilla-mobile/mozilla-vpn-client/wiki/Command-line-interface
@lachesis please, reopen the bug if you want to know more, or this my comment is not enough. Thanks!

**Comment by aredridel** [comment]
FWIW, it doesn't run without an X server running, the binary just aborts
