### ISSUE TITLE
Implement settings refactor

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1680]
**Figma Spec**
https://www.figma.com/file/iBkvpAPTSMQHeRxIrCynQi/Settings-Redesign?node-id=4%3A920

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-932)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on https://mozilla-hub.atlassian.net/browse/VPN-152 ( https://mozilla-hub.atlassian.net/browse/VPN-152|smart-link ) ;

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.
