### ISSUE TITLE
Add missing strings for the settings view

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1684]
To implement the settings redesign we will need to add the following strings

* "System preferences"
* "Connect VPN on startup”
* “Mozilla VPN will launch and connect when you start up your device”

[Figma spec](https://www.figma.com/file/iBkvpAPTSMQHeRxIrCynQi/Settings-Redesign?node-id=48%3A830)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-934)

**Comment by lesleyjanenorton** [comment]
Removing the 2.5 milestone as we will not be adding these strings for 2.5

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the latest VPN 2.7.0 (2.202111170702) build while using Windows 10.

The text for the start-on-boot feature was not updated.

Reopening.

!image-20211117-090550.png|width=288,height=134!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics the updated strings were merged today (12/6) and should be available in builds going forward. moving to ‘needs qa’.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton i see new strings, but not the ones mentioned above.

Expected strings: “Launch VPN app at startup“ title - "Mozilla VPN will launch when you start up your device or open the app" description;

Actual strings: “Connect VPN on startup” title - “Mozilla VPN will launch and connect when you start up your device“ description

Did the strings changed? Thanks!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton What do you think about my question? Thanks!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics I’ve updated the issue accordingly - the strings you reported are correct. Thank you for checking up on this!
