### ISSUE TITLE
Strange layout on linux

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1699]
![image](https://user-images.githubusercontent.com/515957/131824226-6167472c-0473-4688-baee-651b95b35313.png)

The UI goes back to normal when I click around. @lesleyjanenorton , what do you think?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-940)

**Comment by lesleyjanenorton** [comment]
This is really strange. Do we have any idea when this started happening?

**Comment by derenv** [comment]
![dns](https://user-images.githubusercontent.com/35734401/140322035-58d9d3d1-a5d9-4a33-a891-6dd3ebaf6b81.png)
![locations](https://user-images.githubusercontent.com/35734401/140322044-c9762324-e744-4e11-83c4-93a42926839f.png)

I've got similar issues on manjaro using kde plasma (X11, sddm and kwin, etc), is this related or should i open a new issue? It doesn't return to normal on clicking other areas, unlike above.

**Comment by oskirby** [comment]
> ![dns](https://user-images.githubusercontent.com/35734401/140322035-58d9d3d1-a5d9-4a33-a891-6dd3ebaf6b81.png) ![locations](https://user-images.githubusercontent.com/35734401/140322044-c9762324-e744-4e11-83c4-93a42926839f.png)
> 
> I've got similar issues on manjaro using kde plasma (X11, sddm and kwin, etc), is this related or should i open a new issue? It doesn't return to normal on clicking other areas, unlike above.

This is a known issue on KDE based distributions (see: #1937) and should be fixed in the next release cycle which we hope to ship sometime next week.
