### ISSUE TITLE
Add CLI funtionalities

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#170]
It would be great to use `mozillavpn` as a command-line tool.

I would love to have:

1. a way to complete the authentication in command line mode.
1. a way to activate/deactivate the VPN
1. see the list of servers
1. see the list of devices

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-291)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
