### ISSUE TITLE
Sort locations ignoring diacritics

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-mobile/mozilla-vpn-client#1703]
In French, États-Unis (United States) appears at the bottom of the list because of the diacritic on É. This is confusing for users, people will expect it to sit between Espagne (Spain) and Finlande (Finland).

This can be fixed using [Unicode’s Normalization Form D (NFD)](https://www.unicode.org/reports/tr15/#Norm_Forms) to sort strings.

![](https://user-images.githubusercontent.com/1294206/131838763-c808ce54-bea4-4768-a39a-1755f1c6653b.png)

cc @flodolo

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-942)

**Comment by bakulf** [comment]
Can you tell me which OS are you using? This should work correctly. At least I cannot reproduce it on Linux.

![image](https://user-images.githubusercontent.com/515957/131972428-b7443048-0c7f-4499-9030-ae1ce045bf48.png)

**Comment by TheoChevalier** [comment]
I’m using the test web app here https://mozilla-mobile.github.io/mozilla-vpn-client/ (in Firefox on macOS)

**Comment by flodolo** [comment]
The list looks correct also on macOS, so I'd expect this to be a problem with the WASM build (hopefully not affecting mobile either).

**Comment by bakulf** [comment]
Yes, I confirm that for android, linux, windows and macos, we have a proper collator component. I have to check iOS.
See https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/CMakeLists.txt#n800
