### ISSUE TITLE
Windows: Broker-Service crash on v6 DNS firewall rules. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1714]
Followup for https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1633:

Steps to reproduce: 
-> Set  v6 custom dns.
-> Enable.

Service crashes on FwpmFilterAdd0 in 
`allowTrafficTo(QHostAddress(config.m_dnsServer), 53, HIGH_WEIGHT),
        "Allow DNS Traffic to Defined DNS Server")`
Pretty sure we make a memory mistake in FWP_CONDITION_VALUE0_ at
`void WindowsFirewall::importAddress(const QHostAddress& addr,
                                    OUT FWP_CONDITION_VALUE0_& value)`

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-945)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Basti (Sebastian) Streich , do you have time to work on this?

**Comment by strseb** [comment]
yes :)
