### ISSUE TITLE
iOS - Stuck at "Subscription needed"

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/mozilla-vpn-client#173]
Using the Version 2.202011051214 build from TestFlight, it's not possible for me to get past the "Subscription needed" screen on iOS 14.2. 

Clicking the "Subscribe now" button the first time initiated the mocked IAP process, in which I completed the transaction successfully, but no UI interaction happened after that. Clicking the button again just results in iOS telling me I'm already subscribed:

![mpv-shot0002](https://user-images.githubusercontent.com/344777/98612682-f30cd080-22f4-11eb-8e50-b2f1ad5fd3e8.png)

And there appears to be no way to progress from here. Restarting the app results in the same screen, with the same prompts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-294)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
