### ISSUE TITLE
Multiple error messages in the DNS settings view

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1730]
![image](https://user-images.githubusercontent.com/515957/132192467-29019c43-0195-44f7-9bea-9d12833a138c.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-953)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on the last VPN 2.5.0 (2.202109060947) build on Windows 10. The notification in only listed under the custom DNS field.

!image-20210907-090139.png|width=286,height=446!
