### ISSUE TITLE
[Android IAP] Subscription plans are not fully translated into Spanish

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1742]
**VPN version:**

* 2.5.0 (16306850);

**Affected Platforms:**

* Android 9 on a Samsung Galaxy S10 Plus;

**Prerequisites:**

* Have Mozilla VPN installed on your device;
* Have one FxA account without subscription;
* Use Mozilla VPN with Spanish;

**Steps to reproduce:**
1. Open the VPN app;
2. Log in with an account without subscription;
3. Take a look at the VPN subscription page;

**Expected result:**

* The details on the VPN subscription screen are in Spanish;

**Actual result:**

* Not all the details on the VPN subscription page are translated into Spanish (see subscription plans);

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-958)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

The translation for es_CL is wrong (maybe).

<target>%1/month</target>

Francesco Lodolo can you please check?

**Comment by data-sync-user** [comment]
➤ Francesco Lodolo commented:

I fixed it directly, based on the other Spanish translations.

For the reporter: specifying which Spanish would help, since we have 3 of them.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Hi Francesco Lodolo sorry for the missing information.

In the Language setting for the Mozilla VPN I have 2 Spanish options:

  * Español => which is the one where the issue reproduces;
  * Español, Argentina => where the issue does not reproduce;

Please let me know if there is anything else you need.

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Francesco Lodolo commented:

Andrea Marchesini Do you have any idea why only 2 Spanish versions show up, when we should have 4 at this point? I can confirm that this happens on my Android too. On top of that, we’re using es-CL for “Spanish” apparently.

This is the WASM test app

!Schermata 2021-09-07 alle 15.29.45.png|width=514,height=782!

**Comment by bakulf** [comment]
the 4 Spanish languages is fixed by #1764

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been verified as fixed on Mozilla VPN 2.5.0 (16310720) using an Android 9 Samsung Galaxy S10 Plus.

I can confirm that there are 4 Spanish options:

  * Español de España - fully translated
  * Español, Argentina - fully translated
  * Español, Chile - fully translated
  * Español, México - fully translated

Thank you

CC: Valentina Virlics
