### ISSUE TITLE
 Update banner not displayed while forcing the update through Web Controller

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1744]
**VPN version:**

* 2.5.0 (2.202108251758);
* 2.5.0 (2.202109031603)

**Affected Platforms:**

* Windows 10;
* Mac OS 10.15

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;

**Steps to reproduce:**
1. Login to VPN using the account from prerequisites;
2. Go to WebController http://localhost:8766/
3. Force the update (force_update_check 1.0/1.5)
4. Observe client behavior;

**Expected result:**

* An update banner is displayed.

**Actual result:**

* Nothing happens;

**Notes:**

* Attaching logs from Windows.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-959)

**Comment by strseb** [comment]
This seems to be a balrog issue. 
`curl https://stage.balrog.nonprod.cloudops.mozgcp.net/json/1/FirefoxVPN/1.0/WINNT_x86_64/release-cdntest/update.json`
gets me 
```
HTTPSConnectionPool(host='autograph.stage.autograph.services.mozaws.net', port=443): Max retries exceeded with url: /sign/hash (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))
```

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Tried with the last build 2.5.0 (2.202109080825) from release branch, on Windows.

Now the required update screen is displayed, but the recommended one is still missing.

Attaching new logs. Command used: 

[^mozillavpn-2021-9-8.txt]

{quote}force_update_check 1.5{quote}

**Comment by data-sync-user** [comment]
➤ Basti (Sebastian) Streich commented:

We got the issues with balrog resolved, i noticed a bug that the “update recommended” alert does not do anything. A pr for that is in review 😀

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

The banner is triggered via the Inspector while using the Windows signed build. Clicking on it, triggers an installer, but after stops. Will recheck after the PR you mention is done.

!image-20210914-084559.png|width=304,height=459!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Works as expected. We can close this. Thanks everyone!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Lesley Norton , Sebastian Streich This is happening again using the last signed Windows build.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

The update banner is now displayed using the lastest Windows signed build.
