### ISSUE TITLE
Mozilla VPN does not launch on device startup when the “Launch VPN app on startup” option is enabled

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1746]
**Affected versions**:

* Mozilla VPN 2.5.0 (2.202109031603)

**Affected Platforms**:

* MacOS Big Sur 11.5.2;

**Prerequisites**:

* Have an FxA account with an active subscription for Mozilla VPN;
* Have Mozilla VPN app installed and opened;

**Steps to reproduce**:
1. Go to Settings;
2. Check “Launch VPN app on startup” option;
3. Restart your device;
4. Observe the behaviour;

**Expected result**:

* On startup the VPN app launches successfully and the VPN is activated automatically.

**Actual result**:

* On startup the VPN app does not launch.

**Notes**:

* 【 highlighted #ff5630 】This is major issue because the user cannot use the “start on boot“ feature;【 end highlighted 】
* If the application is opened by the user, the VPN is activated automatically.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-960)

**Comment by bakulf** [comment]
is this a regression?

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

It’s not a regression. Tried to reproduce this on older versions (2.3.2 and 2.4.0) and the Mozilla VPN does not launch on startup. Also, this is not reproducible on Windows and Linux.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this on Mozilla VPN 2.5.0 (2.202109100617), while using MacOS Big Sur 11.5.2 and Mozilla VPN does not launch on startup. Reopening.

**Comment by bakulf** [comment]
Madalin, the patch has not been merged yet. Can you please test it again in 1 hour?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Verified this on Mozilla VPN 2.5.0 (2.202109111824) and 2.6.0 (2.202109130734), while using MacOS Big Sur 11.5.2 and Mozilla VPN does not launch on startup. Reopening.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Three production users on Mac with the v2.5 VPN client confirmed they are able to connect and did not see the red banner.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We reach out other Mozillians, that have not used in the past Mozilla VPN and asked their help.

The following behavior was observed:

  * After install->check "launch at startup"->device restart => VPN is automatically opened, but remains in “Connecting…” state
  * “Connecting…” state -> VPN uninstall => no internet connection;

Important: internet connection fixed only with router restart;

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Connectivity issues must be fixed, but they are unrelated. Can we close this bug?

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this on Mozilla VPN 2.6.0 (2.202111031254), while using MacOS Big Sur 11.6 and MacOS Catalina 10.15.7.

On startup the VPN app still does not launch.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

We were able to further investigate this on other devices (Catalina 10.15, Catalina 10.15.7, Big Sur 11.6) while using last VPN 2.6 build (2.202111041035) and noticed that:

Catalina 10.15, Catalina 10.15.7

  * feature "Launch VPN app at startup" checked + restart device => VPN is not launched at all - no matter what actions we perform on the app before restart (quit, turn on, turn off);
  * feature "Launch VPN app at startup" checked AND VPN added in the System Preferences >Users & Groups  Current User -> Login items + restart device => VPN is launched and ON;

Big Sur 11.6

  * feature "Launch VPN app at startup" checked + quit app + restart device => VPN is NOT launched;
  * feature "Launch VPN app at startup" checked + restart device => VPN is launched and ON;
  * feature "Launch VPN app at startup" checked AND VPN added in the System Preferences >Users & Groups  Current User -> Login items + restart device => VPN is launched and ON;

So, in our opinion, we should either add the app automatically in the System Preferences or inform the users that they need to do it themselves.

Hope it helps!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

It turned out that the issue is related to an unsigned login-item embedded
profile.  On github, we do not sign the login-item as we should. Because of
this, the app runs correctly only on devices with the correct provisioning
profile installed.

This issue should not be reproducible in prod builds.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202111091350) - Staging and Production servers, while using MacOS Big Sur 11.6 and Catalina 10.15.7. 

After checking the "Launch VPN app at startup" feature, the VPN app launches successfully on startup and the VPN is activated automatically no matter what actions we perform on the app before restart (quit, turn on, turn off).
