### ISSUE TITLE
[iPad] Red banners are too small

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1754]
**VPN version:**

* 2.5.0 (2.202109031936);

**Affected Platforms:**

* IOS 14.02;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;

**Steps to reproduce:**

1. Login to VPN using the account from prerequisites;
1. Trigger a red banner; (Get Help - Contact us ~~> PP link~~ > back to VPN)

**Expected result:**

* The banner is the correct size.

**Actual result:**

* The banner is smaller;

!image-2021-09-07-17-03-12-075.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-964)

**Comment by flozia** [comment]
@jess-cook03 @peterbenvenuto What are your thoughts on this? Should the notification banners fill the screen width on iPad or do we have any intermediate sizes for different breakpoints?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We verified this on the last VPN build 2.7.0 (2.202112051650) on iOS.

The red or green banners are smaller than iPad display.

Reopening.

!image-20211206-090210.png|width=366,height=311!
