### ISSUE TITLE
Question mark appended to “What’s new” string for some locales

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#1760]
I checked with @chrisrooneys and @peterbenvenuto and it seems like we do not want to display the `?` appended to some translations. The original english string also did not have one.

For now we could just remove the question mark dynamically or how is this handled best?

Original comment ⬇️
---

@flozia Thanks for the detailed response.
Checking different languages we observed that:
- in some of the langs (German) where the string is translated the "?" was added at the end. I expect to see that in English also. What do you think?
- The string is not update after language switch only after navigating away from Settings screen
- the What's New screen content is not wrapped for some langs

![what](https://user-images.githubusercontent.com/15685960/131660580-8f2589f6-fc58-4856-826c-275134405b8b.png)

_Originally posted by @ValentinaPC in https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1529#issuecomment-910166625_

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-967)

**Comment by flozia** [comment]
@flodolo What are our options here? In this case there are question marks appended to some strings — the original english version did not have one and it was not meant to be a question.

**Comment by flodolo** [comment]
I think that's fair for locales to have a question mark, even if English doesn't have one.

**Comment by chrisrooneys** [comment]
@flodolo thanks! If you're comfortable with the question mark added here, then so am I!
