### ISSUE TITLE
Increase frequency of account checks to meet security best practices

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1777]
This could be as simple as increasing the frequency of TaskAccountsAndServers or it could mean implementing a new task and endpoint that just does oauth token verification.

Ref: https://infosec.mozilla.org/guidelines/iam/openid_connect#session-handling

> If the user’s complete session duration is longer than 15 minutes, must re-check/update the ID token every 15 minutes or next user request (whichever comes first), to ensure that the user is still valid and has correct permissions.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-977)

**Comment by bakulf** [comment]
Changing this for 2.6 is OK. I suggest increasing just_ the account check task execution and not all the others (server list, etc).

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

This also has a guardian component. I’ve pushed a change to guardian but the recommended fix is currently not 100% clear from the secops / fxa team.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

The pushed change had to be backed out. This issue is blocked awaiting guidance from secops / fxa.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Taking this out of v1.17 epic as I don’t have any instructions from secops yet.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Closing while we learn what recommendations are.
