### ISSUE TITLE
Frondend issues with the contact-support error view

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1789]
![image](https://user-images.githubusercontent.com/515957/132733920-f2a78ab9-0e56-4ddc-ac38-d4d84249aa71.png)

This is what I see on linux.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-981)

**Comment by lesleyjanenorton** [comment]
Looks like @mbirghan has fixed this in #1734
