### ISSUE TITLE
Quick access screen - "You can quickly access Mozilla VPN from your status bar" - I think we do not have a status bar on devices?

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#179]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-299)

**Comment by ValentinaPC** [comment]
Verified as fixed using the latest VPN build, on Android 10.
The "Quick access" screen was removed on mobile.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
