### ISSUE TITLE
"Launch VPN app on Startup"  - does not work on Android

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#180]

**Comment by strseb** [comment]
Closing this. 
On devices with android < Nougat we should be offering launch vpn on startup should work as expected. 
On devices with android >= Nougat this setting should be hidden. 
Instead users can enable under Device Preferences -> Networking -> VPN the "Always On" Option for Mozilla VPN. This should aswell start the vpn on boot.

**Comment by ValentinaPC** [comment]
Verified this as fixed on Android 10, using the latest cross-plat VPN build.
The "Launch VPN app on Startup" option is hidden.
The "Always On" option for Mozilla VPN triggers the VPN start on system boot.

We do not have an Android < v.7.0 to check the other scenario.
