### ISSUE TITLE
binding loop detected for property "text" in the DNS settings

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#1801]
[10.09.2021 17:11:48.741] Warning: qrc:/ui/components/VPNViewDNSSettings.qml:78:21: QML VPNTextField: Binding loop detected for property "text" (VPNViewDNSSettings.qml:78)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-984)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Andrea Marchesini Lesley Norton Florian Zia Is this something the QA team ca verify or should we just close this?

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Luminita Buruian We can close this — thank you!
