### ISSUE TITLE
%1 in text for support form success form

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1805]
![Screenshot from 2021-09-10 10-44-46](https://user-images.githubusercontent.com/1796208/132891792-c2a0c848-44e9-47e5-ab08-9bee46f565ae.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-992)

**Comment by bakulf** [comment]
This is now fixed.
