### ISSUE TITLE
Installation tips for Arch/Manjaro Linux

### ISSUE THREAD

**Issue by olerich** [mozilla-mobile/mozilla-vpn-client#1814]
# Install on Arch or Manjaro Linux
A write up on what is needed to compile in Arch: 

**Dependencies:**

```
pacman -S qt5-base qt5-tools qt5-networkauth qt5-charts qt5-websockets qt5-graphicaleffects qt5-quickcontrols2 wireguard-tools resolvconf go
pip3 install glean_parser
pip3 install pyyaml
git submodule init
git submodule update
```

**Patch**
At the time of writing is a regression bug preventing compilation on Arch, see #1490, which is the pull request causing the problem. 
To circumvent, edit the file `src/src.pro` and _remove_ the offending lines at 382ff: 

```
system(c++ -lgo 2>&1 | grep "__go_init_main" > /dev/null) {
      LIBS += -lgo
 }
```

**Installation**

```
./scripts/git-pre-commit-format install 
./scripts/generate_glean.py
./scripts/importLanguages.py 
qmake CONFIG+=production
make -j$(nproc)
sudo make install 
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-996)

**Comment by brochard** [comment]
I'm a noob on Manjaro, I followed these steps, (didn't do the patch since it's not necessary anymore ?) and it didn't work at the step
`./scripts/importLanguages.py `

it show
![Screenshot_20211110_163232](https://user-images.githubusercontent.com/31168075/141143551-ca2e5727-d267-4cae-b013-03b495be1d44.png)

**Comment by a5tabout** [comment]
@brochard Did you try running it with sh, not zsh ?

**Comment by brochard** [comment]
> @brochard Did you try running it with sh, not zsh ?

Since I'm on kde, I think it's sh by default

**Comment by a5tabout** [comment]
> > @brochard Did you try running it with sh, not zsh ?
> 
> Since I'm on kde, I think it's sh by default

I'm on KDE too :smiley_cat: 
Your Konsole is running zsh though, you can change this  : Settings -> Edit Current Profile -> Command 
Change the Command to `/bin/bash`, open a new window and try executing the script again

**Comment by brochard** [comment]
> Change the Command to `/bin/bash`, open a new window and try executing the script again

Thanks, managed to switch to bash but I got the same error, installed make from the AUR but I think I'm still missing g++ that I can't find in the store
![Screenshot_20211114_170503](https://user-images.githubusercontent.com/31168075/141688768-142e812b-62a2-45f9-8ff4-1307d52b96bd.png)
.

**Comment by aktaboot** [comment]
Do you have g++ installed on your system ? try `g++ --version`
If you have an error, Install g++.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Closing as stale as build steps have changed dramatically (esp with new cmake and conda dependency management)
Closed during bug squashing.
