### ISSUE TITLE
QML Error: Stack View is not defined

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1828]
After updating to 2.5.0 on my Ubuntu test VM, I am now getting a QML error due to a change in VPNAlerts.qml as follows. So far I have seen this on both Ubuntu bionic and focal. This doesn't appear to stop the VPN client from functioning in any way that I have seen.

```
qrc:/ui/components/VPNAlerts.qml:19: ReferenceError: StackView is not defined (VPNAlerts.qml:19)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1006)

**Comment by flozia** [comment]
@oskirby I have come across this error message earlier today while working on #1826 and fixed this there. However, I have not noticed any problems without the fix as well.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Florian Zia Is there a way for QA to verify this? I think the Jira automatically puts the issue in “needs QA“ if it is closed in GitHub.

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Valentina Virlics This doesn’t need QA — thank you!
