### ISSUE TITLE
[Android 10] Mozilla VPN crash at launch "fatal error"

### ISSUE THREAD

**Issue by smaimon** [mozilla-mobile/mozilla-vpn-client#1831]
### Current Behavior:
mozilla VPN crash at launch with message :
> Your application encountered a fatal error and cannot continue

### Steps To Reproduce:
1. Download from /e/ store (f-droid fork)
2. Launch
3. See fatal error

### Environment:
- Phone : Fairephone 3
- OS: [/e/](https://e.foundation) Andoid 10 e_FP3-userdebug 10 QQ3A. 200805.001 eng.root.20210827.151157dev-keys,stable-release

### Anything else:
I use personal DNS filter think it could be the reason why the app crash but I deactivate it and the problem persist

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1010)

**Comment by smaimon** [comment]
I install the app without problem from aurora store. I open an issue to /e/

**Comment by smaimon** [comment]
Hi @bakulf I suggest you take a look at the point discuss here : https://community.e.foundation/t/fatal-error-using-app-mozilla-vpn-with-fairphone3/34884/3

**Comment by tcecyk** [comment]
the gist is - could Qt use the abi of the apk installed, instead of the device arch, if backwards compatible. This is for the niche of users who somehow installed not the ideal arch, mostly via 3rd party apk mirrors

**Comment by strseb** [comment]
I'm not quite sure how the apk landed there but fyi; the CI also generates "universal" .apks that "should" work everywhere :) - They probably are better suited for other distribution channels.

**Comment by tcecyk** [comment]
thanks @strseb for pointing to signed universal apks straight from the ci.

Is there an easy way to match release version git ref to its ci run in the actions? I had difficulty doing this.

It really is a bug with the App installer of /e/ interacting with the apk mirrors API that leads to the installation of the wrong arch, it's detailed at https://gitlab.e.foundation/e/backlog/-/issues/3809

**Comment by strseb** [comment]
You can filter Ci actions by branch, so you can select any release branch and try to fetch the artifacts there e.g
i.e android 2.5.1 https://github.com/mozilla-mobile/mozilla-vpn-client/actions/workflows/android.yaml?query=branch%3Areleases%2F2.5.1
Note they are as far as i know only kept for 30 day's or so (github policy) - it's planned to have a nicer archive for them :)
