### ISSUE TITLE
Android: Add an in info-alert on VPN-Permission Rejection

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1837]
Currently on start on android this screen is shown if the user has not given us permission to start a system-vpn. If the user presses "no", we stop the activation. 
Maybe we should show an alert indicating why the activation stopped.
![image](https://user-images.githubusercontent.com/9611612/133777015-60eb0e20-bc3c-46e0-815c-53e7a9024c6e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1022)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

This will come up from UX if it's needed.
Closed during bug squashing.
