### ISSUE TITLE
[FP3+][LineageOS] VPN app fails to start for 2.5.0

### ISSUE THREAD

**Issue by ancoron** [mozilla-mobile/mozilla-vpn-client#1841]
Application startup fails with:
> Your application encountered a
> fatal error and cannot continue.
>
> OK

App Version: 2.5.0
Phone Model: Fairphone 3+
OS: LineageOS 18.1 (Android 11)

Downgrading to app version 2.4.0 works around this issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1026)

**Comment by strseb** [comment]
Hi! Did you get the apk via the play store, or did you get it via the " /e/ store"? In that case might be a dupe of: 
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1831

**Comment by ancoron** [comment]
@strseb Sorry for the late reply, but neither, actually. I have installed it via apkpure, since it is not available via F-Droid:
* https://apkpure.com/mozilla-vpn-a-secure-private-and-fast-vpn/org.mozilla.firefox.vpn

So it might still be the same or related issue.

**Comment by ancoron** [comment]
Tested the arm64 build from here, which worked just fine:

* https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/1243325224

So that's obviously not your issue.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

The issue has been closed by the reporter, without any fix being done for it.

closing this, as no QA activities seem to be needed for this.

Thank you.
