### ISSUE TITLE
iOS - what new feature not being shown at all (not in settings or anything)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1850]
!IMG_6596.PNG|thumbnail! 
See image attached -- iOS 14.8 and release version 2.5.0 (2.202109171014)
Date: 9/21/21

I am not seeing the Whats New feature at all in iOS

Expected treatment:

* Whats new would be prompted as soon as I open the updated app (this didn't happen)
* Whats new will live in the settings and can be accessed this way and it is not there

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1030)

**Comment by flozia** [comment]
There should be no action required on this issue and will be resolved with #1853.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

What’s new feature is displayed on Mozilla VPN 2.7.0 (2.202112211200), while using iOS. 

Closing this issue.
