### ISSUE TITLE
Enable Advanced DNS settings on iOS

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#1852]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1031)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Lesley Norton Basti (Sebastian) Streich Is there something the QA team needs to do on this issue or should we just close this?

Thank you.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This feature was tested as part of 2.5 while enabling it from Dev options, but will be released as part of 2.5.1.
Closing this ticket.

CC: Valentina Virlics
