### ISSUE TITLE
VPN client hangs on multihop server switch

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#1875]
When performing a server switch with multihop enabled, and one of the servers is unchanged, this can sometimes result in the VPN client hanging, and failing to connect. An examination of the wireguard devices shows that one of the expected hops is completely missing.

**Steps to Reproduce (multihop to multihop)**:
1. Start the VPN client
2. Open the server selection menu and configure a multihop connection.
3. Activate the VPN and verify that you are connected.
4. Open the server selection menu and change only the entry server.
5.  Click the back button to initiate the server switch.

**Steps to Reproduce (single hop to multihop)**:
1. Start the VPN client
2. Open the server selection menu and configure a single hop connection.
3. Activate the VPN and verify that you are connected.
4. Open the server selection menu and click on the multihop tab. This should use your single hop location as the exit server and choose an entry server at random.
5.  Click the back button to initiate the server switch.

**Expected Behaviour:**
- VPN client switches servers, and reports an active connection within a few seconds.

**Actual Behaviour:**
- VPN client hangs forever while trying to connect.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1043)

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified as fixed on Mozilla VPN 2.6.0 (2.202109271722), while using MacOS Big Sur 11.6. VPN client switches servers, and reports an active connection within a few seconds. 

We will verify on Windows builds as well, and if the issue is not reproducible on Windows, then we will close the issue.

Thank you.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified as fixed on Mozilla VPN 2.6.0 (2.202109281203), while using Windows 10. VPN client switches servers, and reports an active connection within a few seconds. Closing this.
