### ISSUE TITLE
How to communicate errors during the subscription flow?

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#188]
<img width="432" alt="Screen Shot 2020-11-16 at 2 48 26 PM" src="https://user-images.githubusercontent.com/22355127/99306405-cab43300-281a-11eb-9583-e87f6073bbf0.png">
From this screen, if the user clicks "Subscribe Now" and something goes wrong, we need a way to communicate the error to the user.

**Comment by chrismore** [comment]
We should add our terms of service, download terms, and privacy policy to the bottom of this screen before they make their IAP payment, which is exactly what we do below the "pay now" on the web payments flow:

Terms of Service: https://www.mozilla.org/about/legal/terms/mozilla-vpn/
Download Terms: https://accounts-static.cdn.mozilla.net/legal/Mozilla_VPN_ToS/en-US.pdf
Privacy Notice: https://www.mozilla.org/privacy/mozilla-vpn/

As seen here:

![image](https://user-images.githubusercontent.com/751491/100767026-e6910a80-33be-11eb-90a5-40dfdc7316c2.png)

**Comment by jess-cook03** [comment]
Screengrab of what exists today:
<img width="362" alt="Screen Shot 2020-12-01 at 10 36 37 AM" src="https://user-images.githubusercontent.com/54991698/100769849-97e96d80-33ca-11eb-9359-3d455b0b2cc7.png">

View that comes after this screen when user selects 'Subscribe now':
![IMG_4897 2](https://user-images.githubusercontent.com/54991698/100770060-d848eb80-33ca-11eb-9640-c9f8dbb4552f.PNG)

**Comment by chrismore** [comment]
@lesleyjanenorton @bakulf @jess-cook03 I talked to legal and they said to add the terms and privacy policy links at the bottom of the screen that has the "subscribe now" button, similar to how we have it on web payments. We could probably just put the two links on one line. No extra text is needed.

e.g.

<a href="https://www.mozilla.org/about/legal/terms/mozilla-vpn/">Terms of Service</a> | <a href="https://www.mozilla.org/privacy/mozilla-vpn">Privacy Notice</a>

**Comment by jess-cook03** [comment]
@chrismore @bakulf @lesleyjanenorton 
Exploring a few different options we could go with for this terms & privacy treatment.

**Screen 308** - this is the option I would recommend 
Keeping the smaller text size and grey color pushes it back from the other more important CTAs that share the same area of the layout.... also hierarchy wise pushing the terms to the very bottom of the page makes the most sense.

I explored using the blue link treatments, and reflecting the same treatment as web payments and it seemed to clash when brought together with the other CTAs... also from a user perspective treating it grey as tertiary information but keeping the line underneath the active text lets users know, this is a link but its not the primary action we want you to make right now, but its here if you want it.

If we are set on aligning to the web payments treatment -- I think we can make it work as well.

![Screen Shot 2020-12-02 at 10 38 59 AM](https://user-images.githubusercontent.com/54991698/100898763-17407500-348f-11eb-86a9-5c96dd5e6b52.png)

Let me know what we all think!!

**Comment by chrismore** [comment]
I like this one @jess-cook03 

![image](https://user-images.githubusercontent.com/751491/100903294-566cc700-348b-11eb-87f0-0a4e63f3b781.png)

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton 
Following up on the error flows:

We have two options as I was mentioning yesterday for this...
**Option A** where we surface an error toast component or **Option B** we leverage iOS native alert message....
both solutions we will have the **users directed back to the subscribe page** instead of the initial landing page like before.

Link to figma file >> [here.](https://www.figma.com/file/FhYZu3RiEbCNVLQnZ1q1MS/IAP?node-id=225%3A79)

![Screen Shot 2020-12-02 at 2 18 41 PM](https://user-images.githubusercontent.com/54991698/100920820-a8244a00-34a9-11eb-8380-b18d1cf1e248.png)

**Comment by jess-cook03** [comment]
@bakulf 
@lesleyjanenorton 
After reviewing we have decided to implement **Option B** (see above) and Figma spec is also linked above

**Comment by chrismore** [comment]
@lesleyjanenorton can you confirm where the "try again" link goes now in the red error dialog for option A in the screenshot above? If it goes to the subscribe, let's move this priority to a P2. We'll leave it as a P1 until we verify that link.

@lesleyjanenorton we have the other issue of adding the terms and privacy links below the subscribe CTA (https://github.com/mozilla-mobile/mozilla-vpn-client/issues/188#issuecomment-737353140) I will file the issue and assign it to you  and mark that as a P0.

**Comment by chrismore** [comment]
@lesleyjanenorton were you able to verify where the try again link goes to on the latest build?

**Comment by lesleyjanenorton** [comment]
Closing as fixed -> errors are surfaced during the subscription flow.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN beta build on iOS 14.2, Android 10.
The errors are displayed on top of the screens.
Also the ToS and PN links were added under the "Subscribe now" button.
![image](https://user-images.githubusercontent.com/15685960/101904705-ee229180-3bbe-11eb-8d85-d82e5e4359bc.png)
![image](https://user-images.githubusercontent.com/15685960/101904755-ff6b9e00-3bbe-11eb-92d8-aa3a2a5435a5.png)
