### ISSUE TITLE
Need to scroll in Subscribe screen to see all options available

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#191]
Issue in https://github.com/mozilla-mobile/guardian-vpn-ios/issues/294

TF version: 2(2.202011121142)
iPhone 6s

**Steps**
Launch the app and sign in with a valid account

**Expected**
Subscribe screens is shown correctly

**Actual**
The screen is correctly shown but it is necessary to scroll to see all options, Restore purchases and Sign Out. It would be nicer to fit all the elements in there since there is plenty of space for that. See screenshot:
![IMG_8796](https://user-images.githubusercontent.com/1897507/98943569-0041df00-24f0-11eb-9b89-81cf4e9e9ab4.PNG)

**Comment by chrismore** [comment]
We will re-evaluate this screen with scrolling and the subscribe CTA for the future redesign of the app. We are not going to block v2.0 release.
