### ISSUE TITLE
Pre-populate "Use Staging Servers" with staging server url

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#1913]
It's pretty annoying manually entering the staging url.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1075)

**Comment by bakulf** [comment]
For desktop, you can set the env variable.

**Comment by birdsarah** [comment]
For desktop, this is not as annoying :D

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on the VPN 2.7.0 (2.202111100111) build.

The staging URL is pre-populated.

!image-20211110-085222.png|width=296,height=462!
