### ISSUE TITLE
[iOS]Close button in Subscription screen does not

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#192]
Issue in https://github.com/mozilla-mobile/guardian-vpn-ios/issues/293
TF version: 2(2.202011121142)
iPhone 6s

**Steps**
Start the app
On Subscribe screen tap on 'x' button

**Actual**
The button is clicked but nothing happens

**Expected**
That screen is closed and the main view is shown

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-308)

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
The "Cancel" button from subscription screen works as expected.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
