### ISSUE TITLE
[iOS] User is logged out and Authentication error is shown after successfully finish the subscription

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#194]
TF version: 2(2.202011121142)
iPhone 6s

**Steps**
Complete the flow to Subscribe an account

**Expected**
After finishing the flow user remains on the main screen to start using the app

**Actual**
User is logged out. First onboarding screen is shown with an error: Authentication error. Try again even though the subscription has been done correctly. If you log in again, the app starts in the correct screen being able to enable the Turn VPN on toggle
![IMG](https://user-images.githubusercontent.com/1897507/98960772-202fcd80-2505-11eb-8c3b-54aad51a0f92.PNG)UNITO-UNDERSCORE!8802!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-309)

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
After finalizing the subscription user is redirected to the VPN activation screen.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
