### ISSUE TITLE
Adjust events are missing in VPN logs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1954]
**VPN version:**

* 2.5.1 (2.202110011311)

**Affected Platforms:**

* iOS 14.4;

**Prerequisites:**

* Have one FxA account without subscription for Mozilla VPN;

**Steps to reproduce:**
1. Install a fresh copy of the VPN
2. Check the logs for Adjust events;

**Expected result:**

* There are specific Adjust events in the VPN logs for both installs and IAP subscriptions.

**Actual result:**

* There are only 2 Adjust events: “Creating the AdjustProxy server and AdjustProxy listening on port xxxx”

**Notes:**

* Same happens on Android 10 using the last 2.5.1 build.
* see logs: https://controlc.com/ecb2e45c

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1103)

**Comment by bakulf** [comment]
This is now fixed for iOS. I'm going to test android too.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified as fixed on Mozilla VPN 2.5.1 (16335140), while using Android 10 and Android 9. Following the testing steps described in the Adjust - SDK doc ( https://docs.google.com/document/d/1vmtAetj5sdh7qWKs8mNBKRikY82pJyNMR--xTnkBmHE/edit# ), all 4 events are listed in the VPN log file. 

Closing this.
