### ISSUE TITLE
Tune the number of seconds between an ip check and the next one

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#198]
So far it's 10 seconds, but it's too aggressive. Maybe 10 minutes is enough.
Or better: when the connection-info view is opened.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-311)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
