### ISSUE TITLE
Fix Windows 11 Version detection properly. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#1984]
We're going to land a hacky solution in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1982 
We should be able to replace it with a cleaner one, once windows 11 has been fixed :)

```
    NetWkstaGetInfo -> Should report Windows 11 on windows 11
    HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> Should also report 11 
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1129)

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Related to https://mozilla-hub.atlassian.net/browse/VPN-1107 ( https://mozilla-hub.atlassian.net/browse/VPN-1107|smart-link )
