### ISSUE TITLE
Complete the UI

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#2]
List of unfinished views:

* [x] Initial view
* [x] Connecting view
* [x] Main view
* [ ] Settings
* [x] onboarding views
* [x] device view

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-312)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Closing this issue on Jira as it seems to have been created in error by the data sync.
