### ISSUE TITLE
Language hsb not recognized

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#2004]
When running `./scripts/importLanguages.py` I get the following error:

```
File /home/bird/Dev/mozilla/mozilla-vpn-client/src/../translations/hsb/mozillavpn_hsb.ts won't be updated: 
it contains translation but the target language is not recognized
```

cc @flodolo

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1152)
┆author: Data Sync

**Comment by flodolo** [comment]
@bakulf 

Did this happen in the past for other locales? This one has been there for a very long time :-|

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

See the last comments.
