### ISSUE TITLE
Network error: SSL handshake failed

### ISSUE THREAD

**Issue by AlvinRamoutar** [mozilla-mobile/mozilla-vpn-client#2010]
Platform:
- Windows Server 2019 Standard
- Windows 10 Enterprise

Expected:
- Upon fresh install and completing subscription authentication, client setup would be complete.

Actual:
- Client setup fails with red error banner "Unable to connect Try Again"

How to reproduce:
1. Install client on mentioned Windows platforms above.
2. Click 'Get started'
3. Complete authentication in browser session
4. Return to client

Logs:
Refer to attached.
[mozillavpn_logs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7319926/mozillavpn_logs.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1154)

**Comment by AlvinRamoutar** [comment]
Hey @oskirby ,
I've installed the artifact build from Windows #2672.
Logs are attached.
[mozillavpn-2021-10-12.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7332555/mozillavpn-2021-10-12.txt)

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Current status (Oct 14, 21):

  * We need more info to reliably replicate
  * A community member may have found a fix (updating root cert)
  * We have added additional debugging, that will land in v2.6 and give us more details.
  * We cannot estimate this task until we have investigate further.

**Comment by AlvinRamoutar** [comment]
Appreciate the advice @precisionconage - confirmed that I can successfully complete subscription authentication for 2.5.0 by doing the following:
1. Uninstall Mozilla VPN client
2. Delete `%USERPROFILE%\AppData\LocalLow\Microsoft\CryptnetUrlCache`
3. Delete `%LOCALAPPDATA%\Mozilla VPN\cache`
4. Download Mozilla VPN client (2.5.0) from https://vpn.mozilla.org/vpn/download
5. Install Mozilla VPN client
6. Install 
6. Click 'Get started'
7. Complete authentication in Firefox browser

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We requested a Windows VM to our IT department, and as soon as they will provide one, we will try to verify this.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this on a windows 10 machine using VPN 2.6 with the scenarios Luminita mentioned bellow: 

For the ISRG Root X1 being disabled the following error is displayed at log in:

!image-20211110-150925.png|width=757,height=498!

With the ISRG Root X1 deleted when the user starts the log in flow the certificate is reinstalled and can be  found in the certificates manager and also the log in is working correctly.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Sebastian Streich do you have feedback on the questions below?

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Hi! Madalin Cotetiu - thanks for trying this. Scenario 2 is sufficient for validating this bug. Also, this is nothing to worry / concern about further, as this is a state the user's machine should not be in.
