### ISSUE TITLE
Add "loading" spinner to Subscribe Now button

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#204]

**Comment by lesleyjanenorton** [comment]
closed via #219

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
A spinner was added to the "Subscribe now" button and works as expected.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/99811206-8348e200-2b4d-11eb-98cc-f3f4f970ffcc.png)
