### ISSUE TITLE
Tech debt clean-up: Rename / alias the setting gleanEnabled to telemetryEnabled

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#2050]
We have a setting called gleanEnabled, but it would be clearer in the codebase if it was called telemetryEnabled as it's not just about glean data since it also applies to adjust data.

As noted [here](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1911#discussion_r729912095) a migration is overkill.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1172)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

No need to rename the setting.
