### ISSUE TITLE
Change "Support Website" in Help menu(s) to "Help Center"

### ISSUE THREAD

**Issue by malqinneh** [mozilla-mobile/mozilla-vpn-client#206]
@bakulf please update the copy for accessing the "Support Website" to be "Help Center". This change will effect: 

* Menu bar menu dropdown
* Menu bar extras
* App 'Get help' menu screen

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-316)

**Comment by ValentinaPC** [comment]
Verified as fixed on the latest build on Linux Ubuntu 20.04 and Android 10.
The "Support Website" was replaced with "Help Center" in the "Get Help" menus inside the app and in the menubar.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/99657630-178c4980-2a67-11eb-9c96-a7c8b5935c3e.png)
