### ISSUE TITLE
Create a TaskCluster Job to generate Builds

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#2078]
#2071 added taskcluster support to our ci system

This is a parent ticket that has sub issues for all the separate steps

The basics of the windows and mac builds are in there, but they are disabled ([https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2071/commits/b97d93aa196b31c12791590a9ba787ac7a8f47e4)](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2071/commits/b97d93aa196b31c12791590a9ba787ac7a8f47e4)) as they were failing on taskcluster.

We want to get windows and mac builds building in taskcluster as then we'll be able to automate signing, pushing to archive.mozilla.org and releasing via shipit.

Whoever picks this up _should_ be able to un-disable and then start iterating on taskcluster runs. If there are permissions issues in taskcluster, ping @birdsarah as a starting point.

This issue could be split into the mac and the windows build work seperately.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1190)

**Comment by birdsarah** [comment]
This has a series of sub-tasks on jira.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

cc Andrew Halberstadt for our parent issue.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

This has been split up in the epic 😀
