### ISSUE TITLE
VPN fails to start when multiple VPN providers/profiles are present on the device

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/mozilla-vpn-client#208]
I have two VPN clients on my iPhone: Wireguard and Mozilla VPN. When a Wireguard profile is default in the system settings, I am unable to start the Mozilla VPN from within the application: toggling the checkbox immediately changes it back to off.

When I go into the system VPN settings first and select Mozilla VPN as the default, things work as expected.

(I think this is something that should work - because Wireguard.app doesn't have this problem: even if Mozilla VPN is the default in the system VPN settings, I can still go into the Wireguard.app app and turn on any of the profiles I have in there.)

**Comment by chrismore** [comment]
@bakulf do we know if this is an issue with our VPN, WireGuard, or OS integration?

**Comment by bakulf** [comment]
It was a bug in our implementation. @st3fan can you please test it again with the latest build? 2.*055 ?

**Comment by bakulf** [comment]
I tested it with @rlr and it seems to be fixed in the latest builds.

**Comment by ValentinaPC** [comment]
@bakulf is there a way for QA to verify this? Thanks!
