### ISSUE TITLE
Write-up draft speclet for integration monitoring

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2109]
As discussed at engineering team meeting, I'll be writing up a draft speclet for what we'd like to monitor to monitor the whole service we deliver.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1219)

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Next step - talk to luke about relay dashboard.

**Comment by strseb** [comment]
done
