### ISSUE TITLE
Mozilla VPN App Crash MacOS

### ISSUE THREAD

**Issue by magsmoz** [mozilla-mobile/mozilla-vpn-client#2112]
User on MacOS reporting that the VPN app crashes immediately after opening it. The app flashes a message on the screen for a split-second but it is much too quick for the user to read it or take a screenshot. attached is the message that apple shows after this happens.
user has not made any changes to the device or VPN app, this happened without any updates to the OS or VPN
the error started happening all of a sudden, then the user updated the OS, but the issue persists
reinstalling the App does not fix it 

Device version: MacOS Big Sur 
FX product Mozilla VPN 2.5

**Steps to Reproduce**
Sign up for Mozilla VPN
Download/install VPN client
Open VPN Client and turn on

**Actual Results**
VPN App does not open, it flashes a quick error message then closes

![vpn app crash](https://user-images.githubusercontent.com/92737666/138412554-c2bfe14a-0312-4c7c-8450-0ae12d25e181.png)
f.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1220)

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Triage: So far less than 10 support tickets

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This has been fixed already.
