### ISSUE TITLE
Add qml unit tests for more complicated front-end functions

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#2115]
Functions like toggleClickable in the front end make me [nervous](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2073/files#diff-4492b1941e89a20213b5286863be836ff2520fc1d7dda2b957a7ebc12bebbd12R271).

I recently learned from @brizental that we should be able to do qml unit testing (https://github.com/mozilla/glean.js/blob/main/samples/qt/src/Tests/tst_maintests.qml). Functions like that seem like a good candidate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1221)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This bug can be closed. We are writing new unit/qml/functional tests each time we introduce new UI components. We can drop this bug.
