### ISSUE TITLE
Highlighted recommended pricing plan

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2124]
We have to make sure that the correct recommended pricing plan is being highlighted for IAP. [This issue](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1986) mentions that the wrong plan is shown initially to the user.

![image](https://user-images.githubusercontent.com/13835474/138732447-2b8bfc9b-4bd5-4ae1-a74a-484a4fe0ae14.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1226)

**Comment by flozia** [comment]
@ValentinaPC Currently the 6 month plan is configured outside of the app so the app is reflecting the recommended plan correctly. We want to show the 12 month plan, but that has to be changed in another place. Until this is not updated this issue can not be tested.

**Comment by flozia** [comment]
@punster-moz In oder to change the recommended subscription plan from `6 month` to `12 month` I created the issue [Change featured product plan for VPN (SVCSE-198)](https://mozilla-hub.atlassian.net/browse/SVCSE-198) for updating the Guardian endpoint.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last 2.6.1 iOS (2.202111171518) and Android VPN (16370100) builds.

The 12m plan is highlighted as the recommended one.

Postfix screenshot below.

!image-20211118-071949.png|width=646,height=522!
