### ISSUE TITLE
VPN crashes when launching App on iOS

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#2129]
**Description**

Users cannot open VPN app on iOS. After tapping on VPN icon to launch, the app's main screen flashes for a few secs and then the app closes.

**Technical Information**

Platform: iOS 14.1
FX product Mozilla VPN 2.5.1

**Steps to Reproduce**

• Have an active VPN subscription
• Download/install VPN
• tap Mozilla VPN icon to launch

**Actual Results**
- app crashes a few seconds after launch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1228)

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

Apple has this guide on how to collect logs from the user: https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs ( https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs|smart-link ) 

This might help collect the crash logs.

**Comment by magsmoz** [comment]
Hi there, I have just received the first file. Please see attach
[Mozilla VPN-2021-11-02-ioscrash.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7475357/Mozilla.VPN-2021-11-02-ioscrash.txt)
ed

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

This issue only happens on older iOS versions (before 14.3) since these versions do not have AdServices.framework installed. This framework is used by the Adjust SDK and we import it. We can simply set it to optional and which will stop iOS from forcing to load this.

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

This needs to be only tested on iOS versions 14.3 and below

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

We were not able to find a mozillian that has iOS < 14.3 with access to TestFlight.

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

Rebecca Billings what can I do to help you?

Could I Test is myself on a simulator?

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Moritz Birghan Yes, a simulator would be a good next step.

**Comment by adcousin** [comment]
Good day I have a iOS 14.2 and could get TestFlight if it helps.
