### ISSUE TITLE
Confusing instructions to install qt on macOS

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#218]
From the README

```
curl -L https://download.qt.io/archive/qt/5.15/5.15.1/single/qt-everywhere-src-5.15.1.tar.xz --output qt-everywhere-src-5.15.1.tar.xz
tar vxf qt-everywhere-src-5.15.1.tar.xz
mv qt-everywhere-src-5.15.1 qt
```

So far so good, although it might good to explain to run this command from the folder where you want that huge folder to end up.

    bash scripts/qt5_compile.sh `pwd`/qt qtTwo issues:

* It's not obvious that this needs to be run from the clone of the repository. At first, I thought the script folder would be in the qt sources folder.
* That bash script requires 2 parameters, and fails if only one is provided. But it looks like the second is [not used anywhere](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/master/scripts/qt5_compile.sh)?

    export QT_MACOS_BIN=`pwd`/qt/qt/binI can't verify this, since I got a nice "make failed" after 45 minutes where my MacBook was trying to fly aways. But I don't see a `qt/qt/bin` folder? I see a `qt/qtbase/bin` and `qt/qttools/bin/`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-79)

**Comment by bakulf** [comment]
Fix in the latest README
