### ISSUE TITLE
Android 12 tells me that "Mozilla VPN pasted from your clipboard", for no obvious reason

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/mozilla-vpn-client#2183]
Preconditions: Have a phone running Android 12, with Mozilla VPN installed but not currently running. (I've seen this when it was already running, too, but it's more predictable if it's not.)

STR:
1. Copy a URL to your clipboard.
2. Open the Mozilla VPN app.

ACTUAL RESULTS:
Immediately, I get a notification "Mozilla VPN pasted from your clipboard".

EXPECTED RESULTS:
No such notification. There's no reason Mozilla VPN should be inspecting my clipboard (particularly without any interaction on my part besides opening the app).

Screenshot:
![image](https://user-images.githubusercontent.com/426803/139958465-4e1a68bf-c822-45a4-a9b0-fc462510f2b0.png)

See related Fenix bug: https://github.com/mozilla-mobile/fenix/issues/22271
...though this notification is more understandable on Fenix, because over there, this is usually associated with some "fill link from clipboard" UI there, which means users can understand why they're seeing the notification.  Whereas in Mozilla VPN, there's no clear reason for the app to be reading the user's clipboard (particularly at startup before any user interaction).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1266)

**Comment by dholbert** [comment]
Phone model: Pixel 4a
Mozilla VPN App version: 2.5.1

**Comment by strseb** [comment]
Hey! Are you running by chance a pre-release build of android 12? I was able to experience it on my pixel 4 on preview too, but it stopped happening after the latest update. 
Also, we have no code accessing the clipboard, which just makes this extra weird 🙈

**Comment by dholbert** [comment]
I'm not running a pre-release build, no. I just installed the regular Android 12 release when it became availabl.

**Comment by dholbert** [comment]
I just received a ~24mb "security update" to Android 12 (so now System Update shows me as being at version `Android security update: November 5, 2021`.  I retested and confirmed that I can still reproduce.

@strseb: two important factors which impact reproducibility:
(1) Do you have a URL that you've *just* copied to your clipboard?  (needs to be recently copied, or at least new-to-the-clipboard since the last time Mozilla VPN was running)
(2) Are you starting Mozilla VPN "fresh" (if it was previously running, you need to swipe it offscreen in the app-switcher to kill it)?

I can reproduce this system-notification 100% of the time, with these two factors. (Specifically, I'm long-pressing a link in an email and choosing "Copy URL"; and then I start Mozilla VPN, without it having been previously running. I immediately see "Mozilla VPN pasted from your clipboard".)

**Comment by dholbert** [comment]
@strseb just checking in -- is this fix supposed to have made it to release yet? Asking because I'm still seeing this issue with the current VPN release (I've got version 2.6.1, Google Play store isn't offering me an update beyond that currently).

I do see that the fix landed a month ago; I'm not sure what the release model is like for VPN so I'm not sure if it's coming in a future version-bump vs. if the patch was expected to be in the release at this point.

(No big rush; just want to be sure it's not a surprise that the bug is still present in release.)

**Comment by strseb** [comment]
Hey! This should be part of the next release - so 2.7 :)

**Comment by dholbert** [comment]
OK great, thanks!
