### ISSUE TITLE
Consider adding "What's New" panel for Multi-Account Container integration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2194]
Should we create a new 'What's New' panel to let VPN client users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1274)

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Yes! We need to do this for 2.7 – thanks for filing! 
Assigning peter so we can make a panel for this.

**Comment by lesleyjanenorton** [comment]
Closing this as "Considered"
