### ISSUE TITLE
"Install failed" message despite not actually failing

### ISSUE THREAD

**Issue by k88hudson** [mozilla-mobile/mozilla-vpn-client#2196]
I wish I could get a better STR, but while trying to download the VPN client today I got a message that my install failed... but when I looked at my application folder, everything seemed to be fine / the app runs as expected. I'm on a 2018 Macbook Pro / MacOS 11.6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1275)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

We have changed so many things on mac from November to today… I close this issue. Please file a new one in case you are able to share more info! Thanks!
