### ISSUE TITLE
Consider improving layout of main view on mobile

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#220]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-321)

**Comment by jess-cook03** [comment]
@lesleyjanenorton @chrismore 
I think we should consider this as P2 -- backlog -- not for this release.

**Comment by chrismore** [comment]
Lowering priority to P3 and make it part of the future redesign with other changes like landscape mode.
