### ISSUE TITLE
Cannot be installed on Ubuntu 21.10 Impish

### ISSUE THREAD

**Issue by mrerdem** [mozilla-mobile/mozilla-vpn-client#2212]
Ubuntu 21.10 was released on October 14 but the official ppa still does not contain release files for this Ubuntu version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1286)

**Comment by oskirby** [comment]
We have published Linux packages for the latest 2.6.0 release today, which should now include builds for Ubuntu 21.10/Impish.
