### ISSUE TITLE
What should the layout in landscape look like ?

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#223]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-324)

**Comment by lesleyjanenorton** [comment]
Just to provide some more contet here: this is the situation currently on tablets. The content responds to the device width, but the component heights remain essential the same. 
<img width="1209" alt="Screen Shot 2020-11-20 at 12 02 01 PM" src="https://user-images.githubusercontent.com/22355127/99833808-356db300-2b28-11eb-8464-a8f7c8d2f723.png">

**Comment by jess-cook03** [comment]
@lesleyjanenorton 
Looking at this landscape responsiveness on iPad and iPhone and it works perfectly fine for this release.
Giving the thumbs up for this 

> The content responds to the device width, but the component heights remain essential the same.

👍

**Comment by chrismore** [comment]
Lowering priority to a future release and maybe when we redesign the overall app. Not blocking v2.0
