### ISSUE TITLE
Static Qt builds do not have sqlite

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2235]
Windows and Mac builds cannot use Glean as SQLITE

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1316)

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/scripts/qt5_compile.sh#L100 ( https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/scripts/qt5_compile.sh#L100|smart-link )  is the problem line.

**Comment by data-sync-user** [comment]
➤ Marcus Kestler commented:

I’m not getting Qt’s configure script to properly compile this yet.  I’ve tried all the options I know/found on the googles.  I need to circle up with Baku, as he will likely see this on Mac as well.  Will get with him very early eastern time.

**Comment by bakulf** [comment]
The MacOS libs are now compiled with -sql-sqlite. I tested the packages, they are good to go. Extra checks are welcome.

**Comment by data-sync-user** [comment]
➤ Marcus Kestler commented:

I have windows working.,  The qt repo is updated and good to go.  No other changes are required, but I am working on the scripts to try to get debug working locally.  This issue is good to close.
