### ISSUE TITLE
Need UX spec for Android authentication and launch screen

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#225]

**Comment by chrismore** [comment]
@lesleyjanenorton is lack of this spec preventing doing auth in android or just we need a spec/design review to do improved auth?

**Comment by jess-cook03** [comment]
@lesleyjanenorton 
Thinking it would be best to roll with screen 000 from the Android [figma file](https://www.figma.com/file/eVg5QFf12i6Od0Kc46sygl/Android?node-id=2288%3A0)
<img width="847" alt="Screen Shot 2020-11-17 at 3 30 06 PM" src="https://user-images.githubusercontent.com/54991698/99680669-4dbbd000-2a4b-11eb-8b13-0879fbf4270b.png">

Let me know if this works or if you need any more design guidance here!

**Comment by lesleyjanenorton** [comment]
Closing as fixed - thank you @jess-cook03!

**Comment by ValentinaPC** [comment]
The Figma files look different comparing with the actual Android VPN look. 
@lesleyjanenorton  Suppose, intended? 
When is the VPN black screen displayed?
Thanks!
