### ISSUE TITLE
Discovery for multi-single hop UX changes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2252]
Multi hop refinement (v.7 enhancement) https://mozilla-hub.atlassian.net/browse/VPN-962 
UX team needs to learn more and set up user testing (A,B) for solutions here before changing it 

We have possible UI refinements as well as changes to functionality we need to explore.
https://www.figma.com/file/ziJ5tGCqhfst4svjtKJlbr/2.7--Feature-Enhancements?node-id=33%3A3205 
Testing will happen within 2.7 time frame.
Readout and proposed path forward to be defined for 2.8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1330)

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Jessica Cook Brian Yee This was scheduled for Eng work in 2.8, but hasn’t been started yet. Are we going to have exploration and design done in time?

**Comment by lesleyjanenorton** [comment]
Closing - this is Done.
