### ISSUE TITLE
The VPN logo and a few other images are not shown with qt6.2.1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2304]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1356)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Florian Zia could you please post some screenshots with the elements we need to check? Thanks!

**Comment by flozia** [comment]
@ValentinaPC Sure! The images that were affected for Qt 6 builds were:

**Onboarding**
| VPN Logo (before) | VPN Logo (after) |
|---|---|
|![image](https://user-images.githubusercontent.com/13835474/151998963-54955c5c-e6f8-4fcd-b79e-ca82cf6e88e4.png)|![image](https://user-images.githubusercontent.com/13835474/152000697-d1fd06e9-d33a-4ef6-92ca-d3ebe8a43845.png)|

| Learn more (before) | Learn more (after) |
|---|---|
|![Screenshot 2022-02-01 at 16 34 12](https://user-images.githubusercontent.com/13835474/151999809-0d078474-beb6-4050-9fd6-c6c1dabdf8aa.png)|![image](https://user-images.githubusercontent.com/13835474/152000734-6db3f73f-2b34-4559-8b28-d78748fc473d.png)|

**Settings view**
| Avatar (before) | Avatar (after) |
|---|---|
|![Screenshot 2022-02-01 at 16 37 42](https://user-images.githubusercontent.com/13835474/151999714-603a3fdb-2800-43b6-9ba1-507313743604.png)|![image](https://user-images.githubusercontent.com/13835474/152000400-e2b8ed30-43aa-45d8-82fb-39b351135f2a.png)|

**Devices limit reached**
| Remove a device (before) | Remove a device (after) |
|---|---|
|![Screenshot 2022-02-01 at 16 35 55](https://user-images.githubusercontent.com/13835474/151999656-0d89a345-3252-41d4-a400-031f53172d32.png)|![image](https://user-images.githubusercontent.com/13835474/152001483-07f971a8-ffd3-40cc-b186-8640f398f334.png)|

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on the last QT6 VPN 2.7.0 (2.202202011650) on Mac OS 10.15.

All screens contain all elements in their correct form.
