### ISSUE TITLE
[iOS] Authentication error upon clicking on Subscribe almost half of the time I tried

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#232]
VPN TF version: 2(2.202011162055)
iPhone 6S, iOS 14

**Steps**
Open the app, tap on Get started.
Login with a non subscribed account
Tap on Subscribe

**Expected**
The subscription flow is completed successfully

**Actual**
Almost half of the times I tried, the Authentication error is shown and user is taken to the first screen but with the subscription menu to continue shown on top of that.

More info: [video](https://youtu.be/RJMzbhiSn9M) with the complete flow

**Comment by chrismore** [comment]
@isabelrios can you re-verify with the latest version of iOS? thanks!

**Comment by isabelrios** [comment]
Sorry @chrismore but I can't try this on the latest version available on TF due to issue #265, upon launching the app, it crashes :( I will re-verify this issue when next available version fixing the crash is ready. Thanks

**Comment by bakulf** [comment]
A new build is ready to be tested. And a new one should be pushed today. @isabelrios, I appreciate if you can give another round of testing.

**Comment by isabelrios** [comment]
Sorry for the delay in my reply, so far I have not been able to reproduce this, looks like it is fixed. Thanks!
