### ISSUE TITLE
[iOS] Subscribe now button does not change from the spinner to Subscribe now if the subscription is cancelled

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#233]
VPN TF version: 2(2.202011162055)
iPhone 6S, iOS 14

**Steps**
Open the app, tap on Get started.
Login with a non subscribed account
Tap on Subscribe now
When the Subscription menu is open, tap on Cancel

**Expected**
The process is succesfully cancelled and the Subscribe now button is available again

**Actual**
The Subscribe now button keeps showing as the process is ongoing and so it is not possible to click again on it.

![IMG_8861](https://user-images.githubusercontent.com/1897507/99371011-af026880-28be-11eb-843b-514b96a33c4f.PNG)

See [video](https://youtu.be/J3nTBnmgZGA) with all the steps.

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
The spinner wheel from the "Subscribe now" button is immediately change to its normal label after cancelling the subscription.
