### ISSUE TITLE
VPN client not blocking internet access when switching locations

### ISSUE THREAD

**Issue by martinbalfanz** [mozilla-mobile/mozilla-vpn-client#234]
(Note: @chrismore pointed out that this bug may affect all platforms, not just iOS)

The VPN client allows internet access while switching locations. This can expose the real IP address. Instead, it should it block all internet access until the new connection is established.

STR:
- Open the VPN app and connect to any location
- Open a browser with a page that can show your current IP (e.g. `https://duckduckgo.com/?q=what%27s+my+IP&atb=v1-1&ia=answer`)
- Switch to the VPN app and switch to a different location
- While it's switching, head back to the browser and refresh the site

AR:
- the site shows your real IP address

ER:
- the site should not load until the VPN has connected to the new location

See the video attached and pay attention to the selected locations.

![RPReplay_Final1605525880 2020-11-17 12_02_33](https://user-images.githubusercontent.com/653763/99382393-ca747000-28cc-11eb-9288-929ebb057d9d.gif)

**Comment by bakulf** [comment]
@strseb can you take a look at this? What I have done on linux/mac is to ignore the deactivate() if 'forSwitching' is true, and do the disconnect on activate() if forSwitching is true.

**Comment by strseb** [comment]
on it!

**Comment by ValentinaPC** [comment]
Verified this as fixed on Mac, Linux and mobile devices (Android and IOS) using the last cross-plat builds.
When switching locations, the VPN enters in a "No signal" state and the internet is dropping for a few seconds.

If there is anything else to be checked here, please let us know.
