### ISSUE TITLE
Record the log directly from the inspector

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2342]
Right now the logs are fetch from the app, but for QA/testing, it would be easier if the logs are obtained from the inspector directly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1385)

**Comment by strseb** [comment]
(Done)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Andrea Marchesini Could you please let us know what the QA needs to do on this one, if anything?

Thank you.

CC: Madalin Cotetiu

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

The logs are now visible in the Mozilla VPN Inspector. See below image:

!image-20220127-103817.png|width=1254,height=1041!
