### ISSUE TITLE
VPN does not reconnect and breaks internet connection

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2346]
This is not happening every time but pretty often: When toggling the Wi-Fi on and back off on my Macbook the VPN does not reconnect and breaks my internet connection until I turn the VPN off.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1389)

**Comment by flozia** [comment]
Tested a VPN 2.7.0 build from branch main (commit 58d1c9e) using macOS Big Sur (Version 11.5.2).

**Steps to reproduce**
1. Open the VPN
2. Turn VPN on
3. Turn Wi-Fi off
4. Wait until connection status show “Not Signal”
5. Turn Wi-Fi on

**Logs**
- [mozillavpn-2021-11-25_01.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7602728/mozillavpn-2021-11-25_01.txt)
- [mozillavpn-2021-11-25_02.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7602733/mozillavpn-2021-11-25_02.txt)

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

I can still reproduce this issue on my machine running macOS Big Sur (Version 11.5.2). I’m not sure if this is something specific to my setup since we don’t have any related open issue currently. Would you be able to check if you can reproduce this issue Valentina Virlics & Maria Berlinger?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Florian Zia I was able to reproduce this few days ago, on Windows 10, while making some WI-fi checks. I remember that I had the “start on boot“ option checked and that “reset and quit” option fixed my problem. Will try to re-trigger the issue and sent you some logs, if you think are useful.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

I am reproducing this issue on Mozilla VPN 2.7.0 (2.202201112219), while using MacOS Big Sur 11.6. The internet was not working until I restarted the device.

Attaching some logs. 

[^mozillavpn-2022-1-12.txt]

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202202011641), while using MacOS Big Sur 11.6. After turning the Wi-Fi back on, the internet connection and Mozilla VPN app are working as expected.
