### ISSUE TITLE
Cannot subscribe through app without Google Account

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#2354]
"To continue subscribing, please sign in to your Google Account" while trying to subscribe. Workaround: subscribe through the desktop website in a browser (Firefox for Android, "desktop site" enabled)

Samsung phone running Android 11, OneUI 3.1,
Google Play Store and Google Play Services were disabled by user

Expected:
Heuristics for handling this exception, ideally do not rely on Google services for subscription and payment, and/or tactfully explain to the user why exactly Google is required for Mozilla VPN. Add an article to your KB. It seems ironic and a clash of values.

**Comment by marcel263** [comment]
![Screenshot_20211124-164345](https://user-images.githubusercontent.com/76437842/143277109-9a18b78f-8ece-4ef5-a28f-8e89d17acacc.png)

**Comment by JC-Support** [comment]
Hi there. This is currently not on our roadmap as there is a workaround for this in subscribing via the desktop site, should a user want to subscribe outside of Google Play.

**Comment by marcel263** [comment]
> Hi there. This is currently not on our roadmap as there is a workaround for this in subscribing via the desktop site, should a user want to subscribe outside of Google Play.

Please consider expanding Mozilla VPN Support with an article on this, some people are not willfully or consciously using a degoogled phone, moreover it gives off the wrong message that Mozilla VPN requires Google to function, which is somewhat self-defeating

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Joseph Anthony Cuevas can we close this ticket?

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Betty Fleming Clear to resolve. We are investigating updates for SUMO and exploring this internally.
