### ISSUE TITLE
VPN turns into “No Signal/Unstable” after clicking on the app menu icon

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2359]
**VPN version:**

* 2.7.0 (2.202111221702);

**Prerequisites:**

* Have and account with a subscription for Mozilla VPN;
* Have the VPN installed;

**Steps to reproduce:**
1. Turn the VPN ON;
2. Click on the app menu icon (top-left corner);
3. Observe VPN state;

**Expected result:**

* Nothing happens;

**Actual result:**

* VPN state changes to No Signal/Unstable;

**Notes:**

* This is a qa_major issue because the app looks like is not working.
* The app returns to active state only after turn off-on cycle.
* Attaching logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1396)
┆author: Valentina Virlics

**Comment by bakulf** [comment]
How can you turn on the VPN if the account does not have a subscription?

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Will possibly be fixed by https://mozilla-hub.atlassian.net/browse/VPN-846 ( https://mozilla-hub.atlassian.net/browse/VPN-846|smart-link )

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Andrea Marchesini Yeah, typo, an account “WITH“ subscription.

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics is this still reproducible?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Yes, this is still reproducible. It can be seen rapidly after clicking on the “Move“ option from app icon.

Attaching logs and video.

[^mozillavpn-menuclick.txt]

!nosignalunstable.gif|width=1605,height=792!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is no longer reproducible on the last 2.8 RC builds.

Verified this as fixed on 2.8.0 (2.202204071128), on Windows 10.

Closing.
