### ISSUE TITLE
[Android] Settings sub-categories remain selected at scroll

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#236]
#### Affected versions:
- 2;

#### Affected Platforms:
- Android 9;
- iOS 13.1

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Go to “Settings” ;
3. Tap on any sub-category (e.g. "About us") and scroll up or down;

#### Expected result:
- The screen is scrolled up or down without the subsection selected.

#### Actual result:
- The screen is scrolled but the sub-category stays in a selected state. (grey background)

#### Notes:
- The sub-category is deselected after simple tapping on it and returning to the "Settings" screen.
![image](https://user-images.githubusercontent.com/15685960/99393236-b9842880-28e5-11eb-921f-25fc732d0a7e.png)

**Comment by ValentinaPC** [comment]
Verified this on the last Android build (11/18) and seems like it is still reproducible.
See below video.
![select-at-scroll](https://user-images.githubusercontent.com/15685960/99646795-9d08fd00-2a59-11eb-8fb4-4496b5beb61b.gif)

**Comment by bakulf** [comment]
I think the latest build doesn't contain the fix. I close this bug and I submit a new build. In case it happens again, of course, reopen it.

**Comment by ValentinaPC** [comment]
Verified as fixed on Android 10, using the last VPN build (11/20).
Postfix video below.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15685960/99798263-64405500-2b39-11eb-9a3c-71efe2006338.gif)
