### ISSUE TITLE
Inhibits GNOME logout if the Mozilla VPN window is open

### ISSUE THREAD

**Issue by andersk** [mozilla-mobile/mozilla-vpn-client#2370]
If I have the Mozilla VPN window open, and I ask GNOME to log out (or restart or power off), the Mozilla VPN window hides itself, but the GNOME logout does not occur. I need to ask GNOME to log out a second time.

I hypothesize that this is a similar issue to

* keepassxreboot/keepassxc#3944

where the window close handler returns in such a way that the system thinks it didn’t succeed.

I’m using Mozilla VPN 2.5.1 on Linux (NixOS 21.11 with GNOME 41.1).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1401)

**Comment by oskirby** [comment]
I have been able to reproduce this on Ubuntu 21.04/Hirsute with MozillaVPN version 2.6.0 as installed from our official PPA. I'll see what I can do to find a resolution.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

The commit that fixes this (b22480891b49f6f67bdda17f3aade24059bc6bc2) does so by responding to session shutdown requests from the window manager, and takes steps to ensure that the VPN is disconnected properly before a session shutdown is allowed to complete. This fixes a bug where the VPN could remain connected after logging out.

With that in mind, we should give this a test across all of our desktop platforms to ensure there’s nothing broken by these changes. Such a test might look like:

  1. Log into your desktop account
  2. Start Mozilla VPN and connect to any server of your choice.
  3. Open a browser and use a leak-check tool (eg: ipleak.net) to verify that the VPN is active.
  4. Without disconnecting the VPN, log out of your desktop account.
  5. Log back into your desktop account.
  6. Open a browser and use a leak-check tool to verify that the VPN is not active.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Hello, Owen Kirby ! We have some questions regarding mentioned steps below:

  * “Log into your desktop account” - we do this outside the VPN app, using “https://accounts.stage.mozaws.net/ ( https://accounts.stage.mozaws.net/s )“ for example ?
  * “Without disconnecting the VPN, log out of your desktop account” - we do this using the above mentioned page and sign out form there?
  * “Open a browser and use a leak-check tool to verify that the VPN is not active” - how come VPN could be inactive, if we only signed out from browser?

Did I miss something? Thanks in advance!

**Comment by andersk** [comment]
> “Log into your desktop account” - we do this outside the VPN app, using https://accounts.stage.mozaws.net/ for example ?

Not sure if this was answered in some internal tool, but no. This is not an website account in your browser. It’s the account you use to log in to your computer.

(Here’s how to log out of [Windows](https://support.microsoft.com/en-us/windows/sign-out-of-windows-346925bb-024c-cd86-7a53-9066242a9ed3), [macOS](https://support.apple.com/guide/mac-help/log-out-of-your-account-mchlcc122483/mac), or [GNOME](https://help.gnome.org/users/gnome-help/stable/shell-exit.html.en).)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Thanks a lot for clarification! That was very helpful!

Verified this issue on the following platforms: Windows 10, Mac OS 11.6 and Linux Ubuntu 20.04 while using the last VPN 2.7 build.

After logging out and back in from my desktop account, the VPN is no longer active on Windows 10 and Linux Ubuntu 20.04.

This issue is still reproducible on Mac OS. I’ll reopen it. 

Owen Kirby If you think we should track this separately, please let us know.

Thanks!

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

I’ll look into the behaviour on MacOS and see if I can figure out why it behaves differently.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202202011641), while using MacOS Big Sur 11.6. The VPN is no longer active after logging out and back in from desktop account.
