### ISSUE TITLE
Add UTM parameters to “learn more” link for MAC “What’s new”

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2377]
We have to check if we would like to add UTM parameters to the “learn more” link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1403)

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Luminita Buruian We only have to make sure that after clicking on the “learn more” link in the MAC “What’s new”  ( https://mozilla-hub.atlassian.net/browse/VPN-1373 )the browser URL has the following UTM parameters appended: ?utm_source=mozilla.vpn.client&utm_medium=in-app-link&utm_content=whats-new-panel&utm_campaign=vpn-better-together.

Thank you!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hello,

Verified this as fixed on Mozilla VPN:

  * 2.7.0 (2.202112111533), while using MacOS Big Sur 11.6;
  * 2.7.0 (2.202112111537), while using Windows 10;
  * 2.7.0~github3338 (2.7.0~github3338-focal1), while using Ubuntu 20.04;

When clicking on the “Learn more” link from “Mozilla VPN in Firefox” screen, the browser URL has the following UTM parameters appended: ?utm_source=mozilla.vpn.client&utm_medium=in-app-link&utm_content=whats-new-panel&utm_campaign=vpn-better-together
