### ISSUE TITLE
Define what the menubar on mac should look like

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#24]
- [🎨 VPN Mac OS/Linux Menu Bar Icons/States - Figma](https://www.figma.com/file/DQOy6IMHbKylNmvirxh2Ia/Menu-Bar-Icons)

![mac os menu bar icons.jpg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/60689020-f79b-4461-a719-f9a75744cfc9)

**Comment by ValentinaPC** [comment]
Verified this on Mac OS 10.15.7, using VPN v. 2.202011200952.
The icon is smaller than in above images.
See below screenshot.
![image](https://user-images.githubusercontent.com/15685960/99811600-0ec27300-2b4e-11eb-96e3-a915985c413c.png)
Will reopen this until further notice.

**Comment by lesleyjanenorton** [comment]
Thank you @ValentinaPC - I'm going to close this in favor of #262
