### ISSUE TITLE
"ready for you to connect" but it is already connected

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#2421]
STR
Enable Mozilla VPN as "always on" through Android settings and boot the device
VPN icon (key) appears in status bar, Mozilla VPN icon appears in the noticifications
Test IP from for example whatsmyip.com

Expected
Either message should indicate "connected to" status or VPN status should reflect "ready to connect" status, e.g. notification matches VPN state
Actual
VPN already connected despite "ready to connect" message. This changes when launching the Mozilla VPN app, it then correctly updates to its actual status of "connected to"

Details:
Mozilla VPN 2.6.1 (16372470)
Samsung Android 11 OneUI 3.1

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1431)

**Comment by marcel263** [comment]
[bugmpnl.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/7666742/bugmpnl.txt)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Andrea Marchesini Sebastian Streich 

This issue is still reproducing on Android 10 while using VPN build 2.8 (16468770), following the next STRs:

  * turn the VPN ON;
  * change from single hop to multi-hop;
  * observe the notification;

Expected: Notification remains the same as the exit location was not changed.

Actual: Notification displayed is “Ready for you to connect“.

!Screenshot_20220310-121134.png|width=1080,height=1920!

**Comment by marcel263** [comment]
with 2.8.0 still present

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Sebastian Streich is this an open bug or can we close it?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Andrea Marchesini , I am still able to reproduce the issue after enabling the "always on" feature through Android settings and restarting the device, on Mozilla VPN 2.11.0 (16668500), using Android 10. 

“Ready for you to connect” notification is displayed, even if the VPN has already connected. The notification changes to “VPN connected” after the app is opened. 

Attaching a video as well.

!XRecorder_01112022_173222.mp4|width=720,height=1568!

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Bianca Hidecuti -I think this should be fixed in 2.14 🙂 (or behave the same way like the quicksettings notifications)

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.14.0 (2.202302071909), while using Android 11 and I am no longer able to reproduce the issue.

After enabling the "always on" feature through Android settings and restarting the device, “VPN connected” notification is now displayed - attaching a ss as well.

Marking this verified as fixed. 

!1675929694164.JPEG|width=540,height=1080!

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Basti should you be assigned to this one? and was it done during the sprint? 🙂
