### ISSUE TITLE
Tasks queue backs up when connection goes down

### ISSUE THREAD

**Issue by oskirby** [mozilla-mobile/mozilla-vpn-client#2431]
While testing how the VPN responds to a lost internet connection it seems that when the route to the internet is silently blocked, some of the VPN tasks fail to complete, resulting in a backlog of tasks building up. This backlog of tasks seems to prevent the VPN client from detecting and executing upon a silent server switch.

**Steps to reproduce (Linux):**

1. Start the VPN client, and connect to a location of your choice.
1. Run the command `ip rule` to dump the routing policy table, and look for an entry like: `32763 from all to 68.235.44.66` to determine the IP address of the wireguard server (ignore the address starting with `34.107.x.x` as this is most likely the captive portal check).
1. Install a blackhole route to silently drop packets to the Wireguard server: `sudo ip route add blackhole 68.235.44.66`
1. The VPN client should fairly quickly detect the loss of the wireguard server, and report that the connection is unstable or offline.
1. No matter how long you wait, the VPN never executes a server switch.
1. Remove the blackhole route `sudo ip route delete blackhole 68.235.44.66`
1. Eventually a server switch occurs only after the task queue is drained.

**Expected behavior:**

* Shortly after installing the blackhole route the VPN client should execute a silent server switch to resolve the connection loss.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1440)

**Comment by bakulf** [comment]
What about if we delete tasks? Now we have delectable and not-deletable tasks. Maybe, when we want to run `silentSwitch()` we can task `TaskScheduler::deleteTasks()` to clean up the queue. Right now only adjust-SDK tasks are not-deletable so, ignoring them, this approach should work. Thought?
