### ISSUE TITLE
Windows 10 VPN launch on startup connects but shows greyed out slider (VPN is off)

### ISSUE THREAD

**Issue by rubenhx** [mozilla-mobile/mozilla-vpn-client#2442]
Windows 10 VPN launch on **startup** connects but shows greyed out slider (VPN is off).

![image](https://user-images.githubusercontent.com/36697661/145566095-747bf1a0-d0d8-47a4-b010-58c2c9661095.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1446)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on Windows 10 while using Mozilla VPN 2.11.0 (2.202210270555) build.
