### ISSUE TITLE
ViewLogs in mobile needs to use the '->' icon

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#246]

**Comment by ValentinaPC** [comment]
I saw that a "Copy" button was added to the View Log page. But the "Copy" button doesn't do anything. Or I do not know how to use it.
![copy button](https://user-images.githubusercontent.com/15685960/99658268-ebbd9380-2a67-11eb-88b2-e7cc7eb73bd3.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on cross-plat build v.2 while using an Android 10 device.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/100111644-f49ed280-2e76-11eb-9c80-e8715c183328.png)
