### ISSUE TITLE
IP address not displayed in Connection info screen from Mozilla VPN

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2462]
**VPN version:**

* 2.7.0 (2.202112150959);

**Tested Platforms**:

* MacOS Big  Sur 11.6;

**Prerequisites**:

* Have a FxA account with an active subscription for Mozilla VPN;
* Have Mozilla VPN installed and open;
* Be signed in;

**Steps to reproduce**:
1. Turn on the VPN;
2. Click on the “i” button from the activation screen;
3. Observe the IP address displayed on the info screen;

**Expected result**:

* The IP address is correctly displayed;

**Actual result**:

* The IP address is not displayed. “Loading” text is displayed instead;

**Notes**:

* On the Mullvad page (https://mullvad.net/en/check/), the IP address of the server is displayed;
* This is a major issue because the Info screen does not display the elements it should display. Also, the user might think that his real IP address might be revealed;
* See the attached screenshot;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1465)

**Comment by bakulf** [comment]
Can we have logs please?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Sure. Attaching logs. 

[^mozillavpn-2021-12-16.txt]

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Something wrong is happening in your log. There is nothing in the client section. Are they generated from the inspector?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Reattaching logs from the inspector.

[^mozillavpn.txt]

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Interesting. The issue on mac is that there are 2 ssl errors:

  * untrusted certificate
  * subject does not match.

The second one is known. The first one is unexpected.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

We used to ignore SSL errors on the IPInfo network request, since the use of a raw Host header would always lead to a mismatch in the subject name, but I attempted to clean that behaviour up a bit in Github PR #2438 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2438 ). However, this means that the IPInfo request will no longer ignore other errors, such as the untrusted certificate.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Can somebody else take this issue? Otherwise I can continue in 3 weeks time.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

I’m pretty busy this week, but I can start digging into it next week.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Reproducing this on Mozilla VPN 2.7.0 (2.202021131831), while using iOS.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202201192357), while using MacOS Big Sur 11.6 and on Mozilla VPN 2.7.0 (2.202201191834), while using iOS. The IP address is correctly displayed on the info screen. 

See postfix screenshot.

!Screen Shot 2022-01-20 at 11.37.24.png|width=356,height=542!
