### ISSUE TITLE
gh-pages branch bloats .git repository size from 40M to 1538M

### ISSUE THREAD

**Issue by andersk** [mozilla-mobile/mozilla-vpn-client#2479]
This repository has grown to over 1.5 gigabytes; cloning it requires an absurd amount of disk space, network traffic, and time.

```console
$ git clone https://github.com/mozilla-mobile/mozilla-vpn-client.git
Cloning into 'mozilla-vpn-client'...
remote: Enumerating objects: 36584, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 36584 (delta 48), reused 62 (delta 28), pack-reused 36471
Receiving objects: 100% (36584/36584), 1.50 GiB | 8.50 MiB/s, done.
Resolving deltas: 100% (27015/27015), done.
$ cd mozilla-vpn-client
$ du -sBM .git
1538M	.git
```

This is due almost entirely to the `gh-pages` branch, which stores historical copies of the WASM binaries updated many times a day since February. Deleting `gh-pages` reduces the repository to a reasonable size:

```console
$ git branch -dr origin/gh-pages
Deleted remote-tracking branch origin/gh-pages (was 6636f5df).
$ git gc --prune=now
Enumerating objects: 33466, done.
Counting objects: 100% (33466/33466), done.
Delta compression using up to 12 threads
Compressing objects: 100% (7949/7949), done.
Writing objects: 100% (33466/33466), done.
Total 33466 (delta 24812), reused 33466 (delta 24812), pack-reused 0
$ du -sBM .git
46M	.git
```

But of course it will all come back on the next `git fetch`. Although there are more sophisticated client-side workarounds, this should really be addressed on the repository side. Consider squashing the history of the `gh-pages` branch.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1484)

**Comment by bakulf** [comment]
Things are now better! But we do not have a solution yet.
To move forward, I would suggest the following:

1. new github pages contents (wasm) should be committed and amended in order to overwrite the same files over and over again (no size increases)
2. remove a few big files from the main branch
3. reduce the number of remote branches

**Comment by bakulf** [comment]
The files I think we should remove are these: mozillavpn.wasm, "Mozilla VPN".

This can be done with the following commands (via [bfg](https://rtyley.github.io/bfg-repo-cleaner/)):
1. java -jar bfg-1.14.0.jar --delete-files mozillavpn.wasm
2. java -jar bfg-1.14.0.jar --delete-files 'Mozilla VPN'

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

We now use taskcluster builds for the wasm client. Let's close this bug.
