### ISSUE TITLE
“Reset & quit” option causes devices to duplicate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2481]
VPN version:*

* 2.7.0 (2.202112170222);

**Prerequisites:**

* Have and account with a subscription for Mozilla VPN;
* Have the VPN app installed and be logged using stage environment;

**Steps to reproduce:**
1. Open VPN app;
2. Go to Settings-> Get Help-> Developer options;
3. Reset & quit;
4. Reopen VPN;
5. Go to Get Help ~~> Developer Options~~ > Check “Use staging servers.”
6. Quit to apply changes;
7. Reopen VPN and finalize login;
7. Check My devices;

**Expected results:**

* Devices are not duplicated;

**Actual results:**

* Devices are duplicated;

**Notes:**

* Each time above steps are repeated, the device is multiplied;
* Possible because at "Reset&quit" user is not actually signed out?
!image-2021-12-20-15-27-00-894.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1486)
┆author: Valentina Virlics

**Comment by bakulf** [comment]
This is expected. We need to reenable the uniqueID feature to fix this issue.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

We were no longer able to reproduce tis issue on VPN 2.9, using the below:

  * Windows 10 with VPN 2.9.0 (2.202206161924)
  * Windows 11 using VPN 2.9.0 (2.202206161924)

Closing as qa verified.

CC: Bianca Hidecuti Valentina Virlics
