### ISSUE TITLE
Crash after upgrade due to stale QML cache

### ISSUE THREAD

**Issue by andersk** [mozilla-mobile/mozilla-vpn-client#2487]
After upgrading from 2.5.1 to 2.6.1, the `mozillavpn` GUI crashes with the following console output:

```
[22.12.2021 10:51:35.722] Warning: QQmlApplicationEngine failed to load component
[22.12.2021 10:51:35.722] Warning: qrc:/ui/main.qml:9:1: "./components": no such directory (main.qml:9)
Segmentation fault (core dumped)
```

I discovered this on NixOS, but it can be reproduced on Ubuntu 21.10 as follows:

```bash
# Set the SOURCE_DATE_EPOCH variable
# (Some distributions, like NixOS, set this automatically for reproducible builds.)
export SOURCE_DATE_EPOCH=315532800

# Build 2.5.1
git checkout v2.5.1
make distclean
scripts/generate_glean.py
scripts/importLanguages.py
qmake
make -j8

# Install 2.5.1
sudo make install
sudo systemctl restart mozillavpn

# Run 2.5.1 GUI
mozillavpn

# Build 2.6.1
git checkout v2.6.1
make distclean
scripts/generate_glean.py
scripts/importLanguages.py
qmake
make -j8

# Install 2.6.1
sudo make install
sudo systemctl restart mozillavpn

# Run 2.6.1 GUI
mozillavpn
```

One can work around this with `rm -rf ~/.cache/Mozilla\ VPN/qmlcache`.

If I understand the problem correctly, it should be fixable by [enabling the Qt Quick Compiler](https://doc.qt.io/archives/QtQuickCompiler/) so that the directory cache is not needed.

Related issues:

* https://bugreports.qt.io/browse/QTBUG-85967
* https://musescore.org/en/node/309025
* mirukana/mirage#90

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1489)

**Comment by bakulf** [comment]
We do use the Qt-Quick compiler: the QML files are part of the binary and they are not installed separately. The QMLCache folder is a QT thing created to speed up the app. And it should be invalidated automatically. Definitely, there is something buggy somewhere.

**Comment by andersk** [comment]
I see `CONFIG+=qtquickcompiler` in `scripts/android_package.sh` but not for other platforms. I confirmed that adding this to `src/src.pro` produces many fewer files in the `qmlcache` directory, and that it makes the crash disappear.

**Comment by birdsarah** [comment]
The fix in #2490 has been causing core devs build issues on different platforms. We've decided to revert PR #2490 and re-open this issue.

**Comment by andersk** [comment]
Do you have a path forward here? Perhaps I could suggest something if you indicated which issues or which platforms you’re referring to?

**Comment by birdsarah** [comment]
My intention is to get more details on the issues we were seeing documented by the end of the week. 

I didn't take detailed enough notes in the meeting where we came to the decision. So although we agreed on the decision, in back-to-back meetings, my brain lost the specifics of which platforms were struggling....my recollection is that it was mac, iOS and windows.

**Comment by andersk** [comment]
This happens again with the upgrade from 2.6.1 to 2.7.0.

```
[27.01.2022 16:22:17.585] Warning: QQmlApplicationEngine failed to load component
[27.01.2022 16:22:17.585] Warning: qrc:/ui/main.qml:14:1: module "org.mozilla.Glean" is not installed (main.qml:14)
[27.01.2022 16:22:17.590] Warning: QObject::connect(QWindow, NotificationHandler): invalid nullptr parameter
[27.01.2022 16:22:17.590] Debug: (main - SystemTrayNotificationHandler) Retranslate
[27.01.2022 16:22:17.603] Debug: (main - HelpModel) Adding: Help center
[27.01.2022 16:22:17.603] Debug: (main - HelpModel) Adding: Contact us
[27.01.2022 16:22:17.603] Debug: (main - HelpModel) Adding: View log
[27.01.2022 16:22:17.603] Debug: (main - SystemTrayNotificationHandler) Update context menu
Segmentation fault (core dumped)
```

**Comment by andersk** [comment]
Same with the upgrade from 2.7.1 to 2.8.0.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Valentina Virlics Would you be able to look into whether you can reproduce this via the steps described in the bug please?
Sarah Bird It looks based on your comment that you suspected that this affected more than just Linux (which is the focus of what was reported). Do you recall if you were able to confirm this?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Santiago Andrigo I’ve tried to reproduce the issue on Mac OS or Windows, by installing 2.10 version on top of the 2.9 version, and I did not encounter any crash after.

Would like to recheck this once Balrog is updated so that we can test the update automatically.

In regards to Linux 21.10 - this was deprecated - seem more details in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4053 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4053|smart-link ) ;

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Thanks Valentina. Yes, I didn’t notice this was 21.10, which is indeed deprecated. Let’s, however, test this on the LTS versions where we do claim full support.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Lowering this out of High to Low given that it’s (at most) contained to Linux.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We are checking update at each release on the supported distributions and like now, we did not encounter a crash. We checked doing the update by manually installing a pack or via terminal.

Unassining myself and moving into Done. Would be great to add the resolution - works for me.
