### ISSUE TITLE
Define what the menu bar menu and menu bar extras should be

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#25]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-342)

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
Postfix screenshots below.
![menubar11](https://user-images.githubusercontent.com/15685960/99814002-0f103d80-2b51-11eb-91db-f397788fbc4d.png)
![Screenshot 2020-11-20 at 16 53 51](https://user-images.githubusercontent.com/15685960/99814018-17687880-2b51-11eb-8b9a-d2f93b58ecf9.png)

Options were added, but I guess, intended.
