### ISSUE TITLE
Some links from License page do not redirect as expected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2508]
VPN version:*

* 2.7.0 (2.202112281651);

**Prerequisites:**

* Have and account with a subscription for Mozilla VPN;
* Have the VPN app installed and opened;

**Steps to reproduce:**
1.  Go to Settings-> About Us-> Licenses;
2. Click the “available here” from Adjust paragraph;

**Expected results:**

* User is redirected to a specific page.

**Actual results:**

* User is informed that the page does not exist.

**Notes:**

* Reproducing for Lottie-web - “available here” as well;
!image-2022-01-03-15-40-02-108.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1501)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Check the “available here” link from the screen below.

!avhere.png|width=930,height=570!

**Comment by vvalceanu** [comment]
I can also reproduce. "License" opens the default browser with [this page](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/LICENSE.md). 
If you then find the paragraph about "Adjust Framework" and click on its license, it tries to open `https://opensource.org/license/MIT`, which is a 404. It should be replaced with `https://opensource.org/licenses/MIT` (notice the additional `s` in `licenses`).

Relevant Safari headers:

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on VPN 2.7.0 (2.202201061502) while using Windows 10.

All links from Licenses are redirecting  to an available page.
