### ISSUE TITLE
QT compilation fails during new MacOS development environment setup

### ISSUE THREAD

**Issue by vvalceanu** [mozilla-mobile/mozilla-vpn-client#2513]
Setting up a new MacOS development environment, as per README.md.
On master.
MacOS Big Sur 11.6.
Using qt-everywhere-src-5.15.1.tar.xz.

Running ``bash scripts/qt5_compile.sh `pwd`/qt qt``
yields an error:
`./qiosurfacegraphicsbuffer.h:54:32: error: unknown type name 'CGColorSpaceRef'; did you mean 'QColorSpace'?`

generated by not including a Mac OS header that was previously indirectly included. A bit more info [here](https://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/cocoa?id=dece6f5840463ae2ddf927d65eb1b3680e34a547).

Pull request with fix on the way.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1510)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I updated the README.md with a description about Qt6.
