### ISSUE TITLE
Subscription flow does not take me back to the app

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/mozilla-vpn-client#252]
After finishing the subscription flow using the browser (Firefox for Android), the browser did not direct me back to the app.  The subscription does work and I can use the app with no issues, but I had to manually switch back to the app.

To reproduce:
1. Use Firefox for Android (Fenix) as default browser.
2. Start subscription flow using the VPN client on android.
3. Finish the subscription flow.

Expected:
4. Redirect back to the VPN client.

Actual:
4. Subscription flow stopped on the browser.
5. Manually switch to VPN client to confirm subscription was completed.

**Comment by bakulf** [comment]
This has been fixed in the latest android build. Now the authentication flow happens in-app, using a webview.
Can you please check it again? Thanks!

**Comment by ValentinaPC** [comment]
I've verified this as fixed on the last VPN cross-plat build (11/20) while using Android 10.
Postfix video below.
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/15685960/99798952-8b4b5680-2b3a-11eb-8950-82564ae19535.gif)
