### ISSUE TITLE
When launcing the VPN client on macOS I get a VPN disconnected notification

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/mozilla-vpn-client#254]
When launcing the VPN client on macOS I get a VPN disconnected notification. I only expect to see the notification when actually disconnecting or reconnecting from the running app, not when I first launch it.

<img width="844" alt="Screen Shot 2020-11-18 at 2 29 22 PM" src="https://user-images.githubusercontent.com/552390/99596132-a25b3e80-29aa-11eb-8a84-df35ccee7ed9.png">

**Comment by chrismore** [comment]
@bakulf was the intentional or can the logic be modified so that the notification is only shown when changing states instead of including the initial off state?

**Comment by ValentinaPC** [comment]
This happened from the start, on each platform: https://github.com/mozilla-services/guardian-vpn-windows/issues/149

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN cross-platform build while using: Linux and MacOS.
Postfix video below.
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/15685960/99801445-b59f1300-2b3e-11eb-8381-33a50084fa78.gif)

**Comment by ValentinaPC** [comment]
@bakulf could we fix this for iOS, also? Thanks!
