### ISSUE TITLE
[Linux] Some VPN taskbar menu options are not correct

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#255]
#### Affected versions:
- 2.202011181852;

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Click the VPN app icon from taskbar/menubar;
3. Observe the “Show Mozilla VPN” option

#### Expected result:
-  If the VPN is displayed on your desktop, the “Show” option should be replaced with a “Hide” option..

#### Actual result:
- When the VPN is displayed on your desktop the “Show” option is still available and doesn’t do anything.

#### Notes:
- We should also consider in changing the “Preferences...” option to "Settings".

![image](https://user-images.githubusercontent.com/15685960/99649169-887a3400-2a5c-11eb-9d2c-249853eee950.png)

**Comment by bakulf** [comment]
@jess-cook03, two questions:
1. are you OK with renaming 'preferences' to 'settings'? Note that this is cross-platform.
2. about hide/show?

**Comment by jess-cook03** [comment]
@bakulf 
1. Yes renaming preferences to setting totally makes sense -- lets do it ✅

2. Agreed here that the Show/Hide is currently strange -- I agree with the expected result here -- when the VPN is displayed it should say "Hide Mozilla VPN" and when it closed it should say "Show Mozilla VPN'

**Comment by bakulf** [comment]
Can we keep 'preferences' to 'settings' in a separate issue? I'm not totally sure this is the right decision.
On macOS, apps' settings are called 'preferences'.

**Comment by ValentinaPC** [comment]
Verified as fixed while using the VPN cross-plat builds on Linux (2.202012021409) and Mac OS (2.202012022042).
The "Show/Hide" option from menubar works as expected.
![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/15685960/100983042-736bcd80-3551-11eb-8553-354b008c87f9.gif)
