### ISSUE TITLE
Add ability to timeout server locations from the inspector

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2565]
In order we and QA can test the work around [Add a generic error to handle when a server location is down (VPN-858)](https://mozilla-hub.atlassian.net/browse/VPN-858) reliably we need a way to timeout all servers in a city from the inspector.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1533)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

A new command was added in the VPN Inspector so the the server unavailable screen and notification are triggered.

Marking this as verified fixed.
