### ISSUE TITLE
Wrong error message displayed in “Problem confirming subscription” error screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2573]
**VPN version:**

* 2.7.0 (2.202201122015);

**Tested Platforms**:

* iOS;

**Prerequisites**:

* Have Mozilla VPN app installed and opened;
* Have an Apple ID that is associated with a FxA account that has an expired subscription for Mozilla VPN;
* Have a second FxA account without subscription;

**Steps to reproduce**:
1. Tap on “Sign up” / “Already a subscriber?” button from the onboarding screen;
2. Sign in with the second FxA account mentioned in prerequisites;
3. Tap on “Already a subscriber?” button from IAP screen;
4. Observe the subscription error screen;

**Expected result**:

* “Sorry we are unable to connect your Firefox Account to a current subscription. Please try again or contact our support team for further assistance.” text is displayed;

**Actual result**:

* “Another Firefox Account has already subscribed using this Apple ID. Please sign out and try again or contact our support team for help.” text is displayed instead;

**Notes:**

* If we have an Apple ID with a valid IAP subscription that is associated with a FxA account, and we login into VPN with another FxA account without subscription, the: “Sorry we are unable to connect your Firefox Account to a current subscription. Please try again or contact our support team for further assistance.” text is displayed;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1543)

**Comment by lesleyjanenorton** [comment]
Was this fixed in #2580 ?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202201161929), while using iOS. “Sorry we are unable to connect your Firefox Account to a current subscription. Please try again or contact our support team for further assistance.” text is now displayed.

**Comment by data-sync-user** [comment]
➤ Moritz Birghan commented:

Lesley Norton Yes this was fixed in #2580.
