### ISSUE TITLE
MAC extension panel does not reflect the Mozilla VPN app being installed on MacOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2578]
**MAC version:**

* 8.0.4;

**VPN version:**

* 2.7.0 (2.202201130406);

**Affected Platforms**:

* MacOS;

**Prerequisites**:

* Have Mozilla VPN installed and opened;
* Have Mozilla VPN in ON state;

**Steps to reproduce**:
1. Install MAC extension on Firefox browser;
2. Click on the MAC icon;
3. Go through the onboarding panel, while enabling the additional permissions;
4. Click on the MAC icon;
4. Observe the MAC main panel;

**Expected result**:

* Mozilla VPN status indicator which reflects the “ON” state is displayed on the MAC panel;

**Actual result**:

* Mozilla VPN promo is displayed instead of the Mozilla VPN status indicator.

**Notes**:

* This is a major issue because the user is not able to set a custom location from the MAC extension, which is the main MAC-VPN integration functionality;
* If the VPN is on, and the user opens a container from the MAC extension, and checks the location on the Mullvad connection check page (https://mullvad.net/en/check/), the location from the VPN app is displayed on the site;
* See the attached screenshot;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1550)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

I can reproduce this in the latest 2.7 VPN build, but not with 2.6.1. I think this stems from a bug in the VPN client and not the addon. Please file this in the client repository. Thank you for catching!

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Bianca Hidecuti I expect you tested this on other operating systems, but would you please confirm that this is MacOS only?

**Comment by lesleyjanenorton** [comment]
Removing my assignment but will continue to look into this. The newest MAC addon build works as expected with the 2.6.1 build but does not work with the 2.7 build so my feeling is this is an issue in the client. Strangely, the port seems to be successfully connected but then no messages are ever received by the addon. I don't know if it's the same issue but we have run into some similar before here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2312, which was solved via https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2283/files.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Rebecca Billings , yes, this is only reproducible on MacOS.

**Comment by strseb** [comment]
@lesleyjanenorton  - I am currently very suspicious about this. 
- Locally, using my own build (including the own native-messaging) I can't reproduce it. 
- When using the CI generated pkg, things go wrong: 
-- OSX instantly sends SIGKILL (9) to the native-messaging app, thus the extension-port never sends/receives things. 
- However, using the binary from the osx-release-tarball (which we will be using to sign), everything is working fine here as well. 

So i don't quite know. I would now assume this is a signing issue in our pkg generation.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202201182309) while using MacOS Big Sur 11.6 and the latest MAC extension build.

**Comment by user-09876** [comment]
I can also report the same issue in the same condition on arch linux latest. Ref: https://github.com/mozilla/multi-account-containers/issues/2277
