### ISSUE TITLE
Restrict MAC What's new panel to desktop 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2586]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1556)

**Comment by flozia** [comment]
I just checked and this should already the current behaviour.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Verified this on an Android 9 device, using Mozilla VPN 2.7.0 (16421270), and only the Multi Hop feature is present in the What`s New popup. See below screenshot:

!Screenshot_20220117-111400.jpg|width=1440,height=3040!

CC: Valentina Virlics
