### ISSUE TITLE
What's new: Hide indicator dots when there is only one panel

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#2588]
Let's hide indicator dots on What's new panels when there is only one panel...

This lone dot feels more strange than helpful.
![IMG_4FAA9FE392CE-1](https://user-images.githubusercontent.com/22355127/149700738-ba646cb6-c035-4cc5-a372-bf98464d2844.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1557)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on the last VPN builds, across platforms.

When there is only 1 new feature in What’s new menu, there is no navigation indicator in the popup.

Postfix screenshot below.

!image-20220118-090748.png|width=335,height=509!
