### ISSUE TITLE
Add install attribution to mobile VPN clients

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#260]
Attribution will be used to understand if acquisition efforts are successful, so that the marketing team can focus their time where new customers are finding value from the Mozilla VPN.

We have attribution today on the Windows client since the acquisition goes through the website. This is not totally the case for the mobile clients due to the app stores. 

On the v1.0 Android we included a library that passes through the Google Play store referral, but I am not sure if that is included in the new v2.0 cross platform clients.

See previous commit on adding the library to Android:

https://github.com/mozilla-mobile/guardian-vpn-android/commit/c02f0fa6e4c762df2c68b7e713136c5a4ea91a45

From previous investigations, it doesn't look like there is a similar on iOS.

**Comment by chrismore** [comment]
@bakulf is this possible to do on the cross-platform code and include this library for Android? If not, when Android launches, we will regress in our attribution for that platform. Previous investigations found that we can't do this on iOS.

**Comment by ValentinaPC** [comment]
Is there a way that QA can verify this? Thanks!
