### ISSUE TITLE
VPN should auto reconnect to the VPN when VPN=ON and internet is now reconnected

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#261]
I tested this on Mac, but I assume it should be the same on other platforms. I need to test this on the v1.0 clients, as I think this is a regression.

Steps to reproduce:

1) Connect to the VPN
2) Confirm you have a different IP
3) Disconnect your internet connection
4) Confirm that the VPN goes to an "unstable: no internet" state and switch is ON
5) Reconnect your internet connection

Expected results:

VPN reconnects to the remote VPN server very soon after Internet is available

Actual results:

VPN remains "unstable: no internet" (I waited 30 seconds and nothing changed unless I have to wait longer)

Resolving this issue should also help with Captive Portal detection in issue #224

**Comment by chrismore** [comment]
@ValentinaPC could you test this on the v1.0 clients on either Windows, Android or iOS and see if this is a v2.0 cross-platform (Mac, Linux, or iOS) client regression? Thanks!

I tested this on my Windows 10 machine and this looks like a regression. With the Windows v1.0 client, the VPN automatically reconnects as soon as the Internet is restored. On v2.0, the VPN will remain in an "ON" state, but in the "no signal" state.

**Comment by ValentinaPC** [comment]
@chrismore 

- Verified this on **Windows 10** x64, using the **1.2** VPN Windows client and the expected result was the correct one: after reconnecting the internet the VPN app changed its state from "Unstable" to active, in less de 1 second.

- Verified this on **Android 10**, using the last - 2 - VPN **cross-platform** build and the expected result was the correct one: after reconnecting the internet the VPN app changed its state from "No signal" to active, in less de 1 second.

- Verified this on **Linux Ubuntu 20.04**, using the last - 2.202011200942 - VPN **cross-platform** build and the expected results was the correct one: after reconnecting the internet the VPN app changed its state from "No signal" to active, in maximum 5 seconds.

-  Verified this on **Mac OS**, using the last - v. 2.202011200952- VPN **cross-platform** build and the expected results was the correct one: after reconnecting the internet the VPN app changed its state from "No signal" to active, in maximum 5 seconds.

- Verified this on **iOS**, using the last - 2.202011181854 - VPN **cross-platform** build and the expected result was  the correct one: after reconnecting the internet the VPN app changed its state from "No signal" to active, in less de 2-3 seconds.

Results: I cannot reproduce the issue neither on Win with the old VPN client nor on other platforms with the cross-platform builds.

**Comment by chrismore** [comment]
@ValentinaPC thank you! I just verified with the latest Mac build and the issue is now resolved. It must have been fixed in one of the latest builds. I will close. Thanks
