### ISSUE TITLE
Refactor how we handle an attempt to reconnect to an unavailable server

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2615]
In order to prevent that the VPN gets stuck in `StateDisconnecting` when a user tries to reconnect with an unavailable server we introduced PR #2610. The code introduced here should be refactored and the aforementioned issue should better be handled in `Controller::disconnected()`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1584)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

QA shouldn’t be required for this issue, there shouldn’t be any user-visible changes in behavior.
