### ISSUE TITLE
Menu bar icons look very small on mac release builds

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#262]
<img width="418" alt="Screen Shot 2020-11-19 at 12 42 40 PM" src="https://user-images.githubusercontent.com/22355127/99709424-c7ac8300-2a64-11eb-88d9-a09d9a4bffab.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on the VPN cross-plat build (v.2.202012022042) while using Mac OS
The VPN icon has the same dimension as the others.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/101027030-4682df00-3580-11eb-94eb-468997e9e82c.png)
