### ISSUE TITLE
Mozilla VPN signed build cannot be installed on MacOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2628]
**VPN version:**

* 2.7.0;

**Tested Platforms:**

* MacOS;

**Steps to reproduce:**

1. Go to [https://archive.mozilla.org/pub/vpn/candidates/2.7.0-candidates/build2/mac/](https://archive.mozilla.org/pub/vpn/candidates/2.7.0-candidates/build2/mac/|smart-link) 
1. Download the .pkg file;
1. Install the file on your device;

**Expected result:**

* The Mozilla VPN app is successfully installed;

**Actual result:**

* The installation failed;

**Notes:**

* At the end of the installation, a “Mozilla VPN quit unexpectedly” message appears;

* The app appears in the “Applications” folder, but when trying to open it, “You do not have permission to open the application” message is displayed, together with a crash message. 

* This is a blocker issue because QA is not able to test the self-update and MAC - VPN Integration;

* See the attached files;

* See the attached screenshots;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1597)

**Comment by lesleyjanenorton** [comment]
I can reproduce this. Deleting all previous installs and then re-installing resolves this for me however.
<img width="300" alt="Screen Shot 2022-01-21 at 9 44 52 AM" src="https://user-images.githubusercontent.com/22355127/150556699-52dde924-f8a2-4b9a-9e07-86a5a7c601e4.png">

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.0 (2.202201192357), while using MacOS. Mozilla VPN is successfully installed.
