### ISSUE TITLE
The “Server unavailable” modal is displayed for wrong location

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2637]
**VPN version:**

* 2.7~rc15 (2.7~rc15-hirsute1);

**Affected Platforms:**

* All;

**Preconditions:**

* Have Mozilla VPN app installed and opened;
* Be signed in while on Stage server;
* VPN is OFF;

**Steps to reproduce:**

1. Navigate to Settings - Get help - Developer Options - Open Inspector;
1. Have the location server set to Vienna;
1. Enter the following command in Inspector: force_server_unavailable at vie;
1. Change the location to another server: i.e Spain - Madrid;
1. Turn ON the VPN;

**Expected result:**

* The VPN is turned On, the server unavailable modal is not triggered;

**Actual result:**

* The Server unavailable modal  is displayed;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1615)

**Comment by oskirby** [comment]
I think this is a bug caused by the `force_server_unavailable` command which directly triggers the notification on the next connection attempt, regardless of where the connection attempt was made. This should be cleaned up in PR #2633

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Seems like the server unavailable modal issue has a different cause, that the fact that is being triggered from the Inspector, and there is a way that we can trigger the modal outside the Inspector. See last comment from https://mozilla-hub.atlassian.net/browse/VPN-1579 ( https://mozilla-hub.atlassian.net/browse/VPN-1579|smart-link ) ;

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

I’m going to close this issue, since we have removed the buggy behaviour of the force_server_unavailable inspector command, and it no longer directly triggers the notification and instead just blocks a particular location on the next connection attempt.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last VPN 2.8.0(2.202204052006) while using iOS and VPN 2.8.0 (2.202204060304) while using Windows 10.

The server unavailable modal is no longer triggered for the wrong location.
