### ISSUE TITLE
Qt6 / Android Buttons Look Wonky

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#2639]
Alot of the buttons look wonky on QT6 / android. They are functional but their styling is all over the place. 

My current guess ist that the native base-components are injecting some styles we need to disable or so :/

![151009314-49822658-0025-4a98-b82b-63597e8c9eab](https://user-images.githubusercontent.com/9611612/151036992-5dc4dbe1-0aff-4a6d-b80f-9e22da04c761.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1616)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on the last VPN 2.7 (16437330) QT6 build while using Android 10 device.

Postfix screenshot below.

!Screenshot_20220203-102202.png|width=1080,height=1920!
