### ISSUE TITLE
[iOS] Reproducible crashes on startup

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/mozilla-vpn-client#265]
Using iOS 14.2 and the 2.202011191540 build, I can't launch the app. It immediately crashes with no further indications:

![crash MP4](https://user-images.githubusercontent.com/344777/99717098-37dcf800-2aa9-11eb-824a-90ecffc33272.gif)

**Comment by denschub** [comment]
Attached are all messages I see in Console.app, filtering for "FirefoxVPN". If that's not useful, I'd appreciate some guidance on how I can gather useful logs. :)

[log.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/5569384/log.txt)

**Comment by bakulf** [comment]
The crash is fixed. But I want to check a couple of things with the rest of the team before pushing a new build.

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
The VPN app starts with success.
