### ISSUE TITLE
Multi-Account Containers Extension Integration (Linux)

### ISSUE THREAD

**Issue by derenv** [mozilla-mobile/mozilla-vpn-client#2650]
This is a feature i've been excited about, but doesn't seem to be working on my system. Basically the extension doesn't seem to recognise the VPN as present what so ever:

-the "Mozilla VPN logo and a status indicator will be visible on the main panel" mentioned [here](https://support.mozilla.org/en-US/kb/protect-your-container-tabs-mozilla-vpn) isn't present

![Screenshot_20220128_140902](https://user-images.githubusercontent.com/35734401/151561628-3c29680d-cdd0-49eb-8c26-899b24395b62.png)

-the "toggle will show in the Mozilla VPN section of your container editing panel once you have integrated the VPN." mentioned [here](https://support.mozilla.org/en-US/kb/protect-your-container-tabs-mozilla-vpn) also isn't present

![Screenshot_20220128_140919](https://user-images.githubusercontent.com/35734401/151561632-29645d7d-45b8-46ab-ac82-c69cde3fe141.png)

(the VPN was on and connected during these screenshots)

The problem occurs in both firefox (v96.0.3-0.1 from the official repositories) and firefox-developer-edition (v97.0b3-1 from the official repositories).

Here's my system info:
Kernel: 5.16.2-1-MANJARO on x86_64
DE: Plasma 5.23.5
WM: KWin
DM: sddm
DS: x11

Extensions:
Bitwarden
ClearURLs
Facebook Container
Firefox Multi-Account Containers
Mendeley
Plasma Integration

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1633)

EDIT: The VPN version is 2.7.0-1 from the AUR repository

**Comment by user-09876** [comment]
Also here https://github.com/mozilla/multi-account-containers/issues/2277
