### ISSUE TITLE
Blank screen when changing options in Developer Options

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#2654]
When toggling options in the _Developer Options_ view the app shows a blank screen on Android when compiled with Qt 6.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1639)

**Comment by strseb** [comment]
@flozia  is there a specific setting that causes it ?
![screen-20220210-142650_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/9611612/153418231-798e3c18-80fa-4271-998a-010da79aa418.gif)

**Comment by flozia** [comment]
@strseb It is the _Use Staging Servers_ option that is triggering the issue for me. The screen recording shows it happening on an Android emulator and after swipe killing and retrying a couple of times it is working. If it’s not reproducible on a real device we should be good.

https://user-images.githubusercontent.com/13835474/153483996-c9c672f2-141c-471c-95a2-43ba90c73870.mov
