### ISSUE TITLE
Traffic chart UX improvements

### ISSUE THREAD

**Issue by martinbalfanz** [mozilla-mobile/mozilla-vpn-client#269]
On iOS, the traffic chart animates rather unconventionally. It looks like an inchworm crawling. What I would have expected is a that the chart shifts to the left without changing it's "form" on the vertical axis.

![RPReplay](https://user-images.githubusercontent.com/653763/99811024-dec2a200-2b44-11eb-9efe-583babf686b5.gif)UNITO-UNDERSCORE!Final1605881919 2020-11-20 15!UNITO-UNDERSCORE!27!UNITO-UNDERSCORE!06!

Additionally, it's unclear what the numbers show.

* The IP address at the top, is that my real IP or the VPN IP?
* The download and upload "speeds", what do they show? I expected it's related to my current traffic, somehow in sync with the chart on the very right corner. But as you can see in the video above, they remain unchanged regardless of the traffic.

So, overall I find this screen rather confusing at the moment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-81)

**Comment by bakulf** [comment]
I would like to have the UX team to take a look at this issue. How can we improve the usability of this view? @jess-cook03

**Comment by bakulf** [comment]
Now the numbers (download/upload) show the bandwidth per second. This is similar to what the windows app does.

**Comment by ValentinaPC** [comment]
Verified  on the latest cross-plat VPN builds while using Android 10, Linux Ubuntu 20.04, Mac OS and iOS.
The graph is no longer "crawling", but there is a small layout issue regarding the screen size on Android, as you can see below.
![Screenshot_20201203-105125](https://user-images.githubusercontent.com/15685960/100991651-ebd78c00-355b-11eb-8e3c-8229ac224321.png)

**Comment by lesleyjanenorton** [comment]
I filed #365 to address the broken layout and the issue should be fixed in #366

**Comment by ValentinaPC** [comment]
Based on the above comment, we can mark this as verified and close it.

**Comment by bakulf** [comment]
We are removing this component. Closing the issue

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Jessica Cook I think I asked this in Slack, but I can’t find the conversation 😞  Are we good with closing this issue, since it’s covered by the 243 story?
