### ISSUE TITLE
VPN server unavailable error

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#2703]
**Description**

After updating to 2.7, VPN fails to connect displaying "Server not available" error message on every server location. Doing a soft and hard VPN reset does not help fix the issue. 

**Technical Information**

Platform Windows 10/11
FX product Mozilla VPN 2.7

**Steps to Reproduce**
1. Purchase VPN subscription
2. Install VPN on device
3. Flip switch to turn On VPN

**Actual Results**
- After tapping switch to turn on an error message will show in the VPN saying "server is unavailable"

**Expected Results**
- Tapping switch should turn VPN On and show connected regardless of server location.

[mozillavpn-2022-2-4.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8033111/mozillavpn-2022-2-4.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1703)

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

Hey I thought I would update this ticket, seeing there was no response for a while. I have 2 users who confirmed that the VPN is installed on 2 or more devices, but they have not removed it on either. The reinstalled the VPN, deleted app data, tried different DNS settings, but there is no success in connecting the VPN . I will attach some logs of the latest user, maybe it helps

[^mozillavpn-2022-2-8 (2).txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

adding another set of logs from a different user

[^mozillavpn-2022-2-25 (1).txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

FYI: Markus workaround was successful so far for Windows 10 users (verify the Windows local service is running, open Task Manager (ctrl + shift + ESC) and select the Services tab. Locate the service Mozilla VPN Broker. Check the status for "stopped". If it is stopped, right click on the service and select "Restart".)

Regardless, I have one user on Windows 10 (VPN version 2.7.1) where this was not successful . all steps followed are the same: they did a full reset of the VPN app and then tried to restart the service in their task manager. screenshot of error code is the same (regardless of the server they connect to it says “server unavailable”) , screenshot of task manager shows the service is running (“wird ausgeführt”) - logs are also attached

not sure what is different for this user, but I thought I would bring it up in case its relevant for finding a fix

!Taskmanager.server.unavailable.JPG|width=838,height=759!

!server.unavailable.png|width=362,height=559!

[^mozillavpn-2022-3-15 (2).txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Issue is also happening on macOS and basic troubleshooting does not help in all cases

[^mozillavpn-2022-3-18.txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

is there an equivalent workaround to restart a service on Mac (like restarting the service in task manager on Windows)?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Can you provide MacOS logs if you have them?

What I see is that:

  * log 1 (mozillavpn-2022-2-25) - windows - the service is not running at all.
  * log 2 (mozillavpn-2022-2-8) - windows - there are handshaking VPN issues
  * log 3 (mozillavpn-2022-3-15) - windows - the service was slow at startup, then probably there are connectivity issues
  * log 4 (mozillavpn-2022-3-18.txt) - windows - the are no VPN activations in the log.

**Comment by ManuelCalidonio** [comment]
Update on a user that reported the workaround suggested my Markus did not improve the experience. The user tried:

1. Press CTRL + Shift + ESC to open the task manager
2. On Processes locate the Mozilla VPN app
3. Right-click it and End task
4. Select the Services Tab on the Tast manager
5. Scroll down and locate Mozilla VPN Broker
6. Check Status
7. If stopped
8. Right-click
9. Select "start"
10. If Running
11. Right-click
12. Select "Restart"

The user also tried the following:

1. Open Task Manager
2. Click the Processes
3. End Task Mozillavpn.exe
4. Click Services
5. Find MozillaVPNBroker
6. Right-click and Select Open services
7. Search for MozillaVPNBroker again
8. Double click it and select the Start-up to Automatic (Delayed Start)
9. Apply
10. Ok and try again

Attached logs after attempting the above.
[mozillavpn-2022-3-29 (1).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8444850/mozillavpn-2022-3-29.1.txt)

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Attaching macOS logs

[^mozillavpn-2022-3-19.txt]

**Comment by JKingZapata** [comment]
Attaching logs for non-supported Linux Trisquel 10.0.1

[mozillavpn-2022-8-5-1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9294867/mozillavpn-2022-8-5-1.txt)

**Comment by davidhedlund** [comment]
> Attaching logs for non-supported Linux Trisquel 10.0.1
> 
> [mozillavpn-2022-8-5-1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9294867/mozillavpn-2022-8-5-1.txt)

https://github.com/mozilla-mobile/mozilla-vpn-client/issues/4230

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

As of 8/25/2022 we’ve had ~80 reported issues. This issue was first reported 2/9/2022. Initially thought to be on Windows only, our first report of Mac OS was 3/10/2022. 

  * This affects Core user Journey
  * This is annoying
  * Average affected user count per month is 13.3 a month. 
  * There is a workaround on Windows but not Mac OS.

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

attaching set of logs from user on Windows 11 , VPN version 2.9.0 - full reset of VPN app/deleting app data didn't help and the broker is running in the task manager , still cant connect to any server 

[^mozillavpn-2022-9-28.txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Fresh Windows logs on 2.9 

[^mozillavpn-2022-10-5.txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

We have received latest logs for this issue on VPN version 2.10 - Windows 10 . see attached

[^Dublin_mozillavpn-2022-10-26.txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

another user experiencing “server unavailable” error on Windows 10 , VPN version 2.11
(they also mention that they have no problems on their Windows 11 device, same network and VPN version, if helpful we can request VPN logs from that device to compare?) 

attached affected device 

[^mozillavpn-2022-11-23.txt]

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Andrea Marchesini should you un-assign from this?

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

I have received additional logs from a user on 2.12 who has been experiencing this issue since version 2.10

Windows 10 . 

[^mozillavpn-2022-12-27.txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

another set of logs from WIN10 on VPN version 2.12

[^mozillavpn-2023-1-26.txt]

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closed during bug squashing. Low / stale.
