### ISSUE TITLE
Investigate if currentDevice() in Controller::activate might be realistically nullable.

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#2776]
-> vpn->deviceModel()->currentDevice(vpn->keys()); is nullable. 

-> Q: What would happen if TaskAccount new devicemodel does not include the current used keys?
-> How would we get there. I think it's the crash cause for VPN-1747
maybe we should check it before deref. 

``` i.e 
  if (device == nullptr) { resetAPP()});
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1759)

**Comment by bakulf** [comment]
I managed to reproduce it. Yes, this is totally possible. We need to add an intermediate TaskFunction when re-generating the device key to check if all is OK. if not, reset() is a good option. We must check that we do not have other tasks after the reset.
