### ISSUE TITLE
Leaving the password field empty redirects the subscriber to the Email authentication screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2779]
*Affected versions:*

* Mozilla VPN 2.7.1 (16449500) - QT6 build;

*Tested Platforms:*

* Android;

*Prerequisites:*

* Have a FxA account with an active subscription for Mozilla VPN;

* Have Mozilla VPN app installed and opened;

*Steps to reproduce:*

* Tap on the “Sign up” / “Already a subscriber?” button;
* Enter your email address that is associated with the FxA account from prerequisites;
* Tap on the “Continue” button;
* Leave the password field empty;
* Tap on the “Sign in” button 2 or 3 times;
* Observe the behavior;

*Expected result:*

* The user is asked to enter the password in order to finalize log in/ an error message is displayed blocking the user from continuing. (?);

*Actual result:*

* User is redirected to the Email authentication screen where he cannot longer use his email (from step 2);

*Notes:*

* If the user taps on the “Continue” button again, nothing happens. 

* This is a qa-major issue because the user is not able to sign in with an account with subscription, even after app reset;

* Uninstall of the app fixes the issue;

* See the attached video;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1762)

**Comment by bakulf** [comment]
The issue is related to the multiple execution of `signIn()`. In general, the `VPNAuthIn` state machine does not communicate when an operation is in progress. We must expose this to the front-end code to avoid multiple button clicks.

There are basically 2 ways:
- expose transition states (Starting, Signing-In, Signing-Up, checkingAccount, sendingUnblockCode, etc...)
- expose a boolean flag when an operation is in progress.

I think the second approach is better.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Fixed in VPN-1776

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.7.1 (16451180) - QT6 build, while using Android 10. Even though an error message is displayed when leaving the password field empty, after pressing 2-3 times on the “Sign in” button, I am still able to reproduce it. 

Attaching some logs. 

[^Mozilla VPN Logs (65).txt]

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.7.1 (16456580) - QT6 build, while using Android. An error message is displayed if the password field is empty.

Andrea Marchesini The issue is still reproducible if the “Sign in” button is pressed multiple times (aprox 6 times).

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.8.0 (16471740), while using Android. An error message is displayed when leaving the password field empty and the “Sign in” button is disabled.
