### ISSUE TITLE
User is able authenticate in app even though he did not set a password for that account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2781]
*Affected versions:*

* Mozilla VPN 2.7.1 (16449500) - QT6 build;

*Tested Platforms:*

* Android;

*Prerequisites:*

* Have no FxA account;

* Have Mozilla VPN app installed and opened;

*Steps to reproduce:*

* Tap on the “Sign up” / “Already a subscriber?” button;
* Enter an email address that is not associated with a FxA account;
* Tap on the “Continue” button;
* Leave the password field empty;
* Tap on the “Sign up” button;
* Observe the behavior;

*Expected result:*

* User is asked to set a password for his account  / an error message is displayed / user cannot continue (?);

*Actual result:*

* User is redirected to the “Email verification needed” screen, where he can enter a verification code.

*Notes:*

* If the verification code is entered, the user is redirected to the IAP screen. The subscription can be finalized with success and the user is redirected to the VPN activation screen;

* User can log into the client and activate VPN using the passwordless account; same is not possible on web;

* See the attached video;

* This is a qa-major issue because the user is able to sign in on the mobile client even though he did not set a password;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1763)

**Comment by bakulf** [comment]
With the latest UI, I cannot reproduce this bug.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.7.1 (16450720) - QT6 build, while using Android. The user cannot continue with the account creation until a password is entered.
