### ISSUE TITLE
As a user, I want buttons that perform the same function to look the same - [make new 'Cancel' component]

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2783]
Spec: [https://www.figma.com/file/gSRPHqjzqjlMA9rXDc5SqH/VPN_Mobile-Conversion-Funnel_InApp_Auth-%26-FXA-Creation?node-id=636%3A7254](https://www.figma.com/file/gSRPHqjzqjlMA9rXDc5SqH/VPN_Mobile-Conversion-Funnel_InApp_Auth-%26-FXA-Creation?node-id=636%3A7254|smart-link) 

[https://www.figma.com/file/gSRPHqjzqjlMA9rXDc5SqH/VPN_Mobile-Conversion-Funnel_InApp_Auth-%26-FXA-Creation?node-id=676%3A11544](https://www.figma.com/file/gSRPHqjzqjlMA9rXDc5SqH/VPN_Mobile-Conversion-Funnel_InApp_Auth-%26-FXA-Creation?node-id=676%3A11544|smart-link) 

The in-app auth views stipulate a red ‘Cancel’ button, for which we created VPNInAppAuthentiationCancel.qml. After looking through the app, it appears our ‘Cancel’ buttons appear in both blue and red, are different fonts, and different font weights. This is strange. We should have a single ‘Cancel’ treatment and component, like we have for ‘Sign out', and replace instances of ‘Cancel’ everywhere with this single component, remembering to preserve existing `onClicked:` functionality as appropriate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1766)

**Comment by MattLichtenstein** [comment]
@lesleyjanenorton did you notice this inconsistency anywhere else besides the Contact Support page?
