### ISSUE TITLE
Multi-hop doesn't work on Fedora 35 without Gnome Shell

### ISSUE THREAD

**Issue by dannycolin** [mozilla-mobile/mozilla-vpn-client#2788]
### Step to reproduce
1. [Download the RPM package from GitHub Actions on the official repository][download] (Last build tested: 2.7~rc15)
1. Install the package with `dnf install ./path/to/RPM/package` (this is needed to ensure that all dependencies are installed)
1. Open Mozilla VPN Client
1. Configure Multi-Hops

### Actual behavior
Mozilla VPN fails to connect to the servers configured in the multi-hops preference and return a "Server unavailable" error. I have tested multiple server permutations to be sure that it wasn't limited to only a specific set (or specific order) but it didn't look like it.

![mozilla-vpn-unavailable-server-multi-hops](https://user-images.githubusercontent.com/7339076/154329384-9fa0f46a-01e7-467a-9414-3194dc66d058.png)

### Expected behavior
Mozilla VPN successfully connects to the servers (enter and exit nodes) configured in multi-hops.

[download]: https://github.com/mozilla-mobile/mozilla-vpn-client/actions/workflows/linux.yaml?page=2&query=branch%3Amain

### Additional informations
* strace log: https://gist.github.com/dannycolin/811e03f5b35875f1598b903245e825df
* systemd log: https://gist.github.com/dannycolin/5d6567aabfcbece8697f46c7a1e5dcf8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1767)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This might have the same root cause as: https://mozilla-hub.atlassian.net/browse/VPN-1748 ( https://mozilla-hub.atlassian.net/browse/VPN-1748|smart-link ) Andrea Marchesini, could you confirm? Thanks!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I’m not sure yet.

**Comment by dannycolin** [comment]
I've done a fresh install of Fedora 35 (the default install with Gnome) and it now works. I seems like it must be related to a dependency issue or a system configuration that isn't present on (some) non-Gnome environment. 

@oskirby any idea what dependency or configuration could be missing here? or if it could be the same underlaying issue than #1869?

**Comment by dannycolin** [comment]
Still doesn't work on Fedora 36 minimal install but does on Fedora Workstation (Gnome).

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closed during bug squashing. Stale.
