### ISSUE TITLE
Compile mozillaVPN for macOS supporting universal binaries (x86 + apple silicon)

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#286]
https://bugreports.qt.io/browse/QTBUG-85279

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-82)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Is this really a bug or a feature request? What is obtained by this?

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

This would improve network performance on the modern Apple macbooks based on the M1 and M2 chips.

**Comment by jensschaefer** [comment]
+1

**Comment by strseb** [comment]
Done :)

**Comment by yungchin** [comment]
Thanks for all the hard work on this! Can I ask: should this now just work when I fetch the installer from https://www.mozilla.org/en-GB/products/vpn/download/ -- if I understand correctly, all the PRs linked above should be included in the 2.16.0 tag, and I think that's the build I'm getting, but this still prompts me to install Rosetta?

**Comment by strseb** [comment]
The binary is universal, however it seems we forgot to mark the installer as universal too 😓 - Sorry about that.

**Comment by yungchin** [comment]
Ah super, thanks for looking into it so quickly, and for opening a new issue 🙏
