### ISSUE TITLE
The "Done" button on the keyboard does not work when trying to log in

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2871]
**VPN version:**

* 2.7.1 (16460300) - QT6 build;

**Platforms:**

* Android 9;

**Prerequisites:**

* Have and account with a subscription for Mozilla VPN;

* Have the Mozilla VPN app installed;

**Steps to reproduce:**

1. Open the Mozilla VPN app
1. Tap on the email address text field to start the login process;
1. Insert the email address and tap on “Done”;

**Expected results:**

* The keyboard closes and the user can see the “Continue” button;

**Actual results:**

* The keyboard does not close, obstructing the user's view of the main app screen; 

**Note:** please see below video.

There are a couple of workarounds for this issues.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1836)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This issue seems to have gotten fixed here ( https://mozilla-hub.atlassian.net/browse/VPN-1835 ).  

  * tapping the Done button while on the email screen, takes the user to the pasword screen, and 
  * tapping the Done button on the password screen, starts the login process.

The potential issue remaining is that, when tapping the Done button on the password screen, the user is not actually aware that the login process is started, because the cursor is still active and the screen does not get blocked until the spinning wheel screen is displayed, which takes a little time.

Please see attached video.

!20220314_143513.mp4|width=480,height=854!

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Rebecca Billings Betty Fleming considering my latest comment, are we good to close this as fixed or do you want to make additional changes to the behaviour described?

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Lesley Norton when you have time, can you take a look and give us your opinion?

**Comment by lesleyjanenorton** [comment]
Since this is technically fixed I'm going to close this and open another issue to address comments.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Issue to address comments: https://mozilla-hub.atlassian.net/browse/VPN-2134 ( https://mozilla-hub.atlassian.net/browse/VPN-2134|smart-link )

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Lesley Norton Should this be closed, now that we have a new issue to adress the remaining comments?

Thank you.
