### ISSUE TITLE
“Change email” link displayed in the Verification screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2958]
**Affected versions:**

* Mozilla VPN 2.8.0 (16467990) - QT6 build;

* Mozilla VPN 2.8.0 (2.202203021306); 

**Tested Platforms:**

* Android;

* iOS;

**Prerequisites:**

* Have Mozilla VPN app installed and opened;

**Steps to reproduce:**

1. Tap on the “Sign up” / “Already a subscriber?” button;
1. Enter an email address that is not associated with a FxA account and tap on the “Continue” button;
1. In both password fields enter a valid password and tap on “Sign up” button;
1. Observe the “Change email” link from the Verification screen;

**Expected result:**

* There is no “Change email” link in the Verification screen, as per [+Figma file+](https://www.figma.com/file/gSRPHqjzqjlMA9rXDc5SqH/VPN_Mobile-Conversion-Funnel_InApp_Auth-%26-FXA-Creation?node-id=1089%3A16050);

**Actual result:**

* “Change email” link is displayed in the Verification screen;

**Notes:**

* See the attached screenshots;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1884)

**Comment by lesleyjanenorton** [comment]
Will be fixed when #2868 is merged

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on the last Android build - 2.8.0 (16471740). “Change email” link is not displayed in the Verification screen.

This will be verified on iOS as well, when a new build will be available.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Marking this verified as fixed, as the “Change email” link is no longer displayed on the lastest build on iOS.
