### ISSUE TITLE
[iOS] The VPN app crashes when trying to “Get started” after dismissing the sign in flow and tapping the “Cancel and try again” option

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#296]
#### Affected versions:
- 1.202011241205;

#### Affected Platforms:
- iOS 14.2;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Tap “Get Started”;
3. While the FxA login popup is prompted tap outside of it;
4. Tap on “Cancel and try again” option;
5. Tap “Get started”;

#### Expected result:
-  The user is redirected back to the sign in flow.

#### Actual result:
- The VPN app crashes.

**Comment by chrismore** [comment]
@ValentinaPC can we verify this fix?

**Comment by ValentinaPC** [comment]
Verified as fixed on iOS 14.2, while using the VPN version 2.202011301207.
There is no crash after tapping the "Cancel and try again" option and "Get Started" again.
