### ISSUE TITLE
Add loading screen for Android

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#300]
Add screen #000
https://www.figma.com/file/eVg5QFf12i6Od0Kc46sygl/Android
<img width="245" alt="Screen Shot 2020-11-25 at 10 23 51 AM" src="https://user-images.githubusercontent.com/22355127/100254747-522f2f80-2f08-11eb-8eac-5475f07bfcd7.png">

**Comment by ValentinaPC** [comment]
@lesleyjanenorton I cannot see the above screen on my Android, is there a special action, beside starting the app, to do?
Thanks!

**Comment by bakulf** [comment]
I haven't generated new builds yet. This feature should be available in the next builds.
