### ISSUE TITLE
DNS lookup fails while VPN is switched on (Arch Linux)

### ISSUE THREAD

**Issue by HitCoder9768** [mozilla-mobile/mozilla-vpn-client#3003]
When switching on Mozilla VPN it appears that DNS lookup fails.
Pinging an IP works fine while attempting to connect to a domain name or ping a domain name fails.

```
[hitcoder@hitcoder-endeavour ~]$ ping 142.250.187.206
PING 142.250.187.206 (142.250.187.206) 56(84) bytes of data.
64 bytes from 142.250.187.206: icmp_seq=1 ttl=119 time=3.47 ms
64 bytes from 142.250.187.206: icmp_seq=2 ttl=119 time=3.46 ms
64 bytes from 142.250.187.206: icmp_seq=3 ttl=119 time=3.37 ms
64 bytes from 142.250.187.206: icmp_seq=4 ttl=119 time=3.50 ms
64 bytes from 142.250.187.206: icmp_seq=5 ttl=119 time=3.65 ms
64 bytes from 142.250.187.206: icmp_seq=6 ttl=119 time=3.33 ms
^C
--- 142.250.187.206 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5008ms
rtt min/avg/max/mdev = 3.328/3.460/3.647/0.102 ms
[hitcoder@hitcoder-endeavour ~]$ ping google.com
ping: google.com: Temporary failure in name resolution
```

on Arch Linux (EndeavourOS) LINUX510 Kernel

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1906)

**Comment by oskirby** [comment]
Hi, thanks for the bug report. It will be a couple of days before I'll have a chance to test this out myself to see if I can identify the cause. In the meantime, would you be willing to provide us with logs showing an attempt to activate the VPN connection? These can be exported by navigating to the `Get Help` menu and clicking on the `View Logs` link.

In an effort to prevent leaking your browsing activity through your DNS queries, the VPN client will attempt to reconfigure your DNS server to use a server provided by the Wireguard servers. We perform this configuration using the systemd-resolved D-Bus service (see: https://www.freedesktop.org/software/systemd/man/org.freedesktop.resolve1.html). This may present an undocumented dependency on your chosen DNS resolver packages.

As an additional test, we can try using the `dig` tool to determine if this is a configuration problem, or a network connectivity problem by trying to resolve via some well known nameservers:
- `dig @8.8.8.8 www.google.com`: Check if we can resolve any DNS queries with the VPN activated
- `dig @10.64.0.1 www.google.com`: Check if we can resolve DNS queries via the VPN's Wireguard server.

**Comment by HitCoder9768** [comment]
Sorry for the late response, I don't seem to have the issue any more installing with the latest release (I'm installing from the AUR package here https://aur.archlinux.org/packages/mozillavpn and then enabling and starting mozillavpn.service), not sure if you've already implemented a fix for this or if it was caused by another issue. I'll close this for now in this case.

**Comment by shawn-peery** [comment]
I found this github ticket and was able to find a resolution that worked for me so I figured I'd provide the resolution.

I found this link
https://bbs.archlinux.org/viewtopic.php?id=288227

He did the following commands:
systemctl start systemd-resolved.service

systemctl enable systemd-resolved.service

And after I did those MozillaVPN was able to resolve DNS again. Hope this helps
