### ISSUE TITLE
Determine what the subscription validation loading screen should say and look like

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#302]
After someone has completed the IAP subscription flow with Apple, there is a pause while we validate the subscription on our end before redirecting the user to the main view. We need a transitional "loading" screen to show during this pause so that people don't get confused and think they're just stuck on the initial subscription view. 

Here is the placeholder introduced in #301, following the sign in validation loading screen...
<img width="300" alt="Screen Shot 2020-11-25 at 11 42 57 AM" src="https://user-images.githubusercontent.com/22355127/100265325-b6a4bb80-2f15-11eb-8344-3ed384f5e75f.png">

UX Questions

1.) If we want to use another image / approach - what should this look like?
2.) What should we say in the headline?

**Comment by chrismore** [comment]
Headline idea: "Please wait..." to make it more generic?

**Comment by chrismore** [comment]
or maybe something playful while it is doing something

**Comment by lesleyjanenorton** [comment]
Was there a consensus on what should happen with this language?

**Comment by jess-cook03** [comment]
@lesleyjanenorton @chrismore 
I was thinking that we could do something more conservative and generic like Chris suggested:
"Please wait..."

I like the idea of doing something more playful but I feel there would need to be more time exploration of options around that from content/copy perspective -- that being said given the time frame -- 'Please wait..." could be best option for now?

**Comment by lesleyjanenorton** [comment]
"Please wait..." it shall be!
