### ISSUE TITLE
Server unavailable modal is not displayed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3070]
**VPN version:**

* 2.8.0 (2.202203162042);
* 2.8.0 (2.202203162043);

**Platforms:**

* Windows 10;
* Mac OS;

**Prerequisites:**

* Have an FxA account with subscription for Mozilla VPN;
* Be connected to Austria->Vienna location;

**Steps to reproduce:**

1. Log in with the account from prerequisites;
1. Open the [+Inspector+ ](https://mozilla-mobile.github.io/mozilla-vpn-client/inspector/)and run “force_server_unavailable at vie”;
1. Observe the behavior;

**Expected results:**

* A server unav modal is displayed.

**Actual results:**

* No modal is displayed.

**Notes:**

* The location is marked as disabled in Select location list;
* This is “qa-major” issue because the user is not informed about a server being unavailable;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1941)

**Comment by lesleyjanenorton** [comment]
I can reproduce. The modal opens correctly when triggering by other means so I'm wondering if we ever make it to here: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/79038ac2ef71465dce449bf09837104f7161cab3/src/controller.cpp#L600

**Comment by oskirby** [comment]
So, we made a slight adjustment to the `force_server_unavailable` command somewhat recently. Previously it would emit the `readyToServerUnavailble()` signal directly, but this would lead to all kinds of strange state transition bugs and surprise server errors at other times. So this behavior was revised for 2.8, and this command now just adds the selected location to the blocklist, and the server-unavailable notification should not be triggered until an attempt to connect is made.

The steps to test the server unavailable notification should now be as follows:
1. Open the VPN client, log in with the test account if necessary.
2. With the VPN disconnected, open the inspector and issue the command 'force_server_unavailble at vie`
3. Attempt to connect to Vienna, Austria
4. Observe the behavior

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last 2.8.0 (2.202203181225) build, and the current behavior is the following:

  * have the VPN off;
  * have the location selected Vienna;
  * from the Inspector force the server unavailable behavior for Vienna;
  * turn the VPN on;
  * Server unavailable modal is displayed.

If the user has another location selected, a disabled mark will be displayed in Select Location screen and Vienna location could not be selected.

Owen Kirby Is this the expected behavior? Thank you!

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Valentina Virlics Thank you, this is the correct behavior that we expect from the VPN client.
