### ISSUE TITLE
Menubar icon on non-active display is squashed

### ISSUE THREAD

**Issue by mgaudet** [mozilla-mobile/mozilla-vpn-client#3079]
<img width="85" alt="image" src="https://user-images.githubusercontent.com/2906003/159080760-e45f7ff6-03d9-464b-9725-c46dc8898131.png">

On macos 12.2.1 I have a main display (external monitor) and secondary display (builtin 16" macbook pro display). For some reason, the VPN icon on the non-active display is squashed (see screenshot)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1945)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

I can’t reproduce this on my 2021 M1 Macbook Pro with external display, either on 2.8 production build or with local build.

**Comment by mgaudet** [comment]
2.8 looks good. 

I just realized I was still on 2.3, and so re-installed and issue is fixed.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.9.0 (2.202205201941), while on MacOS Big Sur 11.6. The VPN icon on the non-active display is not squashed (attaching a screenshot).

!Screenshot 2022-05-23 at 11.40.40.png|width=304,height=123!
