### ISSUE TITLE
bump android version code

### ISSUE THREAD

**Issue by bhearsum** [mozilla-mobile/mozilla-vpn-client#310]
I signed the latest Android build and attempted to upgrade from the older Mozilla VPN. This failed with `Downgrade detected: Update version code 1 is older than current 1360`. Can we build with a greater version code from now on, so we can make sure upgrades work? (I was going to send a PR, but it looks like that's not in the repo anywhere.)

**Comment by strseb** [comment]
I've bumped the version to 2.0 with version Code 2000 - that should give us the option to upgrade :)

**Comment by bhearsum** [comment]
> I've bumped the version to 2.0 with version Code 2000 - that should give us the option to upgrade :)

Thank you! Once we have a builid with this version available I will sign it and test it out.
