### ISSUE TITLE
QT6 / Android: Does not render correctly

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3101]
Device: Pixel 6 Pro /Android 12

Does not render correctly :c

![Screenshot_20220321-170733](https://user-images.githubusercontent.com/9611612/159459552-502b9b90-3f20-46ae-9a2b-6824ee96a6ce.png)
![Screenshot_20220322-112339](https://user-images.githubusercontent.com/9611612/159459983-fa555a42-97fd-4401-a255-47ceae9af7be.png)
![Screenshot_20220322-112412](https://user-images.githubusercontent.com/9611612/159460031-5b9a13e2-db41-413a-8a70-515eefbaf015.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1956)

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

We verified this on Google Pixel 4 XL, Android 12 using Mozilla VPN 2.8.0(16484840) and we still observed the following issues:

  * The onboarding background screen is black;
  * The animations are missing from the  screen;
  * Missing VPN logo from Testing Speed screen
  * Specific pictogram is missing from CI screen;

See the attached screen record.

Based on this we are reopening it.

Thank you!

!20220329-131121-720x1520.mp4|width=50%!

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

This is verified as Fixed on Google Pixel 4 XL, Android 12 using Mozilla VPN 2.8.0(16486220).
