### ISSUE TITLE
Run ConnectionInfo speedometer animation only once

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#3125]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-1969)

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on the latest Mozilla VPN 2.8 builds, across platforms. The speedometer animation runs only once in the Connection details screen.

Attaching a video.

!Screen Recording 2022-03-25 at 13.51.41.mov|width=728,height=1102!
