### ISSUE TITLE
[Linux] App exclusions not working

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3168]
**VPN version:**

* 2.8~rc32 (2.8~rc32-focal1);

**Affected devices:**

* Ubuntu 20.04;

**Prerequisites:**

* Have a subscription made for Mozilla VPN;

* Have Mozilla VPN installed;

* Have Mozilla VPN opened and OFF;

**Steps to reproduce:**

1. Go to Settings ~~> Network settings~~ > App permissions;
1. Turn the App permissions feature off;
1. Check the Firefox browser;
1. Turn the VPN ON;
1. In Firefox access the[https://whatismyipaddress.com/](https://whatismyipaddress.com/|smart-link)  ;
1. Observe the displayed ip address and location;

**Expected result:**

* The real IP address is displayed;

**Actual result:**

* The VPN IP address is displayed even if the browser is checked in app permission;

**Additional notes:**

* see the attached screen record;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1990)

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Peter Benvenuto May want to look at design for this. Seems confusing to user.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello Betty Fleming 
I’ll attach the logs here.

[^mozillavpn-2022-3-25_1.txt]

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Owen Kirby logs attached…

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Might be fixed with this: https://mozilla-hub.atlassian.net/browse/VPN-2041 ( https://mozilla-hub.atlassian.net/browse/VPN-2041|smart-link ) .

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

So, the explanation of what’s going on in the logs is that there were no application launch events detected in the time between when the daemon was started and the activation of the VPN. Therefore, as far as the daemon was aware, Firefox was not running.

This can be caused by re-starting the daemon while the user has applications running, in which case we lose track of currently active programs. Normally users shouldn’t experience this unless they are upgrading or installing the client, as the daemon normally starts at boot.

However, I don’t want to close this issue just yet because despite this being an edge case, it is still a poor user experience. Hopefully we can do better in the migration to Control Groups v2 in https://mozilla-hub.atlassian.net/browse/VPN-2041 ( https://mozilla-hub.atlassian.net/browse/VPN-2041|smart-link ).

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

* Linux users are about 3% of our total user base as per Looker
  * A further X% of users use app exclusions
  * A further X% suffer this issue where the daemon is unaware of Firefox (or any other excluded app) running

In the light of that, I’m lowering this priority to Low.

Having said that, I’d be curious to know if this is still happening as it seems as though Owen Kirby believes that https://mozilla-hub.atlassian.net/browse/VPN-2041 ( https://mozilla-hub.atlassian.net/browse/VPN-2041|smart-link ) could have fixed this already. Passing this back to QA.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

We have tried to verify this issue, using Mozilla VPN 2.10.0 (2.10.0~rc16-focal1). The issue is still reproducible using Ubuntu 20.04, although using Ubuntu 22.04 (VM) the issue is not reproducible. Reopening.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We have tried to verify this issue, using Mozilla VPN 2.11.0 (2.11.0~rc4-focal1). The issue is still reproducible using Ubuntu 20.04.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Owen Kirby do you have any theories off the top of your head what this might be, given that cgroupsv2 doesn’t appear to have solved it. Alternatively do you have a S/M/L estimate?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is still reproducing on 2.12.0 (2.12.0~rc20221208211304-focal1) as well, while on Linux Focal - 20.04.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Can't reproduce.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Why have we cancelled this bug? Valentina is still able to reproduce it on focal. Reopening because there is not an explanation for the cancelling state.

Owen Kirby could it be that focal uses cgroup v1 still?

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

This is reproducible on Ubuntu 22.04  using Mozilla VPN 2.14.0 (2.14.0~rc20230313172429-jammy1).

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the latest 2.15.0 (2.15.0~rc20230426182028-kinetic1) builds on multiple Linux versions and the issue is still reproducing.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

This appears to be fixed by PR #6505 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6505 ). I have uplifted it to the release branch and I’ll be doing some testing across the various supported distributions to see if there’s anything it missed.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on a real device with Linux Jammy (22.04), while using Mozilla VPN 2.15.0 (2.15.0~rc20230511001643-jammy1) build.

  * VPN ON - select Firefox/Chrome to be excluded - real location displayed on a check-IP web page ✅ 
  * VPN ON - unselect Firefox/Chrome to be re-included in the protection list - real location is STILL displayed on a check-IP web page ❌  - this issue is also happening on Windows - see Basti’s comment here ( https://mozilla-hub.atlassian.net/browse/VPN-4725?focusedCommentId=680520 );
    * turning the VPN OFF and back ON fixes this side issue and the VPN location is show  on a check-IP web page ✅ 

Naomi Kirby maybe we should move this back In Progress until it is completely fixed, or close it, and track it separately? what do you think it would be better?

Thank you!

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Valentina Virlics I will move the issue back into In Progress and continue to look into the problem. It is worth asking whether the current behaviour is worth blocking the release though.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Naomi Kirby they are discussion about it in the Windows ticket - https://mozilla-hub.atlassian.net/browse/VPN-4725?focusedCommentId=680520 ( https://mozilla-hub.atlassian.net/browse/VPN-4725?focusedCommentId=680520|smart-link ) .

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

A fix for the Linux platform has been merged to main and cherry-picked onto releases/2.15.0 so this should be available for QA to test again as soon as the automated builds are done.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on Linux Jammy, using the RC build - 2.15.0 (2.15.0~rc20230512150507-jammy1);

The app exclusion feature is still not working. 

Currently is not working at all, not only when excluding an app while VPN is ON.

  * VPN OFF - real location listed in Chrome;
  * VPN ON - VPN location listed in Chrome;
  * Check Chrome in the App exclusions - VPN location listed in Chrome;
  * Turn the VPN Off and back On - VPN location still listed in Chrome;

Attaching video;

[^Screencast from 16.05.2023 16_25_36.webm]

[^mozillavpn-2023-5-16.txt]

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Valentina Virlics looking through the most recent set of logs it seems that the VPN daemon was restarted while chrome was running, this means that the daemon wasn’t able to detect an application launch event and therefore cannot apply split tunnelling to the instance of chrome that was already running. It will likely work again if you close and re-open Chrome after updating the VPN client.

I would prefer to file this as a separate issue.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Valentina Virlics I have created https://mozilla-hub.atlassian.net/browse/VPN-4798 ( https://mozilla-hub.atlassian.net/browse/VPN-4798|smart-link ) to try and capture the specific failure mode that you have reported.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Hmm, looking through your most logs, I see an unusual error message in the startup of the Daemon:

[17.05.2023 11:55:03.393] (AppTracker) Debug: AppTracker created.
[17.05.2023 11:55:03.540] (main) Debug: Connecting to DBus...
[17.05.2023 11:55:03.542] (main) Debug: Ready!
[17.05.2023 11:55:03.542] (AppTracker) Debug: User created uid: 127 at: /org/freedesktop/login1/user/_127
[17.05.2023 11:55:03.542] (AppTracker) Debug: Connection to unix:path=/run/user/127/bus
[17.05.2023 11:55:03.543] (AppTracker) Warning: Failed to connect to GTK Launched signalSo it looks like this machine wasn’t able to enumerate the active user sessions, meaning that it can’t track the running applications for app exclusions. This is a new error that I haven’t seen before. This is also quite unusual that a UID of 127 was detected, typically on most Linux desktop environments the usable logins start at UID 1000 and go up from there.

Does this issue occur on just one machine for you, or is it reproduceable across all devices?

Would you be able to share some information about your environment as well? Try opening a terminal and running env and sharing the result with us.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Naomi Kirby we were going to take this out of 2.15, right?

**Comment by Cimbali** [comment]
The output if the `id` command on the machine would be helpful to check whether 127 is a legitimate or erroneous user id. If the reply doesn’t say `uid=127`, then it’s worth looking into which desktop environment this system runs?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Thank you for the reply! Naomi Kirby 

We tracked the Lunar issue here ( https://mozilla-hub.atlassian.net/browse/VPN-5535 ).

We can mark this as verified-fixed.
