### ISSUE TITLE
Account verification code field is incorrectly formatted

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3198]
**VPN version:**

* 2.8.0 (2.202203281617);

**Platforms:**

* iOS;
* Android;

**Prerequisites:**

* Have the VPN app installed and turned OFF;
* Have an old account with subscription for Mozilla VPN;

**Steps to reproduce:**

1. Click “Sign up”
1. Use the account from prerequisites;
1. Go to email and get the FxA authorization code;
1. Enter in the corresponding IAA field;

**Expected results:**

* User can finalize log in.

**Actual results:**

* Code field is restricted to 6 chars, and the authorization code (which is different form the verification code) has 8. User is blocked in this screen; the Verify button is only enabled at 6-chars code length.

**Notes:**

* We had difficulties in triggering this screen/email; seems that FxA team set it to be triggered after 1000 attempts in Staging;
* This is a qa-major issue because user cannot finalize log in, while using an old account.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2000)

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Lesley Norton or Florian Zia can you take a look at this one?

**Comment by bakulf** [comment]
We need to do the following:
- check with FxA if there is a fixed size for these 2 codes and if this fixed size can be obtained via API (I don't like to write the number in the code)
- split `VPNAuthInApp.verificationCodeLength` in 2 separate fields.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on the last 2.8.0 (16486670); build on Android 10.

User can enter 8 chars in the authorization code field.
