### ISSUE TITLE
Polish: UI issues after closing survey banners

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3201]
I will follow up with screen caps but to summarize: On some Android emulators, elements in `ViewMain.qml` do not reposition themselves correctly when survey banners are closed, leaving a strange blank space at the top of the app Window.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2003)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closing since I filed this and can no longer reproduce
