### ISSUE TITLE
VPN doesn't work on SQ2 (arm) processor under win11

### ISSUE THREAD

**Issue by hwine** [mozilla-mobile/mozilla-vpn-client#3220]
My work machine is a new (March 2022) Microsoft Surface Pro X ([tech specs](https://www.microsoft.com/en-us/d/surface-pro-x/8xtmb6c575md?activetab=pivot:techspecstab)) which came with windows 11 preinstalled.

Mozilla VPN software installed without complaint, and the UI runs without problems. However, I can't connect to any exit node.

The connection fails after a bit, and a red banner briefly appears on the UI. Text is something about trouble with backend service, and has a "restore" link underlined. I've not been able to click that link before the banner disappears.

Some minutes later, the notification center displays a message:
<img src="https://user-images.githubusercontent.com/132412/160914052-8e7c76b6-1de5-4f2f-9880-954338dd8202.png" alt="Notification" width="192" height="107">

<details><summary>System Info from log file</summary>

```text
==== SETTINGS ====
deviceKeyVersion -> 2.7.1
devices -> <Sensitive>
gleanEnabled -> true
installationTime -> 2022-03-30T08:11:49.934
languageCode -> 
nativeWindowsDataMigrated -> true
postAuthenticationShown -> true
previousLanguageCode -> en
privateKey -> <Sensitive>
publicKey -> xGaaHhQhwt+yOptn0Rr2fZS8EkYadupW29pQqRwsmww=
recentConnections -> [Seattle, WA, us,Skopje, mk -> Seattle, WA, us,San Jose, CA, us] 
servers -> <Sensitive>
surveys -> [{"id":"mozilla-vpn-desktop-survey-q3","url":"https://survey.alchemer.com/s3/6332395/Mozilla-VPN-Desktop-Survey","trigger_time":1209600,"platforms":["windows","macos","linux"]},{"id":"mozilla-vpn-mobile-survey-q3","url":"https://survey.alchemer.com/s3/6353593/Mozilla-VPN-Mobile-Survey","trigger_time":2419200,"platforms":["ios","android"]}]
systemLanguageCodeMigrated -> true
telemetryPolicyShown -> true
token -> <Sensitive>
==== DEVICE ====
Name -> TABLET-935H4GMO windows 11
ABI -> x86_64-little_endian-llp64
Machine arch -> x86_64
OS -> windows
OS Version -> 11
APP Version -> 2.7.1
Build ID -> 2.202202181956
Device ID -> 53dfc5f9-8e39-406c-886d-2a4dc6721917
SSL Lib:OpenSSL 1.1.1m  14 Dec 2021269488351
```
</details>
(Windows provides x86_64 emulation)

[Full log](https://gist.github.com/hwine/d2eb852baedb24d37e4d74d2b1a4b119)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2009)

**Comment by strseb** [comment]
As of #3473 - We're now blocking the x64 .msi to install on arm64 - I will open up a ticket to generate an arm64 msi. :) 

![image](https://user-images.githubusercontent.com/9611612/167678968-0973ab41-c0d8-4be3-a688-69e575e28d56.png)

**Comment by hwine** [comment]
Please add link to the new ticket here.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Here you go 🙂 -  https://mozilla-hub.atlassian.net/browse/VPN-2199 ( https://mozilla-hub.atlassian.net/browse/VPN-2199|smart-link )
