### ISSUE TITLE
 Tapping in the authorization code field triggers only-numbers keyboard

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3229]
**VPN version:**

* 2.8.0 (16486670);

**Platforms:**

* iOS;
* Android;

**Prerequisites:**

* Have the VPN app installed ;;
* Have an account with subscription for Mozilla VPN using a special “*block.test@...*” email.

**Steps to reproduce:**

1. Click “Sign up”
1. Use the account from prerequisites;
1. Enter the email and pass;
1. Tap the authorization code field;

**Expected results:**

* Keyboard is displayed containing alpha-numeric values;

**Actual results:**

* Keyboard containing only numbers is displayed.

**Notes:**

* User is blocked on this screen as the auth code contains alpha-numeric values;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2012)

**Comment by lesleyjanenorton** [comment]
I think this is desired behavior, no?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on VPN 2.8.0 (16487490) build on Android 10.

The keyboard displayed is alpha-numeric.

We could not check this on iOS, as we do not have the build with this fix.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the latest 2.8 (2.202204011327) while using iOS.

The alpha-numeric keyboard is displayed in the authorization screen.
