### ISSUE TITLE
[Regression] [l10n] Scroll bar in Onboarding screens for different languages 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3231]
**VPN version:**

* 2.8.0 (16486670);

**Platforms:**

* Android;

**Prerequisites:**

* Have the VPN app installed;
* Have the device language set to German;

**Steps to reproduce:**

1. Navigate through Onboarding screens;
1. Observe the layout.

**Expected results:**

* There are no display or layout issues.

**Actual results:**

* There is a scroll bar.

**Notes:**

* This might be a regression caused by this fix: [https://mozilla-hub.atlassian.net/browse/VPN-1753](https://mozilla-hub.atlassian.net/browse/VPN-1753|smart-link)  
* Also, the keyboard covers the email/password fields again, due to the large fonts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2016)
┆Reporter: Valentina Virlics

**Comment by lesleyjanenorton** [comment]
Are we seeing this on iOS as well or just Android?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton We could only reproduce it on Android - Google Pixel IV, probably because the device has smaller display, than the rest.

I am almost 100% sure that it is reproducing on both Android and iOS, but needs to be small display devices and a language that has long strings.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

The scroll is also displayed in Data collection and use screen.

!image-20221028-093237.png|width=358,height=625!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01.mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM.mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Repro’d on iOS using an iPhone SE (1st gen). Most of this looks fine to me, these pages need scroll bars because the contents extends beyond the viewport. The only place it really looks bad on the welcome screen because the “already a subscriber” button is always cut off, and the “sign up” button can become cut off, depending on how much text is in the carousel (attached video below). It seems like we shoud:

  * Remove the spacing on top between the “get help” button and the carousel
  * Make each page of the carousel the height of the tallest page so that the buttons aren’t moving around (like the old “feature tour” carousel attached video below)

Peter Benvenuto thoughts?

!Simulator Screen Recording - iPhone SE (1st generation) - 2022-11-23 at 22.02.01 (69bd6827-e5b9-4f7c-b40c-15353deacf93).mp4|width=640,height=1136!

!Screen Recording 2022-06-06 at 3.49.33 PM (87d805f0-27ea-473e-8d3a-1c8fe3938d80).mov|width=842,height=1672!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closed during bug squashing. Working as expected.
