### ISSUE TITLE
Can't Shift-Tab out of the location list in Select location.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#324]
It looks like, when navigating with keyboard, users can't get out of the list of locations using `Shift + Tab` and navigate to the back button.

The only way to get to the back button is to tab through the whole list of locations (forward) and land on the button when the focus wraps to the start of the window again.

**Comment by lesleyjanenorton** [comment]
@yzen if `Shift + Tab` takes the user out of the list, should `Tab` still take the user to the next list item?

**Comment by yzen** [comment]
> @yzen if `Shift + Tab` takes the user out of the list, should `Tab` still take the user to the next list item?

By "mean next list item" do you mean the previously selected item? If so, ideally yes. We would not want to move the selection back to the beginning of the list.

**Comment by lesleyjanenorton** [comment]
Fixed in #293
