### ISSUE TITLE
Cannot make a debug windows build

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3240]
It looks like our static windows build does not have the sqlite debug lib in it:

LINK : fatal error LNK1104: cannot open file 'C:\MozillaVPNBuild\plugins\sqldrivers\qsqlited.lib'

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2019)
┆author: Marcus Kestler

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Marcus Kestler - I generated a new package that should have the debug versions of all libs aswell- https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.latest.qt/qt-windows ( https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.latest.qt/qt-windows )

**Comment by data-sync-user** [comment]
➤ Marcus Kestler commented:

Sebastian Streich Still getting the same issue.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Marcus Kestler - Sorry, new job did compile the debug-libs but didn’t install them it 🙈 - Just double checked, now they should be there

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Baed on slack discussion, this is not qa actionable:

{quote}This is only a dev facing issue - so i would need a dev to double check that our new qt-bundle can be used to build the client in debug mode.
So no qa needed here{quote}

Marking it with the correct label

CC: Valentina Virlics

**Comment by strseb** [comment]
in QT_OUT should be a ./configure.ps1, that will generate a qt-config for you so qmake looks in the right path :)
