### ISSUE TITLE
Run clang-format on pull requests

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#325]
Filing mostly to document what I've tried on top of the l10n linter, in case someone wants to pick it up.

## clang-format GitHub Action

There's an https://github.com/marketplace/actions/clang-format-lint. I've tried running it, and it has way too many failures (about 4k lines).
https://github.com/flodolo/mozilla-vpn-client/pull/4/checks

## Use external Python wrapper.

I've found a [Python wrapper](https://github.com/Sarcasm/run-clang-format), which I had to modify slightly, because it doesn't seem to run correctly with `./` (`fnmatch` fails).

This seems better, but I still have a diff on a bunch of files
https://github.com/flodolo/mozilla-vpn-client/pull/3/checks

```
/src/logger.h
/src/loghandler.cpp
/src/mozillavpn.cpp
/src/platforms/macos/macosmenubar.cpp
/src/platforms/android/androidutils.cpp
/src/platforms/android/androidstartatbootwatcher.h
/src/platforms/windows/windowspingsendworker.cpp
/src/platforms/windows/windowscryptosettings.cpp
/src/platforms/windows/windowspingsendworker.h
```

## Other

As far as I understand:
- `clang-format` doesn't provide an easy way to check an entire folder (unless you pipe it to `find`).
- `.clang-format-ignore` is not natively supported.

But there might be still easier ways to get the same result without a complex Python script on top.

**Comment by flodolo** [comment]
Interestingly enough, I've just realized that the GH Action uses the same Python wrapper. As a consequence, files in `hacl-star` are not ignored 🤦🏼

**Comment by flodolo** [comment]
> Interestingly enough, I've just realized that the GH Action uses the same Python wrapper. As a consequence, files in `hacl-star` are not ignored 🤦🏼

By changing the paths in `.clang-format-ignore`, I'm down to about 300 lines and 13 files affected, so that might be the way to go.
https://github.com/flodolo/mozilla-vpn-client/pull/4/checks

**Comment by bakulf** [comment]
We also have `scripts/apply-format` and `scripts/git-pre-commit-format` to help with clang-format. I reformatted the whole tree this morning.
