### ISSUE TITLE
Multi-hop collapsible card can only be expanded once

### ISSUE THREAD

**Issue by MattLichtenstein** [mozilla-mobile/mozilla-vpn-client#3267]
Affected versions:

- Mozilla VPN 2.9.0 (2.202204051451);

Tested Platforms:

- iOS

Prerequisites:

- Have Mozilla VPN app installed and opened
- Have a FxA account with an active subscription for Mozilla VPN
- Be signed in

Steps to reproduce:

1. Tap the "Select location" navigation button on the main screen
2. Tap the "Multi-hop" tab
3. Tap the downward facing chevron on the "What is multi-hop VPN?" card (observe the card expand)
4. Tap the upward facing chevron on the "What is multi-hop VPN?" card (observe the card collapse)
5. 3. Tap the downward facing chevron on the "What is multi-hop VPN?" card again

Expected result:

- The "What is multi-hop VPN?" card expands (like in step 3 of the reproduction steps)

Actual result:

- The "What is multi-hop VPN?" card does NOT expand

Notes:

- Workaround is to exit and re-enter the "Select location" navigation controller and then return back to the "Multi-hop" tab where you can once again expand the What is multi-hop VPN?" once

https://user-images.githubusercontent.com/15353801/161845445-f661fa10-4708-4b2e-9305-eb324a03aac5.mp4

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2033)

**Comment by lesleyjanenorton** [comment]
@MattLichtenstein nice catch! @peterbenvenuto in light of the upcoming guides & tutorials work, what do we want to do with this drop-down? Does it make sense to remove it and consolidate this kind of information in the new guides & tutorials view? If it's staying, we should definitely fix this.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on iOS using Mozilla VPN build 2.9.0 (2,202205191743).

The Multi-hop collapsible card works as expected.
