### ISSUE TITLE
Support Linux-Fedora

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3322]
Mozilla VPN is currently only available on Linux Ubuntu (Focal Fossa, Bionic, Groovy) and users are also interested in using it on Fedora since it is a popular Linux distribution.

Last request received March 2022

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2085)
┆author: Joseph Anthony Cuevas

**Comment by gzqx** [comment]
Will move to mozilla-vpn when fedora package is provided
