### ISSUE TITLE
“No one can track you” text on subscription screen is misleading

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#336]
Hello. I apologize if this isn't the normal type of bug, but saying that "no one can track you" with a VPN is very misleading. It only really hides where you're connecting from the network, which prevents ISPs and people on the same Wi-Fi network from knowing where you go online, however, it doesn't stop any other tracking like online tracking pixels, advertisements, etc from doing their thing. I highly recommend changing the wording there. 🙂 

![image](https://user-images.githubusercontent.com/17863082/100761529-032e4200-33c1-11eb-8611-dafa55988570.png)

**Comment by lesleyjanenorton** [comment]
@tduzan @chrismore

**Comment by lesleyjanenorton** [comment]
Great points, thank you for filing.

**Comment by chrismore** [comment]
I would agree. Thanks!

We should use variations of words and copy that exists on our homepage: https://vpn.mozilla.org/

We can get help from Kirby in marketing.

We can also use some of the copy on the onboard slides which is about encryption, servers, no bandwidth restrictions, no online activity logs.

**Comment by chrismore** [comment]
@kiiirby ^^

**Comment by jess-cook03** [comment]
@chrismore @Kiiirby 
Whichever copy we decide on, let me know and I will reflect the changes in the documentation/design specs. Thanks!

**Comment by jess-cook03** [comment]
@chrismore 
@lesleyjanenorton and I have been going back and forth on options for this and here is where we have landed:

<img width="375" alt="321v2" src="https://user-images.githubusercontent.com/54991698/101065840-a454fe00-3563-11eb-9188-2982d62c8f16.png">

**Comment by chrismore** [comment]
We are going to change this to a P0 as this copy came from old copy in Figma. We will be updating this copy to reflect the onboarding screens in the app which have already been vetted.

**Comment by ValentinaPC** [comment]
Verified as fixed on iOS 14.2, using the VPN cross-platform build v.2.0.0 (beta build)
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/101349908-b651dc00-3896-11eb-808c-1cebaa0b863b.png)
