### ISSUE TITLE
MacOS - Profile image in not cropped into circle format

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3366]
!Screen Shot 2022-04-22 at 11.54.45 AM.png|width=351,height=509!

See image ^^ but the profile photo is not cropped into a circle as expected
Running Mac OS - version 2.8 just updated
UI bug cc sent to [~accountid:60482d76ceccdd006a1ce9dd]

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2112)
┆author: Jessica Cook

**Comment by lesleyjanenorton** [comment]
We can fix this while making other 2.9 updates to the Setting menu.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.9.0 (2.202205201941), while on MacOS Big Sur 11.6. 

The profile image is cropped into circle format - attaching a screenshot.

Lesley Norton / Jessica Cook , the profile image is now displayed on the left side of the Settings screen. Is this the desired layout? Thank you. 

!Screenshot 2022-05-23 at 12.12.25.png|width=358,height=545!
