### ISSUE TITLE
Modal dimensions off from the spec

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3378]
The what’s new modal dimensions are a bit skinnier than the spec. The modals should have 16 px margins. 

This is was the modal looks like right now:

!Screen Shot 2022-04-22 at 11.55.59 AM.png|width=360,height=551!

This is what the modal looks like in the [spec](https://www.figma.com/file/SjWR5U9aqEiUnmrkuS74O5/What's-new%3F-(Release-notes)?node-id=825%3A7337):

!Screen Shot 2022-04-22 at 12.04.17 PM.png|width=255,height=295!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2127)
┆author: Peter Benvenuto

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Betty Fleming i think this can be moved to vpn project as a bug?

for engineering

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

makes sense to me…

**Comment by lesleyjanenorton** [comment]
Do we want to stipulate a max-width for these modals to prevent very wide modals on iPad? Or should it fill the available width, minus margins, regardless of screen width?

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Lesley Norton Yes, I think we should stipulate a max width for modals on iPad. I think 360px should be fine!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Peter Benvenuto I think this is now fixed after Matt Lichtenstein 's modal work, no? Should we leave it open?

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Lesley Norton Yep this is fixed, with the caveat of 500 being the max width (for large screen devices) instead of the 360 mentioned in Peters comment. If we want to change that, then we should leave this open or maybe create a new bug.
