### ISSUE TITLE
iOS Authentication hangs if signing in with wrong fxa account when already have a vpn subscription

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#3379]
Steps to reproduce:
* Have a VPN subscription on your apply account
* Open VPN client version 2.8
* Click "already a subscriber" or "sign up"
* Enter username and password (and in my case 2fa) for a firefox account that does not have a subscription

Expected result:
* Redirected to some kind of error or restore

Actual result:
* Stuck on authentication spinning wheel

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2128)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We tried different scenarios to repro this on iOS, and we were not able to. Also we only had 2.9 Mozilla VPN version in TestFlight, and not 2.8, like mentioned in the repro steps.

Might be related or the same like: https://mozilla-hub.atlassian.net/browse/VPN-1714?atlOrigin=eyJpIjoiZjhiZDc4OGQwZDVkNDhjNGJlYjIwMzRlOWUyOTIwNmQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ ( https://mozilla-hub.atlassian.net/browse/VPN-1714?atlOrigin=eyJpIjoiZjhiZDc4OGQwZDVkNDhjNGJlYjIwMzRlOWUyOTIwNmQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ|smart-link )?

Sarah Bird Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

See the latest comments.
