### ISSUE TITLE
ReferenceError:​ isDeleteAccountAuth is not defined

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3388]
A bit of new console complaining when using in-app auth to sign into the app:
`qrc:​/​ui/​authenticationInApp/​ViewAuthenticationSignIn.​qml:​17:​ ReferenceError:​ isDeleteAccountAuth is not defined`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2132)
┆author: Data Sync

**Comment by MattLichtenstein** [comment]
This also prevents the user from being able to:

- Press the back arrow in the menu (`Warning: qrc:/ui/authenticationInApp/ViewAuthenticationSignIn.qml:43: ReferenceError: isDeleteAccountAuth is not defined (ViewAuthenticationSignIn.qml:43)`)
- Press the cancel button at the bottom (`Warning: qrc:/ui/authenticationInApp/ViewAuthenticationSignIn.qml:86: ReferenceError: isDeleteAccountAuth is not defined (ViewAuthenticationSignIn.qml:86)`)

<img width="458" alt="Screen Shot 2022-04-27 at 4 56 41 PM" src="https://user-images.githubusercontent.com/15353801/165629677-737fc1fb-a3bb-4af5-9ee1-871ed118c002.png">
