### ISSUE TITLE
Layout breakage in DNS settings

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3389]
Likely caused by the long lines of text in third radio option. Wrapping the text will probably fix this. Not happening on prod.
<img width="366" alt="Screen Shot 2022-04-26 at 8 35 58 PM" src="https://user-images.githubusercontent.com/22355127/165560640-6479f531-d9ef-41c7-9970-0e3e62e22bff.png">

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2133)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.9.0 (2.202205250346), while on MacOS 11.6. The text displayed for the third radio option is wrapped. 

Attaching screenshot. 

!Screenshot 2022-05-25 at 12.38.42.png|width=357,height=550!
