### ISSUE TITLE
Taskcluster: Create Sub-Build Tasks for balrog&tunnel.dll 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3397]
Here's one of my last [runs of build/win-opt:](https://firefox-ci-tc.services.mozilla.com/tasks/T2J-LGGVQOmQBKRSdo7Wqg/runs/0/logs/public/logs/live.log) 

```
2022-04-28T11:17:24.269Z - Task Created
<--->~3m Fetches (qt,vsstudio)
2022-04-28T11:20:59.317Z - Task  Command Started
<--> Submodules/Language/Qmake - 1 min
2022-04-28T11:22:46.404Z - Start Balrog
<--> ~15 min min download go / mingvw & compile
2022-04-28T11:37:49.599  - Finish Balrog
2022-04-28T11:37:49.615Z - Start Tunnel.dll
<--> ~7 min download go & compile
2022-04-28T11:44:13.447Z - Finish Tunnel.dll
2022-04-28T11:44:16.913Z - start nmake on mozillavpn
<--> ~5 min rust-webext, client compile
2022-04-28T11:48:56.754Z - nmake All done.
<--> Bundle & upload
2022-04-28T11:49:13.063Z - Finished  

Total ~ 32min
```

We're spending on each run, ~20 minutes(!) on balrog&tunnel.dll however this are by far the least changed parts of the project. This is a waste of time and energy. We should pull those 2 tasks out cache them and only build, whenever the folder contents change. Same as we do with qt and openssl.

Todo List: 
-> Add an option in the /script/windows/compile.bat to skip 3rdpard-deps.
-> Add a build task for both balrog /tunnel dll
--> Those should produce a balog.zip / tunnel.zip
--> Use hashindex to make sure taskgraph replaces it with old valid runs
-> Make build-win/opt depend on that and add it to it's fetch list
-> Let the taskcluster/windows buildscript move it into the right place before generating an msi bundle

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2137)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

This needs to be addressed diffrently as we now use cmake
