### ISSUE TITLE
Update the app store images and support page images

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#341]
Since the UI is now uniform across platforms we'll need to update the app store images and the support page images.
![image-1](https://user-images.githubusercontent.com/22355127/100802937-de9d8e80-33ef-11eb-83a4-d1b3f4cd9224.png)

**Comment by chrismore** [comment]
Specs: https://help.apple.com/app-store-connect/#/dev910472ff2

We'll need screenshots for 6.5", 5.5", and 12.9"

Thanks!

**Comment by jess-cook03** [comment]
Mac!!! We need to add as well!

**Comment by chrismore** [comment]
This will block release, but not block code freeze. We will keep iOS like they are today, with just a a new screen of the app. Mac screenshots were created by @lesleyjanenorton for the initial app store review, but @jess-cook03 and Kirby will work on adding value props into those images like iOS.

**Comment by lesleyjanenorton** [comment]
Screenshots have been created and added to the shared VPN drive and are ready to be added to Figma

**Comment by jess-cook03** [comment]
Figma file and assets have all been updated for iOS, mobile + iPad and Mac 👍
https://www.figma.com/file/5EVGcq7i8cMQmG1zKvEnLo/App-Store-Screenshots?node-id=533%3A1513
Exported pngs -- sent over to Chris to be uploaded.

**Comment by chrismore** [comment]
Thanks to @jess-cook03 , I have updated all of the iPhone and iPad screenshot images for iOS. I have not updated Mac yet until Apple gets back to us on the status of that review.

**Comment by lesleyjanenorton** [comment]
Thanks everyone! Closing as fixed.

**Comment by ValentinaPC** [comment]
@chrismore Is there a way for QA to verify this? Thanks!

**Comment by chrismore** [comment]
@ValentinaPC you would have to have access to production app store connect. What about if I just put in a screenshot of the admin area showing all of the images uploaded? I can't upload Mac yet as the UI is frozen until Apple decides to accept or reject.
