### ISSUE TITLE
[taskcluster] Android build failures do not cause the task to fail

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#3413]
Noticed this on latest push to main:
https://firefox-ci-tc.services.mozilla.com/tasks/CoACVcV8TyKmGdriyI8y5w/runs/0/logs/public/logs/chain_of_trust.log

Looks like the `release_artifacts` might have changed? Unsure what's going on here, but will poke around.

/cc @gabrielBusta

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2143)
┆author: Data Sync

**Comment by ahal** [comment]
On the subsequent push, the tasks started passing again. I'm going to leave this open a bit to try and understand what happened here.

**Comment by escapewindow** [comment]
This is bizarre; the chain of trust artifact generation, signing, and upload should happen after all the other artifacts are generated, so we should have all of the artifact shas in the [chain of trust artifact](https://firefoxci.taskcluster-artifacts.net/Dtj2rO61TcOxQmDvUxqT8g/0/public/chain-of-trust.json). But we only have ` certified.log`:

```
{
  "chainOfTrustVersion": 1,
  "artifacts": {
    "public/logs/certified.log": {
      "sha256": "4f915b023a39930990a5b26a8bfbc9a60d30f8cbe3fe98fbf5f247ed9bbe3a52"
    }
  },
```

This is the first time I've seen something like this, so I'm thinking it's an anomaly. Otherwise it may be an issue in the worker daemon.

**Comment by ahal** [comment]
Looks like I spoke too soon and one of the Android signing tasks *did* fail in the subsequent push:
https://firefox-ci-tc.services.mozilla.com/tasks/AwFVaSSFQLyszK0H3dd2jg/runs/0

So appears to be intermittent?

**Comment by escapewindow** [comment]
We're using the exact same AMIs as the other docker-worker pools: https://hg.mozilla.org/ci/ci-configuration/file/d3a8d38297b615d875ba05392032eded89c0dfc6/worker-pools.yml#l2877

My guess now is that [docker-worker](https://github.com/taskcluster/taskcluster/tree/main/workers/docker-worker/) may have a race condition between the [artifact upload](https://github.com/taskcluster/taskcluster/blob/main/workers/docker-worker/src/features/artifacts.js) and [chain of trust artifact generation](https://github.com/taskcluster/taskcluster/blob/main/workers/docker-worker/src/features/chain_of_trust.js), but I have no idea why it would be intermittent and isolated to vpn.

**Comment by escapewindow** [comment]
AHA

from https://firefox-ci-tc.services.mozilla.com/tasks/B6oY2lR8TcetJaFzihJpjA/runs/0/logs/public/logs/live_backing.log

This is a long-standing bug where docker-worker will go green even if it's missing a required artifact to upload.

```
[taskcluster 2022-05-02 13:50:13.979Z] Artifact "public/build/mozillavpn-armeabi-v7a-release.apk" not found at "/builds/worker/artifacts/mozillavpn-armeabi-v7a-release.apk"
```

**Comment by ahal** [comment]
Good find!

So there are two issues here:
1) The Android builds intermittently fail
2) The tasks do not turn red when they do

Not sure how much I can help with the first, but will poke at the second a little.
