### ISSUE TITLE
Update support.mozilla.org content on Mozilla VPN clients

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#342]
Given that we will be soon launching the Mac and Linux clients and an updated iOS client, we'll need to refresh the support content.

Updated content:

https://support.mozilla.org/en-US/kb/how-do-i-choose-my-vpn-serverconnection-ios
Update: UI changed

https://support.mozilla.org/en-US/kb/managing-registered-devices-mozilla-vpn
Update: UI is now on the main screen for iOS and not in settings

https://support.mozilla.org/en-US/kb/how-do-i-update-my-payment-information-mozilla-vpn
Update: Payment information is managed in the Apple App store subscriptions.

https://support.mozilla.org/en-US/kb/will-mozilla-vpn-work-my-computer-or-phone
https://support.mozilla.org/en-US/kb/how-download-mozilla-vpn
Update: about available platforms 

New content:

* downloading/installing on mac
* Connecting/changing servers on Mac
* downloading/intalling on Linux
* Connecting/changing servers on Linux

There are probably other places on SUMO that need updated.

**Comment by chrismore** [comment]
@jonichan ^^

**Comment by chrismore** [comment]
@bakulf we need a video recorded for SUMO to see the Linux install and app use. 

@jess-cook03 we can record a video after we have a signed build uploaded to Apple. Will ping you when ready.

Thanks!

This doesn't block code freeze, but it does block v2.0 release.

**Comment by jonichan** [comment]
I've [queued](https://docs.google.com/spreadsheets/d/1N24V5ZnDFx1dk8LxMOyLCF-Gh3NT4422OIhZ3nlvPRQ/edit#gid=0) up the changes and will make them live on the release date unless it's okay to ship them earlier. 

Rather than create separate articles for downloading or turning on the VPN for Mac, Windows and Linux, I propose combining them into one article called "How to install Mozilla VPN on your Windows 10, Mac or Linux computer". Reason is we might get dinged by the search engines for having duplicate content since the instructions for these platforms are identical.

I've made the updates so that the iOS client looks similar to Windows, Mac and Linux while Android will remain the same.

**Comment by chrismore** [comment]
@bakulf can you describe here how the Linux VPN client will work with Ubuntu PPA? As in steps on what they would have to do. A video of that would be even easier if it would be possible to do before the launch.

**Comment by chrismore** [comment]
@jonichan Here is an update on installing the new v2.0 clients that is targeted for Jan 12th:

* iOS -- exactly the same as today with v1.0
* Mac -- This will be a PKG installer with a simple, next, next, finish installer. Very straightforward. I will send you a link to install it for yourself.
* Linux -- We will link to Ubuntu's PPA page where Linux customers can download and install. We shouldn't need to hand hold these customers as PPA's on Ubuntu are common. 
* Windows / Android -- will remain the same as they will be on the v1.0 codebase a bit longer. 

For the article title, how about "How to install the Mozilla VPN on your computer or mobile device" and then have a section for Windows, Android, Mac, Linux and iOS? 

Do you see an issue for a Jan 12th launch of Mac and Linux? iOS is still a maybe for that date.

**Comment by chrismore** [comment]
@jonichan the Android v2.0 app is ready now too, so we have included it in the scope for the launch next week. the UI of the app looks very much like v1.0, so there isn't a mad rush to upload those docs.

**Comment by chrismore** [comment]
Joni and I met today and we should have staged content by Friday COB for me to review. If all looks good, we'll get the support docs live on Monday the 11th.

**Comment by chrismore** [comment]
Support content published by Joni. thanks!

**Comment by ValentinaPC** [comment]
Verified all support pages and below you can find some minor string issues, as follows:
1) https://support.mozilla.org/en-US/kb/how-do-i-choose-my-vpn-serverconnection-ios 
   - change "select connection" to "select location";
2) https://support.mozilla.org/en-US/kb/managing-registered-devices-mozilla-vpn
   - for iOS, the old way of accessing devices menu (from Settings) was not updated; 
3) https://support.mozilla.org/en-US/kb/how-do-i-update-my-payment-information-mozilla-vpn
   - change "Subscriptions & Payments" to "Subscriptions";

**Comment by angela-lazar** [comment]
Updated the articles mentioned above. Let me know if any further updates need to be made. Thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on the mentioned pages.
![image](https://user-images.githubusercontent.com/15685960/105142263-14fbae00-5b03-11eb-9135-b0987b015b2c.png)


Was not mentioned in the first comment, but this page will also need to be updated, I guess, @chrismore ?
https://support.mozilla.org/en-US/kb/choose-mozilla-vpn-serverconnection-android - the screenshot and the "select connection" part. (how it should look: https://support.mozilla.org/en-US/kb/how-do-i-choose-my-vpn-serverconnection-ios)

Thanks!

**Comment by jess-cook03** [comment]
@bakulf @ValentinaPC @jonichan
Do we still need to have this issue open? Is this resolved?

**Comment by ValentinaPC** [comment]
> Was not mentioned in the first comment, but this page will also need to be updated, I guess, @chrismore ?
> https://support.mozilla.org/en-US/kb/choose-mozilla-vpn-serverconnection-android - the screenshot and the "select connection" part. (how it should look: https://support.mozilla.org/en-US/kb/how-do-i-choose-my-vpn-serverconnection-ios)
> 
> Thanks!

As I've mentioned above, there is still one place where the UI is from the old VPN client, and would be great if we can update this also. Design in the second link. Thanks!

**Comment by jonichan** [comment]
Thanks for flagging this. I've updated the image in the article.

**Comment by ValentinaPC** [comment]
> 
> 
> Thanks for flagging this. I've updated the image in the article.

We should update the text before the image as well. See below screenshot.
![image](https://user-images.githubusercontent.com/15685960/110906693-fc469200-8314-11eb-8403-f9498d65a038.png)

**Comment by jess-cook03** [comment]
@jonichan cc on this to update for March 23rd release

**Comment by ValentinaPC** [comment]
Verified this as fixed.
The https://support.mozilla.org/en-US/kb/choose-mozilla-vpn-serverconnection-android was also updated with the correct strings and screenshots.

As a side note, @jess-cook03, the UI of the first page changed few days ago. Maybe is not so mandatory to change these screenshots with the new ones, at leas not for March 23rd release, but we should change them for the next one.
How it looks now:
![image](https://user-images.githubusercontent.com/15685960/111964657-848b1b00-8afd-11eb-8578-57e04fccb45c.png)
