### ISSUE TITLE
Server unavailable warning icon is obscuring server city name

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3433]
<img width="478" alt="Screen Shot 2022-05-03 at 4 10 43 PM" src="https://user-images.githubusercontent.com/22355127/166568615-c2a09b7a-0655-479d-bd9e-30880d4c5688.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2156)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Accidentally fixed this whilst refactoring for tutorial work.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN:

  * 2.9.0 (2.202206161145), while on MacOS Big Sur; 
  * 2.9.0 (16553790), while on Android  10;
  * 2.9.0 (2.202206152005), while on Windows 11;
  * 2.9.0 (2.9.0~nightly20220615-focal1), while on Ubuntu 20.04;

The server unavailable warning icon is correctly displayed.

We will close this issue after we are able to check it on iOS as well.

Attaching postfix screenshot.

!Screen Shot 2022-06-16 at 16.20.23.png|width=358,height=545!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.9.0 (2.202206201726), while using iOS.

Attaching postfix screenshot.

!223C295D-2731-4442-AF18-21D04AA73F4B.png|width=828,height=1792!
