### ISSUE TITLE
PlayStore: Create QUERY_ALL_PACKAGES permission declaration 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3443]
We do use this. We should file the report soon

{quote}If your app does not require use of the QUERY_ALL_PACKAGES permission, you must remove the permission from your app manifest. For apps that require this permission, you can now submit a declaration form in Play Console.

You'll need to provide:

A description of the core feature in your app that requires this permission

A short video showing the core feature in your app that requires this permission

To prepare for the questions you'll be required to answer, review this [Help Center](https://support.google.com/googleplay/android-developer/answer/9214102) article.

Starting **July 12**, you will not be able to submit new apps or app updates if the declaration is missing. You have until **July 12** to submit the declaration, or remove the permission from your app manifest. Apps that fail to meet the [policy requirements](https://support.google.com/googleplay/android-developer/answer/9888170#package-vis) or do not submit the declaration form may be removed from Google Play starting **July 12**.

Thank you for continuing to partner with us to make Google Play a safe platform for you and your users.

{quote}

I don’t think this will be an issue to get approved as: [https://developer.android.com/training/package-visibility/declaring](https://developer.android.com/training/package-visibility/declaring|smart-link) 

{quote}The following list gives some examples of use cases where the `QUERY_ALL_PACKAGES` permission is appropriate to include:

Accessibility apps

Browsers

Device management apps

Security apps 

Antivirus apps{quote}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2162)
┆author: Sebastian Streich

**Comment by kaialsh705** [comment]
how do fix this please help me?

**Comment by Thanhal-P-A** [comment]
Have you tried any of the solutions mentioned here : https://stackoverflow.com/a/73287593/10657559
