### ISSUE TITLE
Attempting to auth in with expired subscription solution

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3446]
It would be helpful to understand, and have visual documentation for, what happens on each platform when someone tries to authenticate into the app with an expired subscription.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MPPUX-509)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Designs for this issue + content reviewed: https://www.figma.com/file/LOEZbr2eqH4kKDgLSlCpaw/Support-Issues?node-id=127%3A3118 ( https://www.figma.com/file/LOEZbr2eqH4kKDgLSlCpaw/Support-Issues?node-id=127%3A3118|smart-link ) 

CC Lesley Norton Betty Fleming

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Peter Benvenuto can we re-visit to see if this is still needed/applicable?

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Betty Fleming  Lesley Norton  This is done, this can go in 2.9 or 2.10 depending on priority.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Can we rename this appropriately Peter Benvenuto

**Comment by data-sync-user** [comment]
➤ Tony Cinotto commented:

Peter Benvenuto provided feedback and need a little clarity + a note for Chris Rooney
