### ISSUE TITLE
In Settings, tapping label to activate an option does not work

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#3453]
Tap any label text next to a checkbox,radio box, etc. to activate.

It does not work. Instead, one has to tap the UI switch to. It is conventional,  on Android at least, to have the label text trigger the item. This improves accessibity also.

Android 11, build 16493300

Kindly show in the video simply below

https://user-images.githubusercontent.com/76437842/166960509-c3c35cff-304c-4703-b068-7d9006041157.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2171)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Thank you for logging this issue! We are currently in the process of fixing this. You can see timeline here https://mozilla-hub.atlassian.net/browse/VPN-889 ( https://mozilla-hub.atlassian.net/browse/VPN-889|smart-link ) .

We will close this, as it is already tracked.
