### ISSUE TITLE
add glean event if updateNow has been pressed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3455]
This will allow us to get some signal about users updating and succeeding or maybe getting into trouble.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2173)
┆author: Sarah Bird

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Spoke with Lesley Norton .  Notes

1 - There maybe be multiple screens in the app currently that need to be instrumented not just the obvious banner one
2 - We need a proper understanding of how the update screens work and what guardian events they listen to
3 - There is upcoming work to improve the update now banner / modal etc. - lets make sure this instrumentation is synced up with that effort.

**Comment by bakulf** [comment]
Can we add the event when the `update` view is shown, passing if it was a recommendation or a required operation? Would it be good enough?

Maybe we can have an `update` event with an extra key `step`. Where the values could be:
- recommend update emit
- required update emit
- update view shown
- update started
- update completed
- update failed

Thoughts?

**Comment by birdsarah** [comment]
@bakulf what is the question you want to answer with all this extra data?

The question I was trying to answer is: what proportion of users, who pressed "update now", do we *think* got in trouble while updating? I say *think* because this will be inferred by looking for that event and then not seeing any more events from that client id which indicates and uninstall and reinstall. For this question, the event we have is enough.

But I haven't been in all the conversations around update problems, so let me know.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Andrea Marchesini / Sarah Bird , Could you please let us know what the QA needs to do on this one, if anything? Thank you!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

The main test is related to the mac and windows installers. The app must restart correctly on a fresh installation and after an update.

To test the fresh installation, please use the dev-menu and force an app reset (+quit). Then uninstall the app, then proceed with a new installation.

Thanks!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.9.0 (2.202206161924), while using Windows 10/11, and on Mozilla VPN 2.9.0 (2.202206161926), while on MacOS 11.6, as follows:

  * After resetting the app (by using the “Reset and Quit” option), uninstalling and reinstalling it, the Mozilla VPN client is restarting.

Andrea Marchesini , thank you for the explanations. Just wanted to mention that if I open the windows installer while the client is opened, the client closes but does not restart itself. This is not happening on MacOS - even though the client is opened, after finishing the installation the client is restarting. Is this the expected behavior if the “Reset and Quit” action is not performed?

Attaching video for the installation part.

Moving this into “Dev Complete”, until we are able to test this scenario after an update (after Balrog is updated). 

!bandicam 2022-06-17 12-14-39-379.mp4|width=1920,height=1080!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verifed this as fixed on Mozilla VPN 2.9.0 (2.202207151703), while on MacOS, and on Mozilla VPN 2.9.0 (2.202207151712), while on Windows 10/11. 

The client is restarting after updating from a previous VPN version (2.8.3 - MacOS / 2.8.4 - Windows) to 2.9 version.

Attaching a video as well for the update part.

!Screen Recording 2022-07-19 at 13.56.03.mov|width=1118,height=1174!
