### ISSUE TITLE
No ability to paste passwords on the password field on the mobile apps

### ISSUE THREAD

**Issue by ManuelCalidonio** [mozilla-mobile/mozilla-vpn-client#3464]
**Description**

Users' are reporting that it's not possible to paste a copied password from their clipboard or password manager app on the password field when trying to log into Mozilla VPN for mobile.

**Technical Information**

Platform: iOS and Android
FX product: Mozilla VPN
Product version: 2.8.0 for Android & 2.8.1 for iOS
OS version: Android 11 & iPhone 12 OS 15.3.1

**Steps to Reproduce**
1. Log out of the Mozilla VPN app
2. Click Sign-up to log in
3. Enter your email
4. If you use a password manager, try to copy the password from there. If not, type your password somewhere and copy it.
5. Try to paste the copied password on the password field

**Actual Results**

Users are not able to paste their copied password to log in 

**Expected Results**

Users should have the ability to paste their password on the password field since manually typing long passwords with special characters might not be an ideal experience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2177)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Thank you for logging this bug! This is already fixed and will be released with Mozilla VPN 2.9. For other details, here is the tracking ticket: https://mozilla-hub.atlassian.net/browse/VPN-1812 ( https://mozilla-hub.atlassian.net/browse/VPN-1812|smart-link )
