### ISSUE TITLE
Cross-platform error message + alert messaging placement (global change)

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#347]
@lesleyjanenorton @bakulf 

We spoke briefly about the placement of the error and alert messages in our design review... capturing here the suggested UI fixes:

Suggesting that we move the error messages from appearing as a toast anchored to the bottom of screens to the top instead. Cross platform global change.
Also error messages should appear and overlap the content of the screen rather than push content down.... this is different behaviour than the alert messaging, where content is pushed in order to create space for neutral messages.

I've started to outline the differences [here](https://www.figma.com/file/FhYZu3RiEbCNVLQnZ1q1MS/IAP?node-id=225%3A79) and some screenshots below:
![Screen Shot 2020-12-02 at 2 42 36 PM](https://user-images.githubusercontent.com/54991698/100929189-3d790b80-34b5-11eb-90a1-7a49b78c305e.png)
![Screen Shot 2020-12-02 at 3 46 10 PM](https://user-images.githubusercontent.com/54991698/100929593-e0318a00-34b5-11eb-9d0d-890cf277f9da.png)

**Comment by chrismore** [comment]
We will keep this a P2 and part of a UI polish for post v2.0 release. We won't block release for this issue.

**Comment by ValentinaPC** [comment]
Verified this on the latest VPN cross-plat builds while using Android 10, iOS 14.2, Mac OS 10.15.7 and Linux Ubuntu 20.04.
Postfix screenshots below.
![errors](https://user-images.githubusercontent.com/15685960/102222991-d0219d80-3eec-11eb-9c98-9a4b21c2777b.png)
