### ISSUE TITLE
Free-Trial Android: TaskPurchase-data is empty

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3488]
Observation -in: 
src\platforms\android\androidiaphandler.cpp
```
void AndroidIAPHandler::validatePurchase(QJsonObject purchase) {
....

  connect(purchaseTask, &TaskPurchase::succeeded, this,
          [this, token](QByteArray data) {
            logger.debug() << "Products request to guardian completed" << data;

```

We sometime have "data" to be empty, when trying to validate the 12mnth-free trial plan. However when using the inspector we can see that the request done sucsessfully. - This might cause in "failure to confirm subsription" error. 
![image](https://user-images.githubusercontent.com/9611612/167509988-cee39477-a1cd-4af9-a5b0-fd04c3527f15.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2195)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

We can close this.
