### ISSUE TITLE
No status in mozillavpn status?

### ISSUE THREAD

**Issue by peteruithoven** [mozilla-mobile/mozilla-vpn-client#3493]
Seeing the UI currently doesn't work on Linux I wanted to check the status using the commandline tool, but I'm having a hard time understanding whether it's active or not.
There is a lot of useful information, but I don't see a field for the actual status. 

I've replaced some stuff for privacy. 
When not active:
```
$ mozillavpn status
[10.05.2022 14:51:53.742] Info: (main - Command) MozillaVPN 2.8.0
[10.05.2022 14:51:53.742] Info: (main - Command) User-Agent: MozillaVPN/2.8.0 (sys:elementary 6.1)
User status: authenticated
[10.05.2022 14:51:53.779] Info: (networking - NetworkRequest) Imported cert from: ISRG Root X1
User avatar: https://profile.accounts.firefox.com/v1/avatar/p
User displayName: 
User email: {email}
User maxDevices: 5
User subscription needed: false
Active devices: 3
Current devices:{device name}
Device 1
 - name: {device name}
 - creation time: Tue May 10 12:50:26 2022 GMT
 - public key: {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Device 2
 - name: {device name}
 - creation time: Tue Feb 22 08:51:46 2022 GMT
 - public key: {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Device 3
 - name: {device name}
 - creation time: Tue Oct 12 16:47:31 2021 GMT
 - public key: {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Server country code: nl
Server country: Netherlands
Server city: Amsterdam
```

Activating:
```
$ mozillavpn activate
[10.05.2022 14:52:04.036] Info: (main - Command) MozillaVPN 2.8.0
[10.05.2022 14:52:04.037] Info: (main - Command) User-Agent: MozillaVPN/2.8.0 (sys:elementary 6.1)
The VPN tunnel is now active
```

When active:
```
$ mozillavpn status
[10.05.2022 14:52:07.119] Info: (main - Command) MozillaVPN 2.8.0
[10.05.2022 14:52:07.119] Info: (main - Command) User-Agent: MozillaVPN/2.8.0 (sys:elementary 6.1)
User status: authenticated
[10.05.2022 14:52:07.152] Info: (networking - NetworkRequest) Imported cert from: ISRG Root X1
User avatar: https://profile.accounts.firefox.com/v1/avatar/p
User displayName: 
User email: {email}
User maxDevices: 5
User subscription needed: false
Active devices: 3
Current devices:{device name}
Device 1
 - name: {device name}
 - creation time: Tue May 10 12:50:26 2022 GMT
 - public key:  {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Device 2
 - name: {device name}
 - creation time: Tue Feb 22 08:51:46 2022 GMT
 - public key:  {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Device 3
 - name: {device name}
 - creation time: Tue Oct 12 16:47:31 2021 GMT
 - public key:  {public key}
 - ipv4 address: {ip4}
 - ipv6 address: {ip6}
Server country code: nl
Server country: Netherlands
Server city: Amsterdam
```

Note that the ip4 and ip6 where the same on my current device, which make me think it's not actually active.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2197)
┆author: Data Sync

**Comment by bakulf** [comment]
I see at least 3 problems here:

1. you see log entries and this is not good. I filed this for it: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3503

2. @peteruithoven, the client does not work in UI mode. Can you tell me more? What does it happen? If it's a opengl issue, we are working on it.

3. The "status" option shows just the current account status. I agree. We need to show the connection status too. I'll work on this in this github issue.

**Comment by peteruithoven** [comment]
> 1. you see log entries and this is not good. I filed this for it: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3503

Thanks!

> 2. @peteruithoven, the client does not work in UI mode. Can you tell me more? What does it happen? If it's a opengl issue, we are working on it.

Ah yeah sorry, there are open issues for that already: 
- https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3447
- https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3367


> 3. The "status" option shows just the current account status. I agree. We need to show the connection status too. I'll work on this in this github issue.

Thanks!

**Comment by peteruithoven** [comment]
I assume this is fixed with #3519

**Comment by bakulf** [comment]
Correct. And it will be included in 2.9

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Not sure what is the implementation here.

While having the Mozilla VPN app installed, we do not see any status indicator, except a small check mark on the icon from the tray-bar.

Reopening until other details are provided.

**Comment by peteruithoven** [comment]
I opened this issue specifically about the cli (command line interface), so closing it again.
