### ISSUE TITLE
Using the Multi-hop feature causes a "Server unavailable" error message

### ISSUE THREAD

**Issue by ManuelCalidonio** [mozilla-mobile/mozilla-vpn-client#3522]
**Description**

User reporting that they encounter a "Server unavailable" error when using server with the Multi-hop feature. This happens regardless of the server combination they try.

This only happens with the multi-hop feature. If they use the servers that cause the error on single-hop the VPN works as expected. 
 

**Technical Information**

Platform: Linux Ubuntu 20.04
FX product: Mozilla VPN 
Version: The issue started with 2.7.0 but persists on 2.8.0.

*The issue might be specific to Linux Ubunto since their Android app works as expected under the same network. 

**Steps to Reproduce**
1. Open the Mozilla VPN app
2. Click on the Server name
3. Switch to Multi-Hop
4. Select an Entry and Exit location
5. Click back
6. Enable Mozilla VPN

**Actual Results**

The VPN app tries to connect and shows the following messaging: 

"Connecting... Masking connection and location" and then a "Server unavailable" message is shown. 

**Expected Results**

Should connect as expected
![wittIE540Bm70HBt](https://user-images.githubusercontent.com/90466930/168132165-e3942959-d1ae-42f4-bc84-60e72a81bf5a.png)
![lNjl4KO0j8nLc9b4](https://user-images.githubusercontent.com/90466930/168132174-3d315124-513b-4a8a-9f3d-2f2c09838a8d.png)
[Multihop fail Linux (1).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8681308/Multihop.fail.Linux.1.txt)
.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2216)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello Rebecca Billings ,

I have tried reproducing this issue on Mozilla VPN 2.8.0 (2.8.0-focal1) and 2.9.0 (2.9.0~rc0-focal1) using Ubuntu 20.04, but  I could not reproduce it.

Please let me know if anything else is needed.

Thank you!

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

This came from Support, and they confirmed that they can no longer reproduce the issue.
