### ISSUE TITLE
Add privacy notice and terms of service to the bottom of the iOS subscribe screen

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#353]
In issue #188 we discussed how to handle error, but also realized there was something missing from the subscribe screen on the iOS application.

What is missing is the link to the terms of service and privacy notice.

This is a mockup that @jess-cook03 created:

![image](https://user-images.githubusercontent.com/751491/101074683-a79db900-3566-11eb-942a-c583a5645d40.png)

Links should be:

Terms of Service: https://www.mozilla.org/about/legal/terms/mozilla-vpn/
Privacy Notice: https://www.mozilla.org/privacy/mozilla-vpn/

**Comment by chrismore** [comment]
This will block v2.0 release due to legal requirements and this will mimic how our web payments flow functions today with Stripe.

**Comment by jess-cook03** [comment]
Wanting to link work to this new ticket:
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/188#issuecomment-737336909

**Comment by ValentinaPC** [comment]
Verified as fixed on iOS 14.2, using the VPN cross-plat build 2.0.0 (12/04/2020).
Both "Terms of Service" and "Privacy Notice" were added in subscription screen (without the "view" part - I guess intended) and redirect to the mentioned pages.

Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/101357877-b9eb6000-38a2-11eb-80ee-92a2e745dc44.png)
