### ISSUE TITLE
"system language" is misleading 

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#355]
Scenario:
1. my device uses 'French' as default language.
2. I open Mozilla VPN -> settings -> languages
3. I see 'system language': 'English' instead of 'French'.

I would suggest to remove the 'system language' vs 'additional languages' and just show a list of supported languages.

**Comment by lesleyjanenorton** [comment]
+1

**Comment by jess-cook03** [comment]
@lesleyjanenorton @bakulf 
I think this copy change makes sense... considering the functionality. 👍
