### ISSUE TITLE
VPN blank UI after 2.8.3 update

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#3568]
Users are seeing a white screen when opening the VPN after having updated to 2.8 and cannot connect to the client, select a location, or access settings. Some options are accessible by right-clicking the VPN icon in the taskbar such as connecting to the latest location used, 

**Technical Information**
Platform Windows 10/11
FX product Mozilla VPN 2.8.3

**Steps to Reproduce**
1. Have Mozilla VPN 2.7 installed
2. Open VPN client
3. Click on VPN update banner/icon to install latest version

**Actual Results**
-  Once update completes the VPN client reopens and only shows a blank screen

**Expected Results**
- VPN Client interface should display options to connect, select location and access settings

![screenshot 4](https://user-images.githubusercontent.com/72564534/169315553-05550d8b-95a1-4832-8125-281b5916b03c.jpg)

[mozillavpn-2022-5-18_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8730046/mozillavpn-2022-5-18_1.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2250)

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

related to previous bug https://mozilla-hub.atlassian.net/browse/VPN-2106 ( https://mozilla-hub.atlassian.net/browse/VPN-2106|smart-link )

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

atting logs as per Trello card - also DxDiag file

[^DxDiag.txt]
[^mozillavpn-2022-5-24.txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

please find another set of logs and DxDiag file from user attached 

[^DxDiag (1).txt]
[^mozillavpn-2022-5-24_1.txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Attaching another Dxdiag file

[^DxDiag (54ed12aa-7ac7-475b-91d7-4774305105e3).txt]

**Comment by data-sync-user** [comment]
➤ Manuel Calidonio commented:

Attaching Dxdiag

[^DxDiag1.txt]

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

Attaching Dxdiag

[^DxDiag (2).txt]

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Hi all,

Even if we were not able to reproduce the blank screen issue on our Windows 10 machines, we can see for few seconds on both 2.8.4 and 2.9.0 a white screen. Not sure if is the same issue and if this can help you or not.

It happens only at fresh install, and is seen better if user is not signed out and the “start on boot” feature is on.

Attaching logs and video.

!whitescreenfewsecs.gif|width=1225,height=818!

[^mozillavpn-2022-5-25.txt]

**Comment by data-sync-user** [comment]
➤ Manuel Calidonio commented:

[^mozillavpn-2022-5-23 (1).txt]
[^DxDiag (4).txt]

Attaching DxDiags and logs from a user after running the GPU check.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Thanks for the DxDiag logs, it does seem like all of the affected users show a Feature level of 10_1 or below, so I would expect that the 2.8.4 update should resolve the issue for them by falling back to software rendering.

The VPN client logs don’t show anything particularly interesting. Their devices are reporting the same shader errors that we were expecting, so I am left without an explanation as to why the gpucheck did not detect the problem.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Owen Kirby Andrea Marchesini We were able to physically configure a PC at the office, that has both old Windows 10 build (17763) and an old graphic card (Intel HD Graphics 2500).

Because of the https://mozilla-hub.atlassian.net/browse/VPN-2135 ( https://mozilla-hub.atlassian.net/browse/VPN-2135|smart-link ) still reproducing on 2.8.4/2.9 version, we were not able to see if this issue is still reproducible, nor to be able to provide other details.

**Comment by data-sync-user** [comment]
➤ Manuel Calidonio commented:

[^mozillavpn-2022-5-24_1 (1).txt]
[^mozillavpn-2022-5-24_1 (3389113e-e4c7-470d-aafe-86971605db51).txt]
[^DxDiag1 (1) (c4cb56fa-d4e0-4cbe-a7fe-069b16598b95).txt]

DxDiag and Logs after GPU check fail.

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

[^mozillavpn-2022-5-25_1.txt]

another set of VPN logs

**Comment by data-sync-user** [comment]
➤ Gustavo Aguilera commented:

Attaching Dxdiag 

[^DxDiag (68a6a688-9257-4f0e-8050-f3f4177f6a17).txt]

**Comment by data-sync-user** [comment]
➤ Gustavo Aguilera commented:

Attaching DxDiags and logs from a user after running the GPU check.

[^DxDiag.20220526.txt]
[^mozillavpn-2022-5-26.txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

[^DxDiag-4.txt]

**Comment by data-sync-user** [comment]
➤ Gustavo Aguilera commented:

Attaching Dxdiag

[^DxDiag (1) (304b9d1e-c7b4-40c4-9f30-ac3524cfd96b).txt]

**Comment by data-sync-user** [comment]
➤ Gustavo Aguilera commented:

Attaching Dxdiag

[^DxDiag (2) (b5d0932c-1be6-41ce-a271-6eaea3814ef0).txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Andrea Marchesini Owen Kirby Would like for support to keep collecting Dxdiag files and VPN logs for this issue?
