### ISSUE TITLE
[iOS] User cannot subscribe twice for Mozilla VPN on the same device while using 2 different fxa accounts

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#357]
#### Affected versions:
* 2.0.0;

#### Affected Platforms:
* iOS 14.2;

#### Prerequisites:
* Have the VPN app installed;
* Have 2 FxA accounts without active subscriptions for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
1. Tap “Get Started”;
1. Finalize authentication and subscription with first account;
1. Sign out.
1. Tap “Get Started” again;
1. Sign up using the second account;
1. Try to subscribe;

#### Expected result:
* Subscription can be finalized.

#### Actual result:
* Tapping on the “Subscribe now” button returns a “Subscription failed. Try again!” message.

#### Notes:
* User can lose access to its old account and needs to create the subscription, on the same device, for the same product, but with different email.
* from the second account forward, any account used, fails subscription;
![image](https://user-images.githubusercontent.com/15685960/101335467-e93da500-3881-11eb-8735-fcd23b0f3c07.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-392)

**Comment by bakulf** [comment]
This is now fixed.

**Comment by chrismore** [comment]
@bakulf what iOS build should @ValentinaPC verify this fix?

**Comment by ValentinaPC** [comment]
Verified this on iOS 14.2 using the latest VPN beta build (12/8).
Using a second account to subscribe to the same product (VPN), will trigger a notification informing the user that he already has a subscription for that product.
![image](https://user-images.githubusercontent.com/15685960/101502655-defed200-3979-11eb-8d8b-7e1e3c86591e.png)

-Tapping on the "Manage" option we are redirected ..nowhere (but I as understood from Baku, that is something managed by Apple Store and not us)
- Tapping on the "OK" option we receive a "Subscription failed. Try again!" error -> not sure if intended?

**Comment by ValentinaPC** [comment]
Verified this on the last VPN 2.4 version while using iOS 14.4.
After tapping OK in the popup an error screen is displayed informing the user that he already has a subscription for that product.
![image](https://user-images.githubusercontent.com/15685960/126796604-48f0680d-8f57-4211-b086-f18ae77a1d16.png)

This expected behavior **only happens if the same plan is used**. If another plan for the same Mozilla VPN product is used, user can subscribe twice for the same product using 2 different accounts.
@bakulf what do you think?

**Comment by bakulf** [comment]
Yeah, this seems correct. You can change the subscription plan but you cannot subscribe twice with the same plan.

**Comment by data-sync-user** [comment]
➤ Pun Lam commented:

Not an issue. Work as expected subscription flow
