### ISSUE TITLE
[Android] Authentication caught in a loop while using the Mozilla VPN prod build

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#358]
#### Affected versions:
- last Android production build;

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have the VPN app installed;
- Have a production FxA account with subscription;

#### Steps to reproduce:
1. Open the VPN app;
2. Tap “Get Started”;
3. Finalize authentication;
4. Tap the “Return to Mozilla VPN” button;

#### Expected result:
-  User is redirected to Mozilla VPN activation screen.

#### Actual result:
- User is redirected to the VPN “Get Started” screen (in a loop) and an error message is displayed. (Internet connection failed. Try again!)

#### Notes:
- No issues on the beta build.

![image](https://user-images.githubusercontent.com/15685960/101364783-a0024b00-38ab-11eb-89aa-3e97ea4976fa.png)

**Comment by bakulf** [comment]
This is now fixed in the latest 'main' branch and in the last build.

**Comment by ValentinaPC** [comment]
Verified as fixed on the latest VPN production build (12/08/2020) while using Android 10.
User can authenticate with success and activate the VPN.
