### ISSUE TITLE
cmake install doesn't install mozillavpn

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/mozilla-vpn-client#3582]
```
$ sudo cmake --install build
-- Up-to-date: /usr/local/share/applications/MozillaVPN.desktop
-- Up-to-date: /usr/local/etc/xdg/autostart/MozillaVPN-startup.desktop
-- Up-to-date: /usr/local/share/icons/hicolor/16x16/apps/mozillavpn.png
-- Up-to-date: /usr/local/share/icons/hicolor/32x32/apps/mozillavpn.png
-- Up-to-date: /usr/local/share/icons/hicolor/48x48/apps/mozillavpn.png
-- Up-to-date: /usr/local/share/icons/hicolor/64x64/apps/mozillavpn.png
-- Up-to-date: /usr/local/share/icons/hicolor/128x128/apps/mozillavpn.png
-- Up-to-date: /usr/local/share/polkit-1/actions/org.mozilla.vpn.policy
-- Up-to-date: /usr/local/share/dbus-1/system.d/org.mozilla.vpn.conf
-- Up-to-date: /usr/local/share/dbus-1/system-services/org.mozilla.vpn.dbus.service
-- Up-to-date: /usr/lib/systemd/system/mozillavpn.service
-- Up-to-date: /usr/local/lib/mozillavpn/mozillavpnnp
-- Up-to-date: /usr/local/lib/mozilla/native-messaging-hosts/mozillavpn.json
-- Up-to-date: /usr/local/etc/opt/chrome/native-messaging-hosts/mozillavpn.json
-- Up-to-date: /usr/local/etc/chromium/native-messaging-hosts/mozillavpn.json
```

No `/usr/bin/mozillavpn` or so (which `MozillaVPN-startup.desktop` and `MozillaVPN.desktop` reference). Also those should probably use `/usr/local/bin`?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2265)

**Comment by oskirby** [comment]
I actually don't think this is fixed when building from sources. We just used the `GNUInstallDirs` module verbatim and while it works great for building the Debian packages, it leads to a bunch of stuff getting installed to `/usr/local/` when building from sources.

This comes with a couple of bugs:
- config files land in `/usr/local/etc` which isn't picked up by a lot of software.
- the `.desktop` files are hard-coded to expect the VPN executable at `/usr/bin/mozillavpn`
- We have some hardcoded icon paths that should be converted to searching `XDG_DATA_DIRS`
