### ISSUE TITLE
Sign-In: Height of the welcome screen depends on the lottie-animation shown. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3595]
The height of the first page changes depending on which animation is shown. That should be a fixed value or equal for all. 
https://user-images.githubusercontent.com/9611612/169821076-b438c277-d7c5-4cc9-91fc-c8eb9ed4a4ff.mp4

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2273)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closed during bug squashing. Verified by Basti as fixed.
