### ISSUE TITLE
Language list is empty

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3596]
**VPN version:**

* 2.9.0 (.202205201943);

* 2.9.0 (2.202205201941);

* 2.9.0 (2.202205191743);

* 2.9.0 (16529810);

**Affected platforms:**

* All;

**Prerequisites:**

* Have Mozilla VPN installed;

**Steps to reproduce:**

1. Open Mozilla VPN;
1. Click the “Settings” button;
1. Go to “System preferences” -> “Language”;
1. Turn the “Use system language” option off;
1. Observe the list;

**Expected result:**

* All languages that are available are displayed without any issue;

**Actual result:**

* The language list is empty;

**Notes:**

* If you have set before another language in the app, the app will be displayed in that language when the “Use system language” option is off;

* Also, the search text box doesn’t work;

* This is a qa-major issue because an entire feature does not work;

* See the attached screen record;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2274)
┆author: Maria Berlinger

**Comment by oskirby** [comment]
There is a reasonably high chance that this was fixed incidentally by PR #3553
A tweak was made to the `Localizer` class to fix the enumeration of languages.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

This is verified as fixed in the latest Mozilla VPN builds from the main branch (2.9.0 (2.202205231924)) on all platforms. All languages that are available are displayed without any issue.
