### ISSUE TITLE
Connection graph layout breaking on some devices

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#365]
From comment in #269 thread:
<img width="910" alt="Screen Shot 2020-12-08 at 3 41 14 PM" src="https://user-images.githubusercontent.com/22355127/101544760-dc957b80-396b-11eb-98dd-197550f60d59.png">

**Comment by lesleyjanenorton** [comment]
@ValentinaPC is this happening only on Android?

**Comment by ValentinaPC** [comment]
As I mentioned in the initial issue, this was happening only on my Android device.
