### ISSUE TITLE
Add sumo faq explaining the limitations of ip lookup services

### ISSUE THREAD

**Issue by ManuelCalidonio** [mozilla-mobile/mozilla-vpn-client#3677]
The issue below the fold is a common question from users.

We should add a sumo article with something like the following text

Problem: I’ve connected to VPN Spain but when I use a geo lookup service it shows a different country

Text:

There are a large number of geo lookup services (geoPlugin, [IPWHOIS.io](http://IPWHOIS.io), Ipregistry, Weatherbit,  BigDataCloud,  [http://ipgeolocation.io](http://ipgeolocation.io|smart-link) , ….). These services maintain databases of the geographic location of IP addresses and use your IP address to present you with “your location.”

However, this isn’t a perfect system. It is normal for these services to sometimes be wrong and sometimes disagree with each other. [https://www.iplocation.net/ip-lookup](https://www.iplocation.net/ip-lookup|smart-link)  if you press “Details” will show you the output of a number of services.

This isn’t a bug with the VPN service as we cannot control the reporting of third party services. In our experience, errors are usually transitory.

=====

Description

Geolocation data from [IPAPI](https://www.iplocation.net/go/ipapi) (Product: API, real-time) shows Czechoslovakia as the location when checking the IP address of Spain when using the Mozilla VPN app on [https://www.iplocation.net/](https://www.iplocation.net/)

Technical Information

Platform: Windows 10
FX product: Mozilla VPN
Version:  2.8.3

Steps to Reproduce

1. Open the Mozilla VPN app
1. Click on the Server name
1. Select Madrid as location
1. Enable Mozilla VPN
1. Head over [https://www.iplocation.net/](https://www.iplocation.net/)
1. Click on details next the the IP location shown

Actual Results

One of the Geolocation shows Czechoslovakia as the location. 

Expected Results

Madrid should be the location for all results.

![width=200,height=183](https://user-images.githubusercontent.com/90466930/171963372-43f3ea34-c4a2-46f4-a06d-e2294af30368.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2331)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-2331

**Comment by birdsarah** [comment]
Unfortunately we cannot control the quality of third party services in determining geo location.

We have seen this in the past and our experience is these issues are often transitory.

To action this report, we are going to create a troubleshooting article to help explain this to folks.

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

See comments
