### ISSUE TITLE
Error: User tries to link multiple FxA accounts to single Apple ID subscription

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#368]
Feel free to edit this issue title if I did not capture it correctly.

Previously QA had documented this issue via video of when a user may have two FxA accounts tied to one Apple ID subscription... in which they should ideally encounter an error from vpn that tries to inform them of whats going on and help nudge them to resolve the error.

‼️Here is the solution @lesleyjanenorton and I have iterated on so far 👉 [https://www.figma.com/file/FhYZu3RiEbCNVLQnZ1q1MS/IAP?node-id=225%3A79](https://www.figma.com/file/FhYZu3RiEbCNVLQnZ1q1MS/IAP?node-id=225%3A79)
![Screen Shot 2020-12-08 at 5.56.50 PM.png](https://images.zenhubusercontent.com/5fa9aeffe066e101cbf88509/725c231c-bb7c-4828-8d1d-60d098d7e8aa)

@bakulf and @chrismore it would be awesome to get your thoughts and feedback on the copy needed in this moment?

**Note:** this solution would ideally require us to have a support article within sumo that breaks down how to solve this that we then point users to directly... **OR** we could for now have the 'get help' button function the same as our other get help ctas and bring users to the help menu -- where then the user can decide what support they want (contact us or help center).

**_More context into the issue //_**

> iOS --- I install mozillaVPN on my iphone. I authenticate and I subscribe to the service. All good!
Then, I decide to logout and do a new authentication with a new FxA account.
The application detects that the new account is not subscribed. We show the subscription view.
I click on the subscribe button and apple says: you are already subscribed.
At this point I'm stuck there because:
-the mozilla vpn service considers the new FxA account as not subscribed.
-apple says that the user is subscribed because the subscription is per appleID and not per FxA account.
We should inform the user. somehow.

**Comment by bakulf** [comment]
@jess-cook03 thanks! I like A and C. They are simple and powerful.
In B we do not have 'logout' which is an important action for this view.

**Comment by chrismore** [comment]
@jess-cook03 should there be a back or "x" button on that screen? Or should all customers who hit this issue click "get help"?

This is an edge case, but could happen. I will mark this as a P2.

**Comment by jess-cook03** [comment]
@chrismore @bakulf hi folks -- where did we land with this issue? I see its now closed, just checking in.
