### ISSUE TITLE
App freezes when starting the first tutorial if controller state is not StateOn or StateOff

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#3684]
Clicking on the first tutorial while `VPNController.state` is anything other than `StateOff `or `StateOn` will cause the app to get hung up [here](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/ea235cb196b0cc97e3113b462f617e587f3fd8d8/src/controller.cpp#L450), become unhappy, and go into a  🥶❄️ Big Freeze ❄️🥶.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2336)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

To test this, you should see that the VPN is turned off before starting the tutorial

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Marking this verified as fixed, as this was tested here: https://mozilla-hub.atlassian.net/browse/VPN-2452?focusedCommentId=562107 ( https://mozilla-hub.atlassian.net/browse/VPN-2452?focusedCommentId=562107|smart-link )
