### ISSUE TITLE
[foxfooding] Slow scrolling speed on mobile/desktop

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3685]
Probably a Qt issue, but scrolling on both mobile (Android) and desktop (Fedora/GNOME) seems more laggy than in other apps.

I am also seeing slow scrolling speed on Windows 10

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2358)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 5 of https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We’ve verified scrolling inside the app on both desktop (Windows/Linux Lunar) and mobile (Android 13) and there are no more lagging.

Mozilla VPN version used:  2.17.0 (2.202308282314);

Marking this verified as fixed.
