### ISSUE TITLE
[foxfooding] Android Notification for "VPN Switched Servers" not dismissible

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3687]
Android Notification for "VPN Switched Servers" not dismissible. 'Likely not reverting to normal "Using VPN ..." notification needed to keep app running.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2360)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 17 of https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Peter deHaan  Could we get a bit more info here around what exactly is “needed to keep app running” ? That sounds bad. Thanks!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Setting the priority here to Medium for now

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

This is a limitation of the Android OS.  This cannot be addressed.
