### ISSUE TITLE
[foxfooding] The VPN "time online" seems to reset intermittently

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3691]
I noticed that the VPN "time online" seems to reset. It doesn't appear to be on a specific cadence. I will look at one point and it'll say I have been online for ~10 minutes, then look again 15 minutes later to see that this timer has been reset. Haven't turned off the client, PC, etc. Almost appears that the server drops connection than reconnects.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2364)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 23 of https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closing in favor of duplicate issue. Closed during bug squashing #2.
