### ISSUE TITLE
[foxfooding] Mozilla VPN desktop application sometimes stalls or freezes when I lose internet connection while VPN is enabled

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3693]
When I lose internet connection while VPN is enabled, the Mozilla VPN desktop application sometimes stalls or freezes (I have yet to experience a crash though) 

### STR:
1. enable VPN
2. disconnect wi-fi
3. notice application behaviour when trying to reconnect to a server

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2366)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 29 of https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

Valentina Virlics  Bianca Hidecuti  - Can either of you try to reproduce this, please?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Adrienne Davenport, verified this while using Mozilla VPN 2.16.0 (2.202307071121) and 2.15 version, on Windows 11 / macOS 12.6.6, and we are not able to reproduce the freezing state after disconnecting from the internet while the VPN is ON (Wi-Fi connection). 

After disconnecting from the internet, the VPN enters in “No signal” state, but recovers after reconnecting to the internet. 

If switching servers while the internet is disconnected, the VPN enters the “Connecting” state, followed by the server unavailable modal → but in this case the VPN is also not freezing. 

I am attaching a video with the behavior as well.

!bandicam 2023-07-10 10-41-19-184.mp4|width=1176,height=1044!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

See last comment from QA
