### ISSUE TITLE
[foxfooding] Tried to switch servers and it just froze for a while, then I got prompted with the "unavailable server" pop up message (iOS)

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3696]
Tried to switch from Paris to Dusseldorf server and it just froze for a while, then I got prompted with the "unavailable server" pop up message, then there was a ⚠️ next to Dusseldorf in the list. When I got back to the app later it was back to normal and now it's working properly.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2369)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 38 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

This is working as intended. If we can’t connect to any server in a given location, we will eventually give up and mark the location as unavailable. We want to improve this (https://mozilla-hub.atlassian.net/browse/VPN-3027) but essentially what this user seems to have experienced is correct.

I also checked Dusseldorf just in case and it’s working, so maybe it was a momentary lapsus on Mullvad’s end.
