### ISSUE TITLE
[foxfooding] After installing, Mozilla VPN client launched on my secondary monitor on first run instead of my primary monitor (Windows)

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3697]
After installing, Mozilla VPN client launched on my secondary monitor on first run instead of my primary monitor

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2370)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-2370

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 41 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by rvandermeulen** [comment]
As an update to this, it happens every time I launch the client.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

We’re not sure we can solve this at the client level.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

See last comment.
