### ISSUE TITLE
[foxfooding] VPN connection is unstable and the signal is lost using server (Android)

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3698]
connection is unstable and the signal is lost using Vienna server, switched to Brussels and Copenhagen with same issue, had to disconnect the VPN on my mobile

this could be due to weak 4G connection in the office area

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2372)

**Comment by pdehaan** [comment]
Row 45 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Santiago Andrigo leaving this one for you to prioritize

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Sorry for the delay on this Frida Kiriakos . I suspect that this indeed was the result of poor connectivity – are you experiencing this still?

**Comment by data-sync-user** [comment]
➤ Frida Kiriakos commented:

Hello Santiago Andrigo thanks for the follow up, yes I still do sometimes when the connection is poor, but I guess this is expected?
