### ISSUE TITLE
[foxfooding] The repeated "Connected to…" popups are distracting when connected to a not-completely-stable network

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3700]
When connected to a not-completely-stable network, The repeated "Connected to..." popups are a bit weird/misleading. They should either not come up at all, clarify that it's talking about reconnections, and/or also show similar notifications for the preceding disconnects. As is, I'm left confused whether some of my requests have just been sent through directly, and not via the VPN.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2373)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 49 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

cc Peter Benvenuto Perhaps we can look into this as part of the connection messaging refinements in 2.10

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Santiago Andrigo leaving this one for you to prioritize

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Hi Eemeli Aro ! Sorry for the delay on this. To better understand the issue - you are saying that when connected to an unstable network, you get a barrage of “disconnected” and “connected” OS notifications, as we lose connection and attempt to reconnect?

Owen Kirby do you know how we might be able to replicate this? Could it be the result of us cycling through servers in the same location while we are in ‘unstable connection’ mode?

**Comment by data-sync-user** [comment]
➤ Eemeli Aro commented:

I’ve not actually used/needed the VPN for a bit, but at least last summer I was not getting any “disconnected” VPN notifications, just the “connected” ones. As a user, this meant that I could not be sure whether or not some of my traffic was getting sent in the clear, and I was only told about it afterwards.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Owen Kirby Might this be the silent server switching functionality? If so, we can address this when we tackle this spike: https://mozilla-hub.atlassian.net/browse/VPN-3277 ( https://mozilla-hub.atlassian.net/browse/VPN-3277|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics are you able to reproduce this? We think we stopped sending the ‘Connected to..’ notifications on silent server switches, but want to verify. Thank you.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

While the silent-switching is applied the connection banners are not triggered.

When a network is Unstable and the app reconnects - no OS notifications are displayed.
