### ISSUE TITLE
[foxfooding] With VPN on, playback on YouTube app seems to randomly stop - no other signs of dropped connection, VPN stays on

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3709]
With VPN on, playback on YouTube app seems to randomly stop - no other signs of dropped connection, VPN stays on. Attempting to pause/unpause has no effect, but I can recover by dragging back the playback a little bit. Have not experienced this in any capacity before Mozilla VPN usage

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2379)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 33 of https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Santiago Andrigo leaving this one for you to prioritize

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Hi David Shin! Sorry for the delay in getting back to you on this. Are you still experiencing this issue? Does it only happen with iOS or have you seen it with other devices?

**Comment by data-sync-user** [comment]
➤ David Shin commented:

Santiago Andrigo  It did only happen on iOS while on VPN first for few months. However, it started happening without VPN, on other devices as well - I suspect CDN in Canada is having some issues as it fares better if I use US VPN locations.

This can probably close now.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Gotcha, thanks David!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Not reproducible
