### ISSUE TITLE
[foxfooding] Multi-hop seems to periodically revert to single hop

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/mozilla-vpn-client#3710]
Multi-hop seems to periodically revert to single hop. May be UX misinterpretation, haven't reliably reproduced.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2380)

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Row 16 in https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1nnhaCKuosXdIRtimbS6SwMvt-SqMWwTsjLoFnBKugO4/edit#gid=0|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

We’ve had a few comments about confusing UX when switching from Multi to Single hop so I’m inclined to think this falls into that category. Joseph Anthony Cuevas Have any users reported spontaneous changes from Multi to Single hop?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Yes, I suspect it’s UX misinterpretation and Peter Benvenuto and I recently had a thread on the toggle question. I think we can cancel this for now, as it’s acknowledged feedback for the new UI proposal that Peter is working on.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

.
