### ISSUE TITLE
QDnsLookup alternative for Android

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#3743]
For the download speed test we are using the `lookup` method of [QDnsLookup](https://doc.qt.io/qt-6/qdnslookup.html) which is currently not supported on Android and as a fallback we are not using it here. It would be good to find another way to do DNS lookups for Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2401)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Yes, if you can check if the ConnectionInfo works correctly on android

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.9.0 (16564800), while using Android 10.

The CI screen works as expected on Android, and displays the correct IP address and connection details based on the internet connection status.

!Screen Shot 2022-06-29 at 14.15.15.png|width=1787,height=922!
