### ISSUE TITLE
squared vs rounded icons

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#376]
We are currently using rounded icons for iOS and squared icons for macOS:

<img width="838" alt="Screenshot 2020-12-10 at 11 23 32" src="https://user-images.githubusercontent.com/515957/101759659-2a2ff680-3ada-11eb-9d88-c142d0e3d48f.png">

In particular, I don't think the macOS icon is great compared with other Mac apps. See these screenshots:
<img width="198" alt="Screenshot 2020-12-10 at 11 26 14" src="https://user-images.githubusercontent.com/515957/101759954-87c44300-3ada-11eb-88f8-7db6e4010137.png">

<img width="838" alt="Screenshot 2020-12-10 at 11 24 32" src="https://user-images.githubusercontent.com/515957/101759801-59defe80-3ada-11eb-8295-8bb17808619d.png">

**Comment by lesleyjanenorton** [comment]
@jess-cook03 should we increase the border radius of our dock icons on mac to match the app icon on iOS? Apple rounds these corners by default on iOS so even though the image we provide is square, it will have rounded corners on iOS.

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton I agree that rounding the icon for Mac makes more sense. 
It will look more elegant if we align both iOS and OS treatment. 
✅ rounded 👍

**Comment by bakulf** [comment]
@lesleyjanenorton @jess-cook03 if you can provide new icons, we can add them to the next build.
I don't care too much about the 'beta' icons because those are just used internally.

**Comment by lesleyjanenorton** [comment]
Awesome- Will push them up shortly!

**Comment by ValentinaPC** [comment]
Verified this as fixed on Mac OS 10.15.7 and Linux Ubuntu 20.04.
The VPN icons are rounded.
Postfix screenshots below.
![image](https://user-images.githubusercontent.com/15685960/101910393-8c1a5a00-3bc7-11eb-9971-cda1dcee805f.png)
![image](https://user-images.githubusercontent.com/15685960/101910442-976d8580-3bc7-11eb-9e4e-642d4414ccaf.png)
