### ISSUE TITLE
[ci] Support Github pre-releases in .taskcluster.yml

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#3769]
According to @strseb , the release process using Github Releases will involve "prereleases" so QA can validate. I think we'll want signing tasks to run on "prereleases" and "deploy" tasks to run on the actual release. In order to support this, we'll need to modify the `.taskcluster.yml` to take prereleases into account and probably add a custom parameter or similar.

One word of warning, is that Taskcluster Github will assume the same role regardless of release event type. So this means it's not possible to grant different scopes to "prerelease" vs "release" graphs. In otherwords, we'll need to be careful to ensure we don't run tasks that can actually ship things on the "prerelease" graph.

I filed https://github.com/taskcluster/taskcluster/issues/5518 to fix this in Taskcluster, but that likely won't be fixed anytime soon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2416)

**Comment by strseb** [comment]
I think this can be closed, as we have promotion actions in place
