### ISSUE TITLE
VPN fails in Pop_OS!

### ISSUE THREAD

**Issue by grafpoo** [mozilla-mobile/mozilla-vpn-client#3779]
using Pop_OS!, based on ubuntu 22.04 (uses same repositories), i am unable to connect to any VPN endpoint. log attached 

[mozillavpn-2022-6-15.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/8931434/mozillavpn-2022-6-15.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2423)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

We're sorry, we're closing because this is not a supported Linux distribution. Thanks for filing.
