### ISSUE TITLE
[iOS] VPN icon does not dissapear from the status bar after disconnecting the account

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/mozilla-vpn-client#379]
iOS 6s, 14.2
TF build 2.0.0(2.202012100932)

**Steps**
Authenticate with a valid user and complete the subscription steps
Start using the app, turn on the vpn
The subscription expired due to the use of a testing account

**Actual** 
The VPN icon remains in the status bar, until restarting the device. See screenshot
![IMG_9205](https://user-images.githubusercontent.com/1897507/101800613-c32c3500-3b0d-11eb-9cfc-dc41fd70e3a9.PNG)

**Expected**
Once the user is disconnected the VPN icon should not appear

**Comment by bakulf** [comment]
This seems a bug in iOS. This doesn't happen with iPhone 12.
But just to be sure, can you please send us the logs? You can obtain the logs from: get help -> view logs
Thanks!

**Comment by isabelrios** [comment]
I have been trying to reproduce this issue in order to share the logs but I did not see it again. I'm closing the issue but if this has happeened to more people or it is reproducible again, feel free to re-open. Thanks!
