### ISSUE TITLE
Make it easier to select US servers.

### ISSUE THREAD

**Issue by rlr** [mozilla-mobile/mozilla-vpn-client#381]
On the iOS app using an iPhone XS it is super awkward to select USA servers. Being the last country on the list it is all the way at the bottom left and it is super awkward to try to expand. It is also right under the bottom bar thingy (not sure what it's called) that is used to switch apps. See screenshot below:

![IMG_2716](https://user-images.githubusercontent.com/36629/101808009-cd393e00-3ae3-11eb-8aa1-0ddcbd7f7280.PNG)

My instinct is to try to scroll more which ends up opening some other country's server list pushing the US row further down. Not sure what the solution is here. Maybe some bottom padding will work?

**Comment by rlr** [comment]
Also, when I click to expand, it doesn't scroll so it's hard to tell that it even expanded. It would be great if it auto scrolled on expansion.

**Comment by bakulf** [comment]
@lesleyjanenorton any thoughts?

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton 
I have been meaning to file a ticket around this idea of auto scrolling when you select a country ..... right now this is funky.. I agree with the above:

> when I click to expand, it doesn't scroll so it's hard to tell that it even expanded. It would be great if it auto scrolled on expansion.

I think if we can do this -- it would help the ux here a lot.

**Comment by lesleyjanenorton** [comment]
We can definitely make this better! What if we...

1.) Added padding to the bottom of the list so that there isn't that conflict between the Bottom Bar Thingy™
2.) Explore auto-scrolling when a country is clicked and the entire city list isn't visible.

**Comment by ValentinaPC** [comment]
Verified this on Android 10 using the latest VPN 2.0 client.
An extra padding was added after the US region, when collapsed or not.
But, if we are at the end of the list, and tap the "USA" region, the list is not scrolled down, @lesleyjanenorton intended?
![footer padding](https://user-images.githubusercontent.com/15685960/102217466-47ebca00-3ee5-11eb-9654-43efbf103b41.png)
