### ISSUE TITLE
Taskcluster Signed Mac builds failing to run. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3831]
After switching the entitlements in #3785 -
The newly signed mac binaries don't run at all 😅 
Install of the pgk fails - when the binary is extracted manually and run, 
it instantly get's killed: 

```
Date/Time:           2022-06-23 13:56:01.9343 +0200
Launch Time:         2022-06-23 13:56:01.8761 +0200
OS Version:          macOS 12.2.1 (21D62)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Highlighted by Thread:  0

Backtrace not available

No thread state (register information) available

Binary Images:
Binary images description not available

```

However! Codesign say's things are fine? 

```
codesign --verify --deep --verbose Mozilla\ VPN.app 
Mozilla VPN.app: valid on disk
Mozilla VPN.app: satisfies its Designated Requirement

```

i.e looked at this run : https://firefox-ci-tc.services.mozilla.com/tasks/WPJbatBxTBihzJ4VUN_WkQ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2451)

**Comment by hneiva** [comment]
@strseb were you able to confirm this has been resolved?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I confirm we are able to sign macos builds.
