### ISSUE TITLE
Taskcluster Windows builds are busted

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#3847]
From [this treeherder link](https://treeherder.mozilla.org/jobs?repo=mozilla-vpn-client&tochange=ba2dce208a60d0fe9e32774319ad7288d3f93a66&fromchange=9745736730ff48f77939d3f2c61cb8db0258a227), looks like this was regressed by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3801

Here's a link to the failure log:
https://firefoxci.taskcluster-artifacts.net/GPvQr0HNRLaOVMFuwcxH0Q/0/public/logs/live_backing.log

Despite the failed retriggers, the task has been perma-fail since this landed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2455)

**Comment by ahal** [comment]
@bakulf I took a quick look at your patch but nothing obvious jumped out at me. Any idea what might have regressed?

**Comment by oskirby** [comment]
If I had to take a guess, it's probably that `CONFIG += qmltypes` has introduced something in the generated makefiles that doesn't build successfully on taskcluster. Otherwise all the QMake changes look harmless.

**Comment by ahal** [comment]
Yeah, it's a bit difficult to spot, but I think the relevant part of the log is:
```
[task 2022-06-23T12:06:17.371Z]  Build Using nmake
[task 2022-06-23T12:06:17.375Z] 
[task 2022-06-23T12:06:17.375Z] Microsoft (R) Program Maintenance Utility Version 14.30.30709.0
[task 2022-06-23T12:06:17.375Z] Copyright (C) Microsoft Corporation.  All rights reserved.
[task 2022-06-23T12:06:17.375Z] 
[task 2022-06-23T12:06:17.592Z] makefile(25029) : fatal error U1033: syntax error : ':' unexpected
[task 2022-06-23T12:06:17.597Z] Stop.
[task 2022-06-23T12:06:17.599Z] Failed to build the project
[task 2022-06-23T12:06:17.605Z] 
[task 2022-06-23T12:06:17.605Z] Microsoft (R) Program Maintenance Utility Version 14.30.30709.0
[task 2022-06-23T12:06:17.605Z] Copyright (C) Microsoft Corporation.  All rights reserved.
[task 2022-06-23T12:06:17.605Z] 
[task 2022-06-23T12:06:17.822Z] makefile(25029) : fatal error U1033: syntax error : ':' unexpected
[task 2022-06-23T12:06:17.830Z] Stop.
```
