### ISSUE TITLE
[Android] Second tap on “App permissions” option makes the VPN app to crash

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#385]
#### Affected versions:
- last beta build;

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with subscription;

#### Steps to reproduce:
1. Open the VPN app;
2. Tap “Get Started”;
3. Finalize authentication;
4. Go to “Settings”;
5. Tap “App permissions”;
6. Tap the “<-” go back arrow;
7. Tap “App permissions” again.

#### Expected result:
-  The option can be accessed.

#### Actual result:
- The VPN app crashes.

#### Notes:
- Attaching the logs.
[3W4kRcSp.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/5679342/3W4kRcSp.txt)

**Comment by strseb** [comment]
This should be fixed in the new build as #386 was merged :)

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN cross-plat beta build on Android 10.
Tapping on "App permission" option multiple times doesn't trigger any crash.
