### ISSUE TITLE
Slower view transitions on external monitor

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#3905]
Screen recordings TBD.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2497)

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

Unreliably reproducible and the reasons vary.  More information would be needed to be able to address.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled
