### ISSUE TITLE
Create PKG installer for Mac

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#394]
Given that we are switching from a DMG to PKG for installing the Mozilla VPN mac client, we will need to build a PKG file, which should include meta data about the Mozilla VPN.

**Comment by chrismore** [comment]
Details:

https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/PackageMakerUserGuide/Introduction/Introduction.html

**Comment by bhearsum** [comment]
For the record, I will be creating and signing the PKG (we have automation for this). I do not intend to do any of the investigation or planning of customizations. If someone figures that out, I can integrate those changes with our scripts.

**Comment by chrismore** [comment]
@bhearsum understood. I opened up issue #395 for figuring out how to customize the installer and getting those assets.

**Comment by chrismore** [comment]
More insights for this task: https://www.hexnode.com/mobile-device-management/help/how-to-sign-macos-pkg-files-for-deployment-with-hexnode-mdm/

**Comment by chrismore** [comment]
@bhearsum I was looking to see if there is a way to have a PKG installer open up the app after installing. If not, after you install, you have to them go open up the app. Just one less thing to do. I found this: https://stackoverflow.com/questions/35619036/open-app-after-installation-from-pkg-file-in-mac

**Comment by bhearsum** [comment]
> @bhearsum I was looking to see if there is a way to have a PKG installer open up the app after installing. If not, after you install, you have to them go open up the app. Just one less thing to do. I found this: https://stackoverflow.com/questions/35619036/open-app-after-installation-from-pkg-file-in-mac

OK, this looks like something that @baku needs to integrate into his branch. I'm already using whatever scripts he has there as part of packaging.

**Comment by chrismore** [comment]
The new installer is working great. Let's close this as the installer has been sent over to QA to verify. Thanks!
