### ISSUE TITLE
Create assets for Mac PKG installer

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#395]
In issue #394, we will be creating a PKG file for installing the Mac client.

We will need to create a background image, copy, and a manifest file to include all of the details to be used when building and signing the installer.

**Comment by chrismore** [comment]
https://stackoverflow.com/questions/13963465/how-do-i-build-an-os-x-installer-package-with-a-custom-background-with-productbu

**Comment by jess-cook03** [comment]
@chrismore 
Can we get a screen recording of the this? I'll tag @bhearsum here on this as well.
Any visuals we can get as a point of reference? Screenshots would be fine too - so I have context into exactly what we are needing to do here.

Right now its a bit hard for me to wrap my head around exactly what needs to happen from my end.
Thanks in advance!

**Comment by chrismore** [comment]
@jess-cook03 when we have PKG to record, we'll send over over. In the meantime, this is what the standard mac installer looks like: https://en.wikipedia.org/wiki/Installer_(macOS)#/media/File:Installer_Screenshot.png

The installer name, introduction text, and background image likely the only piece we can customize.

**Comment by chrismore** [comment]
The recommended size for the background image is 620×418

**Comment by chrismore** [comment]
For the distribution.XML file:

<title>Mozilla VPN for MacOS</title>

<welcome>You will now be guided through the installations steps for the Mozilla VPN. Thank you for choose a VPN from the trusted pioneer in internet privacy.</welcome>

@jess-cook03 I got started on the two pieces of text that we will need for the installer. We can iterate on the title and welcome text here.

**Comment by bakulf** [comment]
I have a PKG to show: https://drive.google.com/file/d/1bVzvcM6O3wHFOfn9aRCJapttiTZUNmSf/view?usp=sharing

It doesn't work because the package is not signed yet.

What we need so far is:
1. a logo - as you can see the Mozilla VPN log is... too big!
2. a 'welcome' page (html)
3. a 'conclusion' page (html)
4. a few strings - the title, mainly.
5. an error page (if we care) - the first screen. If we want, we can drop that message entirely (I think we can do it).

**Comment by jess-cook03** [comment]
@chrismore 
Looking good.... I would suggest one change which I think might be a typo anyways: 
</welcome> ......"Thank you for **choosing** a VPN from the trusted pioneer in internet privacy."

@bakulf thanks for this! Do we have a specific size for the logo/image? 
What would the error page look like?

Here is what I was thinking for the possible background image -- using one of the illustrations from the marketing website.... this one included a laptop which I felt made the most sense given its for the MacOS installer.... let me know what you think?

Honestly, we can use any of those illustrations.
![moz_vpn_content_well_21x](https://user-images.githubusercontent.com/54991698/102386540-2cdc9100-3f9d-11eb-989b-a97abefc8004.png)

<img width="327" alt="Screen Shot 2020-12-16 at 12 51 22 PM" src="https://user-images.githubusercontent.com/54991698/102386711-6ca37880-3f9d-11eb-8a61-7eaba7fb5908.png">

We could also try to mix the laptop into any of the these illustration environments if we want.

**Comment by jess-cook03** [comment]
![example web_laptop](https://user-images.githubusercontent.com/54991698/102386939-c4da7a80-3f9d-11eb-881e-4f73b9d20b59.png)

**Comment by chrismore** [comment]
@jess-cook03 the specific size for the background logo is 620×418. We can add whatever kind of white space around the logo / illustration to make it look good. We may have to try a few times to see what it looks like when the installer is opened.

**Comment by jess-cook03** [comment]
Okay thanks Chris that makes sense! 

@lesleyjanenorton can you try one of these images? just to see how its looking

**Comment by jess-cook03** [comment]
Also just reference @lesleyjanenorton 
Here is a link to figma file I started some different options at the size @chrismore mentioned:
https://www.figma.com/file/EN0R88zGif4SBj2tvpToJ6/Mac?node-id=1875%3A2934
<img width="639" alt="Screen Shot 2020-12-16 at 1 24 35 PM" src="https://user-images.githubusercontent.com/54991698/102390178-12f17d00-3fa2-11eb-8f16-8f06ee143fe1.png">

**Comment by lesleyjanenorton** [comment]
<img width="500" alt="Screen Shot 2020-12-16 at 12 21 52 PM" src="https://user-images.githubusercontent.com/22355127/102389910-66ab9880-3f99-11eb-9638-27e2c0afe421.png"> With the image from above.  Maybe we toggle opacity/add padding to position? I'm doing some digging into what all is possible with these windows.

**Comment by jess-cook03** [comment]
@lesleyjanenorton 
If I imagine myself being able to scale and drag this down to the bottom left hand corner.... thats what I would try to do! lol

**Comment by jess-cook03** [comment]
Something like this perhaps:
![Test03](https://user-images.githubusercontent.com/54991698/102390752-d3776080-3fa2-11eb-86a6-b2a5207e91df.png)

**Comment by lesleyjanenorton** [comment]
Thank you @jess-cook03! Getting pretty dang close I think...
<img width="623" alt="Screen Shot 2020-12-16 at 12 46 26 PM" src="https://user-images.githubusercontent.com/22355127/102394043-cd7f8080-3f9e-11eb-84d5-fa02a2c40630.png">

**Comment by chrismore** [comment]
> @chrismore
> Looking good.... I would suggest one change which I think might be a typo anyways:
> ......"Thank you for **choosing** a VPN from the trusted pioneer in internet privacy."
> 
> @bakulf thanks for this! Do we have a specific size for the logo/image?
> What would the error page look like?
> 
> Here is what I was thinking for the possible background image -- using one of the illustrations from the marketing website.... this one included a laptop which I felt made the most sense given its for the MacOS installer.... let me know what you think?
> 
> Honestly, we can use any of those illustrations.
> ![moz_vpn_content_well_21x](https://user-images.githubusercontent.com/54991698/102386540-2cdc9100-3f9d-11eb-989b-a97abefc8004.png)
> 
> <img alt="Screen Shot 2020-12-16 at 12 51 22 PM" width="327" src="https://user-images.githubusercontent.com/54991698/102386711-6ca37880-3f9d-11eb-8a61-7eaba7fb5908.png">
> 
> We could also try to mix the laptop into any of the these illustration environments if we want.

Sounds good @jess-cook03 . We will also conclusion text on the final summary screen after it is installed. We can tell them it is finished and to go to their Applications and open up the Mozilla VPN. Actually, I wonder if @bhearsum can create a startup script to open the app automatically after it is finished? Then there is one less step to do after the installer.

**Comment by lolrepeatlol** [comment]
Did you all consider how it would look in dark mode? :)

**Comment by lesleyjanenorton** [comment]
@lolrepeatlol yes but this is still a matter of investigation... on my mac, installer window background images disappear entirely in dark mode. I'm not sure if this is the case for all versions though so definitely worth calling out and verifying.

**Comment by chrismore** [comment]
Maybe something like this for the conclusion?

`<conclusion>The Mozilla VPN is successfully installed. Please go to your applications and open up the VPN to take more control of your online privacy.</conclusion>`

**Comment by chrismore** [comment]
@lesleyjanenorton how about this for a generic error message?

`<error>Well, this is embarrassing. The Mozilla VPN failed to install on your computer. Please reboot and try again.</error>`

**Comment by chrismore** [comment]
@lesleyjanenorton could you post screenshots here of the opening screen, error screen and conclusion here? Thanks!

**Comment by chrismore** [comment]
Sending the installer over to QA to verify. We can close this for now.

**Comment by ValentinaPC** [comment]
> 
> 
> @lolrepeatlol yes but this is still a matter of investigation... on my macs, the installer window background image disappears entirely in dark and auto modes (this is true for other products as well). I'm not sure if this is the case for all macOS versions though so definitely worth calling out and verifying.

This is also happening in Mac OS 10.15.7.
