### ISSUE TITLE
“Loading” strings displayed in "Connection Info" screen instead of the actual IP address

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3963]
**Affected versions:**

* 2.9.0 (2.202207061818)      

**Tested Platforms:**

* Windows 10/11;

**Prerequisites:**

* Have a FxA account with an active subscription for Mozilla VPN;
* Have Mozilla VPN installed but **be signed out;**

**Steps to reproduce:**

1. Open the app and sign in with the account from prerequisites;
1. Turn ON the VPN;
1. Open the CI screen by clicking on the speed icon from the activation screen;
1. Observe the IP address displayed on the CI screen;

**Expected result:**

* The IP address is correctly displayed;

**Actual result:**

* The IP address is not displayed. “Loading” text is displayed instead;

**Notes:**

* This is reproducible every time when accessing the CI screen right after signing in (both Stage and Prod servers);
* The issue is no longer reproducible after switching the server;
* Not reproducing on other platforms;
* On the Mullvad page ([https://mullvad.net/en/check/](https://mullvad.net/en/check/|smart-link) ), the IP address of the server is displayed;
* This is a major issue because the CI screen does not display the IP address and the user might think that his real IP address might be revealed;
* See the attached video and logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2551)
┆Reporter: Bianca Hidecuti

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Something strange happens in the IPFinder task:

[07.07.2022 09:11:23.691] Debug: (networking - NetworkRequest) Network request created by TaskIPFinder
[07.07.2022 09:11:23.724] Debug: (networking - NetworkRequest) Network reply received - status: 0 - expected: 200
[07.07.2022 09:11:23.724] Error: (networking - NetworkRequest) Network error: Host unreachable status code: 0 - body: XXXXXXXX
[07.07.2022 09:11:23.724] Error: (networking - NetworkRequest) Failed to access: https://34.102.244.91/api/v1/vpn/ipinfo
[07.07.2022 09:11:23.724] Error: (networking - TaskIPFinder) IP address request failed QNetworkReply::UnknownNetworkError

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving to Medium as this is aesthetic. Having said that – I could replicate this in v2.9 on Windows. If I re-run the speed test, the problem disappears. What’s also very odd is that in the first run, like shown in the video, there is a mention of IPv4 and IPv6, whereas in a successful run, only one shows.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is also reproducing in the new IP screen, while using the last 2.13.0 (2.202301041559) Mozilla VPN build from release branch, on Windows. Also, I confirm that the ipv6 section is also displayed only in this case.

!image-20230106-115552.png|width=420,height=755!

**Comment by duffontherun** [comment]
I been getting the same error on an Ubuntu install. 

[19.03.2023 17:38:17.647] Error: Network error: Network unreachable status code: 0 - body: XXXXXXXX
[19.03.2023 17:38:17.647] Error: Failed to access: http://[2600:1901:0:38d7::]/success.txt
[19.03.2023 17:38:17.647] Warning: Captive portal request failed: QNetworkReply::UnknownNetworkError

I managed to fix an issue I was having last night with netfilter, but I have no idea about any of this.

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Closing in favor of VPN-2659. Closed during bug squashing #2.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Bringing this back to life since https://mozilla-hub.atlassian.net/browse/VPN-2659 ( https://mozilla-hub.atlassian.net/browse/VPN-2659|smart-link ) was cancelled due to Speed Tests getting cancelled. This bug describes an issue in the CI screen, which needs to be addressed.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.21.0 (2.202402151707), using Windows 10/11 and we are no longed able to reproduce this issue. “Loading” strings are displayed only for a second and opening the CI screen, but it recovers itself - attaching video as well.

Marking this verified as fixed. 

!bandicam 2024-02-20 17-17-29-462.mp4|width=912,height=1076!
