### ISSUE TITLE
[Intermittent] Mozilla VPN enters in “No signal” state after running for a few minutes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#3964]
**Affected versions:**

* 2.9.0 (2.202206301705)

**Tested Platforms:**

* MacOS 11.6;

**Prerequisites:**

* Have a FxA account with an active subscription for Mozilla VPN;
* Have Mozilla VPN installed and opened;
* Be signed in (Production server);

**Steps to reproduce:**

1. Turn ON the VPN;
1. Let the VPN running for a few minutes;
1. Observe the VPN status in the activation screen and try to navigate on the internet.

**Expected result:**

* The screen displays the following text: “Secure and private” and the period of time since the VPN is running. The user is able to navigate on the internet.

**Actual result:**

* A “No Signal” message is displayed on the activation screen. The user is not able to navigate on the internet;

**Notes:**

* This is reproducing intermittently and random;
* After turning the VPN OFF and ON again the user is able to navigate on the internet;
* See the attached logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2552)
┆author: Bianca Hidecuti

**Comment by locustangerine** [comment]
Just installed fresh Firefox and VPN today on Windows 10 machine and have been having this issue/cycling between no signal/unstable/working states.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

I am also unable to reproduce the issue.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Santiago Andrigo Given this is not easily reproducible and hasn’t been experienced by QA in a while, would you agree to lower the priority on it? Or maybe even close it as invalid? I think we need to create a task to create dashboards to help us monitor connection stability on clients, but that is a different task.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

As per Valentina Virlics this happened intermittently for 2-3 days and has since stopped happening completely. Can't be reproduced now. We will be investing in a better metric to measure this at scale.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Back to cancelled
