### ISSUE TITLE
In connection info, back should come before IP information.

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/mozilla-vpn-client#398]
In terms of keyboard focus, there are no issues. The only focusable element inside connection info UI is the back button.

This issue is a screen reader issue, where layout order is different from component order inside `VPNConnectionInfo`. When screen reader user navigates using virtual focus (for example `controls + optinos + ←/→` the order is: ip information then back button then download/upload information. This is confusing because visually back button comes before ip information.

To fix this we just need to move the back button to come before the ip information component inside `VPNConnectionInfo`. This makes the QML order the same as layout order (screen reader respects QML order).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-88)

**Comment by bakulf** [comment]
Closing this issue because the connection info panel is now changed.
