### ISSUE TITLE
Create a Taskcluster parameters file? 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#3999]
So we currently do pass our config: 
i.e "which version of qt are we using" as an env variable to the task, which is fine. 
However chaning the default env's for a task will not cause toolchain tasks to invalidate the old ones.
Also it's a bit hidden if someone wants to update that.

Maybe we should have a .conf file where we can enter those things, and add them as a dependency to the toolchain tasks as needed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2572)

**Comment by data-sync-user** [comment]
➤ Basti commented:

The way we use conda.env files superseed's this efford 😀

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Back to Cancelled

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Back to Cancelled
