### ISSUE TITLE
Write documentation for how to pass-through the Mozilla VPN on specific operating systems

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#400]
For Mac and Linux users with complex software and hardware firewalls to allow the Mozilla VPN to pass-through the firewall, we need to write documentation for SUMO for those technical customers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-90)
┆Reporter: Data Sync

**Comment by chrismore** [comment]
@tduzan any details on what you had to do on your machine would be helpful here.

**Comment by birdsarah** [comment]
test comment.
