### ISSUE TITLE
Wrong edit notification message is displayed in “App Permissions”

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#407]
#### Affected Platforms:
- Android 9.0;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
- Have VPN turned on;
 
#### Steps to reproduce:
1. Reach “App Permissions” page
2. Observe the edit error message under “Protect specific apps” option;
 
#### Expected result:
- Error message displays “VPN must be off to edit app permissions”.
 
#### Actual result:
- Error message displays “VPN must be off to edit network settings”.
![image](https://user-images.githubusercontent.com/15685960/103522609-4ded1f00-4e83-11eb-9212-6b2b239d07f0.png)

**Comment by strseb** [comment]
This is fixed with #397 :)

**Comment by ValentinaPC** [comment]
Verified as fixed on the latest VPN beta build while using Android 10 device.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/103759945-1ca85680-501d-11eb-807f-75b7fa8a78f0.png)
