### ISSUE TITLE
Taskcluster Windows build missing files in `unsigned.zip` artifact

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#4107]
The Taskcluster Windows build upload an `unsigned.zip` artifact which is then repackaged into an msi and released. While working on automated Windows signing, I noticed several files are missing, causing the MSI package task to fail.

Here's the contents of `unsigned.zip` from the latest [2.9.0 release build](https://firefox-ci-tc.services.mozilla.com/tasks/efV7lpSpTk2CyRrCfpek-Q):
```
addons
balrog.dll
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
Microsoft_VC142_CRT_x64.msm
mozillavpn.exe
mozillavpn.json
MozillaVPN.pdb
mozillavpnnp.exe
mullvad-split-tunnel.cat
mullvad-split-tunnel.inf
mullvad-split-tunnel.sys
tunnel.dll
WdfCoinstaller01011.dll
wintun.dll
```

And here are the contents of a [recent task](https://firefox-ci-tc.services.mozilla.com/tasks/TsHQHKnkR-S5BEzdSPllJA) from `main`:
```
logo.ico
Microsoft_CRT_x64.msm
Mozilla VPN.exe
mozillavpn.json
Mozilla VPN.pdb
mozillavpnnp.exe
mullvad-split-tunnel.cat
mullvad-split-tunnel.inf
mullvad-split-tunnel.sys
tunnel.dll
WdfCoinstaller01011.dll
wintun.dll
```

I also noticed that `MozillaVPN.{exe,pdb}` changed to `Mozilla VPN.{exe,pdb}`. If this was intentional we'll also need to update the `wxs` files.

Fixing this blocks both releasing and automated Windows signing so should likely be a high priority in case there's a need for a chemspill.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2633)

**Comment by strseb** [comment]
```
addons
balrog.dll
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
```
Those are fine that they are missing. The .dll's are now static linked. The addons folder will be fetched on the fly from taskcluster. 
I've created #4112 to address the .wxs adjustments :)
