### ISSUE TITLE
Mozilla VPN keeps reconnecting every few minutes after being turned ON for several minutes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4128]
**Affected versions:**

* Mozilla VPN 2.10.0 (2.202208011506);

**Tested Platforms:**

* MacOS;

**Prerequisites:**

* Have Mozilla VPN app installed and opened;

* Have a FxA account with an active subscription for Mozilla VPN;

* Be signed in;

**Steps to reproduce:**

1. Turn ON the VPN;
1. Download some files / navigate on the internet, while the VPN is running (for at least 20-30 minutes - the time may vary);
1. Observe the behavior;

**Expected result:**

* The VPN is running without reconnecting. The timer indicates the minutes since the VPN has been turned ON, without losing the connection;

**Actual result:**

* The VPN is reconnecting every few minutes. The timer is resetting as the connection is lost;

**Notes:**

* This is reproducing intermittently with no clear steps;

* I was able to reproduce this issue while being in a call as well;

* See the attached logs (check the logs at about 16:41 - 16:57 - 17:03 - 17:10 - 17:14);

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2647)
┆author: Bianca Hidecuti

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I don't think we have a proper fix, but can you please test this issue and see if it's less reproducible?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Andrea Marchesini , verified this on Mozilla VPN 2.10.0 (2.202209220101), while using MacOS 11.6 and I was not able to reproduce the reconnecting anymore.

I have also left the VPN running while being in a call / navigating on the internet / downloading files, for a longer period of time, and it did not reconnect. 

Giving the above, marking this verified as fixed.

Will reopen if encountering again.

**Comment by suncoastkid** [comment]
Why was this closed? Still an issue on LInux:
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8905
