### ISSUE TITLE
Active server is hidden in the locations list

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#413]
#### Affected versions:
- last beta build;

#### Affected Platforms:
- Linux Ubuntu 20.04;

#### Prerequisites:
- Have the VPN app installed and turned on;
- Have a FxA account with subscription;

#### Steps to reproduce:
1. Click “Select location” option;
2. Pick a server (i.e Romania-Bucharest);
3. After server switching go back to the locations list
4. Observe selected server;

#### Expected result:
-  The user is scrolled to the selected location,and the location is displayed.

#### Actual result:
- The user is scrolled to the selected location, but the location is hidden.
![image](https://user-images.githubusercontent.com/15685960/103649172-aea15800-4f66-11eb-933b-0fe4d924af57.png)

**Comment by lesleyjanenorton** [comment]
I can reproduce this on Mac - thank you for filing.

**Comment by lesleyjanenorton** [comment]
Fixed via #419

**Comment by ValentinaPC** [comment]
Verified as fixed on all platforms using the last VPN build.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/103998031-5ce61100-51a4-11eb-8bc8-4d08a461dbb2.png)
