### ISSUE TITLE
Android: Can't connect to vpn on <8

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#414]
The updated wireguard library for android uses `Optional<T>` when building the VPN configuration Object. Since it was [introduced in API Level 24 / 7.1](https://developer.android.com/reference/java/util/Optional) so we currently fail on the conf step on lower versions. 

Probably de-shugaring broke?

- https://developer.android.com/studio/write/java8-support

**Comment by bakulf** [comment]
Do we need to update the library? Can we keep the previous version of it?

**Comment by strseb** [comment]
Just checked: Actually its 8.0 ... minimum currently. We also have now usage of `java.time.Instant` which lines out 7.11 aswell. 
This is most certainly a problem with our gradle file. - apparently it should be able to backport all of those things back to API level 20.

**Comment by strseb** [comment]
@ValentinaPC - Is it possible maybe to verify this? 
As in using any android device within Android 5.0-7.1, open the app start a vpn connection.
Currently i've checked with the Android Emulators on (5.0,7.0,7.1) so far.
