### ISSUE TITLE
Whitelist specific system-app applications on Android for split tunneling / per-app feature

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#416]
On Android, there are two types of installed applications. System apps and non-system apps. System apps generally cannot be uninstalled.

The Android VPN client filters out all system apps, because if not the list would be long and would include apps that customers would likely never use. The only system apps that are whitelisted are browsers, which in the case of Android, is Chrome.

While including Chrome is a good first step on the per-app VPN feature (what existed on the v1.0 client), there are a number of other "system apps" that we have heard from customers would be good to include in a whitelist for v2.0.

The System Apps that could be whitelisted are:

- Gmail
- Google Assistant
- Google News
- Google Play Music
- Google Play Movies & TV
- Google Play Store
- Google Location History
- Camera

**Comment by ValentinaPC** [comment]
Verified this on the last VPN beta build, while using Android 10.
@strseb I've checked the new apps added in the App Permissions section, and a few of the ones you mentioned, are missing.
See above list (the ones with star are not listed)
 -  Gmail
-  Google Assistant*
-  Google News*
-  Google Play Music
-  Google Play Movies & TV
-  Google Play Store
-  Google Location History*
-  Camera

Maybe related with the Android version?

**Comment by strseb** [comment]
Yes, these are missing in the allow-list sorry about that.

**Comment by ValentinaPC** [comment]
Verified as fixed on my Android 10 device, while using the last VPN beta build.
Side note: the above marked apps were not installed by default on my device.
All apps all listed in the App Permissions section.

**Comment by strseb** [comment]
![Uploading Screenshot_20210126-161108.png…]()
@jess-cook03 :) current screenshot
