### ISSUE TITLE
Add periodic event controllerStateOn to iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4165]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2663)
┆Reporter: Sarah Bird

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Sarah Bird What’s the diff between this and the `connectivity-stable' event we send any 45 secs?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

The controllerStateOn is sent on desktop and from an android background service every 3 hours as part of metrics to help us measure VPN client usage.

This ticket is about getting this specific event for iOS running on a background process like we do for android.

**Comment by birdsarah** [comment]
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3724/files is the android PR.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Blocking this on https://mozilla-hub.atlassian.net/browse/VPN-3871 ( https://mozilla-hub.atlassian.net/browse/VPN-3871|smart-link ), the two tickets are aiming at providing better tools for analysts to calculate session length and partition the data by session.
