### ISSUE TITLE
Mac app requires re-authentication if used on a multi-profile computer

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#417]
Steps to reproduce:

1) Ensure you have two system profiles on a Mac OS computer
2) Install the Mozilla VPN on either of the profiles
3) Log in to profile A
4) Open the Mozilla VPN
5) Authenticate using FxA
6) Use the VPN
7) Stop the VPN and quit the app (app has to be closed to use it on another profile) 
8) Log out of profile A and log into profile B
9) Open up the Mozilla VPN
10) Authenticate using FxA
11) Use the VPN
12) Stop the VPN and quit the app (app has to be closed to use it on another profile) 
13) Log out of profile B and log into profile A
14) Open up Mozilla VPN

Expected results

* Mozilla VPN is still logged in using the FxA account used previously

Actual results

* You need to re-authenticate using FxA. Any time another profile on the computer uses the Mozilla VPN, you will need to re-authenticate the VPN client. This could be an annoyance for customers who use multiple profiles.

Is this expected behavior? Would this also happen on Linux?

**Comment by lesleyjanenorton** [comment]
Not sure if this is intended behavior or not but I would expect to re-authenticate when switching profiles.

**Comment by ValentinaPC** [comment]
@chrismore We investigated around this issue on both Mac OS and Linux and obtained the following results:
**Mac OS 10.15.7**
- following the above steps, having two system profile with admin rights, and be logged in VPN using  the same account on both profiles, we reproduce the issue.

**Linux Ubuntu 20.04**
We have the following scenarios:
1. After finalizing step 14 and returning to profile A, the user is not required to re-authenticate, but VPN ends up into "No signal" state after few seconds. The sign out-sign in actions fix the problem.
2. If after step 14 and above results, I quit VPN (that now is turned on and active) from profile A and return to profile B, I am required to re-authenticate.

Please let me know if I made myself clear, or if you need any extra details.

**Comment by chrismore** [comment]
@ValentinaPC thank you for the test and scenarios! 

@bakulf is this expected behavior for Mac and Linux or not?

**Comment by bakulf** [comment]
There is a PR. This is fixed but I would like to have it as part of the next releases and not 2.0.1.
