### ISSUE TITLE
Android / Fxa: Change Text on Sign in successful Page 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#418]
It might be Possible that an Android user is Forced to go through the Desktop Sign in flow, if their installed WebView is too Old to work with FxA. In that case they will also see the Prompt "Redirecting you back to the VPN" ... which does not happen. I think should change that text for Android User Agents in something like "Please return to the app" or something similiar :)  or add a mozvpn:// uri button that would also trigger a navigation.

![image](https://user-images.githubusercontent.com/9611612/103671455-37c28a00-4f7b-11eb-9dd1-b0190c836701.png)

**Comment by lesleyjanenorton** [comment]
Refiled [here](https://github.com/mozilla-services/guardian-website/issues/1067)
