### ISSUE TITLE
Consider replacing the server list ListView with Repeater

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#425]
After reading [this](https://doc.qt.io/qt-5/qml-qtquick-repeater.html#considerations-when-using-repeater), I think it might behoove us to replace the ListView item in ViewServers.qml with a "Repeater"... 

Pros: 
- Country items would remember their state when scrolled out of view (if the city list was open when it was scrolled out of view, it would still be open when scrolled back in to view.
- Would resolve #132 
- Would allow for more exact scrolling to current city when opening the view and less logic to find 
- Would prevent the jumping scroll bar which is caused by the city lists collapsing when an open delegate is scrolled out of view.

Cons:
- Possibly a performance ding as all list items would be loaded immediately
- Possibly some semantic accessibility issues

**Comment by bakulf** [comment]
This is done, right?
