### ISSUE TITLE
Inconsistency between button label and its design in Get Help screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4261]
**VPN version:**

* 2.10.0 (2.202208231537)

**Tested Platforms:**

* All;

**Prerequisites:**

* Have the VPN app installed;
* Have a FxA account;

**Steps to reproduce:**

1. Launch VPN app;
1. Go to Settings->Get Help screen;
1. Hover the Close button;
1. Observe tool-tip;

**Expected result:**

* Close button tool-tip should say “Close”.

**Actual result:**

* Close button tool-tip says “Back”.

!image-20220825-094722.png|width=475,height=714!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2742)
┆author: Valentina Virlics

**Comment by flozia** [comment]
Resolved by PR #4070
