### ISSUE TITLE
Switching from landscape to portrait causes UI issues on iPad

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4293]
**Affected versions:**

* 2.10.0 (2.202208282204)

**Tested Platforms:**

* iOS on iPad;

**Prerequisites:**

* Have a FxA account with an active subscription for Mozilla VPN;

**Steps to reproduce:**

1. Open the app and log in with the account from prerequisites;
1. Access Settings -  Tips & Tricks option - Tips;
1. Tap on a quick tip;
1. Rotate the iPad in landscape view;
1. Observe device menu bar options;
1. Go back to Settings and see Sign out button;

**Expected result:**

* 5: Menu bar is displayed in white color.
* 6: Sign out button has no UI or layout issues;

**Actual result:**

* 5: Menu bar is displayed in black color.
* 6: Sign out button is moved to the right.

**Notes:**

* Navigating away from the tips page, the menu color is correct but the Sign out button position remains broken.
* Reproducing in On-boarding screens as well;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2758)
┆author: Valentina Virlics

**Comment by lesleyjanenorton** [comment]
I don't know why this was closed, the PR is still in review. Reopening.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on iOS 15 while using last TestFlight available build 2.10 (2.202209182004) (2673) and it is still reproducing.

Reopening.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton Observed that this fix only addresses the “Sign out” UI part. Confirming that the “Sign out“ button is positioned correct after restoring from landscape mode on iPad iOS 15 while using 2.10 (2.202209192004).

Should we track the other issue separately or how should we proceed? Thank you!

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics lets go ahead and close this as we have another ticket for the menu bar coloring issues.
