### ISSUE TITLE
VPN crashes at location switch if is made during “confirming” state

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#430]
#### Affected versions:
- last beta build;

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have the VPN app installed and turned off;
- Have a FxA account with subscription;

#### Steps to reproduce:
1. Turn off the internet;
2. Turn on the VPN;
3. While VPN is in “confirming” state, change the location;

#### Expected result:
-  The location is changed with success.

#### Actual result:
- The app crashes.

#### Notes:
- we could disable the location switch while VPN is in “confirming” state.

**Comment by bakulf** [comment]
The latest build fixes this crash. Let's close it. @ValentinaPC please verify it. Thanks!

**Comment by ValentinaPC** [comment]
Verified this as fixed on Android 10 and Mac OS 10.15.7 using the last VPN beta build.
The locations are no longer active while the VPN is in the "confirming" state.
