### ISSUE TITLE
Testing web app for l10n is broken

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#4362]
cc @bakulf 
https://mozilla-mobile.github.io/mozilla-vpn-client/

I get redirected to https://mozilla-mobile.github.io/mozilla-vpn-client/?branch=main

With an error about being unable to load that page in a frame, but even opening that in a new window doesn't help
https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/N5dNMR2ST56nAxYcXjrYfQ/artifacts/public/build/index.html

**Comment by flodolo** [comment]
Ah, didn't realize it was a temporary thing. I guess I'm always lucky 🍀

**Comment by bakulf** [comment]
@strseb is there a way to replace the wasm client only when ready? In this way we can reduce the probability of this bug.

**Comment by strseb** [comment]
We should be able to use the taskcluster index for the main branch, that way we can automatic just get the last "good" build :)

**Comment by strseb** [comment]
This should have been done :) - reopen if not
