### ISSUE TITLE
Update Linux PPA metadata for v2.0 release

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#437]
From talking to @bhearsum he needs meta data from @bakulf to be able to release the app.

Let's get that metadata defined here so we can get it updated and back over to Ben.

**Comment by bhearsum** [comment]
@bakulf - this is just the usually .buildinfo, .changes, etc. that I've used in the past.

**Comment by bhearsum** [comment]
This is done.
