### ISSUE TITLE
Validation of the input params when calling wgquickprocess

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#438]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1684623

**Comment by data-sync-user** [comment]
➤ Frida Kiriakos commented:

Hello Andrea Marchesini , I am following up on the Bugzilla issue since it is reopened. As Freddy mentioned in the report, the temporary fix was not enough to completely resolve the issue, is there an update regarding on a more permanent fix? Thanks.
