### ISSUE TITLE
 “Remote service error” banner displayed when accessing the Profile view after upgrading to Bundle

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4469]
**Affected versions:**

* 2.10.0 (2.202209151733);

**Tested Platforms:**

* All;

**Prerequisites:**

* Have Mozilla VPN app installed and opened;

* Have a FxA account with a **web active DAILY** subscription for Mozilla VPN;
* Be signed in;

* Have the system language / app language set to en-US/en-CA;

**Steps to reproduce:**

1. Navigate to Messages screen and open the Bundle upsell message;
1. Click on the “Add Firefox Relay” button;
1. Finalize the upgrade to Bundle;
1. Go back to the client and navigate to Settings - Profile view;
1. Observe the behavior;

**Expected result:**

* The user is redirected to the Profile view. There are no issues;

**Actual result:**

* “Remove service error” banner is displayed. The user is not able to access the Profile view;

**Notes:**

* Reproducing if starting the upgrade from the Profile view as well;

* See the attached ss and logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/PSP-523)
┆author: Bianca Hidecuti

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

FYI that Mullvad is claiming they are experiencing issues that may lead to several disconnections. It might be that that is at play here.
https://mozilla.slack.com/archives/C01PFJ2LLE6/p1663364463543239 ( https://mozilla.slack.com/archives/C01PFJ2LLE6/p1663364463543239|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

[16.09.2022 10:33:36.759] Debug: (networking - NetworkRequest) Network reply received - status: 500 - expected: 200
[16.09.2022 10:33:36.759] Error: (networking - NetworkRequest) Network error: Error transferring https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/api/v1/vpn/subscriptionDetails - server replied: Internal Server Error status code: 500 - body: XXXXXXXXGuardian returns 500. Florian Zia Sarah Bird this seems a guardian issue, right?

**Comment by flozia** [comment]
@bakulf Yes, that’s a Guardian issue. We’ll need to handle the new bundle product id. Opened a PR to add support for the bundle to the `/subscriptionDetails` endpoint: [Add product id for bundle subscriptions #1564](https://github.com/mozilla-services/guardian-website/pull/1564).

**Comment by bakulf** [comment]
@flozia is this bug now fixed?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

The fix is deployed in Guardian v1.26.b11.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Guardian v1.26.b11, while using the latest 2.10 Mozilla VPN build.

“Remote service error” is still displayed when accesing the in-app subscription management view (tried this with an account that only has a Bundle subscription and also an account that upgraded from Mozilla VPN to Bundle).

Reopening this issue. Attaching logs as well. 

[^just bundle.txt]

!Screen Shot 2022-09-23 at 12.02.28.png|width=363,height=655!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Florian Zia and I have talked and it seems that the prod ID for the Bundle should be: +prod_MQ9Zf1cyI81XS2+ ( https://accounts.stage.mozaws.net/subscriptions/products/prod_MQ9Zf1cyI81XS2 )  and not: +prod_LcfR3EzYMVJlZQ+ ( https://accounts.stage.mozaws.net/subscriptions/products/prod_LcfR3EzYMVJlZQ?plan=price_1KvQ6uKb9q6OnNsLDcZcC1L6 ) - while using this one, the error is still displayed.

If using the following link for subscribing to Bundle: https://accounts.stage.mozaws.net/subscriptions/products/prod_MQ9Zf1cyI81XS2 ( https://accounts.stage.mozaws.net/subscriptions/products/prod_MQ9Zf1cyI81XS2 ) and then logging into Mozilla VPN and accesing the in-app subscription management view, the error message is no longer displayed and the user is redirected to the Profile view.

Marking this verified as fixed. Attaching postfix ss (for the new prod ID).

!Screen Shot 2022-09-23 at 13.12.39.png|width=363,height=654!

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Andrea Marchesini Yes! The fix landed with https://github.com/mozilla-services/guardian-website/pull/1564 ( https://github.com/mozilla-services/guardian-website/pull/1564|smart-link ) and the issue was confirmed to be solved.
