### ISSUE TITLE
When VPN turned On, device loses internet connection on iOS 16

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#4472]
After updating to iOS 16, users connecting to VPN get a "No signal" message and device loses internet connection. Changing server location, reinstalling, port53, and resetting device network settings do not help. Internet connection is restored after VPN is turned Off.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Very annoying
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Core functionality. 

**Technical Information**
Platform iOS 16
FX product Mozilla VPN 2.9
Region/Languages
Network type (Mobile/Wifi/Wired): Both

**Steps to Reproduce**

1. Purchase a subscription
1. Install VPN
1. Complete setup
1. Connect to server location

**Actual Results**
After VPN connects, "No Signal" message appears and user cannot browse the web or use any apps that requires internet

**Expected Results**
VPN should show "VPN is On, secure and private" and the device continues to have internet access

[MozillaVPN-logs-14.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9587032/MozillaVPN-logs-14.txt)

![width=200,height=183](https://user-images.githubusercontent.com/72564534/190725697-2d962a4b-df2c-406c-a754-1957592117b5.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2905)

**Comment by mdsfau** [comment]
Seeing the same exact issue. Totally broken on iOS 16.

**Comment by Austionian** [comment]
I'm also seeing this issue.

**Comment by mthomasuk** [comment]
me too

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Joseph Anthony Cuevas is reporting that this is a growing problem with iOS 16, and that it’s beginning to show up even in App Store ratings.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

I have been experiencing exactly the same symptoms with exactly the same steps to reproduce on my iPad for a very long time…..like at least 9 months.

The most recent time I complained about it. Either @basti ( https://mozilla.slack.com/team/UH1BMST47 ) or @Owen ( https://mozilla.slack.com/team/U01URNTE598 ) identified that maybe we're not matching ipv4 vs ipv6 properly.

The challenge is that it was hard to reproduce. The other challenge is that my ipad just died and I got rid of it and I have not been experiencing the same on my iphone.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

I just looked at the logs attached to the ticket and my logs had exactly the same “Failed to receive packet: address family not supported by protocol family”

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

I just upgraded from iOS 14.7.1 to iOS 16.0 and I am able to reproduce this issue on Mozilla VPN 2.10.0 (2.202209212004).

The VPN enters in “No signal” state as soon as the app is turned ON and the user is not able to navigate on the internet.

After turning the VPN OFF, the internet is working again.

Attaching a video and logs as well.

!original-5C398CFD-9646-445F-952E-AD75F2A89BB6.mp4|width=444,height=960!

[^no signal.txt]

**Comment by qualitaetsdefensive** [comment]
This may just be an additional front-end issue but on my side it doesn't even show "No Signal" it shows me that I succefully connected and the running timer while there is no actual (internet) connection. Only when I use the build-in testing tool it recognises that there is no actual signal and shows the "No Signal" message.

2.9.0 (2.202207210518) on iOS 16.0 (20A362)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

It seems that the problem is due to an outdated gobridge component on iOS that has been neglected for a while and needs to get updated to the latest and greatest code to support iOS 16.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.10.0 (2.202210022004), while using iOS 16.0.2 and I am still able to reproduce the “No signal” state. The internet is working only after turning the VPN OFF.

Attaching video and logs as well.

[^MozillaVPN-logs no signal 13-31.txt]

!no signal 13-31.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

issue is also happening on iOS 15.6

[^VPN Logs.txt]

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Former mozillian Nils (drno) reported that they’re experiencing this issue as well on iOS 16 running VPN 2.9.0. Just in case this adds any helpful information Owen Kirby , I wanted to share Nils' experience:

{quote}Basically it connects to an outlet. And then their is no networking connectivity. Initially I had to manually run the build in speed test to make it realize. Recently it changed to: it connect, I wait for 5 seconds, and then it will say "No Signal".

Initially I thought it wasn't working for any US based VPN exit nodes. But by now I think it is more random.

And the same WiFi without the VPN works perfectly fine. So it's not a network issue on my local end.

And the Mozilla VPN used to work fine up till a couple of weeks ago.{quote}

Owen, happy to help provide any additional info - or if you’d like to chat with Nils directly, you can find them as drno in chat.mozilla.org ( http://chat.mozilla.org ) 🙂

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.10.0 (2.202210052004), while using iOS 16.0.2, and I am no longer able to reproduce the “No Signal” state, after turning the VPN ON. The internet is also working while the VPN is ON.

Marking this verified as fixed.

Attaching postfix video as well.

!original-C0E363A8-661F-4853-9A92-2EFF1CD100FB.mp4|width=444,height=960!

**Comment by dscience7** [comment]
This is not fixed. I am running ios 16.0.2 with the latest version from the app. There is still no internet connection when the vpn is turned on. 
iPhone 13 Pro

**Comment by ddavini** [comment]
I’m happy it’s fixed in 2.10 but on the App Store is still 2.9. When is 2.10 going to be released?
