### ISSUE TITLE
MozillaVPN object for unit tests

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#4475]
For more comprehensive unit tests we need access to the _actual_ MozillaVPN object.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2906)

**Comment by bakulf** [comment]
MozillaVPN is already too "polluted". I want to suggest a different approach: let's take out from MozillaVPN what we need and move it into separate testable classes/objects.

If you have any particular issue with this approach, let me know. In the meantime, I close the issue.
if you disagree, please reopen it. Thanks!
