### ISSUE TITLE
The connection time should start from the final connection (after the confirming)

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#452]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-93)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

The code that handles the connection state has long since been refactored, and we should enter the connected state only after the wireguard handshake has been completed. Therefore I believe that this is now Done.
