### ISSUE TITLE
Doesn’t compile with Qt ≥ 6.4

### ISSUE THREAD

**Issue by andersk** [mozilla-mobile/mozilla-vpn-client#4537]
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/553364a81070f0182c1018b1fa47fdcf7c56f2bb/src/connectionbenchmark/benchmarktaskdownload.cpp#L50-L52

(They did not: see [QTBUG-56143 Implement QDnsLookup for Android](https://bugreports.qt.io/browse/QTBUG-56143). The bug tracker lets you add yourself as a watcher if you’d like a notification when it’s fixed.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2951)

**Comment by bakulf** [comment]
Yes, we added that to revisit the QDnsLookup::lookup for android with 6.4.
https://wiki.qt.io/Qt_6.4_Release - we need to start supporting 6.4.
