### ISSUE TITLE
Pop!_OS - Aborted (core dumped)

### ISSUE THREAD

**Issue by JoeDotPHP** [mozilla-mobile/mozilla-vpn-client#4549]
I use Pop!_OS and successfully installed everything.  The app icon showed up, and nothing went wrong during installation.  But when opening or running in the terminal, the title of this is what I get as a result.  I know it says Ubuntu only, but with Pop being downstream - would it not also work?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2961)

**Comment by JoeDotPHP** [comment]
Solved.

**Comment by miguelmota** [comment]
Seeing the same `Aborted (core dumped)` error on arch linux after installing with yay and not sure how to fix it..
