### ISSUE TITLE
[a11y] [Linux] “Mozilla VPN” app name from traybar is not correctly read by default Screen Reader tool

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4551]
**Mozilla VPN affected versions:**

* 2.10.0~rc54-focal1;

**Platform tested:**

* Linux Ubuntu 20.04;

**Prerequisites:**

* Be logged in with an account with subscription for Mozilla VPN;
* Have the default Screen Reader or other voice over tool enabled;

**Steps to reproduce:**

1. Open the VPN app; 
1. Go to tray bar and click/hover on the Mozilla VPN icon;
1. Listen the Screen Reader;

**Expected results:**

* “Mozilla VPN” or something similar can be heard;

**Actual results:**

* No app name is heard;

**Notes:**

* Not reproducing on Windows or MacOS

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2963)
┆Reporter: Valentina Virlics

**Comment by bakulf** [comment]
Is it different with other icons/apps in the sysytray bar?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Partially, as for the rest of the options, the name of the app is also heard, at the end.

Listen below video for clarification.

!Screencast 2022-10-06 08_40_58.mp4|thumbnail!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is an OS specific behavior, as it happens for all of the apps that are displayed in the systray menu.

We can close it.
