### ISSUE TITLE
Mozilla VPN client crash on launch - SIGSEGV

### ISSUE THREAD

**Issue by piojpub** [mozilla-mobile/mozilla-vpn-client#4564]
The Mozilla VPN client crashes on launch.
It was installed without problems via pacman from chaotic-aur repo.

System:
  Kernel: 5.19.12-zen1-1-zen arch: x86_64 bits: 64
  Desktop: GNOME/Wayland v: 42.5 tk: GTK v: 3.24.34 wm: gnome-shell dm: GDM v: 42.0 
  QMake version 3.1 Using Qt version 5.15.6 in /usr/lib 
 Distro: Garuda Linux  base: Arch Linux
Init: 
 systemd  v: 251 default: graphical tool: systemctl 
Compilers: gcc: 12.2.0 clang: 14.0.6 
  pm: pacman pkgs: 1695 libs: 403 tools: gnome-software,pamac,paru

Logs:

```
─λ mozillavpn
QML debugging is enabled. Only use this in a safe environment.
fish: Job 1, 'mozillavpn' terminated by signal SIGSEGV (Address boundary error)
```

```
─λ sudo systemctl status mozillavpn.service
● mozillavpn.service - MozillaVPN D-Bus service
     Loaded: loaded (/usr/lib/systemd/system/mozillavpn.service; disabled; preset: disabled)
     Active: active (running) since Mon 2022-10-03 15:09:07 EDT; 7h ago
   Main PID: 27435 (mozillavpn)
      Tasks: 8 (limit: 9291)
     Memory: 20.9M
```

```
─λ sudo dmesg | grep mozillavpn
[   92.992088] mozillavpn[6875]: segfault at 86 ip 00007f696a460b6c sp 00007ffdf132da38 error 4 in libQt6Core.so.6.4.0[7f696a3d2000+313000]
[   92.992167] audit: type=1701 audit(1664810419.548:139): auid=1000 uid=1000 gid=1000 ses=4 pid=6875 comm="mozillavpn" exe="/usr/bin/mozillavpn" sig=11 res=1
[  153.173821] mozillavpn[10823]: segfault at 86 ip 00007ffa0ecd6b6c sp 00007ffcc233ca98 error 4 in libQt6Core.so.6.4.0[7ffa0ec48000+313000]
[  153.173906] audit: type=1701 audit(1664810479.737:253): auid=1000 uid=1000 gid=1000 ses=4 pid=10823 comm="mozillavpn" exe="/usr/bin/mozillavpn" sig=11 res=1
[13820.609637] audit: type=1325 audit(1664824147.475:342): table=mozvpn-v6:2 family=10 entries=2 op=nft_register_chain pid=27435 comm="mozillavpn"
[13820.609645] audit: type=1325 audit(1664824147.475:342): table=mozvpn-inet:2 family=1 entries=5 op=nft_register_chain pid=27435 comm="mozillavpn"
[13820.609767] audit: type=1300 audit(1664824147.475:342): arch=c000003e syscall=46 success=yes exit=568 a0=5 a1=c000058988 a2=0 a3=0 items=0 ppid=1 pid=27435 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mozillavpn" exe="/usr/bin/mozillavpn" key=(null)
[13820.615333] audit: type=1130 audit(1664824147.558:343): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=mozillavpn comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[13856.013602] mozillavpn[27562]: segfault at 86 ip 00007fa4c641ab6c sp 00007ffdf8aaa4e8 error 4 in libQt6Core.so.6.4.0[7fa4c638c000+313000]
[13856.013688] audit: type=1701 audit(1664824182.957:351): auid=1000 uid=1000 gid=1000 ses=4 pid=27562 comm="mozillavpn" exe="/usr/bin/mozillavpn" sig=11 res=1
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2974)

**Comment by bakulf** [comment]
More likely there is a missing QT/QML dependency.  You can know more checking the logs.
I also have a question: is the app compiled in debug mode? Why do you see the QML debugger enabled?

**Comment by Miroito** [comment]
I have the same issue on the arch based EndeavourOS with i3-gaps.
```
─λ mozillavpn
QML debugging is enabled. Only use this in a safe environment.
zsh: segmentation fault (core dumped)  mozillavpn
```

Installed the mozillavpn AUR package through `yay`.
The cli works fine.

I would agree with @bakulf that a qt dependency might be missing. I can't find a log file.

**Comment by bakulf** [comment]
The log file should be in ~/.local/share/mozillavpn.txt

**Comment by piojpub** [comment]
> More likely there is a missing QT/QML dependency. You can know more checking the logs. I also have a question: is the app compiled in debug mode? Why do you see the QML debugger enabled?

Honestly I don't have an answer... I installed it via pacman from chaotic-AUR repo.

Log ~/.local/share/mozillavpn.txt
```
error: Invalid value "rules" for '--style <components>': Unknown style, 'rules'
```

**Comment by XavierCLL** [comment]
Hi @piojpub @Miroito I just fixed it, update it to v2.9.0-3, as @bakulf said it was due to a missing Qt6 dependency: https://aur.archlinux.org/cgit/aur.git/commit/?h=mozillavpn&id=b7caa61dfc58f8a70dd1700c94f5160845a6ea52

**Comment by piojpub** [comment]
Well done! 
Thank you so much. The client UI is back to work again!

**Comment by bakulf** [comment]
Can we close this bug?
