### ISSUE TITLE
Rendering issues with qt6.4 on linux

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4585]
I haven't tested other platforms but I see a gray border around the navigation bar.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2986)
┆Reporter: Andrea Marchesini

**Comment by bakulf** [comment]
I suspect it's related to the Qt5 compact component. We should get rid of it.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Since we were not able to reproduce this, we cannot mark it as verified.
