### ISSUE TITLE
No complete badge after completing tutorial

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4590]
The “Complete” badge is missing from the tips and tricks cards upon tutorial completion. Here’s a screen shot from the figma spec below of what it should look like. 

!Screen Shot 2022-08-03 at 9.51.54 AM.png|width=745,height=566!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2989)
┆Reporter: Peter Benvenuto

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hello Peter Benvenuto ,

When the VPN tips and tricks feature was implemented in 2.9 version, the “Complete” badge was removed, as per the following comment: https://mozilla-hub.atlassian.net/browse/VPN-2075?focusedCommentId=558617 ( https://mozilla-hub.atlassian.net/browse/VPN-2075?focusedCommentId=558617|smart-link ).

Has this requirement changed in 2.10 version?

Thank you!

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Bianca Hidecuti Yeah, I’m not sure why it was removed. It actually wasn’t supposed to be removed, and I created this bug a while ago I just had it in the wrong place. I don’t think this will make it into 2.10 but instead 2.11.

**Comment by bakulf** [comment]
@MattLichtenstein how complex is this? Can we have it for 2.11/2.12?
About the status of an addon, we can have settings per add-ons already. See the addon message with its read/notified/dismissed states

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Andrea Marchesini this is low effort and definitely viable for 2.11

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Santiago Andrigo IMO this should not be a bug since it is not expected behavior - this was just never implemented
