### ISSUE TITLE
The VPN locks up or freezes, the timer stops and there's no internet connection during this issue.

### ISSUE THREAD

**Issue by gus8923** [mozilla-mobile/mozilla-vpn-client#4614]
**Description**

The VPN locks up from time to time, sometimes every few seconds to a few hours. I call it a lockup but it could be a freeze the VPN stops counting and there's no internet connection during this issue. 

Does it impact functionality or aesthetics? 
- Functionality

Does this endanger users? What would be compromised and how likely is the threat? 
- Since the VPN blocks the internet connection the user is not being exposed.

How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do)
- It's very annoying, the VPN is blocking their internet connection.

Does it degrade the user experience significantly? 
- Yes

Is it legally sensitive?
- Don't know

**Centrality** 
Is it on a core user journey or on a secondary one?
- It's a core user journey issue since when it happens it stops all users' internet connection traffic.

**Technical Information**

Platform: Windows10
FX product: Mozilla VPN
Version: 2.9
Network type: Home Wifi

**Steps to Reproduce**
1. Install the VPN
2. Turn The VPN on

**Actual Results**

The VPN locks up or freezes, the timer stops and there's no internet connection during this issue.

**Expected Results**

The VPN should connect normally.

**Support Info**

Logs: 
[mozillavpn-2022-10-5.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9748638/mozillavpn-2022-10-5.txt)

Screenshots:

Can Support reproduce or not?
- No

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2999)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Josh Schrader any progress to report on this issue? Should we consider addressing this in the January sprint?

**Comment by data-sync-user** [comment]
➤ Josh Schrader commented:

Owen Kirby I have left my VPN running on my Windows 10 machine for a few days (playing music so I would notice any interruption in connection) and have not seen this issue reproduce. However, my machine is on Ethernet and does not have a WiFi card to test on WiFi. 
I would suggest someone else give it a test or lower priority to Low until we receive more reports of this.
