### ISSUE TITLE
[Linux] Multi-hop Mozilla VPN cannot be turned ON if the default Firewall is enabled

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4628]
**Mozilla VPN affected versions:**

* 2.10.0~rc78-focal1;

**Platform tested:**

* Linux Ubuntu 20.04;

**Prerequisites:**

* Be logged in with an account with subscription for Mozilla VPN;
* Be on Stage;
* Have the Ubuntu default firewall (ufw) enabled;

**Steps to reproduce:**

1. Go to Select Location and enable Multi-Hop option
1. Turn the ufw on -> “sudo ufw enable”
1. Turn the VPN on;

**Expected results:**

* The VPN is turned on with success;

**Actual results:**

* The VPN cannot be turned on; after few seconds the “server unavailable” modal is displayed;

**Notes:**

* Not reproducing for single hop;
* Not reproducing on other platforms;
* Reproducing for both stage and prod;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3007)
┆Reporter: Valentina Virlics
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3007

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Owen Kirby Please take a look over this to see if this is not actually an “expected“ behavior; thanks!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Corner case of UFW interfering with multi-hop.
Valentina Virlics does this also happen if UFW is enabled before the multi-hop selection? (step 1)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Santiago Andrigo  Yes, it does. The apps enters in “No signal“.

**Comment by oskirby** [comment]
I have been able to reproduce this. It seems like the connection to the entry server works just fine, as expected, but it's the connection to the exit server that never completes.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Owen Kirby should’nt we expect to see the “firewall block“ strings in the server unavailable modal, in this case? (more details https://mozilla-hub.atlassian.net/browse/VPN-1748 ( https://mozilla-hub.atlassian.net/browse/VPN-1748|smart-link ))

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

In this particular case, because the firewall is local to the user’s computer, we should be able to configure the firewall to permit this VPN connection, so I would prefer to focus our efforts in that direction.

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

This should be fixed on main via PR #4735 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4735 ) do we want to uplift this fix to 2.11?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed on Linux Focal 20.04 using Mozilla VPN 2.12.0 (2.12.0~rc1-focal1) build.

Mozilla VPN can be turned on while multi hop and default firewall are enabled.

!Screenshot from 2022-11-16 11-20-29 (1).png|width=1920,height=1080!
