### ISSUE TITLE
Ubuntu deb not installable on 20.04

### ISSUE THREAD

**Issue by futurechimp** [mozilla-mobile/mozilla-vpn-client#468]
I've just grabbed the Mozilla VPN package for Ubuntu 20.04, from https://launchpad.net/~mozillacorp/+archive/ubuntu/mozillavpn/+packages, but the deb doesn't install cleanly.

Hopefully this is the right place to file a bug, apologies if not.

So, after doing:

```
sudo add-apt-repository ppa:mozillacorp/mozillavpn
sudo apt-get update
sudo apt install mozillavpn
```

Apt says I'm missing QT packages:

```
$ sudo apt install mozillavpn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 mozillavpn : Depends: qt515base (>= 5.15.2-1basyskom4) but it is not installable
              Depends: qt515charts-no-lgpl (>= 5.15.2-1basyskom1) but it is not installable
              Depends: qt515declarative (>= 5.15.2-1basyskom1) but it is not installable
              Depends: qt515graphicaleffects (>= 5.15.2-1basyskom1) but it is not installable
              Depends: qt515imageformats (>= 5.15.2-1basyskom) but it is not installable
              Depends: qt515networkauth-no-lgpl (>= 5.15.2-1basyskom1) but it is not installable
              Depends: qt515quickcontrols2 (>= 5.15.2-1basyskom1) but it is not installable
              Depends: qt515svg (>= 5.15.2-1basyskom1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I don't _think_ that I have any QT-related problems as far as I'm aware.

**Comment by bakulf** [comment]
Our installation steps are not completed. There is 1 missing step:

`sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-focal`

Unfortunately, Ubuntu focal doesn't have QT v5.15 (v5.12 is available but a few features are missing to run mozillaVPN - mainly related to accessibility). We are porting those packages in the mozilla PPA and I hope it will be done relatively soon. In the meantime, add that PPA and install MozillaVPN.

I keep this issue open. I'll close it when the packages will be moved into our PPA.

**Comment by bakulf** [comment]
OK! This is now fixed. You don't need the second PPA. Just run the usual commands:

```
sudo add-apt-repository ppa:mozillacorp/mozillavpn
sudo apt-get update
sudo apt-get install mozillavpn
```

**Comment by futurechimp** [comment]
Thanks! It works very well, I'm impressed with both the performance and the ease of use.
