### ISSUE TITLE
Future of the Firefox Private Network

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/mozilla-vpn-client#4702]
Hi,

_I originally asked this question in https://github.com/mozilla-extensions/secure-proxy/issues/979 but I am not sure if still people read the issue tracker there. So I reposted it here because it's related._

I wanted to write an article about Mozilla's current Premium services and how to support Mozilla using their subscription offers. In this context I wondered what the state of the Firefox Private Network is and whether it has a future at all. It has the "Beta" label since more than three years, the last commit in this repository was in March 2021 and the Mozilla VPN is more and more a thing. So I guess it's kind of "replaced" by the Mozilla VPN. On the other hand fpn.firefox.com is still live, takes new subscriptions from users in the USA and it's also still advertised in the main navigation of [www.mozilla.org](http://www.mozilla.org/).

@bakulf Since you worked very active on the Firefox Private Network and now on the Mozilla VPN, could you please clarify if this project is still alive and if the Firefox Private Network should still be recommended to new users who don't need a full VPN, or if it's better to recommend only the Mozilla VPN?

Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3061)

**Comment by lesleyjanenorton** [comment]
cc @birdsarah @albionx

**Comment by cadeyrn** [comment]
This is answered by https://github.com/mozilla-extensions/secure-proxy/pull/985.
