### ISSUE TITLE
Incorrect Authentication URL - Ubuntu 20.04

### ISSUE THREAD

**Issue by BuffaloWill** [mozilla-mobile/mozilla-vpn-client#471]
I followed the instructions in the README to build the binary from source on Ubuntu 20.04. 

After the build is complete and I run `mozillavpn` I get the VPN client. However, when I click on 'Get Started' from the VPN client it forwards me to `accounts.stage.mozaws.net`. I believe this should be `accounts.firefox.com`? I cannot login using my paid VPN account to `accounts.stage.mozaws.net`.

**Comment by NilsIrl** [comment]
You need to build with the option production.

To do so, run qmake with `CONFIG+=production`.

**Comment by BuffaloWill** [comment]
Great. Thank you!

**Comment by chrismore** [comment]
> You need to build with the option production.
> 
> To do so, run qmake with `CONFIG+=production`.
> 
> like so:
> 
> ```
> qmake CONFIG+=production
> ```

Thanks! We have also updated the README file.
