### ISSUE TITLE
Cargo not installed for Taskcluster Linux builds

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#4730]
The Taskcluster builds are failing because `cargo` is not installed:
https://firefox-ci-tc.services.mozilla.com/tasks/SIYGl5JqT1yugl672LkgSw/runs/0/logs/public/logs/live.log#L92

According to @oskirby , this is why they failed to build on launchpad.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3080)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Raphael Okafor If this does not require any QA work, could you please add the “qa-not-actionable“ label? Thanks!
