### ISSUE TITLE
VPN initially works, after 5 minutes of being on it blocks internet connection.

### ISSUE THREAD

**Issue by gus8923** [mozilla-mobile/mozilla-vpn-client#4734]
Description

The user turns on the VPN and initially (for 5 minutes) it works as expected. After that, the VPN blocks the user's internet connection. They are no longer able to access the internet, they have to turn off the VPN to regain internet access

- Does it impact functionality or aesthetics?
Functionality

- Does this endanger users? What would be compromised and how likely is the threat?
Since the VPN blocks the internet connection the user is not being exposed.

- How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do)
It's very annoying, the VPN is blocking their internet connection.

- Does it degrade the user experience significantly?
Yes

- Is it legally sensitive?
Don't know

Centrality
- Is it on a core user journey or on a secondary one?
Core functionality: It happens 5 minutes after turning it on and it stops all user's internet connection traffic.

Technical Information

Platform: macOS 12.5
FX product: Mozilla VPN
Version: 2.9
Network type: Home Wifi

Steps to Reproduce
1. Install the VPN
2. Turn the VPN on
3. After 5 minutes the VPN will block the internet 

Actual Results

The internet connection will be blocked after 5 minutes.

Expected Results

The internet connection shouldn't be blocked by the VPN.

Logs: 
[mozillavpn-2022-10-7.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9873337/mozillavpn-2022-10-7.txt)

- Can Support reproduce or not?
No

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3085)

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

If we get additional reports of this (or are able to reproduce), logs would be very helpful to try to isolate the cause. Thanks!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Matt Cleinman just checking – you did see the logs in the ticket but there wasn’t any smoking gun there, right?

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Santiago Andrigo Apologies for the lack of the clarity. Yes, I looked at the logs on this ticket, and nothing jumped out at me. If we get additional reports (and more logs), it would help identify similarities between them.

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

Dormant for 6 months; 6 versions behind.   No new info gathered to assist in troubleshooting.
