### ISSUE TITLE
Error building latest release on Linux with Qt 6.4

### ISSUE THREAD

**Issue by Cimbali** [mozilla-mobile/mozilla-vpn-client#4770]
This was technically fixed in 09be7f1e13a24f8e22eb9ac9947e8fcc4f7e9e5e but didn’t ship in the latest release, so the latest releases can’t build on up-to-date systems. Even if shipping the fix in a 2.10.1, that’s just introducing a builder time bomb until the next qt release, where currently working builds will suddenly stop working.

Could the `#error` be guarded with an additional `defined(MVPN_ANDROID)` maybe, so platforms where `QDnsLookup::lookup()` exists can build correctly?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3106)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This will be included in the next release.

**Comment by Cimbali** [comment]
Which means the next release won’t build with Qt 6.5, and so on. Moving the `#error` would be future-proof.
