### ISSUE TITLE
Disable the app-permission view in KDE

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4777]
Following bugzilla bug 1730224, the app-permission view is visible in KDE. 
We should not expose the feature on not-supported environments.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-2779)
┆Reporter: Andrea Marchesini

**Comment by oskirby** [comment]
As of PR #5279 we should now detect and support KDE for split tunnelling, it is no longer an error do display this view on KDE.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Based on below comment I understand that we should have App Permissions on KDE builds, but from the title I understand the contrary. Which is correct? Andrea Marchesini 

Thank you!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Owen Kirby we do have split-tunneling for KDE, right?

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

Andrea Marchesini we should support split tunneling on KDE version 5.75 and newer (you can check the KDE version with kf5-config --version). IIRC, this means that the app permissions menu should work with KDE on Ubuntu 22.04 (jammy) and later. Unfortunately, Ubuntu focal and bionic are too old to support this feature.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Owen Kirby should you be assigned to this one? and was it completed during the sprint? 🙂

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

That’s debatable if it should be assigned to me, since it was implemented by an external contributor. I really just clicked the merge button, and yes it was merged in the January sprint.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Owen Kirby I chatted with Adrienne, Santiago and Sarah about this situation, and we think that we should go ahead and assign it to a sprint, (and Fix Version, once it’s merged) assign it to whoever merged the code, but not add any story points. That way it’s on QA’s radar for the sprint/release testing, but it doesn’t affect our velocity.
