### ISSUE TITLE
VPN app and taskbar icon missing on 2.10

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#4799]
**Description**
Issue is intermittent and random. VPN client disappears from view on desktop, as well from the taskbar icon and system tray. Client does not appear to be disconnected since network icon in system tray detects the VPN is connected. Can work around this by searching for App in start menu and relaunching it causes VPN to be in view and icons reappear on taskbar. Issues does not appear to happen if icon is pinned to taskbar

Does it impact functionality or aesthetics? Aesthetics

Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? Yes. Users believe they are no longer connected to the VPN, believe it is not installed correctly, and can struggle to find the client again.

Does it degrade the user experience significantly? Yes

Is it legally sensitive? No

**Centrality** 
core user journey

**Technical Information**

Platform Windows 10
FX product Mozilla VPN
Version 2.10
Region/Languages
Network type (Mobile/Wifi/Wired)

**Steps to Reproduce**

1. Purchase VPN subscription
1. Download/Install VPN
1. Launch VPN
1. Connect and leave open in the background.

**Actual Results**
After an undetermined amount of time, the VPN client is missing from view.

**Expected Results**
Client should remain in view, unless the window is minimized. If minimized, client can be opened from icon in taskbar or sys tray.

[mozillavpn-2022-11-2.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9924340/mozillavpn-2022-11-2.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3148)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3148

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Support reporting no new occurrences of this issue being reported as of 12/8/2022 👍

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Cancelling this since there haven't been tickets in a while for this, which implies we likely addressed this.
