### ISSUE TITLE
Long display name is not wrapped in Settings page of VPN app

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#480]
#### Affected versions:
- 2.0.2;

#### Affected Platforms:
- Linux Ubuntu 20.04 and 20.10;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;
- Have a LONG display name set to your FxA account;

#### Steps to reproduce:
1. Open the VPN app;
2. Click settings gear icon;
3. Observe the display name;

#### Expected result:
- The LONG account display name is wrapped.

#### Actual result:
- The display name is cut.

#### Notes:
- reproducing across platforms.

![long name](https://user-images.githubusercontent.com/15685960/105034871-cc8cb380-5a62-11eb-8e98-fadbd63da1fd.png)

**Comment by bakulf** [comment]
@lesleyjanenorton can you take this bug?

**Comment by lesleyjanenorton** [comment]
yep!

**Comment by ValentinaPC** [comment]
Verified as fixed on the last cross-plat build, while using Windows 10.
The display name is wrapped.
![longdn](https://user-images.githubusercontent.com/15685960/106155070-efb51280-6188-11eb-895c-390321067344.png)
