### ISSUE TITLE
[Android] VPN cannot be turned on after location switch

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#483]
#### Affected versions:
- 2.0.3; 

#### Affected Platforms:
- Android 10;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Switch locations;
3. Turn on the VPN;

#### Expected result:
- The VPN is turned on.

#### Actual result:
- The VPN cannot be turned on after the location switch.

#### Notes:
- after reproducing this issue, the re-authentication is working after sign out only if VPN is force stopped.

https://user-images.githubusercontent.com/15685960/105172148-d9270f80-5b27-11eb-97e8-eba713133c30.mp4

**Comment by chrismore** [comment]
@ValentinaPC I ran into this bug today too and it required me logging out and back in to get it to work again.

**Comment by ValentinaPC** [comment]
Verified this as fixed on the 2.0.3 version, on Android 10.
The VPN can be turned on after location switch.
