### ISSUE TITLE
[Linux Kinetic] Mozilla VPN “start on boot” feature does not work as expected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4830]
**Mozilla VPN affected versions:**

* 2.11.0 (2.11.0~rc2-kinetic1);

**Platform tested:**

* Linux Kinetic 22.10;

**Prerequisites:**

* Have the Mozilla VPN app installed and be logged.
* Have the “start on boot” app feature ON;

**Steps to reproduce:**

1. Open the VPN and leave it OFF:
1. Leave the app in foreground;
1. Restart the device;
1. Observe the behavior;

**Expected results:**

* App is turned ON and is minimized;

**Actual results:**

* App does not start.

**Notes:** 

* If the app is manually opened, it goes ON;
* 【 highlighted #ff5630 】**Another weird thing happened on Kinetic - after a restart, 2 instances of the app were triggered - attaching logs for this;**【 end highlighted 】

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3176)
┆Reporter: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on 2.13 and 2.14 version while using a VM of Linux Kinetic.

After enabling the start on boot feature and performing a log off - log back in action, I am not able to reproduce this anymore:

  * app is turned on, but minimized;
  * only one app instance is displayed;

For some reason when this issue was logged, we consider it ok that the app is not put in foreground, Andrea Marchesini any idea why? Thank you!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

What is going here is the following:

  1. ubuntu is configure to do not ask for the user password. No login mode.
  2. but the keyring is opened only when the user inserts the password for the first time.
  3. because of this, when mozillavpn starts early in the process, is unable to retrieve the key to decrypt the setting file.  
  4. The file is then overwritten to allow the user to recover from this scenario

Owen Kirby and I are working on a solution.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Andrea Marchesini could you please add a fixVersion? Thank you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on a Linux Kinetic (VM) using 2.14.0 (2.14.0~rc20230301185126-kinetic1) build.

While having the auto-login OS function enabled and restarting the VM, Mozilla VPN app settings are not reset and “start on boot” works as expected (except the foreground old issue).

**Comment by nickavem** [comment]
> ➤ Andrea Marchesini commented:
> 
> What is going here is the following:
> 
>     1. ubuntu is configure to do not ask for the user password. No login mode.
> 
>     2. but the keyring is opened only when the user inserts the password for the first time.
> 
>     3. because of this, when mozillavpn starts early in the process, is unable to retrieve the key to decrypt the setting file.
> 
>     4. The file is then overwritten to allow the user to recover from this scenario
> 
> 
> Owen Kirby and I are working on a solution.

Was a solution ever found? On version 2.16.1 (2.202308091941) this is still an issue. I have an encrypted drive, so I like autologin to be able to only enter my password once.

**Comment by oskirby** [comment]
As of the 2.14.0 release this should have been fixed, the behaviour now checks whether the desktop session was configured for auto-login and if so we disable the use of an encrypted settings file, and store settings in plaintext. This should ensure that the keyring is only needed in situations where it is already unlocked.

If the problem persists for you, would you be able to share logs with us?
