### ISSUE TITLE
Mozilla VPN as Qubes NetVM

### ISSUE THREAD

**Issue by sebastianlutter** [mozilla-mobile/mozilla-vpn-client#4843]
I'm trying to use the Ubuntu 22.04 mozilla vpn client in an Qubes OS environment. Qubes OS has the concept of NetVM which are used by App VMs to gain network access. I try to set up a vpn-mozilla VM that other AppVMs can use to have MozillaVPN connection.

I installed mozillavpn ([details here](https://forum.qubes-os.org/t/mozilla-vpn-as-proxy-vm/14669)) and everything is fine when I use applications in this VM. When other AppVM use internet through the `vpn-mozilla` VM the traffic is not routed through the VPN but they directly get internet access via 'eth0' (the default gw). The AppVM traffic enters the `vpn-mozilla` VM via a `vifX.Y` network interface that is established by Xen (the supervisor QubesVM is running on) and is routed (NAT/MASQUERATE) to the `eth0` default gw. 

`vif*` interface example (ip range 10.137.0.x/24)

```
user@vpn-mozilla:~$ ip addr show vif9.0
3: vif9.0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 32
    link/ether fe:ff:ff:ff:ff:ff brd ff:ff:ff:ff:ff:ff
    inet 10.137.0.30/32 scope global vif9.0
       valid_lft forever preferred_lft forever
    inet6 fe80::fcff:ffff:feff:ffff/64 scope link 
       valid_lft forever preferred_lft forever
```

As far as I understood this are the mozillavpn/wireguard routing entries, correct?

```
user@vpn-mozilla:~$ ip route list table 51820
0.0.0.0/5 dev moz0 
8.0.0.0/7 dev moz0 
10.64.0.1 dev moz0 
10.124.0.0/20 dev moz0 
11.0.0.0/8 dev moz0 
12.0.0.0/6 dev moz0 
16.0.0.0/4 dev moz0 
32.0.0.0/3 dev moz0 
64.0.0.0/2 dev moz0 
128.0.0.0/3 dev moz0 
160.0.0.0/5 dev moz0 
168.0.0.0/6 dev moz0 
172.0.0.0/12 dev moz0 
172.32.0.0/11 dev moz0 
172.64.0.0/10 dev moz0 
172.128.0.0/9 dev moz0 
173.0.0.0/8 dev moz0 
174.0.0.0/7 dev moz0 
176.0.0.0/4 dev moz0 
192.0.0.0/9 dev moz0 
192.128.0.0/11 dev moz0 
192.160.0.0/13 dev moz0 
192.169.0.0/16 dev moz0 
```

How can I tell MozillaVPN/Wireguard that all incoming traffic from `vif*` interfaces should be routed through the VPN? Any advice would be great!

lg
Sebastian

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3186)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3186

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

At present we do not support Qubes NetVM and we are unable to work on this any time soon, but we would love you hear if you are able to find a solution that works for you.

FWIW, you might have some luck in investigating how the `fwmark` interacts with the routing table, as that's what drives most of the VPN routing decisions.

**Comment by sebastianlutter** [comment]
Thanks for the hint with `fwmark`! I got it to work by changing a rule in `mozvpn-preroute` filter hook:
```
root@vpn-mozilla:/home/user# nft -a list table inet mozvpn-inet
table inet mozvpn-inet { # handle 7
	chain mozvpn-mangle { # handle 1
		type route hook output priority raw; policy accept;
	}

	chain mozvpn-nat { # handle 2
		type nat hook postrouting priority srcnat; policy accept;
	}

	chain mozvpn-conntrack { # handle 3
		type route hook output priority -201; policy accept;
		meta mark 0x0000ca6c ct zone set 40524 # handle 8
	}

	chain mozvpn-preroute { # handle 4
		type filter hook prerouting priority raw; policy accept;
		iifname != "vif*" iifname != "moz0" meta iiftype != loopback meta mark set 0x0000ca6c ct zone set 40524 # handle 10
	}
}
```
At `# handle 10` I have added `iifname != "vif*"` to the condition:
```
# find the handle number of rule that contains "mark set 0x0000ca6c"
nft -a list table inet mozvpn-inet
# then delete that rule
nft delete rule inet mozvpn-inet mozvpn-preroute handle HANDLE_IDX
# and add this extended rule
nft -a add rule inet mozvpn-inet mozvpn-preroute iifname != vif* meta iifname != moz0 meta iiftype != loopback meta mark set 0x0000ca6c ct zone set 40524
```
This avoids that packages from `vif*` interfaces are directly routed to `eth0` by getting marked with `fwmark 0x0000ca6c` (packages with `fwmark 0x0000ca6c` are routed to `eth0`, anything else goes through `moz0`)

I put everything together as NetworkManager dispatcher script (`/etc/NetworkManager/dispatcher.d/99-mozilla-vpn.sh`). It is triggered when `eth0` gets `up`, it starts `moz0` and applies the needed fixes:
```
#!/bin/bash
#
# Run as root. Init mozilla VPN when eth0 is up.
# Fix things for NetVM when moz0 is up
#

set -e

if [ "$1" = "eth0" -a "$2" = "up" ]; then
	# enable vpn state
	su - user -c "mozillavpn deactivate && mozillavpn activate"
fi
if [ "$1" = "moz0" -a "$2" = "up" ]; then
	# fix DNS using nmcli
	su - user -c "nmcli d modify eth0 ipv4.dns 8.8.8.8"
	# get handle id of nftable rule
	HANDLE_IDX=$(sudo nft -a list table inet mozvpn-inet | grep "mark set 0x0000ca6c" | sed "s/.*handle \(.*\)/\1/g")
	# remove the rule
	nft delete rule inet mozvpn-inet mozvpn-preroute handle ${HANDLE_IDX}
	# replace it with new rule
	nft -a add rule inet mozvpn-inet mozvpn-preroute iifname != vif* meta iifname != moz0 meta iiftype != loopback meta mark set 0x0000ca6c ct zone set 40524
fi
```
Works for now, but nothing production stable. I also uncommented this lines in `/rw/config/qubes-firewall-user-script`
```
# Block forwarding of connections through upstream network device
# (in case the vpn tunnel breaks)
iptables -I FORWARD -o eth0 -j DROP
iptables -I FORWARD -i eth0 -j DROP
ip6tables -I FORWARD -o eth0 -j DROP
ip6tables -I FORWARD -i eth0 -j DROP
```

The script uses `8.8.8.8` as DNS since I need a proper way to get the DNS servers mozillaVPN is using (I tried `wg`, `nmcli` and `mozillavpn`).  Is the list of DNS servers somewhere available? Can I retrieve it somehow using some CLI?

Thanks
