### ISSUE TITLE
Internet connection on Mac is flaky when VPN is enabled/disabled

### ISSUE THREAD

**Issue by groovecoder** [mozilla-mobile/mozilla-vpn-client#488]
On my Mac 10.15.7 using VPN 2.0.1 it seems to have real trouble fully enabling or disabling the VPN connection? Sorry I can’t find reliable STR, but the general pattern is:

1. Need to connect to Mozilla VPN so open Viscosity
1. Before connecting to Viscosity, disable Mozilla VPN
1. All browser, slack, etc. connections stop working (somewhat expected)
1. Try to connect to Mozilla US-East via Viscosity
1. Spin spin spin, never connects
1. Go back to browser and try to refresh mail - spin spin spin, never connects
1. Go get coffee to see if the connection will fully reset
1. Come back to browser and try to refresh mail - spin spin spin, never connects
1. Try to connect to Mozilla VPN
1. Mozilla VPN connects, and all the push notifications from Mozilla US-East come thru at once
1. Browser and Slack are working again

So, there seems to be some time after disconnecting from Mozilla VPN where most of my apps are still “stuck” trying to use Mozilla VPN? Sometimes for a good long while like 5 minutes? Other people experiencing this?

Experienced this again. Today’s STR:

1. Disconnect from VPN so I can open Hulu in Nightly
1. Visit hulu.com in Nightly …
1. spin spin spin never connects
1. Restart Nightly
1. spin spin spin never connects
1. check all my other apps - they’re all d/c now (including Slack)
1. reconnect to VPN
1. everything starts working again immediately

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-94)
┆author: Data Sync

**Comment by chrismore** [comment]
@ValentinaPC have you seen anything like the above in your testing on Mac?

**Comment by ValentinaPC** [comment]
@groovecoder @chrismore 

Verified this using the last VPN prod build on Mac OS 10.15.7.
While using the Viscosity VPN you mentioned, and following the above STRs, we were not able to reproduce the issue you experienced.
We tried with another VPN - Windscribe - and following the STRs, we were able to reproduce the connectivity issue and the apps getting stuck.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

stale

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Moving back to Cancelled
