### ISSUE TITLE
VPN client suddenly turns off on Android

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#4882]
**Description**
VPN 2.10 client on Android suddenly appears to be switched off without any notice. Users may notice an icon on the device status bar that the VPN is still On and confirm that the device is still protected by doing a Mullvad check [https://mullvad.net/en/check/](https://mullvad.net/en/check/)

Log entries stand out:

```
(VPNService) - Client Disconnected, VPN is down - Service might shut down soon  
(VPNService) - Client Disconnected, VPN is up  
(VPNService) - Service got Destroyed  
(VPNService) - Got Bind request  
[info] - (VPNService) - Dispatch Daemon State -> connected 
```

Does it impact functionality or aesthetics? Yes, aesthetics
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Yes, users belive they are no longer protected by the VPN
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality** 
Is it on a core user journey or on a secondary one? 

* Core user journey

**Technical Information**

Platform Android 11, 12, 13
FX product Mozilla VPN
Version 2.10.1
Region/Languages
Network type Mobile/Wifi

**Steps to Reproduce**

1. purchase subscription
1. install VPN
1. connect to any server location
1. leave VPN On

**Actual Results**

* After an undetermined amount of time, the VPN client appears to be Off without any notice

**Expected Results**

* Client should display On unless it is manually turned off

[MozillaVPN_Logs_2022-05-05-14-5-13.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/9965121/MozillaVPN_Logs_2022-05-05-14-5-13.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3208)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3208

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

We were not able to reproduce this issue on Mozilla VPN 2.10.1 while using Android 10 and 12. We let the VPN running for about 3h and the client remained ON, while being connected to a Wi-Fi network. 

Was this reproduced after being turned ON for more than 3h? 

As we could not reproduced it on the 2.10.1 version, we will not be able to verify it on the 2.12 version.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Marking this is “Done”. As per Basti: “Thats super tricky to reproduce, as that’s dependent on resource management. It took me about 12h of using the phone without checking the app to trigger this. I’d propose we setup a post launch reminder, to checking with support - as they originally reported this”. Joseph Anthony Cuevas Is this something you could take a look at, maybe by early January? (2.12 is expected to launch in Mid December).

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Santiago Andrigo We will monitor going forward and check back in Early Jan 2023. Thanks!

**Comment by toddmazierski** [comment]
Hello! The bug might be happening to me.

I updated to 2.11.0 recently. Now, every 1-2 days the "VPN Connected" notification disappears. When I open the app, the UI displays "VPN is off".

However, when I check my device's IP address, it's still masked — i.e. connected through the VPN. The logs are:

```
[2022-12-10T12:00:20.599] [error] - (DaemonConnectionHealth) - Failed to Reach VPN-Gateway  
[2022-12-10T12:00:20.647] (VPNService) - Try to reconnect tunnel with same conf  
[2022-12-10T12:00:20.692] [info] - (VPNService) - VPN Permission Already Present  
[2022-12-10T12:00:20.693] [info] - (VPNService) - Currently have a connection, start switching  
[2022-12-10T12:00:20.726] (VPNService) - Client Disconnected, VPN is up  
[2022-12-10T12:00:20.736] (VPNService) - Service got Destroyed  
[2022-12-10T12:00:20.814] (VPNService) - Got Bind request  
[2022-12-10T12:00:20.859] [info] - (VPNService) - Dispatch Daemon State -> connected  
[2022-12-10T12:00:21.005] [info] - (Android-Glean) - Initialised android glean  
[2022-12-10T12:00:21.008] [info] - (VPNService) - Initialised Service with Wireguard Version 219296a  
```

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Just happened to me as well (on Windows, on the 2.11 client). The client seems to be disconnected but the key (and tests on the browser) indicate that I’m still connected. Logs attached.

[^MozillaVPN_Logs_2022-12-10-15-12-07.txt]

!Screenshot_20221210-151145.jpg|width=1080,height=2400!
