### ISSUE TITLE
Addon functional test is broken

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#4888]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3216)
┆Reporter: Andrea Marchesini
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-3216

**Comment by strseb** [comment]
Sorry, testing something with this comment :)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Added the qa-not-actionable label for this. Thanks!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Adding the December sprint to this ticket.
