### ISSUE TITLE
VPN does not finalize location switch while in background

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#489]
#### Affected versions:
* 2.0.3 production-debug build; 

#### Affected Platforms:
* Android 10;

#### Prerequisites:
* Have the VPN app installed;
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
1. Tap to switch a location;
1. Put the VPN in background before the switching is finalized;
1. Go to an IP location show page;
1. Check the IP;
1. Go back to VPN;

#### Expected result:
* The VPN has switched to the new location.

#### Actual result:
* The VPN has not switched to the new location, while in the background.

#### Notes:
* The internet is working while the VPN is in the switching state.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-95)
┆Reporter: Data Sync
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/VPN-95

**Comment by bakulf** [comment]
This has been improved a lot recently on both iOS and Android. Let's close this bug.

**Comment by ValentinaPC** [comment]
On iOS, there were some changes and this issue is fixed, but not on Android.

Verified this on Android 10, VPN build 2.3.0 (16214150) and the location switch is not finalized in the background (is finalized when VPN is back in focus);

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

stale
