### ISSUE TITLE
The “Cancel and try again” sign in option does “cancel” but not “try again”

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#49]
#### Affected versions:
- 1.202010050934;

#### Affected Platforms:
- Linux Ubuntu 20.04 (64-bit);

#### Prerequisites:
- Have the VPN app installed and running;
- Don’t be signed in;

#### Steps to reproduce:
1. Click on the “Get Started” button;
2. Close the browser page that opens for you to sign in;
3. Click the “Cancel and try again” link;

#### Expected result:
-  The process is canceled and a new page is opened for you to sign in again.

#### Actual result:
- The process is canceled but no new sign in the browser window is launched.

#### Notes:
- user is redirected to the “Get Started“  app screen.
![image](https://user-images.githubusercontent.com/15685960/95085153-81ef6180-0727-11eb-8032-0edc6a358120.png)

**Comment by bakulf** [comment]
@jess-cook03 what do you think about this change? Do we want to proceed?

**Comment by chrismore** [comment]
Change text to simply "Cancel" since the action is only cancelling and there is no real "try again" automatic action.

**Comment by ValentinaPC** [comment]
Verified as fixed on the latest cross-plat VPN builds (12/02) while using Android, Linux, iOS and Mac OS.
The "Cancel and try again" message was replaced with "Cancel" and works as expected.
![image](https://user-images.githubusercontent.com/15685960/100980757-6ac5c800-354e-11eb-864f-640e2b292a8d.png)
