### ISSUE TITLE
Max limit exceed warning wrongly displayed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#491]
#### Affected versions:
- 2.0.1 prod installed with promo codes; 

#### Affected Platforms:
- iOS 14.2;

#### Prerequisites:
- Have the VPN app installed;
- Have an Apple ID without subscriptions attached;

#### Steps to reproduce:
1. Log into VPN with an account without subscription;
2. Make the IAP using a coupon;
3. Wait until you are redirected to the VPN activation screen.
4. Observe the My devices section from starting screen;

#### Expected result:
There are no display or layout issues.

#### Actual result:
There is a max limit exceeding the red triangle displayed.

#### Notes:
- only 1 device was attached to that account;
- the devices page did not display any devices.
- the VPN cannot be started.
![IMG_20210121_171751](https://user-images.githubusercontent.com/15685960/105376806-d05f3800-5c12-11eb-8ce5-dfb8d955d402.jpg)

**Comment by chrismore** [comment]
@lesleyjanenorton @bakulf @strseb do you have any ideas here? Do you think this is related to iOS or something with the cross-platform code?

**Comment by lesleyjanenorton** [comment]
Nothing is coming immediately to mind. Was this a fresh install?

**Comment by strseb** [comment]
Just a wild guess looking at this: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/mozillavpn.cpp#L289
What if during the iap step the device's keys were not registered? That could also trigger this condition.

**Comment by ValentinaPC** [comment]
> Nothing is coming immediately to mind. Was this a fresh install?

Yup. Fresh as Spring! :)

**Comment by bakulf** [comment]
@ValentinaPC Can I see the logs?

**Comment by bakulf** [comment]
Fixed

**Comment by ValentinaPC** [comment]
Verified as fixed on the last prod build, while using iOS 14.02.
After installing the VPN app using promo codes and make subscription also using promo codes, the user was redirected to the VPN activation screen and no error were displayed.
