### ISSUE TITLE
Update links in the about us section of the VPN

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#492]
On the "about us" section, we have the following four pieces of information

> Mozilla VPN
>(copy)
> 
> Release Version
> (version)
> 
> Terms of Service
> 
> Privacy Notice

We need to add a 5th piece of information. 

Please add a link with the text of "License" with an external link of:

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/LICENSE.md

The list should finally then be:

> Mozilla VPN
>(copy)
> 
> Release Version
> (version)
> 
> Terms of Service
> 
> Privacy Notice
> 
> License

**Comment by chrismore** [comment]
Link added and merged.

**Comment by ValentinaPC** [comment]
Verified this on all cross-platform VPN builds, including the new WIN client.
The new link is there.
![image](https://user-images.githubusercontent.com/15685960/106153479-44578e00-6187-11eb-8b38-1e66f0a75739.png)
