### ISSUE TITLE
mozillavpn fails with libGL errors

### ISSUE THREAD

**Issue by bansp** [mozilla-mobile/mozilla-vpn-client#4927]
This is an issue similar to the closed #3447 but unfortunately still alive for me.

When trying to run the command, I see a little transparent window appear for a while and get the following:

```
~$ mozillavpn
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Aborted (core dumped)
```

The OS is Ubuntu 18.04.6 LTS, fully updated:
`4.15.0-196-generic #207-Ubuntu SMP Thu Oct 27 21:24:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

The driver is NVIDIA-SMI 340.108

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3250)

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Santiago Andrigo could use your help on prioritizing this.

**Comment by albionx** [comment]
The driver seems pretty old. It was released in December 23, 2019, whereas the latest is from just a few days ago.
https://www.nvidia.com/en-us/drivers/unix/linux-amd64-display-archive/

Piotr are you able to update the driver and check again?

**Comment by bansp** [comment]
Thanks for the quick reaction and for the suggestion, @albionx . I was sure I upgraded the driver around May so I didn't even bother to check when reporting, and yes, upgrading to 390.154 has fixed the issue.
Closing with thanks!
