### ISSUE TITLE
Fix calculation of network upload speed

### ISSUE THREAD

**Issue by flozia** [mozilla-mobile/mozilla-vpn-client#4948]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3261)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Florian Zia Can we add a few details about what needs to happen here?

**Comment by flozia** [comment]
@lesleyjanenorton The issue is already addressed by #4947. The total transferred bytes were added up instead being being set.
