### ISSUE TITLE
“No internet connection. Try again!” red banner appears after a few seconds from turning on the VPN

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#495]
#### Affected versions:
- 2.0.3 beta-debug build; 

#### Affected Platforms:
- All Android;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN app;
2. Tap to turn ON the VPN;
3. Wait about 10-15 seconds;

#### Expected result:
- Nothing strange happens.

#### Actual result:
- The “No internet connection. Try again!” red banner is displayed.

#### Notes:
- while the banner is being displayed, the VPN is still ON.

https://user-images.githubusercontent.com/15685960/105497416-79676a80-5cc7-11eb-9b3c-d294d65452cd.mp4

**Comment by bakulf** [comment]
This is not fixed.

**Comment by ValentinaPC** [comment]
Verified this on v. 2.1.0 (16163980) while using Android 10 and Android 11.
After 15-20 second after a fresh install of the app and turn ON, the red banner is still displayed.

https://user-images.githubusercontent.com/15685960/111962084-8a333180-8afa-11eb-9a6a-aa7696c34aa6.mp4

**Comment by ValentinaPC** [comment]
Verified as fixed on the last 2.1 VPN build while using Android 10.
The red banner is no longer displayed after a few seconds from turning the VPN on.

https://user-images.githubusercontent.com/15685960/112636204-6f87f200-8e45-11eb-8bf5-fdc41e9cf034.mp4
