### ISSUE TITLE
[foxfooding] Android app needs to be turned on when device is restarted

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/mozilla-vpn-client#4970]
**Describe the bug**
When turning on restarting the device, Mozilla VPN needs to be manually turned on, increasing the chance that a user forgets to do so (such as after an Android update).

**VPN version:**
2.11.0

**Affected Platforms:**
Android

**Steps to reproduce:**
With Mozilla VPN turned on, restart the device.
Open app

**Expected result:**
VPN is on

**Actual result:**
VPN is off

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3300)

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

dupe 😀 - it's in progress for 2.12
