### ISSUE TITLE
Replace "WIP" image with permanent SVG.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#50]
We need an SVG to replace the "WIP" in the right-hand panel below. 
![](https://user-images.githubusercontent.com/22355127/95092740-9d3d7b00-06ed-11eb-8cb5-4f35d7bb7a49.png)

![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/f8b554a2-a68f-476e-8e41-2c8df759a576)

![WIP SVG.svg](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/1d33e578-4c39-43e9-a6f8-4299ac05fba5)

* [:art: VPN WIP replacement image - Figma](https://www.figma.com/file/EN0R88zGif4SBj2tvpToJ6/Mac?node-id=0%3A1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-458)

**Comment by ValentinaPC** [comment]
Verified as fixed on VPN version 2.202011162054 , while using Linux Ubuntu 20.04.
The WIP image was replaced with a specific one.
![Screenshot from 2020-11-17 14-14-56](https://user-images.githubusercontent.com/15685960/99389295-8048ba00-28df-11eb-8775-df693dcec90e.png)
