### ISSUE TITLE
Stop using a clone of the official wireguard-apple repo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#5061]
We are currently using a copy of wireguard-apple because we want to use an extra commit.
This is bad for several reasons:

* we are out-of-sync with the official repo
* we can forget to update it
* we are using non-tested commits - probably there is a good reason why that PR was not merged yet.

Note: maybe next time we can apply the commit instead of forking the entire repo.

This bug is about removing that repo and go back to the official wireguard-apple one asap.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3392)
┆Reporter: Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

This is blocked on Wireguard updating their library. A PR like this one ( https://github.com/WireGuard/wireguard-apple/pull/17 ) must be accepted. (Of course, their GH is just a mirror of their official repo ( https://git.zx2c4.com/wireguard-apple ), so it’s unlikely that exact PR will be accepted.)

I’m setting a reminder to check in a month to see if the library has been updated.

For what it’s worth, at least two other VPN clients (and likely more) are running a fork with a similar change to ours.

**Comment by protonjohn** [comment]
I reached out to the maintainer at his personal email address on Nov 16 and unfortunately still haven't received a response. It may be worth considering wireguard-apple abandonware at this point.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Matt Cleinman Santiago Andrigo assume we roll this over to 2.14?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Andrea Marchesini Was there any update on this from your email?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Santiago Andrigo none yet.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Betty Fleming correct. No rush for this issue.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Removed the 2.13 fixVersion and the January sprint (until it’s officially added). Is Blocked the right status, though?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Any updates on this Andrea Marchesini ?

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

This is unblocked, can be added to next sprint.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

* As per https://gs.statcounter.com/ios-version-market-share/ ( https://gs.statcounter.com/ios-version-market-share/|smart-link ) , as of February 2023, 4.39% of users are using older versions than 13, and 10.83% of users are using older versions than 15. 
  * Looking at our actual clients, in the VPN Clients Seen dashboard, 1.57% of our iOS userbase is using an iOS version older than 15. Fun fact: 0.37% seems to be using it on iOS 12.5, which is not supported right now either.

The latter datapoint tells me that we are probably fine updating to a min version of iOS 15. It seems as though we are fine staying where we are at this point, but I’m just signaling that I’m OK pulling the plug on iOS v13 and v14 if this will make the vast majority of our users have a potentially more reliable / safe / performant Wireguard module.

Thoughts?

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Good to know, thanks. 

If we get some improved/smoothed functionality by cutting off those old users, I’m 100% in for that tradeoff. So far though, the only changes made to wireguard-apple after bumping the minimum version was changing the copyright date in files and bumping the version number. So I recommend waiting until there is something we get in return for cutting off those users. (Also if we can hold off for 6 months, even more users will be on newer iOS versions as iOS 17 and new iPhones will get released.)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Great to know, thanks Matt!
