### ISSUE TITLE
Client hang

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#5078]
**Describe the bug**
Client hangs on Android every time fter reopening, needing force quit after which VPN is disabled.

**VPN version:**
  
16679290

**Affected Platforms:**
 Android,

**Prerequisites:**
 Have client open
**Steps to reproduce:**
   Switch apps, reopen

**Expected result:**
  

**Actual result:**
  Hangs, Android asks to wait or force kill

**Additional notes:**
 
[github-mozillavpn-hang.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10115571/github-mozillavpn-hang.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3399)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Please reopen this ticket if you can still reproduce

**Comment by marcel263** [comment]
It is reproducible still. Start the app, then change location. Background the app. Reopen app, screen is frozen. Need force quit. v 2.20.0
