### ISSUE TITLE
Let's add the VersionCode or CommitID to the info page. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#511]
Since we now have several android builds with 2.0.3 flying around it's kinda hard to check if we're testing the right build.

**Comment by bakulf** [comment]
Yeah. I agree. What about if we show 2.0.3 (buildID) ?

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN Windows build.
The build ID is listed after the version number in the About us screen.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/110455239-dc269100-80d0-11eb-8274-989c0a02defe.png)
