### ISSUE TITLE
Issues with WASM simulator not responding to click, asking for email on release branch

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#5120]
CC @bakulf 

## Main branch

https://mozilla-mobile.github.io/mozilla-vpn-client/?branch=main
It's not working anymore, it doesn't seem to take clicks, and the menu on the right doesn't change view

## Release branch

https://mozilla-mobile.github.io/mozilla-vpn-client/?branch=releases%2F2.12.0

It goes past the first screen, but then requires an email to proceed. Switching view creates what looks like a list of errors in the sidebar

```
Existing account: wasm@wasm.wasm - Password: wasm
Blocked account: blocked@wasm.wasm
Invalid email address: invalid@wasm.wasm
Already existing address in creation: dup@wasm.wasm
Unusable email: unusable@wasm.wasm
Type not supported address: type@wasm.wasm
Too many requests: toomany@wasm.wasm
Unknown account: unknown@wasm.wasm
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3433)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Adding the December sprint to this ticket.

**Comment by flodolo** [comment]
Why was this closed? The problem is still there.
