### ISSUE TITLE
Windows icons

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#513]
We need the windows icons. I just converted logo-dock.png and logo-dock-beta.png to ico files, in 16, 32 and 256 pixel sizes:

https://github.com/mozilla-mobile/mozilla-vpn-client/blob/windows/src/ui/resources/logo-beta.ico
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/windows/src/ui/resources/logo.ico

Please check if this is right or something different needs to be done.

**Comment by lesleyjanenorton** [comment]
These look great!

**Comment by ValentinaPC** [comment]
Verified that the VPN app icon is displayed in the taskbar, tray menu, control panel or shortcut, on the latest VPN build (2.0.3) using Windows 10 x64.
Attaching postfix screenshot.
![icons](https://user-images.githubusercontent.com/15685960/106725152-b7db1e80-6611-11eb-90ae-89f0ab819b28.png)
