### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sritheturbocoder** [mozilla-mobile/mozilla-vpn-client#517]
**Tried to build source in Ubuntu 20.01.1 and get a bunch of compilation error :**

In file included from apppermission.h:11,
                 from apppermission.cpp:5:
applistprovider.h:14:38: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   14 |   Q_DISABLE_COPY_MOVE(AppListProvider)
      |                                      ^
applistprovider.h:14:38: error: expected ‘;’ at end of member declaration
   14 |   Q_DISABLE_COPY_MOVE(AppListProvider)
      |                                      ^
      |                                       ;
applistprovider.h:14:23: error: cannot declare parameter to be of abstract type ‘AppListProvider’
   14 |   Q_DISABLE_COPY_MOVE(AppListProvider)
      |                       ^~~~~~~~~~~~~~~
applistprovider.h:12:7: note:   because the following virtual functions are pure within ‘AppListProvider’:
   12 | class AppListProvider : public QObject {
      |       ^~~~~~~~~~~~~~~
applistprovider.h:23:16: note: 	‘virtual void AppListProvider::getApplicationList()’
   23 |   virtual void getApplicationList() = 0;
      |                ^~~~~~~~~~~~~~~~~~
In file included from apppermission.cpp:5:
apppermission.h:15:36: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   15 |   Q_DISABLE_COPY_MOVE(AppPermission)
      |                                    ^
apppermission.h:15:36: error: expected ‘;’ at end of member declaration
   15 |   Q_DISABLE_COPY_MOVE(AppPermission)
      |                                    ^
      |                                     ;
In file included from mozillavpn.h:8,
                 from apppermission.cpp:9:
captiveportal/captiveportal.h:20:36: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   20 |   Q_DISABLE_COPY_MOVE(CaptivePortal)
      |                                    ^
captiveportal/captiveportal.h:20:36: error: expected ‘;’ at end of member declaration
   20 |   Q_DISABLE_COPY_MOVE(CaptivePortal)
      |                                    ^
      |                                     ;
In file included from mozillavpn.h:9,
                 from apppermission.cpp:9:
captiveportal/captiveportaldetection.h:13:45: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   13 |   Q_DISABLE_COPY_MOVE(CaptivePortalDetection)
      |                                             ^
captiveportal/captiveportaldetection.h:13:45: error: expected ‘;’ at end of member declaration
   13 |   Q_DISABLE_COPY_MOVE(CaptivePortalDetection)
      |                                             ^
      |                                              ;
In file included from mozillavpn.h:10,
                 from apppermission.cpp:9:
closeeventhandler.h:15:40: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   15 |   Q_DISABLE_COPY_MOVE(CloseEventHandler)
      |                                        ^
closeeventhandler.h:15:40: error: expected ‘;’ at end of member declaration
   15 |   Q_DISABLE_COPY_MOVE(CloseEventHandler)
      |                                        ^
      |                                         ;
In file included from mozillavpn.h:11,
                 from apppermission.cpp:9:
connectiondataholder.h:25:43: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   25 |   Q_DISABLE_COPY_MOVE(ConnectionDataHolder)
      |                                           ^
connectiondataholder.h:25:43: error: expected ‘;’ at end of member declaration
   25 |   Q_DISABLE_COPY_MOVE(ConnectionDataHolder)
      |                                           ^
      |                                            ;
In file included from mozillavpn.h:12,
                 from apppermission.cpp:9:
connectionhealth.h:27:39: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   27 |   Q_DISABLE_COPY_MOVE(ConnectionHealth)
      |                                       ^
connectionhealth.h:27:39: error: expected ‘;’ at end of member declaration
   27 |   Q_DISABLE_COPY_MOVE(ConnectionHealth)
      |                                       ^
      |                                        ;
In file included from controller.h:9,
                 from mozillavpn.h:13,
                 from apppermission.cpp:9:
connectioncheck.h:18:38: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   18 |   Q_DISABLE_COPY_MOVE(ConnectionCheck)
      |                                      ^
connectioncheck.h:18:38: error: expected ‘;’ at end of member declaration
   18 |   Q_DISABLE_COPY_MOVE(ConnectionCheck)
      |                                      ^
      |                                       ;
In file included from mozillavpn.h:13,
                 from apppermission.cpp:9:
controller.h:25:33: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   25 |   Q_DISABLE_COPY_MOVE(Controller)
      |                                 ^
controller.h:25:33: error: expected ‘;’ at end of member declaration
   25 |   Q_DISABLE_COPY_MOVE(Controller)
      |                                 ^
      |                                  ;
In file included from mozillavpn.h:15,
                 from apppermission.cpp:9:
models/devicemodel.h:15:34: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   15 |   Q_DISABLE_COPY_MOVE(DeviceModel)
      |                                  ^
models/devicemodel.h:15:34: error: expected ‘;’ at end of member declaration
   15 |   Q_DISABLE_COPY_MOVE(DeviceModel)
      |                                  ^
      |                                   ;
In file included from mozillavpn.h:16,
                 from apppermission.cpp:9:
models/helpmodel.h:12:32: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   12 |   Q_DISABLE_COPY_MOVE(HelpModel)
      |                                ^
models/helpmodel.h:12:32: error: expected ‘;’ at end of member declaration
   12 |   Q_DISABLE_COPY_MOVE(HelpModel)
      |                                ^
      |                                 ;
In file included from mozillavpn.h:17,
                 from apppermission.cpp:9:
models/keys.h:12:27: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   12 |   Q_DISABLE_COPY_MOVE(Keys)
      |                           ^
models/keys.h:12:27: error: expected ‘;’ at end of member declaration
   12 |   Q_DISABLE_COPY_MOVE(Keys)
      |                           ^
      |                            ;
In file included from mozillavpn.h:18,
                 from apppermission.cpp:9:
models/servercountrymodel.h:18:41: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   18 |   Q_DISABLE_COPY_MOVE(ServerCountryModel)
      |                                         ^
models/servercountrymodel.h:18:41: error: expected ‘;’ at end of member declaration
   18 |   Q_DISABLE_COPY_MOVE(ServerCountryModel)
      |                                         ^
      |                                          ;
In file included from mozillavpn.h:19,
                 from apppermission.cpp:9:
models/serverdata.h:17:33: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   17 |   Q_DISABLE_COPY_MOVE(ServerData);
      |                                 ^
In file included from mozillavpn.h:20,
                 from apppermission.cpp:9:
models/user.h:16:27: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   16 |   Q_DISABLE_COPY_MOVE(User)
      |                           ^
models/user.h:16:27: error: expected ‘;’ at end of member declaration
   16 |   Q_DISABLE_COPY_MOVE(User)
      |                           ^
      |                            ;
In file included from mozillavpn.h:21,
                 from apppermission.cpp:9:
releasemonitor.h:13:37: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   13 |   Q_DISABLE_COPY_MOVE(ReleaseMonitor)
      |                                     ^
releasemonitor.h:13:37: error: expected ‘;’ at end of member declaration
   13 |   Q_DISABLE_COPY_MOVE(ReleaseMonitor)
      |                                     ^
      |                                      ;
In file included from mozillavpn.h:22,
                 from apppermission.cpp:9:
statusicon.h:15:33: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   15 |   Q_DISABLE_COPY_MOVE(StatusIcon)
      |                                 ^
statusicon.h:15:33: error: expected ‘;’ at end of member declaration
   15 |   Q_DISABLE_COPY_MOVE(StatusIcon)
      |                                 ^
      |                                  ;
In file included from apppermission.cpp:9:
mozillavpn.h:38:33: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   38 |   Q_DISABLE_COPY_MOVE(MozillaVPN)
      |                                 ^
mozillavpn.h:38:33: error: expected ‘;’ at end of member declaration
   38 |   Q_DISABLE_COPY_MOVE(MozillaVPN)
      |                                 ^
      |                                  ;
In file included from apppermission.cpp:12:
settingsholder.h:13:37: error: ISO C++ forbids declaration of ‘Q_DISABLE_COPY_MOVE’ with no type [-fpermissive]
   13 |   Q_DISABLE_COPY_MOVE(SettingsHolder)
      |                                     ^
settingsholder.h:13:37: error: expected ‘;’ at end of member declaration
   13 |   Q_DISABLE_COPY_MOVE(SettingsHolder)
      |                                     ^
      |                                      ;
make: *** [Makefile:1620: .obj/apppermission.o] Error 1

**Comment by bakulf** [comment]
@sritheturbocoder,  what version of QT and g++ (Clang) are you using?

**Comment by bakulf** [comment]
QT should be 5.15 or higher (qt6 support is not completed yet)
For the compiler, I use: clang-9 or 10.

**Comment by sritheturbocoder** [comment]
With QT 5.15 it compiles successfully
