### ISSUE TITLE
Provide a mechanism to alert customers of a service interruption

### ISSUE THREAD

**Issue by chrismore** [mozilla-mobile/mozilla-vpn-client#518]
Here is an idea that we could consider if we can do it that doesn't compromise the privacy of our customers and doesn't add a substantial network load.

Idea: 

Currently within the VPN clients, we have a dialog box that opens at the top of the app when there is an available update, which is good, but there is another type of alert that would be helpful for customers. For example, if there is an outage or service interruption and we want to tell customers about it, we don't currently have a method to communicate this to the VPN user.

We could have the clients regularly check (privately and securely) if there is a service issue via an API call. If there is an outage, the API call would return true a link to a page to learn more about the issue. The page could be a service status page where we would share the estimated time of resolution. Without this alert ability, customers would have to manually go to our website, check out Twitter, or file a support request to see what is happening.

**Comment by bakulf** [comment]
This is not implemented
