### ISSUE TITLE
Windows installer needs to stop the execution of the app if running

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#523]

**Comment by bakulf** [comment]
This is actually done. The problem is that, if the version matches, the installer does the wrong thing: it doesn't stop and it doesn't overwrite the binary. This bug can be closed.

**Comment by ValentinaPC** [comment]
Verified this as fixed on Windows 10 while installing an old version of the VPN (v 1.2) and then tried to install the last cross-plat build that I have (2.0.3) and at installation the installer asked me to close the VPN app to continue. 
Postfix screenshot below.
![image (3)](https://user-images.githubusercontent.com/15685960/106724496-f45a4a80-6610-11eb-8dda-1a4457e05645.png)
