### ISSUE TITLE
Backfill APKs on previous releases

### ISSUE THREAD

**Issue by dmp1ce** [mozilla-mobile/mozilla-vpn-client#5246]
**Describe the bug**
APK downloads only appear for some releases on Github. Why aren't APKs provided for all releases?

**Expected result:**
APKs would be provided for each release.

**Actual result:**
Only some releases have APK downloads.

**Additional notes:**
  <Optional: Any Screenshots, Videos, Logs>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3509)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Incidentally, in conversations with Design to deliver on improvements to the VPN Download page (https://mozilla-hub.atlassian.net/browse/VPN-3322 ( https://mozilla-hub.atlassian.net/browse/VPN-3322|smart-link )), we discussed solving for users who want to have old versions of the app (https://mozilla-hub.atlassian.net/browse/VPN-3296 ( https://mozilla-hub.atlassian.net/browse/VPN-3296|smart-link )) and decided that the most straightforward way would be to link to the GitHub releases tab. I’ve added this step to our release process.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Santiago Andrigo - We have this SRE ticket to backfill all releases onto archive https://mozilla-hub.atlassian.net/browse/SVCSE-506 ( https://mozilla-hub.atlassian.net/browse/SVCSE-506|smart-link )

And given that in https://mozilla-hub.atlassian.net/browse/VPN-3526 ( https://mozilla-hub.atlassian.net/browse/VPN-3526|smart-link ) it’s asked to have new android releases also on archive and linked to a release, do we still need to upload all to gh aswell?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Correct, we can cancel this ticket in favor of the current plan.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Rather than outright publish in GitHub, we will publish in Mozilla Archives and deeplink to it from the "release notes" in GitHub Release tab (for each version).
