### ISSUE TITLE
Australia listed as a region for cities outside of it

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#531]
On Android, while testing the last version, I've noticed some incorrect notifications, as follows:
- selecting Auckland (New Zealand) -> the notification lists Australia, Auckland
- selecting Zurich (Switzerland) -> the notification lists Australia, Zurich

Did not see happening for other region, except Australia.
Unfortunately I do not have, yet, steps to reproduce the issue.

![image](https://user-images.githubusercontent.com/15685960/106564902-93f6da80-6536-11eb-854c-5464e87dccc5.png)

**Comment by chrismore** [comment]
We also got this from a customer:

![image](https://user-images.githubusercontent.com/751491/106485180-f340e600-6475-11eb-92d4-ac924344e34d.png)

on Android 2.0.3

**Comment by bakulf** [comment]
This looks like a migration bug. Here: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/platforms/android/androiddatamigration.cpp#L123
We take the first name always.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 builds across platforms.
Australia does no longer have issues.
