### ISSUE TITLE
[prod] Unexpected error at CI screen access

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#5326]
**Important details:**

* Not reproducing for Stage server

**Mozilla VPN affected versions:**

* 2.13.0 (2.202212260751);

**Platform tested:**

* Windows 10;
* Mac OS 13;

**Prerequisites:**

* Have Mozilla VPN app installed and open;
* Have an Fx account with subscription for Mozilla VPN;
* Be logged on Production server;

**Steps to reproduce:**

1. Turn the VPN ON;
1. Access CI screen;
1. Observe the screen;

**Expected results:**

* Connection information is displayed.

**Actual results:**

* Unexpected error screen is displayed.

**Notes:**

* Reproducing for both single and multi hop;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3561)
┆Reporter: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

As described, this seems to regress an entire user journey back, so marking as High for the time being.

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Putting component as “front end”, but if front end folks look into it and decide it’s connectivity, pls update.

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Florian Zia any thoughts as to what could be happening here?

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

From an initial inspection, doesn’t appear to be front end related, but an issue with the dns lookup

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Currently only the dev server (https://dev.vpn-network-benchmark.nonprod.webservices.mozgcp.net ( https://dev.vpn-network-benchmark.nonprod.webservices.mozgcp.net )) for benchmark upload is available. The staging server for the benchmark upload is throwing an SSL related error and the prod server (https://benchmark.vpn.mozilla.org ( https://benchmark.vpn.mozilla.org/upload )) is not deployed, yet. I’d expect that issue to be resolved next week when SRE is back from PTO.

Error 443 for stage.vpn-network-benchmark.nonprod.webservices.mozgcp.net/upload ( http://stage.vpn-network-benchmark.nonprod.webservices.mozgcp.net ):

{quote}LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to stage.vpn-network-benchmark.nonprod.webservices.mozgcp.net:443 ( http://stage.vpn-network-benchmark.nonprod.webservices.mozgcp.net:443 ){quote}

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Florian Zia Based on you last comment, shouldn't this also happen in Stage (because it does not)? or I am missing something? Thank you!

**Comment by jbuck** [comment]
The stage & prod benchmark servers should be working as of now

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is currently also happening on Stage, using the last build from release branch (2.13.0 (2.202301140424)) across platforms.

**Comment by data-sync-user** [comment]
➤ Florian Zia commented:

Valentina Virlics I just pushed the changes to fix this from main to the 2.13 release branch.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed while using the last build from release branch - 2.13.0 (2.202301161600) - across platforms.

The CI screen is accessible on both stage and prod and works as expected.
