### ISSUE TITLE
Debian unstable

### ISSUE THREAD

**Issue by dtl131** [mozilla-mobile/mozilla-vpn-client#5344]
$ gdb mozillavpn 
GNU gdb (Debian 12.1-4) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mozillavpn...
warning: Unsupported auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/bin/mozillavpn.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /usr/bin/mozillavpn 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff17ff6c0 (LWP 11933)]
[New Thread 0x7fffc57ff6c0 (LWP 11934)]
[New Thread 0x7fffc4ffe6c0 (LWP 11935)]
[New Thread 0x7fffbf7fe6c0 (LWP 11937)]
[New Thread 0x7fffbffff6c0 (LWP 11936)]
[New Thread 0x7fffbeffd6c0 (LWP 11938)]
[New Thread 0x7fffbdfff6c0 (LWP 11939)]
[New Thread 0x7fffbd7fe6c0 (LWP 11940)]
[New Thread 0x7fffbcffd6c0 (LWP 11941)]
[New Thread 0x7fffa3fff6c0 (LWP 11942)]
[New Thread 0x7fffa37fe6c0 (LWP 11943)]
[New Thread 0x7fffa2ffd6c0 (LWP 11944)]
[New Thread 0x7fffbc3bc6c0 (LWP 11945)]
[New Thread 0x7fffa27fc6c0 (LWP 11946)]
[New Thread 0x7fffa25fb6c0 (LWP 11947)]
[New Thread 0x7fffa23fa6c0 (LWP 11948)]
[New Thread 0x7fffa1bf96c0 (LWP 11949)]
[New Thread 0x7fffa19f86c0 (LWP 11950)]
[Thread 0x7fffa1bf96c0 (LWP 11949) exited]
[New Thread 0x7fffa1bf96c0 (LWP 11951)]
[Thread 0x7fffa19f86c0 (LWP 11950) exited]
[Thread 0x7fffa27fc6c0 (LWP 11946) exited]
[New Thread 0x7fffa13ff6c0 (LWP 11952)]
[New Thread 0x7fffa0bfe6c0 (LWP 11953)]
[New Thread 0x7fff7bfff6c0 (LWP 11954)]
[New Thread 0x7fff7b7fe6c0 (LWP 11955)]
[New Thread 0x7fff7affd6c0 (LWP 11956)]

Thread 1 "mozillavpn" received signal SIGSEGV, Segmentation fault.
0x0000555555822660 in QmlEngineHolder::window() const ()
(gdb) backtrace
#0  0x0000555555822660 in QmlEngineHolder::window() const ()
#1  0x00005555558451b6 in SystemTrayNotificationHandler::initialize() ()
#2  0x0000555555701ad0 in LinuxSystemTrayNotificationHandler::initialize() ()
#3  0x0000555555818a4a in NotificationHandler::create(QObject*) ()
#4  0x00005555557ad361 in CommandUI::run(QList<QString>&)::{lambda()#1}::operator()() const ()
#5  0x00005555557a118e in Command::runQmlApp(std::function<int ()>&&) ()
#6  0x00005555557ab35b in CommandUI::run(QList<QString>&) ()
#7  0x00005555557a2dc1 in CommandLineParser::parse(int, char**) ()
#8  0x00005555556afc55 in main ()
#9  0x00007ffff504618a in __libc_start_call_main (main=main@entry=0x5555556afc30 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffde18) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff5046245 in __libc_start_main_impl (main=0x5555556afc30 <main>, argc=1, argv=0x7fffffffde18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde08) at ../csu/libc-start.c:381
#11 0x00005555556bc8c1 in _start ()
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) n
Program not restarted.
(gdb) backtrace
#0  0x0000555555822660 in QmlEngineHolder::window() const ()
#1  0x00005555558451b6 in SystemTrayNotificationHandler::initialize() ()
#2  0x0000555555701ad0 in LinuxSystemTrayNotificationHandler::initialize() ()
#3  0x0000555555818a4a in NotificationHandler::create(QObject*) ()
#4  0x00005555557ad361 in CommandUI::run(QList<QString>&)::{lambda()#1}::operator()() const ()
#5  0x00005555557a118e in Command::runQmlApp(std::function<int ()>&&) ()
#6  0x00005555557ab35b in CommandUI::run(QList<QString>&) ()
#7  0x00005555557a2dc1 in CommandLineParser::parse(int, char**) ()
#8  0x00005555556afc55 in main ()
#9  0x00007ffff504618a in __libc_start_call_main (main=main@entry=0x5555556afc30 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffde18) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff5046245 in __libc_start_main_impl (main=0x5555556afc30 <main>, argc=1, argv=0x7fffffffde18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde08) at ../csu/libc-start.c:381
#11 0x00005555556bc8c1 in _start ()
(gdb)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3583)

**Comment by dtl131** [comment]
Debian unstable has moved on to Qt 6.4, and I can now run mozillavpn with a debug build (Release build fails, but that's another bug report). I guess the problem was upstream in Qt6.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

.
