### ISSUE TITLE
build failure on Linux: failed to load source for dependency `glean`

### ISSUE THREAD

**Issue by RBKreckel** [mozilla-mobile/mozilla-vpn-client#5354]
Currently, mozilla-vpn-client fails to build on Linux from the git repository (last commit is 230bb22c) and from the 2.12.0 release tarball:

error: failed to get `glean` as a dependency of package `vpnglean v0.1.0 (/home/rbk/contrib/mozillavpn-2.12.0/vpnglean)`

Caused by:
  failed to load source for dependency `glean`

Caused by:
  Unable to update /home/rbk/contrib/mozillavpn-2.12.0/3rdparty/glean/glean-core/rlb

Caused by:
  failed to read `/home/rbk/contrib/mozillavpn-2.12.0/3rdparty/glean/glean-core/rlb/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

Indeed, 3rdparty/glean/ remained empty.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3592)

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

This looks like the glean submodule was not fetched. git submodule update should fix it. I am not sure if this is an issue with our build system though or just local issue for OP. cc Owen Kirby

**Comment by RBKreckel** [comment]
> This looks like the glean submodule was not fetched. git submodule update should fix it.

I was thinking that, too, but it doesn't. I just tried on a fresh git clone. Something seems to be missing.

**Comment by RBKreckel** [comment]
Is this related to #5119?

**Comment by RBKreckel** [comment]
Ah, one has to manually git submodule update --init first after downloading the sources. There seems to be nothing which does this automatically.

And yes, this should also be the problem behind #5119.

Dear Mozilla developers: What is the proper fix so that we can keep building distro packages etc?

**Comment by RBKreckel** [comment]
(I am saying that because this seems to have broken somewhen since 2.9.0.)

**Comment by RBKreckel** [comment]
Also, downloading the one of the tagged download links from github (the latest one is https://github.com/mozilla-mobile/mozilla-vpn-client/archive/refs/tags/v2.12.0.tar.gz) does not work, because git submodule update --init fails with
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
After all, the packages don't contain the .git directory.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

This would be resolved by the creation of a post-release action to generate a tarball with all the submodules and vendored components in place. We are going to track that work in VPN-5778

This JIRA task should be mirrored onto github at https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8412
