### ISSUE TITLE
Incorrect update restriction message

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#537]
#### Affected versions:
- 2.0.3 build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;
- Be in a country where VPN is not available;
- Have a previous version of VPN installed;

#### Steps to reproduce:
1. Open the VPN app;
2. Wait to have the update banner be displayed;
3. Click on the “Update now” link;
4. Observe the red banner from the bottom of the screen;

#### Expected result:
- The red banner mentions that you should be in the countries where VPN is available to be able to update it.

#### Actual result:
- The banner mentions that you must be in the US to be able to update the VPN.

#### Notes:
- I’ve used another VPN to trigger that I am in Canada (also tried Malaysia), and the banner was no longer displayed and the update was made, so I am inclined to say that is only a string thing.

![image](https://user-images.githubusercontent.com/15685960/106713427-1fd63880-6603-11eb-87e9-773534b46493.png)

**Comment by bakulf** [comment]
@jess-cook03 what do you think the string should be here?

**Comment by bakulf** [comment]
This message is from v1.0 and not v2. We need to implement the same message, so yes, let's keep this issue open.

**Comment by jess-cook03** [comment]
@bakulf
If a user is outside of the US -- can we not show the update banner at all?
Only show updates available to those that are able to update?

I would say if we need to keep the updates banner then it should maybe say:
'New features are available for countries where our VPN is available."

Or the error could read -- 'Updates are only available for users located in countries where our VPN is available'

**Comment by bakulf** [comment]
Probably that error message is too big to stay in 1 single row. On slack, @jess-cook03  suggested: "Updates are not available where you are located".

**Comment by ValentinaPC** [comment]
The update blue banner is no longer displayed if the users are not signed into VPN client. The verification was made using the Web Socket.
@bakulf Is this intended?
Attaching logs;
[mozillavpn-2021-7-27.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6885182/mozillavpn-2021-7-27.txt)
