### ISSUE TITLE
Improve notification while VPN is turned off and swipe-killed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#548]
#### Affected versions:
- v. 2.0.3 last build; 

#### Affected Platforms:
- Android 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Sign in (but not turn on the VPN);
3. Swipe-kill the app;
4. Open the VPN;
5. Observe the notification message;

#### Expected result:
- A more clear message regarding VPN status is described.

#### Actual result:
- “Mozilla VPN is running in the background” message is displayed;

#### Notes:
- The message can be confusing as the VPN is not ON.
![image](https://user-images.githubusercontent.com/15685960/107023693-a891d780-67af-11eb-951f-3a567735deb2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-100)

**Comment by strseb** [comment]
@jess-cook03 Do you maybe have any idea what we could put there?
The old app just showed an empty notification for that case (wierd). 
Maybe something like 
"Ready to Connect"
"VPN Service is running" 
"Idle" (?)

**Comment by jess-cook03** [comment]
@strseb @bakulf 
Taking a look at this now.
Maybe we can do something like:
'Your app is running, but VPN is off.'
**'Ready for you to connect'** --- I liked that idea Basti!

**Comment by ValentinaPC** [comment]
Verified as fixed on Android  10 using VPN version 2.0.4.
While the service is running in the background, but the VPN is OFF, a specific message is displayed.
Postfix screenshot below.
![Screenshot_20210211-131240](https://user-images.githubusercontent.com/15685960/107629654-1b48fa00-6c6b-11eb-809b-b84b88c60787.png)

**Comment by ValentinaPC** [comment]
After following the initial STRs: no message is displayed.

> * Open VPN app;
> 
> * Sign in (but not turn on the VPN);
> 
> * Swipe-kill the app;
> 
> * Open the VPN;
> 
> * Observe the notification message;

Not sure what happen in between there an now.
The "ready to connect" notification is displayed if, at the above STRs we add: turn ON ->swipe kill -> open-> turn off -> swipe kill -> open app.
Reopening this issue.

**Comment by ValentinaPC** [comment]
Verified this on Android 10 (2.3.0 - 16209050) and I was able to reproduce it as follows:
- uninstall the VPN client you have;
- re install the client
- sign in (do not turn it on)
- check the notification

Reproducibility rate: each time.

**Comment by jess-cook03** [comment]
@ValentinaPC @strseb 
This looks to be resolved -- is that correct?
If so, can we close this issue?

**Comment by ValentinaPC** [comment]
@strseb @jess-cook03 The "Mozilla VPN is running in Background" confusing notification is still displayed for VPN OFF, while following the [above](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/548#issuecomment-841058364) steps.
