### ISSUE TITLE
Glean uses rust functions depreciated in chrono 0.4.23

### ISSUE THREAD

**Issue by hungrymonkey** [mozilla-mobile/mozilla-vpn-client#5499]
**Describe the bug**
Mozilla fails to build on Opensuse tumbleweed. Upstream Chrono rust package has depreciated a few functions.

https://docs.rs/chrono/latest/chrono/struct.Date.html

**VPN version:**
[main-1/9/2023](https://github.com/mozilla-mobile/mozilla-vpn-client/commit/b338c83e5e3a96de02d1eb0ac34096e00e654f4e)

**Affected Platforms:**

 lsb_release  -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20230108
Codename:	n/a

rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12) (built from a source tarball)

chrono = "0.4.23"                   # Date and time library for Rust

**Prerequisites:**
  <Optional: Any special steps taken not related to the app to trigger the bug>

**Steps to reproduce:**
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr
cmake --build build -j$(nproc)

**Expected result:**
The build succeed without compile error.

**Actual result:**
The build fails

**Additional notes:**

```
warning: use of deprecated associated function `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
  --> /home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/src/metrics/datetime.rs:99:23
   |
99 |         let date = dt.date();
   |                       ^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `chrono::FixedOffset::east`: use `east_opt()` instead
   --> /home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/src/metrics/datetime.rs:162:49
    |
162 |                

 let datetime_obj = FixedOffset::east(dt.offset_seconds)
    |                                                 ^^^^

warning: use of deprecated associated function `chrono::TimeZone::ymd_opt`: use `with_ymd_and_hms()` instead
   --> /home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/src/metrics/datetime.rs:163:22
    |
163 |                     .ymd_opt(dt.year, dt.month, dt.day)
    |                      ^^^^^^^

warning: use of deprecated associated function `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
   --> /home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/src/metrics/datetime.rs:204:39
    |
204 |             TimeUnit::Nanosecond => d.date().and_hms_nano_opt(
    |                                       ^^^^

warning: use of deprecated associated function `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
   --> /home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/src/metrics/datetime.rs:216:19
    |
216 |                 d.date().and_hms_nano_opt(
```

[mozillavpn-buildlog.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10378828/mozillavpn-buildlog.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3722)

**Comment by hungrymonkey** [comment]
I guess somebody needs to figure out the issue with the build system


I checked Glean's cargo.lock and they hardcoded a working revision. They even rejected the 0.4.23 bump

https://github.com/mozilla/glean/pull/2265
https://github.com/mozilla/glean/blob/main/Cargo.lock
```
[[package]]
name = "chrono"
version = "0.4.19"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "670ad68c9088c2a963aaa298cb369688cf3f9465ce5e2d4ca10e6e0098a1ce73"
dependencies = [
 "libc",
 "num-integer",
 "num-traits",
 "serde",
 "time",
 "winapi",
]
```

**Comment by brizental** [comment]
Hey @hungrymonkey thank you for the bug report. The messages in the log provided are all warnings, how are they breaking the build? We are aware of these warnings as is the Glean team, the reason why they haven't updated and I think we shouldn't either is there is a regression in the newer version of chrono on iOS. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1780401

Would you mind providing your full build output?

**Comment by hungrymonkey** [comment]
@brizental  Either MozillaVPN or Glean team build file doesn't work properly because the new version of chrono is being downloaded. I am not familiar with rust cargo, but any build system should allow you to lock a particular package version.

I attached the full build log. Please tell me if you need to see any particular build flags.

[fullbuildlog.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10383262/fullbuildlog.txt)

**Comment by hungrymonkey** [comment]
```
   Compiling glean v52.0.0 (/home/doof/gitrepo/mozilla-vpn-client/3rdparty/glean/glean-core/rlb)
warning: `glean-core` (lib) generated 18 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 2m 13s
[ 11%] Built target vpnglean_bindings_builder
gmake: *** [Makefile:146: all] Error 2
````
Maybe I have been reading the build log improperly.

**Comment by hungrymonkey** [comment]
```
warning: `glean-core` (lib) generated 18 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
gmake[2]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
[ 13%] Built target vpnglean_bindings_builder
[ 13%] Linking CXX static library libglean.a
cd /home/doof/gitrepo/mozilla-vpn-client/build/glean && /usr/bin/cmake -P CMakeFiles/glean.dir/cmake_clean_target.cmake
cd /home/doof/gitrepo/mozilla-vpn-client/build/glean && /usr/bin/cmake -E cmake_link_script CMakeFiles/glean.dir/link.txt --verbose=1
/usr/bin/ar qc libglean.a CMakeFiles/glean.dir/glean_autogen/mocs_compilation.cpp.o CMakeFiles/glean.dir/glean.cpp.o CMakeFiles/glean.dir/glean_autogen/EWIEGA46WW/qrc_glean.cpp.o CMakeFiles/glean.dir/glean_autogen/3BMTVXIA4T/qrc_telemetry.cpp.o
/usr/bin/ranlib libglean.a
gmake[2]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
[ 13%] Built target glean
gmake[1]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
gmake: *** [Makefile:146: all] Error 2
```

**Comment by hungrymonkey** [comment]
I might close it because I was missing a dependency. rust-cbindgen

Its fetch a file now after a clean build.

**Comment by hungrymonkey** [comment]
```
cd /home/doof/gitrepo/mozilla-vpn-client/build/glean && /usr/bin/cmake -E cmake_link_script CMakeFiles/glean.dir/link.txt --verbose=1
/usr/bin/ar qc libglean.a CMakeFiles/glean.dir/glean_autogen/mocs_compilation.cpp.o CMakeFiles/glean.dir/glean.cpp.o CMakeFiles/glean.dir/glean_autogen/EWIEGA46WW/qrc_glean.cpp.o CMakeFiles/glean.dir/glean_autogen/3BMTVXIA4T/qrc_telemetry.cpp.o
/usr/bin/ranlib libglean.a
gmake[2]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
[ 11%] Built target glean
gmake[1]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
gmake: *** [Makefile:146: all] Error 2

```
I will  might need to make a new bug report after I figure out what is going on .

**Comment by mihirsamdarshi** [comment]
> ```
> cd /home/doof/gitrepo/mozilla-vpn-client/build/glean && /usr/bin/cmake -E cmake_link_script CMakeFiles/glean.dir/link.txt --verbose=1
> /usr/bin/ar qc libglean.a CMakeFiles/glean.dir/glean_autogen/mocs_compilation.cpp.o CMakeFiles/glean.dir/glean.cpp.o CMakeFiles/glean.dir/glean_autogen/EWIEGA46WW/qrc_glean.cpp.o CMakeFiles/glean.dir/glean_autogen/3BMTVXIA4T/qrc_telemetry.cpp.o
> /usr/bin/ranlib libglean.a
> gmake[2]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
> [ 11%] Built target glean
> gmake[1]: Leaving directory '/home/doof/gitrepo/mozilla-vpn-client/build'
> gmake: *** [Makefile:146: all] Error 2
> ```
> 
> 
>     
>   
> 
> I will  might need to make a new bug report after I figure out what is going on .

Did you ever figure this out? I haven't been able to
