### ISSUE TITLE
Show default avatar while real avatar is loading in Settings

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#552]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-102)

**Comment by bakulf** [comment]
This issue is important for wasm because FxA doesn't allow the loading of user avatar via javascript (CORS).

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/19 . Changing it back to Done.

Thank you.
