### ISSUE TITLE
Audit for any JCenter dependencies in App

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/mozilla-vpn-client#553]
JCenter is going away:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

The following is the plan for the A-C Android based projects Fenix/Focus/etc

> The official date is May 1st, but the timeline mentions some maintenance beginning April 12th, so let's assume it's gone in April more or less and move on asap.

> Some ideas:
> - Depend on Maven Central only and see where we are at. A large chunk of our dependencies should be available there. Now there's a high chance more libraries migrate to it. I'm not so sure about older versions of libraries, let's see.
> - Everything that isn't available in a reasonable place (we don't want to add random repositories) could be cached by us - either on maven.mozilla.org, or in repos directly too.
> https://github.com/mozilla-mobile/android-components/issues/9603

**Comment by strseb** [comment]
We got one as it seems 

```
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:
         project : > com.android.tools.build:gradle:4.0.0 > com.android.tools.build:builder:4.0.0 > com.android.tools:sdk-common:27.0.0

```

**Comment by bakulf** [comment]
@strseb can we close this issue?
