### ISSUE TITLE
Log view for IOS is broken

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#56]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-479)

**Comment by ValentinaPC** [comment]
Verified as fixed while using VPN v.2.202011201408 on iOS 14.2.
View Logs page is available on iOS device.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/99810022-cdc95f00-2b4b-11eb-8e23-6329c687f590.png)
