### ISSUE TITLE
ci: Switch to the `public_restricted` pullRequest policy

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#5608]
The PR policy is currently set to `collaborators` so we don't leak secrets into PRs opened by non-collaborators.

There's a relatively new policy (as of last September) called `public-restricted`. This would allow us to restrict tasks with secrets to only run on PRs opened by a collaborator, while still letting the "safe" tasks run on contributor PRs. This way, most CI would run automatically and we'd only need to open shadow PRs to run the sensitive tasks (or simply land without running them + backout if they break).

In order to make the switch over, some co-ordination will be needed.

1. Releng will need to land a patch to the [ci-configuration]() repo.
2. Around the same time we'll need to land a patch to the `main` branch which switches the [PR policy](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/.taskcluster.yml#L6) to `public_restricted`.
3. We'll also need to update the Taskgraph configuration to make sure we don't try to schedule these sensitive tasks on non-collaborator PRs (otherwise the Decision task will fail with scope errors).

It's probably most expedient if Releng handles all this work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3873)

**Comment by gabrielBusta** [comment]
1. https://phabricator.services.mozilla.com/D167047
2. https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5650
3. It seems we are only running builds and a taskgraph test on PRs
