### ISSUE TITLE
Changing the time/zone of the device affects the VPN connection time layout

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#561]
#### Affected Platforms:
- Windows 10 x64;
- Android 9.0;
- macOS 10.15.7;
- Ubuntu 20.10;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
 
#### Steps to reproduce:
1. Launch VPN app;
2. Turn VPN on;
3. Observe the time of connection;
4. Change the time/time zone on your device(e.g. one hour earlier);
5. Observe the time of connection again;
 
#### Expected result:
- Changing the time/time zone shouldn't affect the connection time.
 
#### Actual result:
- Changing the time/time zone affects connection time.
 
#### Notes: 
- Turning the VPN off and on again fixes the issue.
![image_2021_02_08T14_21_35_291Z](https://user-images.githubusercontent.com/15685960/107236124-10edec80-6a2e-11eb-90f7-4c70cb466c52.png)

**Comment by bakulf** [comment]
We should replace QDateTime with a QElapsedTimer.

**Comment by madalincm** [comment]
Verified the issue using Mozilla VPN 2.0.5 latest build on Windows 10 x64, macOS 10.15.7, Ubuntu 20.10 and Android 9.0. Changing the time and/or the time-zone no longer affects the timer of the VPN. Closing the issue as verified.
