### ISSUE TITLE
clean-up passing m_lastConfig around

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#566]
From #510 - "about passing m_lastConfig, we can remove it from run()/serverSwitch(), yes. Follow up?"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-106)

**Comment by oskirby** [comment]
This area of the code received a significant amount of refactoring as part of #1376 and I'm not sure that this is still necessary. The `m_lastConfig` variable got removed but it was replaced by a list of VPN connections, which still retain a copy of the configuration.
