### ISSUE TITLE
clean-up activate method

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#567]
Marking this as a questions as I think we just need to talk about this more.

I find myself confused by the logic of the activate method in `daemon/daemon.cpp`. Comments have been added that help, but is there a different structure or re-org, perhaps of related code too that helps keep this clean and easy to reason about state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-107)

**Comment by oskirby** [comment]
Much of this code was changed by #1376 so I'm going to close this unless some specific recomendations can be made.
