### ISSUE TITLE
Document QmlPath syntax on /docs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#5694]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3959)
┆Reporter: Beatriz Rizental Machado

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

There is a presentation on https://docs.google.com/presentation/d/14VDdWbK6Z4ToHsj3SqT1gHzXR2Hs2fGkN8pTWt8QJS8/edit?usp=sharing ( https://docs.google.com/presentation/d/14VDdWbK6Z4ToHsj3SqT1gHzXR2Hs2fGkN8pTWt8QJS8/edit?usp=sharing|smart-link ) , but that info should be on the Github docs.

**Comment by bakulf** [comment]
The documentation is here: https://mozilla-mobile.github.io/mozilla-vpn-client/docs/classQmlPath.html
Why do we need more? You want to include examples?

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Oh, ok. I didn’t realize it was already there. That is not easy to find if you don’t know where to look for though. I feel like the whole part where the syntax is described should be in the developer docs, not in-code.
