### ISSUE TITLE
Enable paste in password field

### ISSUE THREAD

**Issue by im7mortal** [mozilla-mobile/mozilla-vpn-client#5696]
**Describe the bug**
I am experiencing for years already problems with entering my password `TsXeXeqH3y6joYCh8HJAaZt9GygyWaAkRTk67v9E` . I use normally 1password. 
Just finished entering this password manually in the MozillaVPN android and I am crazy angry 😡😡😡 

**VPN version:**
All

**Affected Platforms:**
 All

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-3960)

**Comment by lesleyjanenorton** [comment]
Fix is coming in next update- sorry about the hassle!

**Comment by im7mortal** [comment]
Thank you!
