### ISSUE TITLE
User real IP is listed while VPN is ON

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#572]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Android 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Turn ON the VPN;
3. Select a location i.e Spain-> Madrid;
4. Go to ipinfo.io and check the location/IP listed;

#### Expected result:
- Location name and IP is displayed.

#### Actual result:
- My real IP is listed.

#### Notes:
- I am not able to reproduce on Android 9,11;
- I am able to reproduce with different browsers;
- I performed migration via Play Store by clicking “update now” blue banner (not sure if it matters);
 Attaching logs and video.
 https://user-images.githubusercontent.com/15685960/107536128-1bdd8400-6bca-11eb-8811-ca649363da83.mp4
[diMBVTfm.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/5959503/diMBVTfm.txt)

**Comment by chrismore** [comment]
Hmm. Interesting and something that will block this update. Thanks for the bug file @ValentinaPC.

@strseb can you reproduce this and investigate, because maybe this an Android 10 specific issue?

**Comment by strseb** [comment]
Can't reproduce. :( - I've been looking through the logs and we have an interesting case here: 
1. Our PingSendWorker is able to Ping the internal Mullvad Gateway. So we need to have a vpn connection to mullvad.
2. Also the vpn connection is open and registered with android, otherwise the lock in the topper right would not be shown. 
3. The apps do not seem to be using this. I would probably require a full system log to get more insights here.

**Comment by chrismore** [comment]
@ValentinaPC any more system logs you can provide @strseb ?

**Comment by strseb** [comment]
I've just tried with another android 10 Device ( some huawei) - works fine. Is this issue maybe resolvable with a reinstall?

**Comment by ValentinaPC** [comment]
I am no longer able to reproduce on my Android 10 device, but was able to reproduce it on my Android 6 device.
Might have something to do with how long the VPN was ON on each device (over 20 h). Will investigate further.

**Comment by ValentinaPC** [comment]
I was re-trying to reproduce the initial issue, and I was not able to do it anymore.
I had encountered another thing on Android 6 - the VPN is closed at swipe-kill - this too did not happen in the past.
Strange things are happening on Android.

**Comment by ValentinaPC** [comment]
I'll close this due to the fact that I am no longer able to reproduce this.
