### ISSUE TITLE
[Windows] Using the 2.12 version does not trigger the “Update available” modal

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#5721]
**Important details:** 

* on macOS the client is updated to 2.13; 

**Affected versions:**

* 2.13.0 (2.202301192156);

**Tested Platforms:**

* Windows 10/ 11;

**Prerequisites:**

* Have Mozilla VPN app installed and opened;

* Have a Fx account with an active subscription;

* Be signed in (Stage);

**Steps to reproduce:**

1. Go to Settings - About us and click the “Check for update” button;

**Expected result:**

* “Update available” modal is displayed;

**Actual result:**

* “You are up to date” modal is displayed;

**Notes:**

* See the attached video and logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3978)
┆Reporter: Bianca Hidecuti

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

In the log I see this:

[20.01.2023 16:54:04.149] Debug: (networking - Balrog) BalrogGo: Verification failed with error: Error parsing cert chain: failed to parse root certificate from chain: x509: invalid authority key identifier

We should check with releng what is going on. If the staging key has changed, we should update the code.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Then it sounds like a balrog issue as we had in 2.12. Owen Kirby Sebastian Streich do you think it’s possible?

**Comment by data-sync-user** [comment]
➤ Andrew Halberstadt commented:

I double checked the rule on the Balrog prod release-cdntest channel and it looks good afaict. As a reminder, older clients that are still pointing to Balrog stage are expected to receive no updates.. But I’m pretty sure 2.12 is supposed to be recent enough. The cert error Baku linked looks worrisome, but I don’t know what could have changed and it’s passed my eod.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Owen Kirby I think this is a known issue with 2.12 where golang was wrong with prod balrog validation. I think we can close this. Do you agree?

**Comment by data-sync-user** [comment]
➤ Andrew Halberstadt commented:

Does that mean that Windows 2.12 users are stranded?

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

So, this ought to have been addressed by PR #4968 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4968 ) which updated the golang compiler used in Taskcluster. However, it seems that in the chaos of the 2.11->2.12 release cycle this was never merged into the releases/2.12.0 branch. Presumeably this is because it was caught in post release after we had cut the 2.12 branch and we simply forgot.

This raises a few other questions:

  * I though we had also updated the balrog release channels, so why isn’t the 2.12 release checking balrog prod?
  * Do we need to prepare another 2.13 update message due to this bug.

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

It seems like the version in 2.11 was never updated to trigger the Update Now message, which is why this issue came about. main already has the 2.13 message update ( https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/addons/message_update_v2.13/manifest.json ) so this shouldn’t be an issue in this release. No further action is required.

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Fixed in 2.13/main via addons.

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

.

**Comment by ValentinaPC** [comment]
@Gela We checked the Addons RCs and did not encounter any new one that would include the Download message. Are we missing something?
Thank you!

**Comment by data-sync-user** [comment]
➤ Andrew Halberstadt commented:

{quote}I though we had also updated the balrog release channels, so why isn’t the 2.12 release checking balrog prod?{quote}

It is, but the problem is that it errors out when making the request. We only test updating to the new version and not updating from it, so this went uncaught again.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

We cancelled this bug because it’s a bug with 2.12. Because 2.12 is out the door we believe we cannot reproduce. 

Andrew Halberstadt you wrote “We only test updating to the new version and not updating from it, so this went uncaught again.” We need to test FROM the current version (2.13). Typically we do this by testing from 2.13 to 2.13 (by using a force function in the inspector).

Valentina Virlics Andrew Halberstadt do we need to meet on Monday to all be in sync about making sure the update path is well tested?

**Comment by data-sync-user** [comment]
➤ Andrew Halberstadt commented:

{quote}Typically we do this by testing from 2.13 to 2.13 (by using a force function in the inspector).{quote}

Oh I didn’t realize this was part of the test process.. Would balrog even serve an update if the versions are the same? It’s possible there’s some other reason this wasn’t caught. I think we’re pretty confident that this particular issue is fixed on the 2.13 branch at least

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Valentina Virlics I have made https://mozilla-hub.atlassian.net/browse/VPN-4028 ( https://mozilla-hub.atlassian.net/browse/VPN-4028|smart-link ) to capture improving this process moving forward.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sarah Bird Solving this issue, was adding an Update message with a “Download“ button, like in 2.10? If yes, is there a tracking bug for it? Also, using the last RC for Addons, we don’t see an update message with a Download button.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Hey Valentina Virlics! That sounds like a bug in the update message addon. It should be showing the web updater for Windows indeed. I’ll file a separate bug for that.
