### ISSUE TITLE
Show the scrollbar in the language view

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#575]

**Comment by bakulf** [comment]
Would be great if we can scroll to the selected language too.

**Comment by ValentinaPC** [comment]
Verified this on the last VPN version (2.0.4) while using Windows 10.
A scrollbar is listed in the Settings/Language page.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/107773763-cd092900-6d46-11eb-9b68-c34852c68fd0.png)
