### ISSUE TITLE
Chinese language is not rendered correctly in the wasm viewer

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#579]
This issue is related to the fonts. See: https://bugreports.qt.io/browse/QTBUG-81736

I use p3, but feel free to increase the priority if needed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-109)
┆Reporter: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

It seems that the problem is related to our fonts. They do not have chinese/japanese support.
We have to update the font because WASM is unable to use local fonts.

**Comment by flodolo** [comment]
@bakulf 
Any chance to make progress on this? I got asked again in a recent event for localizers.

**Comment by bakulf** [comment]
Quick update: QT has fixed their issue in 6.5 (currently in beta).

**Comment by data-sync-user** [comment]
➤ Francesco Lodolo commented:

Andrea Marchesini How complex would it be to try using 6.5 beta just for the WASM build?
