### ISSUE TITLE
Version 2.13 does not compile on Archlinux

### ISSUE THREAD

**Issue by XavierCLL** [mozilla-mobile/mozilla-vpn-client#5868]
**Describe the bug**
Build error:

```make
[ 31%] Building CXX object src/CMakeFiles/mozillavpn.dir/mozillavpn_qmltyperegistrations.cpp.o
[ 31%] Building CXX object src/CMakeFiles/mozillavpn.dir/apps/vpn/addons/addon.cpp.o
/run/media/xavier/Xavier-ext4/ArchLinux/AUR-packages/mozillavpn/mozillavpn-2.13.0/src/apps/vpn/addons/addon.cpp: In member function ‘void Addon::updateAddonState(State)’:
/run/media/xavier/Xavier-ext4/ArchLinux/AUR-packages/mozillavpn/mozillavpn-2.13.0/src/apps/vpn/addons/addon.cpp:435:3: error: ‘mozilla’ has not been declared
  435 |   mozilla::glean::sample::addon_state_changed.record(
      |   ^~~~~~~
/run/media/xavier/Xavier-ext4/ArchLinux/AUR-packages/mozillavpn/mozillavpn-2.13.0/src/apps/vpn/addons/addon.cpp:436:7: error: ‘mozilla’ has not been declared
  436 |       mozilla::glean::sample::AddonStateChangedExtra{
      |       ^~~~~~~
make[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1212: src/CMakeFiles/mozillavpn.dir/apps/vpn/addons/addon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1126: src/CMakeFiles/mozillavpn.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**VPN version:**
  2.13.0 with Qt 6.4.2
  (using the tar sources from ubuntu ppa, see more [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mozillavpn))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4096)

**Comment by XavierCLL** [comment]
Hi @oskirby I know that you are one of the Linux dev here, could you throw any idea about this issue? Thanks!

**Comment by oskirby** [comment]
Hey @XavierCLL we have seen this kind of issue before when the glean/telemetry components are stale or haven't been built correctly, but if you downloaded the tarballed sources from one of our PPAs then the only requirement should be a sufficiently recent versison of `cargo` an the Rust toolchain.

I would try to install the python dependencies and regenerate the glean/telemetry bindings to see if this resolves your problems. You can do this with a `pip3 install --upgrade -r requirements.txt` and then running `python3 vpnglean/glean_parser_ext/run_glean_parser.py` and this should ensure that everything is up to date.

**Comment by XavierCLL** [comment]
Thanks @oskirby for your reply. I'm using the Ubuntu tar source to build the package to not put more dependencies in that package, like glean. I hope that you could update/fix that ubuntu tar source soon. Thanks.

**Comment by oskirby** [comment]
Yeah, I find it strange that you are encountering a build issue when using the PPA sources, because the Ubuntu build workflow doesn't allow us to access pip during the build process. So, in theory, what was uploaded to the PPA ought to have built successfully without requiring this step. I suspect that there is something unusual about your version of `cargo` and Rust that hadn't thought about when preparing out Ubuntu build system.

**Comment by 1alphabyte** [comment]
Hi!
Any update on this, I am getting the same issues. I am using the same PKGBUILD ([aur.archlinux.org](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mozillavpn&id=e53cad1b0e3f7e7e6a6dbd8e397f58e814395db6). For now in the AUR package I switched to using the GitHub repo and using pip to install glean_parser.

**Comment by XavierCLL** [comment]
I'm closing this issue because after switching the source to github, finally we were able to build the package correctly, thanks @1alphabyte
