### ISSUE TITLE
Captive portal unblock notification is not dismissed even if the user signs out from VPN

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#587]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Settings/Notifications;
3. Check the “Guest wi-fi” option;
4. Turn ON the VPN;
3. Go to http://localhost:8766/ and run “triggerCaptivePortal”;
4. Click the first notification;
5. Sign out from VPN;

#### Expected result:
- The Captive Portal unblock notification is no longer displayed after sign out.

#### Actual result:
- The second notification is still displayed even after sign out.

#### Notes:
- Clicking on the second notification after being signed out, _triggers the VPN to be quit_.

**Comment by bakulf** [comment]
Well, we cannot do it. We do not have control of the notifications. When they are displayed, with QT we cannot remove them. They will disappear after a while automatically.

**Comment by bakulf** [comment]
The crash is fixed in the latest build.

**Comment by ValentinaPC** [comment]
Verified this as fixed on the last receive build, while using Windows 10.
The Captive Portal unblock notification is no longer shown if user does not interact with it=> the "kill-VPN" issue can no longer be encountered.
