### ISSUE TITLE
tutorials section is empty

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/mozilla-vpn-client#5871]
**Describe the bug**

The tutorials section is empty.

**VPN version:**
2.13

**Affected Platforms:**
macOS 13.2

**Steps to reproduce:**

1. open the tutorials section

**Expected result:**

You can see tutorials, especially since there were tutorials in Mozilla VPN 2.12 and you mentioned two new tutorials in the release notes of Mozilla VPN 2.13.

**Actual result:**

There are zero tutorials.

**Additional notes:**

<img width="350" alt="Bildschirm­foto 2023-02-04 um 13 55 08" src="https://user-images.githubusercontent.com/1100614/216768855-3ecf089f-29bc-4fc5-b110-c808164cdec6.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4097)

**Comment by bakulf** [comment]
can you share logs? Thanks!

**Comment by cadeyrn** [comment]
@bakulf I attached a log.

[mozillavpn-2023-2-7.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10678551/mozillavpn-2023-2-7.txt)

**Comment by cadeyrn** [comment]
@bakulf I now got the update to Mozilla VPN 2.13 on Android and there the tutorials section is empty as well.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

I can reproduce this.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This is because the addons have not been released yet.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Copy pasting Valentina Virlics announcement from Slack:

2.13 release updates (QA) - after Addons RC release

  * Windows 10 - performed addons checks in production => versions 2.10, 2.11.0, 2.12.0 all have download message and 2.11.1 has update message;
  * MacOS - performed addons checks in production => update message available;
  * Linux 22.10 - performed addons checks in production => all good
  * Android/iOS - performed addons checks in production => all good

All new guides and tutorials are available;

**Comment by cadeyrn** [comment]
I can confirm that the tutorials are available now. Thanks.
