### ISSUE TITLE
Checking the Unsecured Wi-Fi option triggers the Captive Portal notifications

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#588]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Settings/Notifications;
3. Check the “Unsecured wi-fi” option;
4. Make sure that the Captive Portal checkbox is not checked;
5. Turn ON the VPN;
6. Go to http://localhost:8766/ and run “triggerCaptivePortal”;

#### Expected result:
- No Captive Portal notification should be displayed.

#### Actual result:
- Both Captive Portal notifications are displayed.

**Comment by bakulf** [comment]
Fixed!

**Comment by ValentinaPC** [comment]
Verified this as fixed on last VPN build, using Windows 10.
Having the unsecured wi-fi checkbox checked and triggering the Captive Portal, no notification is displayed.
