### ISSUE TITLE
Wrong edit message is displayed in "Notifications"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#595]
#### Affected Platforms:
- Windows 10;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
- Have VPN turned on;
 
#### Steps to reproduce:
1. Go to Settings screen;
2. Click “Notifications” option;
3. Observe the edit message displayed;

#### Expected result:
- Error message displays “VPN must be off to edit Notifications”.
 
#### Actual result:
- Error message displays “VPN must be off to edit network settings”.

![image](https://user-images.githubusercontent.com/15685960/108208068-3adf9700-7131-11eb-8add-7f24d3c53e35.png)

**Comment by bakulf** [comment]
@jess-cook03  @lesleyjanenorton can you help with this string?

**Comment by jess-cook03** [comment]
@bakulf 
My reccomendation --
“VPN must be off to edit notifications”
Basically following what Valentina has written as her expected result, makes sense to me.

**Comment by jess-cook03** [comment]
@jess-cook03 
@lesleyjanenorton 
@bakulf 
Update -- lets change the strings in both places (network settings and notification settings) to -- this:
'VPN must be off to edit these settings"

**Comment by ValentinaPC** [comment]
Verified this on the last VPN build, while using Windows 10.
The edit options message is changed, but is not yet labeled.
![image](https://user-images.githubusercontent.com/15685960/109631157-5b0a4f80-7b4e-11eb-80b3-9298e07ac598.png)
Will not mark this verified until the labels are applied.

**Comment by ValentinaPC** [comment]
Verified this as fixed on the last Win VPN build.
The message has the correct label.
![image](https://user-images.githubusercontent.com/15685960/109938056-43f76900-7cd8-11eb-8b10-7b5e54c87814.png)
