### ISSUE TITLE
A vertical scroll bar is displayed in the VPN activation screen when the update banner appears

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#596]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Go to http://localhost:8766/ and run “triggerUpdate 1.0”;
3. The “update” blue banner is displayed;
4. Observe VPN activation screen;

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- A vertical scroll bar is displayed.
![update now scroll](https://user-images.githubusercontent.com/15685960/108215081-93b32d80-7139-11eb-8ddb-ebb9b934fe51.gif)

**Comment by lesleyjanenorton** [comment]
So this is actually "as expected" for this type of alert message. When you dismiss the update notification, it should go away.

**Comment by ValentinaPC** [comment]
> So this is actually "as expected" for this type of alert message. When you dismiss the update notification, it should go away.

It does disappear after dismissing the blue banner.
Marking as verified.
