### ISSUE TITLE
Different languages are causing UI issues on VPN activation screen

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#599]
Different languages are causing UI issues on VPN activation screen
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Click the switch on button;
3. Observe the VPN activation screen;

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- There are some display issues.
![image](https://user-images.githubusercontent.com/15685960/108361457-31bafc80-71fb-11eb-8076-a15b7482485e.png)

**Comment by bakulf** [comment]
@flodolo is this something you can help with? Or we need to change it at the code level?

**Comment by flodolo** [comment]
I'm afraid this should be fixed at code level.

1) Can we avoid the text wrapping in that weird way in the first line? I'm surprised there's a line break on the ellipsis, when there's no space `Verbindung wird getrennt…`.

2)  Can we plan for 2+2 lines of text, and place the toggle accordingly. I'm OK truncating if content goes beyond 2 lines for each label.

**Comment by lesleyjanenorton** [comment]
@flodolo Yes, we'll make sure there is room for 2+2 lines of text.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build while using Windows 10 x64.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/110325674-4af7e180-8020-11eb-88b1-c86f88c5fea0.png)
