### ISSUE TITLE
VPN is closed at swipe-kill on Android 6

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#605]
#### Affected versions:
* v. 2.0.4 last build; 

#### Affected Platforms:
* Android 6;

#### Prerequisites:
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
1. Turn ON the VPN;
1. Swipe-kill the app;
1. Re-open the app;
1. See VPN status;

#### Expected result:
* The VPN is ON and time notes that it was not closed during swipe-kill.

#### Actual result:
* The VPN is OFF.

#### Notes:
* this is only happening on Android 6;

https://user-images.githubusercontent.com/15685960/108701020-19efbb00-7510-11eb-96d7-d7060833e0d5.mp4

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-111)

**Comment by rbillings** [comment]
Android 6 is no longer supported, closing.
