### ISSUE TITLE
Name and description for second Notifications option are incorrect

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#608]
#### Affected Platforms:
- Windows 10;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
 
#### Steps to reproduce:
1. Go to Settings screen;
2. Click “Notifications” option;
3. Observe the second option;

#### Expected result:
- Both name and description are localized.
 
#### Actual result:
- The name and description are not yet formatted;
![image](https://user-images.githubusercontent.com/15685960/108835060-98fbf680-75d7-11eb-92c2-54ec958d6c43.png)

**Comment by bakulf** [comment]
Fixed in the latest build

**Comment by ValentinaPC** [comment]
Verified as fixed on the lat VPN build using Windows 10.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/108851181-d4ed8680-75ec-11eb-9610-5cdea8564979.png)
