### ISSUE TITLE
VPN stops responding when opening on-screen keyboard and switching to another app

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#6115]
User on 2.11 and 2.13.1 for Android reports the VPN stops responding, resulting in a crash after opening the VPN on-screen keyboard, switching to another app or task, and then going back to the VPN. Crash results in losing WiFi connection, and restore it by turning WiFi off and back On. Tried opening keyboard from login and in-app messages screen. User reports issue happens regardless of which type of keyboard they use, but they are currently using FlorisBoard 4.0 Beta. Support cannot reproduce the issue.

**VPN version:**
 VPN 2.11/2.13

**Affected Platforms:**
Android 13

**Steps to reproduce:**
1. Launch Mozilla VPN
2. Switch to the login screen or messages view
3. Tap email field to enter Firefox credentials or the search box in the messages view to bring up the on-screen keyboard.
4. Optional (Dismiss the on-screen keyboard)
5. Switch to another task.
6. Switch back to Mozilla VPN.

**Expected result:**
VPN should not crash when switching apps

**Actual result:**
An error appears causing the VPN to crash.

**Additional notes:**
  Attaching ANR crash report and VPN logs.

[anr-mozilla-vpn.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10797357/anr-mozilla-vpn.txt)

[MozillaVPN_Logs_2023-58-16-11-58-09-4.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/10797368/MozillaVPN_Logs_2023-58-16-11-58-09-4.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4232)

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Unfortunately we are currently unable to reproduce this using standard keyboards from the play store. Feel free to reopen if you have additional info.
