### ISSUE TITLE
If we switch the VPN OFF while being connected to an unsecured network the notification alert is not shown

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#612]
#### Affected versions:
* v. 2.0.4 last build; 

#### Affected Platforms:
* Windows 10;

#### Prerequisites:
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
1. Go to Settings/Notifications;
1. Check the “Unsecured network alert” option;
1. Turn ON the VPN;
1. Connect to an unsecured guest network;
1. Turn OFF the VPN;

#### Expected result:
* A unsecured network notification should be displayed.

#### Actual result:
* No notification is displayed.

#### Notes:
* User ends up being connected to an unsecured network, without being protected.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-112)
┆author: Data Sync

**Comment by bakulf** [comment]
@jess-cook03 what do you think about this issue? If the user is an unsecured network, and they turn off the VPN, should we show the unsecured network alert?

**Comment by jess-cook03** [comment]
@bakulf yes ^ I agree with what you said -- lets show the unsecured network notification.

**Comment by rbillings** [comment]
If the user agrees to an unsecured network, they do not get another notification when they rejoin in the future. We can consider a time limit or a number of notifications limit.

**Comment by rbillings** [comment]
If the user agrees to the unsecured network and signs in again within 20 seconds they do not get a notification, if it's longer than 20 seconds they DO get a notification.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This is a 2.0 bug. I suspect this cannot be reproduced in 2.10. In case I'm wrong, reopen the bug.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Andrea Marchesini This is still reproducing using 2.10.0 (2.202210111527) on Windows 10.

  * VPN ON → connect to a hot-spot (unsecured) → turn OFF the VPN => no unsecured notification;
  * VPN OFF → connect to a hot-spot (unsecured) => unsecured notification displayed;
