### ISSUE TITLE
Issue: Mozilla VPN adds back itself to the Startup applications

### ISSUE THREAD

**Issue by davidhedlund** [mozilla-mobile/mozilla-vpn-client#6131]
**Describe the bug**
Removed Mozilla VPN from startup applications

Mozilla VPN adds back itself to the Startup applications when I'm rebooting, which is extremely intrusive.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4241)

**Comment by birdsarah** [comment]
Hi @davidhedlund thanks for the report and apologies for the inconvenience.

If we could get some extra details to help us reproduce that would be great.

In particular: version of windows, version of mozilla vpn, and mozilla vpn logs.

If you'd prefer not to put that information here, you're welcome to file a support ticket from inside the app (see Settings->Get Help->Contact support).

**Comment by davidhedlund** [comment]
Cannot reproduce the issue.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

can't repro
