### ISSUE TITLE
Redundant survey when closing Mozilla VPN

### ISSUE THREAD

**Issue by Mozinet-fr** [mozilla-mobile/mozilla-vpn-client#6178]
**Describe the bug**
A French Mastodon user [reports](https://framapiaf.org/@jotak/109918729295932085) that Mozilla VPN asked him when quitting to respond to a survey where the three questions are the same.

**VPN version:**
a recent RPM version

**Affected Platforms:**
GNU/Linux

**Prerequisites:**
Install a Mozilla VPN RPM version from GitHub repository.

**Steps to reproduce:**
<Please fill this in>

**Expected result:**
<Please fill this in>

**Actual result:**
3 time the same question in a survey triggered by Mozilla VPN

**Additional notes:**
Screenshot provided by the initial reporter:

![width=100%](https://user-images.githubusercontent.com/8845401/221682655-c0271456-a04b-4eb6-93ea-2287d8b5dcdf.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-4258)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Alice Rhee Two questions
1. Do you recognize this survey? The first question is not alike the CSAT surveys we send to users (since they mention the device).
2. This made me think - are we localizing the CSAT survey to other languages? I only see the surveys in English in Alchemer. Are they automagically translated somehow?

**Comment by data-sync-user** [comment]
➤ Alice Rhee commented:

Hmmmmm I thought I fixed this on desktop. Maybe I didn’t fix it on mobile and that’s where he’s seeing it? I think this is the CSAT survey. Alchemer translates it into French and German AFAIK but there was something wrong with the German version on desktop (German users were seeing the same Q) and I fixed it like 6 months ago. Let me double check this.

**Comment by data-sync-user** [comment]
➤ Alice Rhee commented:

Argh I changed it on mobile and not on desktop. I’m fixing this now. An edit to my previous comment: Alchemer does not magically translate this; we need to put in our own translations.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Alice Rhee Can you point me to the surveys please? I didn’t find them in Alchemer

**Comment by data-sync-user** [comment]
➤ Alice Rhee commented:

Desktop - https://app.alchemer.com/translation/languages/id/6897437 ( https://app.alchemer.com/translation/languages/id/6897437 )

Mobile - https://app.alchemer.com/builder/build/id/6897488 ( https://app.alchemer.com/builder/build/id/6897488 )

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Thanks you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Currently both Desktop and Mobile versions of the survey don’t list multiple times a question.

!image-20230728-095204.png|width=1305,height=514!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Reported issue was about the fact the same question was listed 3 times. I just confirmed that that was not the case anymore. Sorry for the confusion.
