### ISSUE TITLE
Android Crash: Type "abort"

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#622]
This type of crash is ~60% of all our reported crashes. 
This happens only on Huawei devices, apparently when they try to exit the app with the back button.

There is an open QT bug for this, currently open: https://bugreports.qt.io/browse/QTBUG-85449
Also there is a diy patch in the bug, maybe we should also compile qt/android and include this. 
Stacktrace:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> org.mozilla.firefox.vpn <<<

backtrace:
  #00  pc 000000000006f06c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #00  pc 00000000000500fc  /system/lib64/libc++.so (abort_message+232)
  #00  pc 0000000000050218  /system/lib64/libc++.so (demangling_terminate_handler()+44)
  #00  pc 00000000000646c4  /system/lib64/libc++.so (std::__terminate(void (*)())+12)
  #00  pc 000000000006466c  /system/lib64/libc++.so (std::terminate()+52)
  #00  pc 00000000000bb150  /system/lib64/libc++.so (std::__1::thread::~thread()+20)
  #00  pc 00000000000d0f68  /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+212)
  #00  pc 00000000000cc950  /apex/com.android.runtime/lib64/bionic/libc.so (exit+24)
  #00  pc 0000000000034534  /data/app/org.mozilla.firefox.vpn-18k5up_u3M-aF41KJvRmsg==/lib/arm64/libplugins_platforms_qtforandroid_arm64-v8a.so (startQtApplication(_JNIEnv*, _jclass*)) (SourceCode: androidjnimain.cpp)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-498)

**Comment by strseb** [comment]
https://codereview.qt-project.org/c/qt/qtbase/+/331906 was merged - 
So once QT 5.15.3 is released we can just set qEnvironmentVariable QT_ANDROID_NO_EXIT_CALL.
It should be released this week :)

**Comment by strseb** [comment]
Moving this to 2.3, as fixing this depends on swithcing to qt6 ( #827 )

**Comment by punster-moz** [comment]
Back  Button also caused the vpn app to exit on the my Samsung S10+. Connection stays if switch to another app. But back button will cause app exit, not sure it crash or not.

**Comment by ValentinaPC** [comment]
Verified this on my Android 10 (Google Pixel 4) device, while using the VPN client 2.3.0 (16209050).
Back option is handled correctly and VPN app does not crash.

**Comment by strseb** [comment]
Opening this, as numbers are not going down. We Probably need to upgrade to qt6 here, as the patch for the problem is included there.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Sebastian Streich can we close this issue?
