### ISSUE TITLE
Inconsistency between button label and button design

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#626]
**Affected Platforms:**

* Windows 10 x64;

**Prerequisites:**

* Have the VPN app installed;
* Have a FxA account;

**Steps to reproduce:**

1. Launch VPN app;
1. Go to Settings screen;
1. Hover the Close button;
1. Observe tool-tip;

**Expected result:**

* Close button tool-tip should say “Close”.

**Actual result:**

* Close button tool-tip says “Back”.
![width=200,height=183](https://user-images.githubusercontent.com/15685960/109127861-8f010180-7757-11eb-8d9f-97cd39a332ca.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-500)
┆author: Data Sync

**Comment by ValentinaPC** [comment]
Verified this as fixed on the last VPN build, while using Windows 10 x64.
While hovering over the closing Settings button, the tool tip displayed is correct.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/110323492-585f9c80-801d-11eb-99d3-9c4226f64612.png)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is happening again while using Mozilla VPN 2.9.0 (2.202206271708);

!image-20220628-124749.png|width=151,height=169!

Reopening.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Lesley Norton Did I hear you say this doesn’t need to be fixed for 2.9?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We are blocked in verifying this on Windows - 2.10 build from Treeherder, due to some building issue.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on Mozilla VPN  2.10.0 build on Windows 10, Linux 20.04 and Mac OS 10.15.

The “Close” Settings button is labeled accordingly.

!image-20220808-100139.png|width=462,height=154!
