### ISSUE TITLE
Implement "unsecured network alert" for android

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#631]
From the play store reviews there is a request to automatically start when using public Wi-Fi.

At least on android it's fairly trivial to register to wifi change events and start vpn if the wifi is not in some "do not connect" list.

**Comment by bakulf** [comment]
This is the "unsecured network alert" feature. It's already implemented on Linux, mac and windows. Let's use this issue to implement it for android too.

**Comment by strseb** [comment]
@bakulf  - that info is provided by androids WifiManager. Sadly accessing it requires us to ask for fine-location-access. 
I'm not sure if thats a permission we would add since that might raise some eyebrows. What do you think?
https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-restrictions

**Comment by strseb** [comment]
Closing this as wontfix, until we have a way to get the info without Fine location access :)

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Supporting this would require to get permissions to fetch detailed wifi info. this means requesting fine.location.permission which is not worth
