### ISSUE TITLE
CI windows build is broken again (on main)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#6358]
See https://firefox-ci-tc.services.mozilla.com/tasks/ALqsO0haSdaTwXg3opglVg/runs/0/logs/live/public/logs/live.log

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-4379)
┆Reporter: Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

@baku are you already looking at this one? broken on Main, maybe on 2.15 branch?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Confirmed that 2.15 is not on TaskCluster 🙁

https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build ( https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build )

**Comment by oskirby** [comment]
At last! It looks like we have working builds again on `main` and it only took me three tries.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Should I expect a Windows client to land here at some point soon?
https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build ( https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build )

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Santiago Andrigo there should be signed Windows builds available now for 2.15

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on Task-cluster 2.15 branch - https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build ( https://firefox-ci-tc.services.mozilla.com/tasks/index/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build ) ;

The Windows build is available.
