### ISSUE TITLE
Build on MacOS 11 (Big Sur)

### ISSUE THREAD

**Issue by jchimene** [mozilla-mobile/mozilla-vpn-client#636]
Is there anything I can do to help push the stone for a MacOS Big Sur version? Is there an issue #? I tried building following the instructions on this repo. The `apple_compile.sh` step did not complete. I think it only wants to build under MacOS 10.15 or earlier. I notice that qt has a 6.0.1 release, but the `scripts/qt5_compile.sh` step failed with an undefined switch (sorry, I didn't capture the switch name).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-503)
┆Reporter: Data Sync

**Comment by bakulf** [comment]
There is this issue for Big Sur: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/286
So far the main blocker is that qt 6 doesn't support Big Sur yet. See: https://bugreports.qt.io/browse/QTBUG-85279
We also need to update the script to compile and use qt6, but we need to see if this step is compatible with all the supported platforms.

**Comment by jchimene** [comment]
Thank-you for confirming my research. I was hoping there was some secret sauce on Mozilla's side.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Look at this again in January 2023
