### ISSUE TITLE
IOS app disconnects the VPN randomly

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#640]
It seems to happen when the connectivity goes from wifi to mobile data. But not always.

**Comment by bakulf** [comment]
I haven't written the final fix for this issue, but the current `main` contains a reasonable fix: @autoreleasepool{} for the logs.

To summarise the issue, a network-extension, on IOS can allocat 15mb max. 99% of the network-extension code is from WireGuard. The rest is the logging component. I wrapped that new code to prevent leaks (even if they are not detected by Xcode) or extra memory allocation. This is not the proper fix because, doing nothing, the network-extension allocates already between 10 and 12mb. It's easy to imagine a pick to 15mb.

The proper fix is to replace the network extension with the new WireguardKit component. See: https://github.com/WireGuard/wireguard-apple/tree/master/Sources/WireGuardKit

I close this issue and I'll file a new one to use WireGuardKit.

**Comment by jr-johnson-support** [comment]
@bakulf  can you share the updated github issue you noted you filed?

**Comment by mbirghan** [comment]
This was already done but not synced with jira
