### ISSUE TITLE
UI - refine the modal component (cross-platform)

### ISSUE THREAD

**Issue by jess-cook03** [mozilla-mobile/mozilla-vpn-client#642]
<img width="372" alt="Screen Shot 2021-03-03 at 3 12 30 PM" src="https://user-images.githubusercontent.com/54991698/109874518-36d96c00-7c3d-11eb-9e26-a999aeee2ca6.png">

- Not currently optimized for mobile
- Needs UI refresh

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-114)

**Comment by rbillings** [comment]
Blocked until a new spec is created.

**Comment by jess-cook03** [comment]
Updating this from design side --- need to move this into an enhancement for v2.5
cc @bfyee @lesleyjanenorton

**Comment by bfyee** [comment]
added to PRD for v2.5

**Comment by peterbenvenuto** [comment]
Designs have been completed for this issue. Here is the [figma file](https://www.figma.com/file/Pv2ub3IqQt4CaDPwhFTyst/Refine-Modal-UI-Device-Management?node-id=15%3A1038) -- let me know if you have any questions!

cc @bfyee @lesleyjanenorton

**Comment by lesleyjanenorton** [comment]
@peterbenvenuto @jess-cook03 Spec looks great, only one comment - we can almost guarantee that there will not be enough room for those buttons to exist side x side in more verbose locales. It would be great to have an additional view of what should happen when the buttons in the modal are too wide and must be stacked.

**Comment by jess-cook03** [comment]
@peterbenvenuto What do you think about making a button stacked option for this modal as well to account for what lesley is mentioning above?

**Comment by peterbenvenuto** [comment]
@jess-cook03 Yes, I can make both options!

**Comment by peterbenvenuto** [comment]
Here's the link to the new [figma file](https://www.figma.com/file/Pv2ub3IqQt4CaDPwhFTyst/Refine-Modal-UI-Device-Management?node-id=15%3A1038) @lesleyjanenorton

**Comment by ValentinaPC** [comment]
As we did not found another issue for this enhancement, we will add our verification results here.
Verified this across platforms on the last v. 2.5 version (2.5.0 (2.202108310209)), and observed the following:
- the "Cancel" button has a blue border (no listed in figma files);
- for some languages (German) or long device names the UI vertical padding seem to be missing;
![image](https://user-images.githubusercontent.com/15685960/131480639-54635d99-aca7-444b-9af3-d0a08f8ae3f0.png)

Please let us know if a separate issue should be logged.

**Comment by data-sync-user** [comment]
➤ Nma-Sie-Anyene Davenport commented:

New issue has been logged.  See https://mozilla-hub.atlassian.net/browse/VPN-933 ( https://mozilla-hub.atlassian.net/browse/VPN-933|smart-link )

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 07/28 . Changing it back to Done.

Thank you.
