### ISSUE TITLE
Change “Get Help” link color from red to blue in “Heartbeat” failure screen

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#646]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Turn ON the VPN;
3. Go to Websocket - http://localhost:8766/ ;
6. Run the command “triggerHeartbeatFailure”;
7. See VPN screen;

#### Expected result:
- The “Get Help” link is colored in blue.

#### Actual result:
- The “Get Help” link is colored in red.

#### Notes:
- Let’s keep it blue, as it is everywhere, for consistency.
![image (4)](https://user-images.githubusercontent.com/15685960/109965683-f7bc2100-7cf7-11eb-9b0a-db1395e36e08.png)

**Comment by lesleyjanenorton** [comment]
@jess-cook03 What are your thoughts here?

**Comment by jess-cook03** [comment]
@lesleyjanenorton I wonder now looking at it and getting this feedback..... maybe its best if we pull back the alert red on that 'Get help' text and keep it blue. Right now it looks like possibly we are wanting users to click that and its standing out maybe too much.

I agree, lets make it blue and call it. 
Sorry about the back and forth.
Thank you @ValentinaPC for this!

**Comment by lesleyjanenorton** [comment]
no worries, I'll make the update!

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build while using Windows 10 x64.
Postfix screeshot below.
![image](https://user-images.githubusercontent.com/15685960/110324673-f738c880-801e-11eb-8d83-9411edc9874a.png)
