### ISSUE TITLE
Disconnect notification at VPN connection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#655]
#### Affected VPN versions:
* last VPN version;

#### Affected Platforms:
* Windows 10 x64;

#### Prerequisites:
* Have an FxA account with active subscriptions;

      1. Steps to reproduce:

1. Open VPN client;
1. Sign in with success;
1. Click the "Continue" button.
1. Observe the Windows notification about the VPN app;

#### Expected result:
* As the VPN app is shortly starting after signing up, the only notification that should be displayed is the one related to the fact that VPN is connected.

#### Actual result:
* The  notification mentions “VPN disconnected. ....”.

#### Notes:
* the message suggests that the VPN was ON but you disconnected.
![3notification](https://user-images.githubusercontent.com/15685960/110327557-cb1f4680-8022-11eb-8123-24bf32a90c08.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-115)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Valentina Virlics can you still reproduce it?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed on Mozilla VPN 2.11.0 (2.202210270555) build, while on Windows 10.

The connecting OS notification is displayed while turning the VPN ON.
