### ISSUE TITLE
[L10n][DE] UI issues on VPN Onboarding screen

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#661]
#### Affected versions:
- v 2.0.4 (2.202103081839)
 
#### Affected Platforms:
- Windows 10 x64;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with a subscription made for VPN;
 
#### Steps to reproduce:
1. Launch VPN;
2. Set the language to "German";
3. Reach the third onboarding screen;
 
#### Expected result:
- Text on the onboarding screen is displayed correctly.
 
#### Actual result:
- Text is not displayed correctly.
![l10n-2](https://user-images.githubusercontent.com/15685960/110486103-fe320a80-80f4-11eb-931e-ce7ac7b6c01c.png)

**Comment by bakulf** [comment]
@flodolo do you have any solution to fix this problem in general and not for DE?
Can we compute if a single word matches the whole available width size, and if it does, we reduce the font size until it's OK.
Would it work?

**Comment by bakulf** [comment]
QML offers a nice way to change the font dynamically: https://doc.qt.io/qt-5/qml-qtquick-text.html#fontSizeMode-prop

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build () while using Windows 10.
Postftix screenshot:
![image](https://user-images.githubusercontent.com/15685960/111315225-d7cb1c80-866a-11eb-911d-48db8f80165c.png)
