### ISSUE TITLE
[L10n][FR] UI issues on VPN Select location section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#662]
Different languages are causing UI issues on VPN Select location button
 
#### Affected versions:
- v 2.0.4 (2.202103081839)
 
#### Affected Platforms:
- Windows 10 x64;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with a subscription made for VPN;
 
#### Steps to reproduce:
1. Launch VPN;
2. Set the language to "French";
3. Go to VPN activation screen;
4. Observe the location section;
 
#### Expected result:
- Current location is visible in Select location section.
 
#### Actual result:
- Current location is not visible. Only the flag.
![l10n-1](https://user-images.githubusercontent.com/15685960/110486710-9203d680-80f5-11eb-81cc-c977ee442991.png)

**Comment by bakulf** [comment]
@flodolo can we contact the translator to have something smaller here?

**Comment by flodolo** [comment]
I'm not sure there's a good way to approach this at scale (cc @theochevalier).

Is there any change to set a max-width on the label, and have it wrap on two lines if necessary?

**Comment by flodolo** [comment]
I think having the city name is important. On the other hand, flags might get us into trouble at some point :-(

**Comment by TheoChevalier** [comment]
Is it safe to replace "location" with "city" in the translation?

**Comment by lesleyjanenorton** [comment]
@TheoChevalier  Yep - "city" is safe

**Comment by lesleyjanenorton** [comment]
Something to possibly note: for US cities we include the state... "Dallas, TX" instead of just "Dallas" but from my perspective "city" still makes sense in this case.

**Comment by lesleyjanenorton** [comment]
Another thought on how to free up more space:
<img width="364" alt="Screen Shot 2021-03-10 at 9 37 23 AM" src="https://user-images.githubusercontent.com/22355127/110654955-392f4f00-8184-11eb-8573-00fb6a72c329.png">

**Comment by TheoChevalier** [comment]
> @TheoChevalier Yep - "city" is safe

Nice, thanks! I shortened to "Sélectionner une ville", I could go further with "Choisir une ville" (Choose a city) if needed, but it doesn’t sound as good

**Comment by jess-cook03** [comment]
@lesleyjanenorton 
I wonder what if we pull it into 2 lines always. I know we spoke about this briefly as a UI improvement a while back.
But no time like a the present hah.
So I'm suggesting cross-platform we address this .... we keep the labels on one line.... selection underneath... see examples below:

<img width="800" alt="Screen Shot 2021-03-10 at 12 03 23 PM" src="https://user-images.githubusercontent.com/54991698/110667825-a351ef00-8198-11eb-92bf-8f34d9f39d06.png">

**Comment by lesleyjanenorton** [comment]
@jess-cook03 They both look good to me so If 710 is your preference, let's go with it.

**Comment by jess-cook03** [comment]
@lesleyjanenorton let do the 710 option then! Is this doable cross platform?

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build, across platforms.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/111754864-22ce7500-88a1-11eb-9aa5-0696b44c7f5a.png)
