### ISSUE TITLE
 “No internet connection. Try again!” red banner after VPN restart

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#664]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- Windows 10;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Settings and check the “Launch VPN at startup” option;
3. Uncheck the options from Network settings and Notifications;
2. Turn ON the VPN;
3. Restart the VPN;

#### Expected result:
- VPN is restarted without issues.

#### Actual result:
- A red banner is displayed and internet connection is down for a few seconds.
![internetconnection](https://user-images.githubusercontent.com/15685960/110490684-3e938780-80f9-11eb-85d4-c7ba89a41513.gif)

**Comment by bakulf** [comment]
This should be fixed by: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/654
