### ISSUE TITLE
Issue with starting the application after ubuntu update

### ISSUE THREAD

**Issue by danwchan** [mozilla-mobile/mozilla-vpn-client#6674]
**Describe the bug**
MozillaVPN does not start

**VPN version:**
From the ubuntu repo or from ppa:mozillacorp/mozillavpn

**Affected Platforms:**
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="5.27"
VERSION_CODENAME=jammy

**Prerequisites:**
N/A

**Steps to reproduce:**
install

**Expected result:**
VPN runs

**Actual result:**
vpn does not launch via gui and via command line the following error occurs
mozillavpn: symbol lookup error: mozillavpn: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6

**Additional notes:**
  <Optional: Any Screenshots, Videos, Logs>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4612)

**Comment by Miroito** [comment]
I have the same problem after updating this morning on EndeavourOS.
Here is the pacman log for qt6 packages that includes their previous (where mozillavpn worked) and current versions (where the error above is showed on startup):
```
22255   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-base (6.4.3-1 -> 6.5.0-3)
22256   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-5compat (6.4.3-1 -> 6.5.0-1)
22257   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-declarative (6.4.3-1 -> 6.5.0-2)
22258   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-charts (6.4.3-1 -> 6.5.0-1)
22259   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-imageformats (6.4.3-1 -> 6.5.0-1)
22260   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-networkauth (6.4.3-1 -> 6.5.0-1)
22261   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-shadertools (6.4.3-1 -> 6.5.0-2)
22262   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-svg (6.4.3-1 -> 6.5.0-1)
22263   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-tools (6.4.3-2 -> 6.5.0-4)
22264   │ [2023-04-13T09:38:25+0200] [ALPM] upgraded qt6-websockets (6.4.3-1 -> 6.5.0-1)
```

It is worth mentioning that not only the GUI but the whole application seems to be impacted as the cli also gives this error message.

I'm using the mozillavpn aur package which claims to use the version `2.14.0-1`.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Naomi Kirby This looks related to the dynamic linking to QT, and thus to be fixed in 4.15.1, right? Is there a ticket to follow on that work?

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Santiago Andrigo our plans to produce a statically linked version of the client is being tracked by https://mozilla-hub.atlassian.net/browse/VPN-4585 ( https://mozilla-hub.atlassian.net/browse/VPN-4585|smart-link ) (Github issue #6646 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/6646 )). That should get users who install it unstuck and decouple us from these kinds of issues when the distros change Qt version.

**Comment by danwchan** [comment]
New version was installed 2.19 and it seems to work now although the UX on the multicontainer extension isn't showing anything.
