### ISSUE TITLE
Ubuntu 23.04 Lunar Lobster packages and support missing?

### ISSUE THREAD

**Issue by KlfJoat** [mozilla-mobile/mozilla-vpn-client#6752]
**Describe the bug**
I expect MozillaVPN to be available and working on my Ubuntu system that I upgraded from 22.10 Kinetic Kudu to 23.04. #6155 and #6156 give me this impression.

**VPN version:**
```
$ mozillavpn --version
mozillavpn 2.14.1
```

**Affected Platforms:**
Ubuntu Linux version 23.04 "Lunar Lobster"

**Prerequisites:**

1. Install Ubuntu 22.10.
2. Add the MozillaVPN PPA.
3. Install MozillaVPN.
4. `do-release-upgrade` to Ubuntu 23.04.

**Steps to reproduce:**

1. Use Mozilla VPN successfully in Ubuntu 22.10.
2. Upgrade to Ubuntu 23.04.
3. Try running MozillaVPN via `.desktop` file or command-line.

**Expected result:**
The MozillaVPN UI running as normal.

**Actual result:**
Nothing when I execute the `.desktop` file.
From the command line I get a segfault.
```
$ mozillavpn 
QDBusArgument: write from a read-only object
Segmentation fault (core dumped)
```

**Additional notes:**
The GitHub issues I referenced above mention a version 2.15, but I cannot find that version for any series on Launchpad, nor can I find any Lunar series on Launchpad. https://launchpad.net/~mozillacorp/+archive/ubuntu/mozillavpn

Additionally, `apt` cannot find MozillaVPN for Lunar and no update occurs.
```
$ sudo apt update
...
E: The repository 'https://ppa.launchpadcontent.net/mozillacorp/mozillavpn/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4669)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We will support Lunar Lobster starting with 2.15 Mozilla VPN version. (https://mozilla-hub.atlassian.net/browse/VPN-4252 ( https://mozilla-hub.atlassian.net/browse/VPN-4252|smart-link ) )

**Comment by KlfJoat** [comment]
I'm aware it will be supported in v2.15. That info was in the GitHub issues I linked in my original post.

That's also why I said I could not find version 2.15 in my original post... Because I knew that Ubuntu 23.04 would be supported in version 2.15 and I was looking for the version that supports Ubuntu 23.04.

So the information I obviously need is
1) Please point me to a publicly posted timeline showing when version 2.15 (and future versions) will be released.
or
2) Please tell me now when 2.15 will be released.

**Comment by albionx** [comment]
Hi! 

Sorry for that KlfJoat. We don't actually post official timelines for versions, but I can tell you that 2.15 is _expected_ to come out mid May after we've QA'd it. In the meantime, here you can find the non-QA'd and non-signed version:

https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mozillavpn.v2.mozilla-vpn-client.branch.releases.2.15.0.latest.build.linux-lunar/artifacts/public%2Fbuild%2Fmozillavpn-lunar.tar.gz

If you give it a spin, please let us know how it goes. Thanks!

**Comment by fabricedesre** [comment]
fwiw, I tested the linke build from [comment](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/6752#issuecomment-1526694220) and it worked fine on 23.04.

**Comment by KlfJoat** [comment]
> If you give it a spin, please let us know how it goes. Thanks!

Thanks! I downloaded and installed the `.deb` and it works just fine as far as the actual VPN functionality.

There are some issues with spacing in the settings menus.  

* The App Exclusions list is intermittent. Sometimes it's normal, sometimes it's compressed.
* Privacy Features compresses the text on top of itself.
* About Us compresses the text and overlays it.

I have screenshots, if you'd like them.

**Comment by albionx** [comment]
Thank you both. Yes, KlfJoat, please send those screenshots along!

**Comment by KlfJoat** [comment]
> Thank you both. Yes, KlfJoat, please send those screenshots along!

https://imgur.com/a/dpnpsKQ

**Comment by VoxelPrismatic** [comment]
Oh I just found the issue actually
This appears to be an issue with `2.14.1-kinetic1` specifically. If you go to the source file and change from `kinetic` to `jammy`, then run `sudo apt update; sudo apt install mozillavpn=2.14.1-jammy1` you should be all good

See #7002
