### ISSUE TITLE
VPN can be turned ON on the 6th device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#676]
#### Affected versions:
- v. 2.0.4 last build; 

#### Affected Platforms:
- iOS 14.02;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;
- Using the same account have the VPN active on 5 devices;

#### Steps to reproduce:
1. Open VPN app on the 6th device;
2. Turn On the VPN;

#### Expected result:
- VPN cannot be turned ON.

#### Actual result:
- VPN is turned ON;
![IMG_20210315_155516](https://user-images.githubusercontent.com/15685960/111169995-25348480-85ac-11eb-9d60-8e4e89f2a989.jpg)

**Comment by bakulf** [comment]
Fixed

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build (202103160852) on iOS 14.02.
The VPN cannot be turned ON in the 6th device.
![image](https://user-images.githubusercontent.com/15685960/111321144-57a7b580-8670-11eb-9662-6f8829b6aca0.png)
