### ISSUE TITLE
[Intermittent] VPN app crashes when Logs are accessed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#677]
* v. 2.0.4 last build; 

#### Affected Platforms:
* iOS 14.02;

#### Prerequisites:
* Have a FxA account with active subscription for Mozilla VPN;
* Have a newly installed VPN app;

#### Steps to reproduce:
1. Open VPN app;
1. Turn ON the VPN;
1. Access all “Settings” submenus (open-back) until “Get Help” option;
1. When at the language menu - change the language;
1. Open the “Get Help” menu;
1. Tap “View log” option;

#### Expected result:
* Logs are open;

#### Actual result:
* The VPN crashes.

#### Notes:
* this is an old issue….was not able to find more clearer STRs than the above ones.
* I cannot reproduce it each time;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-119)

**Comment by ValentinaPC** [comment]
Just reproduced this on VPN 2.5.0 (202109031936).

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Closing this, as this has been resolved by adding the ability to LogShare - ios does not use the log viewer anymore 😀
