### ISSUE TITLE
Obsolete whatsnew/update addons exposed to localization

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#6814]
Currently in the repository there are a lot of addons:
* message_update_v2.15
* message_whats_new_v2.10
* message_whats_new_v2.11
* message_whats_new_v2.12
* message_whats_new_v2.13
* message_whats_new_v2.14
* message_whats_new_v2.15 

Is there a point in keeping all these old whatsnew addons?

The other problem is that we still have all the old `message_update` (from 2.12) still exposed in the l10n repository. That might be a problem that I need to fix on my side though.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4715)

**Comment by flodolo** [comment]
> The other problem is that we still have all the old `message_update` (from 2.12) still exposed in the l10n repository. That might be a problem that I need to fix on my side though.

This is fixed by https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/345

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Hi Flod, thanks for bringing this up.

I’m just starting thinking through the next phase of our addons world. This ticket points to a broader class of problem of whole set of addons (particularly messages) that don’t need furtger translating after they’ve been deployed.

Is it important for you to have a stop-gap solution or can you wait while I try and put a more comprehensive solution together?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Totally reasonable Flod. Lesley Norton's idea here which I think is good is that all the messages you mention have a max client version. So we should update the localization export script to not export addons that have a max client version that’s in the past.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Adrienne Davenport Betty Fleming I think flod, quite reasonably, would like us to start working on this as soon as possible. Wanted to flag you on it.

**Comment by flodolo** [comment]
As another example, we also have 3 versions of the tunnel tutorial, only one valid for 2.15.+
https://github.com/mozilla-mobile/mozilla-vpn-client/tree/main/addons

And yet we're asking new locales to translate all strings in these 3 versions.

**Comment by flodolo** [comment]
@brizental 
Do we want to keep this open, or should I file another issue to automate this?

**Comment by brizental** [comment]
Let's file a separate issue to automate this. Making the addons obsolete is done.
