### ISSUE TITLE
[L10N] App permissions screen has layout issues for some languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#682]
- v. 2.0.4 (16155440) last build; 

#### Affected Platforms:
- Android 11;

#### Prerequisites:
-  Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open VPN app;
2. Go to Languages and select FR;
3. Go to App Permissions and check the option;
4. Observe the description of those 2 options;

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- The description and links are cut.

#### Notes:
- Reproducing for other languages too.
![image](https://user-images.githubusercontent.com/15685960/111279947-ec47ee80-8643-11eb-9ba1-fef12d0df50b.png)

**Comment by jess-cook03** [comment]
@lesleyjanenorton we resolved this with that previous layout fix correct? Otherwise I will remove me as assigned

**Comment by ValentinaPC** [comment]
Verified as fixed on the last Android VPN build (2.3.0 - 16188100) while using French language.
Postfix screenshots below.
![appperm](https://user-images.githubusercontent.com/15685960/115223544-94a21480-a114-11eb-8247-f8308357baad.png)
