### ISSUE TITLE
`test-taskgraph-definitions` task has errors but isn't failing

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/mozilla-vpn-client#6952]
The `test-taskgraph-definitions` task has errors, but isn't failing. Example log:
https://firefox-ci-tc.services.mozilla.com/tasks/IUYUESHiQnK9KEivf2ALFw/runs/0/logs/live/public/logs/live.log

This has resulted in some regressions to the release promotion graphs slipping by unnoticed. It's possible the issue is that Taskgraph itself is returning 0 when there's a failure, in which case it should be fixed over there.. but maybe the task could be a bit more robust as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4837)

**Comment by ahal** [comment]
This is going to be fixed in https://github.com/taskcluster/taskgraph/pull/250

This issue will be closed by updating to a Taskgraph version containing that fix.

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Andrew Halberstadt it looks like that PR has merged. Can we close this as Done?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Adding Loon

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton is there something that QA can check here, or can we add the QA-not-actinable label? Thank you!
