### ISSUE TITLE
Ensure obligations for China are met

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#696]
We need to meet our obligations for service in China:
* We should not accept payments (systems integration problem, not strictly this repo)
* We should block connections

**Comment by birdsarah** [comment]
@tcinotto I believe you had some thoughts on the user experience for this.

**Comment by birdsarah** [comment]
@bakulf has clarified that VPN API should handle this.

**Comment by bakulf** [comment]
Right. We need to show a proper error, but this issue seems already fixed.

**Comment by birdsarah** [comment]
For the scenario: user downloads and subscribes in US but then travels to china.

If they left he app on and logged in, once they got to china they may be able to use the app for up to one hour. Every hour we run three tasks (https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/mozillavpn.cpp#L84-L86). One of these tasks is called TaskAccountAndServers and it contains two tasks: fetch the status of the user's account and fetch the server list. Both of these tasks are geo blocked and will cause everything to stop working.
