### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by Mikksrund** [mozilla-mobile/mozilla-vpn-client#6961]
https://vpn.mozilla.org/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4841)

**Comment by lesleyjanenorton** [comment]
hi @Mikksrund , was this a misfile? I'm going to close this because I can't tell what the issue is here.

**Comment by birdsarah** [comment]
@lesleyjanenorton this looks like spam. This happens periodically on our repo. You can report to our sec team. And you can report to github and delete the issue.
