### ISSUE TITLE
Language page has layout issues at scroll on iPad Air

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#700]
#### Affected versions:
v. 2.0.4 (202103160852)

#### Affected Platforms:
- iOS 14.02;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN;
2. Go in Settings->Language;
3. Scroll up through the page;

#### Expected result:
- There are no UI or layout issues.

#### Actual result:
- There are some layout issues.

#### Notes
- Not reproducing on small devices.

https://user-images.githubusercontent.com/15685960/111468188-f34b2b80-872d-11eb-943c-c8e540313d60.mp4

**Comment by bakulf** [comment]
@lesleyjanenorton can you work on this issue?

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build (2.202103181323) while using iOS 14.02.
There are no UI issues while scrolling in Languages page.
