### ISSUE TITLE
[L10n][DE] Download and Upload strings not translated in the informations screen

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#704]
#### Affected versions:
- v 2.0.4 (2.202103081839)
 
#### Affected Platforms:
- Windows 10 x64;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account with a subscription made for VPN;
 
#### Steps to reproduce:
1. Launch VPN;
2. Set the language to "German";
3. Click the information icon from the top-left corner of the window;
4. Observe the Download and Upload strings;
 
#### Expected result:
- The Download and Upload strings are translated to DE;

#### Actual result:
- the strings are not translated;
![image](https://user-images.githubusercontent.com/15685441/111507754-a9753c00-8753-11eb-995d-8201035a4eba.png)

**Comment by lesleyjanenorton** [comment]
Not sure what is up here but it does look like the strings are correctly updated when changing to other languages... 


<img width="368" alt="Screen Shot 2021-03-18 at 9 16 00 PM" src="https://user-images.githubusercontent.com/22355127/111722383-c41ce300-882f-11eb-8081-cb9938ddf660.png">
<img width="361" alt="Screen Shot 2021-03-18 at 9 16 24 PM" src="https://user-images.githubusercontent.com/22355127/111722412-cb43f100-882f-11eb-8a4d-07eec4a8e650.png">

**Comment by lesleyjanenorton** [comment]
Closing since seems to be related to the German translations and not the infrastructure.
