### ISSUE TITLE
Windows: Layout falls appart with MultiMonitor MultiDpi Setup

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#707]
1: Start VPN on Monitor with 150% scaling
2: Drag Window to Monitor with 100% scaling

Window size is off. Also if i repeat dragging the window gets bigger with every iteration. 🙈 
After 3x dragging
![grafik](https://user-images.githubusercontent.com/9611612/111621897-ce67be80-87e8-11eb-9d94-284762ef7299.png)

**Comment by lesleyjanenorton** [comment]
whoa!

**Comment by lesleyjanenorton** [comment]
I know we did some work to address other scaling issues on Windows, not sure if it's related.

**Comment by ValentinaPC** [comment]
I've tried to reproduce this, with the last build (2.202104200913) on Windows 10, using the mentioned scales, and I was not able to do it. The size of the VPN app was changing as expected while going back and forth between different scaling.
