### ISSUE TITLE
Uninstalling the VPN while the instance is opened does not close it 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#709]
#### Affected versions:
- v. 2.0.4 (202103171823); 

#### Affected Platforms:
- Linux;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;
- Have a VPN package ready for install;

#### Steps to reproduce:
1. Open the VPN and turn it on;
2. Double click on the package and pick “remove”;
3. Observe the opened VPN instance;

#### Expected result:
- The instance is closed.

#### Actual result:
- The instance remains open as if were not uninstalled;

#### Notes:
- the user might be confused about the fact that VPN did not got uninstalled.
- Changing the VPN status, triggers a “background service error” red banner;
- Quitting the app finalizes the uninstall process.

**Comment by bakulf** [comment]
This is a linux feature. A running application is kept running. There is nothing we can do here. Let's close this bug.
