### ISSUE TITLE
Revamp the App Store Image Carrousel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#7113]
This is relevant to the Market Expansion effort. Requirements are captured offline, in meetings between [~accountid:60c36ea48f2cc10069c8d993] [~accountid:615b125ac669a600695aeba2] [~accountid:62e6feee32850ea2a32368bb]  and [~accountid:637bcfc2fde064eda2ed7e61]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-4947)
┆Reporter: Santiago Andrigo

**Comment by hlsoto** [comment]
@peterbenvenuto Please provide an update on the status. thanks
