### ISSUE TITLE
VPN cannot be turned ON while local network access option is selected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#712]
#### Affected versions:
- v. 2.0.4 (202103181053); 

#### Affected Platforms:
- Linux;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN;
2. Go to Settings - Network settings option;
3. Select “Local network access”;
4. Turn ON VPN;

#### Expected result:
- The VPN is turned on.

#### Actual result:
- The VPN cannot be turned on and a red banner with “Background service error. Restore?” is displayed.

#### Notes:
- was reproducing on the previous build (3/17) also;
![image](https://user-images.githubusercontent.com/15685960/111755832-34fce300-88a2-11eb-9865-f328cf04e4a3.png)
[mozillavpn-2021-3-19.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6169841/mozillavpn-2021-3-19.txt)

**Comment by bakulf** [comment]
Fixed

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN stage build (2.2022103210816) while using Linux Ubuntu 20.04.
The VPN is turned ON with success, while having the Local network access option checked.
