### ISSUE TITLE
“No Signal” message displayed for few seconds when VPN app is back in focus

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#713]
#### Affected versions:
- v. 2.0.5; 

#### Affected Platforms:
- Android 11;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN;
2. Close the device or put the VPN in background;
3. Wait a few seconds and put the VPN back in focus;

#### Expected result:
- The VPN is ON and working.

#### Actual result:
- The VPN shows the “No signal” state for a few seconds.

**Comment by bakulf** [comment]
This has been fixed by @strseb 1 day ago.

**Comment by madalincm** [comment]
Verified the issue using Mozilla VPN version 2.1.0(16163980) on Android 9.0. After focusing back to the VPN the "No signal" state does not appear any more. Closing the issue as verified.
