### ISSUE TITLE
onboarding screen still mentions free trial on macOS

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/mozilla-vpn-client#7177]
**Describe the bug**
According to #6949 the free trial feature is disabled. But the onboard screen still mentions the free trial.

**VPN version:**
2.15

**Affected Platforms:**
macOS 13.4

**Steps to reproduce:**
1. Open the Mozilla VPN
2. log out if you're logged in

**Expected result:**
No mention of free trial

**Actual result:**
Free trial is mentioned (bold text in the screenshot).

**Additional notes:**
<img width="469" alt="Bildschirmfoto 2023-06-13 um 20 04 01" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/1100614/98871d45-abb0-4f30-960e-b339e7580466">

Can not be reproduced on Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5001)

**Comment by lesleyjanenorton** [comment]
Thanks for filing. Is it possible you have enabled this from the developer menu?
