### ISSUE TITLE
Replace “click here” with “click the Turn VPN on button” in the captive portal/unsecured network notifications

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#729]
#### Affected versions:
* v. 2.1.0; 

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN;
1. Check the “Unsecured network alert” option from Settings->Notifications;
1. Connect to an unsecured network or simulate it via localhost:8766;
1. See the notification description;

#### Expected result:
* The notification suggests that the user should click “the Turn VPN on button” to turn the VPN on.

#### Actual result:
* The notification suggests that the user should click “here” to turn the VPN on.

#### Notes:
* Same applies for Captive Portal notifications;
* User might get confused on where to click;

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-123)

**Comment by bakulf** [comment]
@jess-cook03 can you help us to define the right message here?

**Comment by jess-cook03** [comment]
#919 lets look these together I think #919 content solutions will help this issue for v2.4
cc @chrisrooneys

**Comment by jess-cook03** [comment]
This issue is linked to #919 lets track the latest there as I see thats most up to date

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

The spec for this issue is linked in https://mozilla-hub.atlassian.net/browse/VPN-150 ( https://mozilla-hub.atlassian.net/browse/VPN-150|smart-link ) 

CC Adrienne Davenport Pun Lam

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Is this issue still blocked?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on latest VPN 2.7 build while using Windows 10 and MacOS
The unsecured network notification still suggests that the user should “click here” to turn on VPN.

Reopening.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sebastian Streich The notification for Unsecured network still list the “click here“ strings. But, are we sure we wanna remove those strings? because for unsecured network we do not have additional screens inside the VPN, nor the “Turn VPN ON“ button.

!image-20220112-105019.png|width=1031,height=745!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Based on the below comment, we will mark this as verified and close it. If something else is decided, please let us know.
