### ISSUE TITLE
Mozilla VPN is displayed in English when the language selected for Windows OS is Spanish (Spain)

### ISSUE THREAD

**Issue by Bianca-O** [mozilla-mobile/mozilla-vpn-client#745]
**Affected versions:**
v. 2.1.0;

**Affected Platforms:**
Windows 10

**Prerequisites:**
Spanish is selected as Windows OS language.
Have a FxA account with active subscription for Mozilla VPN;

**Steps to reproduce:**

1. Open the VPN;
2. Observe the language that the VPN is displayed in;

**Expected result:**
VPN is displayed in Spanish.

**Actual result:**
VPN is displayed in English.

**Comment by bakulf** [comment]
We have disabled the feature.
