### ISSUE TITLE
The remove a device warning message from My devices menu is not accurate

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#752]
#### Affected versions:
- v. 2.1.0; 

#### Affected Platforms:
- all platforms;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;
- Connect to VPN using the same FXA account on at least 5 devices;

#### Steps to reproduce:
1. Open the VPN on a 6th device and log in with the same account;
2. Open the My devices menu and observe the warning message;

#### Expected result:
- Because the vpn is already installed the message should be: "You've reached your limit. To **turn on** the vpn on this device...";

#### Actual result:
- The message displayed is: "You've reached your limit. To **install** the vpn on this device...";

![image](https://user-images.githubusercontent.com/15685441/112463402-db495c80-8d6a-11eb-9e0d-49f369bfbc96.png)

**Comment by bakulf** [comment]
@jess-cook03 can you help here?

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton lets go with the proposed: "You've reached your limit. To **turn on** the vpn on this device..."
