### ISSUE TITLE
Elapsed time is not tracked while the device is blocked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#753]
#### Affected versions:
- v. 2.1.0 (202103251027)

#### Affected Platforms:
- iOS 14.02;

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Open the VPN;
2. Turn it ON;
3. See elapsed time;
4. Block the device;
5. Wait 2 minutes;
6. Unblock the device;
7. See elapsed time;

#### Expected result:
- Elapsed time is correct. The 2 minutes from STR5 are counted.

#### Actual result:
- Elapsed time is the same as it was before blocking the device.

#### Notes
- Might be confusing and suggest that VPN was not working meanwhile;
- Not reproducing on Android;

**Comment by bakulf** [comment]
The elapsed time was added for that reason. Durning the blocking device, the VPN was not actually active.
@jess-cook03 what do you suggest here?

**Comment by rbillings** [comment]
Needs feedback from UX.

**Comment by jess-cook03** [comment]
@bakulf  I would imagine if the VPN was not active during the device block than the time would be the same as it was before. If the VPN is not active during that time than we shouldn't show more-false time.....

So therefore I think that this is performing as expected.

Let me know if I'm not understanding this correctly!

**Comment by ValentinaPC** [comment]
@bakulf @jess-cook03 
Then, we should change the way it behaves on the other platforms too, as we show false time on Android, Win, Mac.

As a side note here: maybe we should consider having the VPN on, while device is blocked, as there are apps that run in this state and might need the VPN, for security reasons.

**Comment by ValentinaPC** [comment]
We can mark this as verified fixed based on #1263 fix.
