### ISSUE TITLE
VPN Languages are not alphabetically ordered

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-mobile/mozilla-vpn-client#754]
**Affected versions:**
- v. 2.1.0;

**Affected platforms**
- Windows 10

**Prerequisites:**
- Have the VPN app installed;
- Have a FxA account with active subscription for Mozilla VPN;

**Steps to reproduce**
1. Open the VPN 
2. Go to Settings -> Language.
3. Check how the available languages are displayed.

**Expected results**
- The languages are alphabetically ordered.

**Actual Results**
- The available languages are randomly displayed.

![Screenshot_21](https://user-images.githubusercontent.com/18114210/112476189-51a18b00-8d7a-11eb-805e-05f6009864a0.png)

**Comment by bakulf** [comment]
@jess-cook03 currently the languages are sorted by code. But maybe we should sort them by name.
As you can see we have 2 language names: native and translated. What do you think would the right sorting?

**Comment by jess-cook03** [comment]
@lesleyjanenorton @bakulf having the languages alphabetically ordered makes most sense to apply here -- I agree.

**Comment by lesleyjanenorton** [comment]
@jess-cook03 thanks! is your preference that these be ordered alphabetically by their translated name ("German", "Spanish", etc) or native name ("Deutsch", "Espagnol") ?

**Comment by jess-cook03** [comment]
@lesleyjanenorton Alphabetical by the native name - sorry I didnt mention this before

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage v 2.1.0 (2.202104060900) under Windows 10 64-bit. I confirm that the VPN languages are correctly ordered by the native name.

![Screenshot_18](https://user-images.githubusercontent.com/18114210/113696405-9f06ec00-96da-11eb-8663-e7c7d7202f9d.png)
