### ISSUE TITLE
VPN opens 2 windows when connect on startup is enabled.

### ISSUE THREAD

**Issue by JKingZapata** [mozilla-mobile/mozilla-vpn-client#7568]
On Mac VPN 2.15 opens 2 windows when the connect on startup setting is enabled. Confirmed MozillaVPN in login item on system settings is only listed once. Resetting VPN through developer options and reinstalling does not help.

Does it impact functionality or aesthetics? Yes
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Very annoying to see 2 VPN windows open at the same time
Does it degrade the user experience significantly? No
Is it legally sensitive? No

**Centrality**
Is it on a core user journey or on a secondary one? Secondary journey

Technical Information

Platform: macOS 13.4.1
FX product Mozilla VPN
Version 2.15
Region/Languages
Network type 

**Steps to Reproduce**
- Have a VPN subscription and install VPN
- Enable VPN connect on startup setting
- Restart device

**Actual Results**
- After device restarts, 2 VPN windows open and connect

**Expected Results**
- Only 1 App window should open and connect

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5248)

**Comment by JKingZapata** [comment]
[mozillavpn-2023-7-19 (first instance after startup).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/12114009/mozillavpn-2023-7-19.first.instance.after.startup.txt)

[mozillavpn-2023-7-19 (Second instance 10 seconds later after startup).txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/12114011/mozillavpn-2023-7-19.Second.instance.10.seconds.later.after.startup.txt)

<img width="719" alt="KCR9MLhJDlddzcM0" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/72564534/1d55aa9d-8f0e-4bcd-a7ce-6fc38176386f">

<img width="185" alt="c2eXqKdJpIDB2O8Y" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/72564534/537acedd-920f-48c1-920f-ad852dded7a9">

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

cc Santiago Andrigo for priority here

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Is this reproducible on your end Lesley Norton Matt Cleinman ?
I’m surprised two windows could open, since opening the same binary again should simply pop the UI back to the foreground, no?

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Santiago Andrigo I have never experienced this.

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

I tried last week, and was unable to replicate.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

We are also unable to reproduce this issue. Instead, on macOS 13.4.1 the following behavior is reproducing (but not on macOS 12.6.6): https://mozilla-hub.atlassian.net/browse/VPN-4126 ( https://mozilla-hub.atlassian.net/browse/VPN-4126|smart-link )

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Downgrading to ‘Low’ as it’s support-low and ultimately is just inconvenient. 
When it happens again, can we get logs please? Juan Zapata

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Santiago Andrigo no problem, here is another set of logs from a different user 

[^mozillavpn-2023-7-25.txt]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

I can reproduce the issue on my Mac as well, OS 13.5

[^mozillavpn-2023-7-26.txt]

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Juan - Good to know. I’m also on 13.5, so maybe we can get to the bottom of this:

On your machine, can you confirm:

  * How did you install Mozilla VPN? Which version are you running?
  * That the in-app option to Start on Boot is enabled?
  * Provide us a screenshot of the “Login items” in system settings (under General)?

Thanks!

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Remembering this work: https://mozilla-hub.atlassian.net/browse/VPN-4307 ( https://mozilla-hub.atlassian.net/browse/VPN-4307|smart-link ) 

Leaving this here for me to dig into in a bit.

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Matt, here’s the requested info:

  1. VPN 2.15 fresh install, downloaded from the VPN homepage https://www.mozilla.org/en-US/products/vpn/download/ ( https://www.mozilla.org/en-US/products/vpn/download/|smart-link ) 
  2. Connect VPN on startup option is selected from the app
  3. Screenshot of the login items from Mac settings 
!Screenshot 2023-07-27 at 07.28.23.png|width=1440,height=900!

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

This is what I see. The difference here is probably it. I’d love to dig into this in the next sprint.

!Screenshot (4d075a89-f7f3-4bad-9854-d75bbf1a0eb7).png|width=481,height=187!

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Issue still happening on 2.16. attaching user logs for review

[^mozillavpn-2023-9-6.txt]

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Upgrading to Medium.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is still happening using Mozilla VPN 2.19.0 (2.202311132237) while on macOS 14. 

This is very easy to reproduce: clean install, check/uncheck/check the “start on boot“ option => two Mozilla VPN instances.

The device does not require a restart to reproduce this.

Santiago Andrigo I would say this is confusing for user and a “high“ priority.

!Screenshot 2023-11-14 at 12.58.49.png|width=2880,height=1800!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Upgrading.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Downgrading to Medium since:
1. It didn’t reproduce for Lesley.
2. The behavior of check/uncheck/check is not the usual flow.
3. It doesn’t unprotect users.

Is this deterministic on your end? Does it happen if you don’t do a clean install?

Juan Zapata

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton What MacOS version do you have? Thanks!

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Santiago Andrigo we haven’t had further user reports for over a month. However, issue is still reproducible on my end after updating from 2.16 to 2.18 (no clean install) on macOS 14

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Juan Zapata with a clean install, a check-uncheck-check of the Connect on start up option, do you reproduce the issue? Thank you!

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Valentina Virlics yes, issue persists even after a clean install. Similar to how you report it, the second window opens after checking Connect on Startup (in my case it opened after checking it once)

!Screen Recording 2023-11-20 at 07.54.42.mov|width=2180,height=1548!

**Comment by RichardValerosoUniverse** [comment]
🧅😘🫰🐈😆

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified as fixed using 2.20.0 (2.202401041847) build on macOS 14 - M1.

If the option is checked-unchecked multiple times, the client does not duplicate.
