### ISSUE TITLE
error: Failed dependencies: libQt6Network.so.6(Qt_6.5.1_PRIVATE_API)(64bit) is needed by mozillavpn-2.15.3~rc20230711201611-1.x86_64

### ISSUE THREAD

**Issue by devurandom** [mozilla-mobile/mozilla-vpn-client#7598]
**Describe the bug**

Trying to install Mozilla VPN on Fedora 38 fails with an error:
```
❯ sudo rpm -i RPMS/x86_64/*
error: Failed dependencies:
	libQt6Network.so.6(Qt_6.5.1_PRIVATE_API)(64bit) is needed by mozillavpn-2.15.3~rc20230711201611-1.x86_64
```

**VPN version:**

2.15.3

**Affected Platforms:**

Fedora 38 (Linux)

**Steps to reproduce:**

1. Download RPM from https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/5524461414
2. Extract ZIP file
3. `sudo rpm -i `RPMS/x86_64/*`
4. Observe error

**Expected result:**

Installation succeeds.

**Actual result:**

Installation fails with an error:
```
❯ sudo rpm -i RPMS/x86_64/*
error: Failed dependencies:
	libQt6Network.so.6(Qt_6.5.1_PRIVATE_API)(64bit) is needed by mozillavpn-2.15.3~rc20230711201611-1.x86_64
```

**Additional notes:**

I see that the RPM was built using Fedora 37: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/4b7f3f28c8abcdec18df94f3659b14e8323fddf0/.github/workflows/linux.yaml#L47

The Fedora 37 RPM `qt6-qtbase` provides `libQt6Network.so.6(Qt_6.5_PRIVATE_API)(64bit)` but not `Qt_6.5.1_PRIVATE_API`: https://packages.fedoraproject.org/pkgs/qt6-qtbase/qt6-qtbase/fedora-37-updates.html#provides
Fedora 38 or Rawhide versions of the RPM do not provide that symbol, either.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5270)

**Comment by devurandom** [comment]
Installing a 2.16 RC works, probably because it was built against a refreshed version of the qt6-qtbase packages: https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/5624135650

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

As per the user report, this works on 2.16
