### ISSUE TITLE
Devices View - Consider updating list order from "Added X days ago" to  "Last used X days ago" 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#762]
<img width="357" alt="Screen Shot 2021-03-29 at 11 35 00 AM" src="https://user-images.githubusercontent.com/22355127/112869460-cd554d80-9082-11eb-9f99-7d51833a2c5b.png">

When a customer is being asked to remove a device, it might be more helpful if the list were ordered by "last used" instead of "last added".

**Comment by bakulf** [comment]
This requires a new API endpoint to store the last VPN activation because we do not store the last VPN usage (per device) yet. The concern I have is that this is an extra log per user.

**Comment by rbillings** [comment]
Needs feedback from UX.

**Comment by rbillings** [comment]
Closing, we considered and decided not to do it.

**Comment by rbillings** [comment]
This is more complicated than updating a string, so it's a lot of work. In the future we can update the string if we choose to.
