### ISSUE TITLE
Implement in-app surveys (logic + UI)

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#763]
It would be great to collect some feedback from customers about what they think is working and where they would like to see improvement.

**Comment by jess-cook03** [comment]
Update met with Baku yesterday to discuss in depth:

**Proposed solution:**
For the user to see it and then dismiss it in app using our banner component makes the most sense from an interaction stand point. And also for our goals for the survey, we want users to see it so an in-app notification feels like the best solution here.

However talking with Baku and knowing the timeline with this work (q3).....there are more things to consider and explore here.
- Desktop vs. mobile treatment do we do in-app treatment for both or just for mobile and keep system notifications for desktop? 
- I think doing an A, B test on this would answer all of our questions and confirm what solution will work best 
A) being in-app across all platforms
B) being system notifications
- How does an in-app notification look when there are multiple banners in-app? Do we assign priority to these messages (I think yes - idea there would be: 1) error first 2)update 3) survey)

**Needs/questions/to do:**
- [ ] Survey content... need to define scope with team and understand what we want to accomplish

- [ ] Jess needs to create design document around this and mockups/visuals to support this solution

- When do we trigger surveys?
- Do we send a reminder if they don't do it after a while?

**Comment by jess-cook03** [comment]
Hi! Checking in on the status of this? I see it has been moved to in progress. Thanks!

**Comment by bakulf** [comment]
See #970

**Comment by jess-cook03** [comment]
MVP design solution ready!
@dianahorn annd Gloria and Brian to work through the content needs for the survey
@chrisrooneys review UX writing on the notifications.

**Comment by jess-cook03** [comment]
![survey banner](https://user-images.githubusercontent.com/54991698/118007079-cecc9380-b319-11eb-93eb-a9f11b3f1b4a.png)

@bakulf @lesleyjanenorton 
String confirmed by @chrisrooneys 
This would mark this UI complete and ready for v2.3

**Comment by ValentinaPC** [comment]
Verified this across platforms, while using the last VPN 2.3.0 builds.
The banner is prompted with success. It is also localized (fr, de and others). It redirects to Mozilla VPN homepage, for now.
We can mark this as verified.
