### ISSUE TITLE
Consider adding Glean Telemetry

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#765]
I would really love some telemetry :) 
E.g. to measure how many People on android are really hitting the "fallback" web-auth case.

**Comment by bakulf** [comment]
This is a complex decision. VPN clients are often log-free. If we decide to implement this feature, we need have a way to disable it entirely. And maybe keep it disabled by default.

**Comment by rbillings** [comment]
We need feedback from marketing.

**Comment by bakulf** [comment]
There are 3 things to do here:
- have a proper UX to allow the user to enable/disable the telemetry
- include glean.js
- define the telemetry events/ids

About glean.js, there are a couple of missing pieces. The main one is that glean.js doesn't allow the use of custom storage jet. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1702419

**Comment by birdsarah** [comment]
I've assigned myself for now as I've been given the initial task of starting to think about what telemetry we might want to start collecting to help build a better product.

**Comment by bakulf** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1706103

**Comment by birdsarah** [comment]
Assigning to @bakulf. See PR #897

**Comment by jess-cook03** [comment]
UX effort here is XLarge, as there is discovery work needed here to understand what we all want to collect and also what we can/should collect from a Mozilla policy and business decisions need to be made as well.
cc @dianahorn

**Comment by jess-cook03** [comment]
@jess-cook03 create another ticket for UX part of this -- discovery to circle back on data points from user perspective

**Comment by ValentinaPC** [comment]
Verified this across platforms using the last VPN 2.3.0 build.
The telemetry screen was added before authentication.
Some issues were found, but are tracked separately.
We can mark this as verified.
