### ISSUE TITLE
Clicking on the disconnected notification after quitting the app relaunches it

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#768]
#### Affected versions:
- v 2.1.0 (2.202103261745);
 
#### Affected Platforms:
- macOS 10.15.7;
 
#### Prerequisites:
- Have a FxA account with an active subscription for Mozilla VPN;
- Have VPN installed;
- have VPN turned on;
 
#### Steps to reproduce:
1. Quit the app (right click on the icon in taskbar or command+Q);
2. Click the VPN Disconnected notification;
 
#### Expected result:
- Nothing happens, the VPN remains closed;
or
- No disconnected notification is displayed when quitting the VPN;
 
#### Actual result:
- The app is relaunched upon clicking on the notification.

**Comment by bakulf** [comment]
@jess-cook03 I would like to know your thoughts about this issue.
A bit more context: the app doesn't "quit" when the user does Command+Q. It just hides. If the app quits for real, the VPN tunnel disconnects. The app is still accessible via the system-tray icon (menubar icon).

So, what does happen if the user clicks on the notification? Should we just ignore the click? Or show the app again?

**Comment by jess-cook03** [comment]
@bakulf I was informed by @peterbenvenuto that this issue should already now be resolved and the expected behavior is the following:
- Command + Q will quit the app and disconnect
- and therefore the disconnected notification if clicked by the user will only reopen the app window but not reconnect them and turn the VPN back on

I am going to say its safe to close this issue :)

**Comment by ValentinaPC** [comment]
@peterbenvenuto @bakulf 
Clicking the "Quit Mozilla VPN" option from app tray menu while VPN ON, closes the VPN and removes the icon from the tray. Clicking on the disconnect notification, relaunches the app, while being off. Is this ok?
If we do the exact steps with VPN off, there is no disconnect notification (as the VPN is already disconnected), therefor no notification to click and nothing to happen after.
From my point of view, clicking on the disconnect notification should not do anything.
