### ISSUE TITLE
Localize server country and city names 

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#769]
It would be great to localize the server list country and city names. These names are pulled from Mullvad so we'll need to figure out...

1.) How should these strings be localized? Should we use Pontoon or is there an api we could make use of? 
2.) What happens when/if Mullvad adds a server in a new country/city?

**Comment by jess-cook03** [comment]
I can add some context to this issue:

Improve user experience by translating the country and server names as shown in the screen grab below ---
![Image from iOS](https://user-images.githubusercontent.com/54991698/113319355-55d02a00-92df-11eb-9a60-b9b954018c12.png)

**Comment by birdsarah** [comment]
This will also be an issue for any status page that we stand-up.

**Comment by bakulf** [comment]
I would use a trusted source of truth such as WikiData (the semantic-web media-wiki of Wikipedia). We can run queries to retrieve the country/city names translated. Here is an example:

Extract the country name + the language code of a resource, instance-of (wdt:P31) Country (wd:Q6256).

```
SELECT ?countryName (lang(?countryName) as ?lang)
WHERE 
{
  # wdt:P31 is: "instance-of"
  # wd:Q6256 is: "country"
  ?country wdt:P31 wd:Q6256 ;
           rdfs:label ?countryName ;
           rdfs:label "Italy"@en .
}
```

https://query.wikidata.org/#SELECT%20%3FcountryName%20%28lang%28%3FcountryName%29%20as%20%3Flang%29%0AWHERE%20%0A%7B%0A%20%20%23%20wdt%3AP31%20is%3A%20%22instance-of%22%0A%20%20%23%20wd%3AQ6256%20is%3A%20%22country%22%0A%20%20%3Fcountry%20wdt%3AP31%20wd%3AQ6256%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3FcountryName%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%22Italy%22%40en%20.%0A%7D

**Comment by strseb** [comment]
Should be done with #783
