### ISSUE TITLE
Localization for city/country names are out of date

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/mozilla-vpn-client#7698]
This file hasn't been updated in a while, so new locales are not covered.
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/apps/vpn/translations/extras/servers.json

Not sure if there's a script that needs to be manually run, similarly to what happened in #7663 for language names.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5325)

**Comment by flodolo** [comment]
The file is now here, but I don't think it's been touched beyond the folder reorg
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/translations/extras/servers.json

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton Does this need QA verification? If yes, could you please provide more details? Thank you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this while checking the cities from the servers list inside the client while using v. 2.21 (2.202403151700) build.

The locations that were previously not localized, are currently localized (i.e Boston), and the new locations have the same issue. (i.e. McAllen, TX).

For the previous locations we had this tracking ticket: https://mozilla-hub.atlassian.net/browse/VPN-5512 ( https://mozilla-hub.atlassian.net/browse/VPN-5512|smart-link ). 

I’ll close that, as those servers are currently localized, and …log a more general one for the new locations? What do you think, Lesley Norton?

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Valentina Virlics sorry, are you saying there are still unlocalized server locations? please do file a new ticket if that is the case and I will take care of it today. thanks!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Lesley Norton I am saying that if this issue refers to the servers being localized or not, than yes, the new servers are not, and the example is “McAllen, TX“, that is new server and contains the state abbreviation, and should not.

!image-20240319-100621.png|width=494,height=174!

While looking in the location Francesco Lodolo linked below, this new server is not listed.

We assume that if this is a script and it is run manually/automatically, maybe the server was added after last run?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Based on below comments and the follow up ticket ( https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/issues/VPN-6258?jql=project%20%3D%20%22VPN%22%20ORDER%20BY%20created%20DESC ) Lesley Norton logged, we can mark this as Done.
