### ISSUE TITLE
Icon does not show up on taskbar after install

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#771]
Icon did not show up on the taskbar correctly after install (looked like an empty white square). After closing window, once VPN icon in sys tray clicked on, the icon showed up correctly on taskbar.

From: Brian Yee
platform: Windows

**Comment by bakulf** [comment]
Can you provide a screenshot to understand better?

**Comment by rbillings** [comment]
This no longer repros. Closing.
