### ISSUE TITLE
Linux Focal unmet dependency for QT

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#772]
UNMET DEPENDENCY IN .deb PACKAGE: Attempted to install client with sudo dpkg -i mozillavpn_2.1.0-focal1_amd64.deb . Failed with "dpkg: dependency problems prevent configuration of mozillavpn:
 mozillavpn depends on qt515websockets (>= 5.15.2-1basyskom1); however:
  Package qt515websockets is not installed.
This is likely related to the way that packaging for QT has changed - https://medium.com/@DrKaoliN/using-travis-ci-for-qt-projects-3121d723be12. It took me about an hour to get all the deps installed - I documented it in this file:
https://medium.com/@DrKaoliN/using-travis-ci-for-qt-projects-3121d723be12

Found by: Kathy Reid
Platform: Linux Focal

**Comment by rbillings** [comment]
Client fails to launch, fails on more Qt5 dependencies: kathyreid@kathy-ROG-Zephyrus-G15-GA502IV:~/Downloads$ mozillavpn
mozillavpn: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by mozillavpn)
mozillavpn: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /opt/qt515/lib/libQt5Charts.so.5)
mozillavpn: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /opt/qt515/lib/libQt5WebSockets.so.5)
mozillavpn: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /opt/qt515/lib/libQt5NetworkAuth.so.5)

**Comment by mckaymatt** [comment]
I'm having the same problem also on 20.04.
```
# apt install mozillavpn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mozillavpn : Depends: wireguard (>= 1.0.20200513-1~18.04.2) but it is not installable
              Depends: wireguard-tools (>= 1.0.20200513-1~18.04.2) but it is not installable
              Depends: resolvconf (>= 1.82) but it is not installable
              Depends: qt515imageformats (>= 5.15.2-1basyskom) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by bakulf** [comment]
These are 2 different problems:
- installing packages by hand using `dpkg` does not install dependencies. The right way to install mozillavpn on Linux is how is written in the documentation.
- for the @mckaymatt issue, I would like to know more. Can you tell me what happens if you do: `apt-get update && apt-get dist-upgrade && apt-get install mozillavpn` ?

**Comment by mckaymatt** [comment]
@bakulf I had the exact same issue as before. I use the Dell variant of Ubuntu 20.04 so maybe that's part of it, but It shouldn't be different.

I tried installing it in a 20.04 Docker image and got a different issue.

**Comment by mckaymatt** [comment]
Update I got this installed. The issue was that Dell does not support my device on 20.04 after all. I just switched off the OEM ppa and the install worked.

**Comment by bakulf** [comment]
Thanks for sharing this!
I close the bug.
