### ISSUE TITLE
No option to contact support if user's payment method fails

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#773]
If a user hits the page where they receive an error that their currency isn't supported, there is no way to contact support or get help.

**Comment by bakulf** [comment]
@jess-cook03 can you take a look?

**Comment by ValentinaPC** [comment]
If the user cannot subscribe from inside the VPN app, he can "Cancel" the subscription check from the app and has the possibility to contact support from the "Get Started" screen.
![subscr](https://user-images.githubusercontent.com/15685960/113718475-590b5180-96f5-11eb-8539-88085eeebef9.png)

Things change while hitting this error from the webpage.

**Comment by rbillings** [comment]
This issue is for the initial subscription process, where payment fails and the user then does not have an account to contact support. This is prior to downloading the product.

**Comment by ValentinaPC** [comment]
Yes, but maybe we should change the repo for this (maybe log it in Jira under FxA). For visibility.

**Comment by rbillings** [comment]
Good point - I'll file it in FxA.
