### ISSUE TITLE
We should track failures to sign up

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#774]
We should track, using telemetry or some other measure, how often users fail to sign up for VPN.

**Comment by rbillings** [comment]
This could apply to a lot of different failures, potentially have a review by the data team. Also involves FxA and SubPlat.

**Comment by rbillings** [comment]
This needs more clarification of our needs.

**Comment by bakulf** [comment]
We are instrumenting glean.js to collect telemetry events. This issue is covered by #765
