### ISSUE TITLE
Select location is hard to scroll because it's overly sensitive

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#776]
The "Select location" screen is hard to scroll because it overly sensitive to touchpad scrolling.

Found by: cpeterson
Platform: Windows

**Comment by lesleyjanenorton** [comment]
The language list is affected as well.

**Comment by rbillings** [comment]
This applies to all of the lists on Windows. Known QT bug.

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.2 (2.202104211853) while using WIndows 10.
Scrolling using touch pad works as expected inside the VPN screens.
