### ISSUE TITLE
Obstructed string when switching servers

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#777]
When switching servers (and the "vpn.controller.connectingState" string is shown), the "Masking connection and location" string is partially hidden behind the toggle switch.

Found by: cpeterson
Platform: Windows

<img width="315" alt="Screen Shot 2021-04-05 at 10 17 50 AM" src="https://user-images.githubusercontent.com/737878/113602980-36dfd980-95f8-11eb-9013-ff969d4250e4.png">

**Comment by bakulf** [comment]
We need to generate a new windows package with the latest strings.

**Comment by ValentinaPC** [comment]
@rbillings could we find out what version is Chris using? Because, on the last public version, that is now available to the users, the strings are as expected. 
Thanks in advance!

**Comment by rbillings** [comment]
We confirmed it was an old build, and QA verified that the strings have been updated and no longer have the UI issue described here.
