### ISSUE TITLE
Suggest taskbar action on single click

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#779]
Clicking the Mozilla VPN icon in the Windows taskbar does nothing. Double-clicking the icon opens the VPN app, but double-clicking a taskbar icon is not a standard action. I only discovered that double click works because my first click did nothing and I thought I might have clicked the wrong icon.

Found by: cpeterson

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN build (2.202104200913) while using Windows 10.
The VPN app is displayed after clicking its icon from tray.
