### ISSUE TITLE
Breakpad Error

### ISSUE THREAD

**Issue by dtl131** [mozilla-mobile/mozilla-vpn-client#7813]
I know this could be more of a help request than a bug report, but for some weeks now, I keep getting hung up on this error, which doesn't seem to have any obvious solution or package to install to fix it:

-- Looking for getcontext - found
-- Configuring done (1.0s)
CMake Error at external/CMakeLists.txt:122 (target_sources):
  Cannot find source file:

    breakpad/src/common/convert_UTF.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc

CMake Error at external/CMakeLists.txt:121 (add_library):
  No SOURCES given to target: breakpad_client

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5410)

**Comment by oskirby** [comment]
The `3rdparty/sentry` submodule includes some nested modules which appear not to have been initialized. Could you try doing a `git submodule update --init --recursive` to see if that solves the problem for you?
