### ISSUE TITLE
Get started link opened blank page

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#782]
Clicking the app's "Get started" button opened a URL in my Firefox, but the page was blank and never finished loading. I have two Firefox Accounts: a personal account I use for Firefox and an @mozilla.com account I created for testing VPN. Perhaps the login URL is getting confused by the two accounts?
https://accounts.stage.mozaws.net/authorization?client_id=XXX&redirect_uri=https%3A%2F%2Fstage.guardian.nonprod.cloudops.mozgcp.net%2Foauth%2Fsuccess&scope=profile&response_type=code&state=pkce2-bd2eff9cf21c5338508fe29ff7b1e6e8e5541d74fe9575d2ad01fabaace7059be00ef7d499104aaf&access_type=offline&action=email

Found by: cpeterson

**Comment by rbillings** [comment]
FxA issue, able to repro on an old version Android 5 with default browser on an emulator.

**Comment by birdsarah** [comment]
Steps I use to reproduce:
- In Android Studio create emulator for Android 5, 6, 7
- Open emulator
- Open default browser
- Go to accounts.firefox.com 
- See blue spinning wheel

Same steps for Android 8 and 11 and accounts.firefox.com loads normally. I didn't bother testing the distros in between as I assume they're good.

cpeterson may not have been on android.

**Comment by birdsarah** [comment]
I may have conflated two issues.

cpeterson was on Nightly on MacOS on a stage build and saw an actual blank screen. I am seeing a blue spinning wheel on old android.

**Comment by rbillings** [comment]
I filed https://github.com/mozilla/fxa/issues/8176 so will close this issue.
