### ISSUE TITLE
Random VPN connection loss

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#7830]
For several months, but officially reported on 2.15, user experiencing random connection loss regardless of which server they are using. At times the VPN disconnects after 5-10 mins and reconnects on its own, but other times they need to manually restore the connection. According to user, it happens regardless of the network activity they are doing (from normal browsing to video calls ) Affecting only user's Linux devices on the same network. Issue does not occur on iOS device that connects to the same network. Issue persists after updating to 2.16. 

Tried:
1. uninstalling/reinstalling, resetting VPN through the developer options, installing system updates,

2. No third-party VPN, firewall or antivirus installed

3. Restarted router, firmware updated and no integrated firewall installed

Does it impact functionality or aesthetics? Functionality
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Very annoying
Does it degrade the user experience significantly? Yes
Is it legally sensitive? No

**Centrality**
Is it on a core user journey or on a secondary one? Core journey

**Technical Information**

Platform Ubuntu 22.04
FX product: Mozilla VPN
Version 2.15 and 2.16
Region/Languages
Network type (Mobile/Wifi/Wired)

**Steps to Reproduce**

1. Install VPN
1. Connect to desired server
1. Leave VPN On
1. Watch VPN’s connection

**Actual Results**

At random, the VPN disconnects

**Expected Results**

Connection should remain On

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-5417)
┆Reporter: Juan Zapata

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this while using the latest 2.17 build, on Ubuntu 22.04 and noticed that after awaking the device from standby, the timer shows less time than expected. 

It could be a silent switch maybe? Naomi Kirby 

I am attaching logs as well - time of the timer reset ~ 10:52->10:53

[^mozillavpn-2023-8-25.log]

I’ve reproduce it with/without the “start on boot” feature on.

I did not reproduce the have-to-“manually restore the connection“ part. Every time the VPN was already ON and connected.

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

Thanks for the debugging efforts here Valentina Virlics

**Comment by keithfancher** [comment]
Not sure if these GH issues are meant to be public-facing, but I am a real user in the wild experiencing this issue. Seems pretty major, especially given the kill switch does NOT activate in these cases. My internet just keeps working fine, with the VPN having silently disconnected, showing a "Something went wrong..." error on the client.

**Comment by mdimd** [comment]
I am also experiencing this problem regularly. The client silently gores into  "Something went wrong..." but the device still has internet access with the local IP exposed. A kill switch feature should configure the routing to make this impossible. There is no value in using a VPN if it can't be trusted to protect the IP. 

Mozilla VPN release:  2.17.0 (2.17.0-jammy1)
OS: Linux Mint 21.2 Cinnamon

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Juan Zapata Is there a way to reliably test a fix for this? There is a good chance that the ongoing work for VPN-5612 will address this but I don’t have access to a Linux machine to test.

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Gela Malek Pour maybe I can help, I have Linux VM with Ubuntu 22.04, though only have access to the VPN on production

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Gela Malek Pour We were not able to repro this in the first place. 

We also investigated this today on Linux Focal, Mantic and Jammy, using the latest 2.18.0~rc20231019205659 builds from release branch.

While logged into the client with VPN ON on all of the 3 devices - 2 VMs and 1 physical machine - no connection loss was noticed. All devices are in the same network.

The only thing that can be observed is that after awaking the devices, the timer shows smaller values that it should → a timer reset happened - this happens intermittently.

Please let us know f other checks are required.

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Thank you, Valentina Virlics I think this should suffice, thank you for testing!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Fulfilled by VPN-5612
