### ISSUE TITLE
Suggest adding strings to replace state messages

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#784]
Suggest replacing these messages with strings:

Missing string when switching servers: vpn.controller.connectingState
Notifications screen: vpn.settings.unsecuredNetworkAlert, vpn.settings.unsecuredNetworkAlert.description, and vpn.settings.notificationVpnMustBeOff

Found by: cpeterson

**Comment by bakulf** [comment]
Duplicate of https://github.com/mozilla-mobile/mozilla-vpn-client/issues/777
