### ISSUE TITLE
Suggest editing link to Support info for VPN

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#786]
Clicking the Help > "Contact us" menu item opens the FxA settings page with no instructions for how to contact Mozilla about VPN. https://accounts.firefox.com/settings

Steps:
Right-click on the Mozilla VPN icon in the Windows system tray > Select "Help" > Select "Contact us". 

Expected result: link goes to a page with Support options
Actual: link goes to settings which does not include Support options

Found by: cpeterson

**Comment by ValentinaPC** [comment]
Following the steps mentioned above: "Mozilla VPN icon in the Windows system tray > Select "Help" > Select "Contact us"." :
- user is asked to sign in using FxA production account, if that exists and has a subscription, is redirected to the Contact Support page.
- if the user does not have a subscription for that production account, the fallback is the FxA Settings page -> as Contact Support is accessed for a specific product, from Manage Subscriptions page.

Hope I was able to clarify things.

**Comment by cpeterso** [comment]
> if the user does not have a subscription for that production account, the fallback is the FxA Settings page -> as Contact Support is accessed for a specific product, from Manage Subscriptions page.

I think I was testing with staging, so that might explain why I saw the FxA Settings page instead of the Contact Support page.

**Comment by rbillings** [comment]
Closing as the extra details show this was expected.

**Comment by ValentinaPC** [comment]
@cpeterso Yeah, staging also asks you to sign with prod account while clicking the "Help" >"Contact us" option. There isn't a stage page for this.
