### ISSUE TITLE
[MacOS] Installer prompting to install Rosetta 2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#7914]
We’ve been shipping a universal binary with 2.16. 

Expceted: Therefore Rosetta 2 should not be requested to be installed alongside. 

Actual: Rosetta 2 is required when opening the installer. 

[https://github.com/mozilla-mobile/mozilla-vpn-client/issues/286#issuecomment-1703937187](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/286#issuecomment-1703937187|smart-link)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-5473)
┆Reporter: Basti

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Is this the ticket Matt was asking in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7913#issuecomment-1707174761 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7913#issuecomment-1707174761|smart-link ) ? Basti

**Comment by data-sync-user** [comment]
➤ Basti commented:

Yes! 🙂 

So if you have a “fresh” MacOS Installation on an M1/M2 Macbook and try to install the vpn, the OS will ask to install rosetta, which is a helper to run “old” intel apps on the new macbooks. 

We no longer need that, but the installer still asks users to have it.  

!image-20230906-120838.png|width=960,height=466!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Basti Would you mind adding a “fixVersion” to the Merged tickets so that we know where/when to verify them? Thank you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Basti We’ve went back to previous versions and checked this with 2.8.3/2.15/2.16 on an M1 MacOS 13 device and we were not able to see the Rosetta popup. We asked other Mozilla colleagues with M1, that did not had Mozilla VPN ever installed, to verify this and the popup was still not displayed - so we cannot confirm that this is indeed fixed.

I can only confirm that I am still not able to see the popup with the latest 2.17(2.202309071903) build.

Please let me know if any other checks are required here. Thank you!

**Comment by yungchin** [comment]
Hi Valentina, you won't be prompted to install Rosetta if you've already got it installed for other reasons -- could that be the explanation?

I've seen the pop-up for 2.16 on my system. Is this 2.17 build accessible to non-Mozilla folks, so I can help check for you?

**Comment by data-sync-user** [comment]
➤ Basti commented:

>Basti Can we share a build with Yung-Chin Oei? 

Oh ofc! Feel free to share, they are not private 🙂 .

**Comment by ValentinaPC** [comment]
@yungchin here is the MacOS 2.17 RC build you could verify the fix - https://archive.mozilla.org/pub/vpn/releases/2.17.0/mac/.
Thank you in advance!

**Comment by yungchin** [comment]
Hi Valentina, thanks!

I can confirm that in this build, the installer lets me proceed to the install step as expected, without prompting me to install Rosetta. Works wonderfully!!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Thank you for confirming, Yung-Chin Oei!

We can mark this as Done.
