### ISSUE TITLE
Failure on building sentry component on Tuxedo OS  / Kde Neon

### ISSUE THREAD

**Issue by tuxmac** [mozilla-mobile/mozilla-vpn-client#7919]
**Describe the bug**
The default deb package won't run on Tuxedo OS which is an Ubuntu mixed with Kde Neon for current KDE distribution. So a more up2date Qt6 then Ubuntu 22.04. Gives some error regarding Qt6. So I have to build my own installation. Managed to install every dependency until I got stucked on sentry.

Configuring for Unix Makefiles
Generated BUILD_ID: 2.202309061004
Using Qt version 6.5.2
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.20.5
Building sentry for Linux
CMake Error at /usr/share/cmake-3.22/Modules/ExternalProject.cmake:2882 (message):
  No download info given for 'sentry' and its source directory:

   /usr/local/src/mozilla-vpn-client/3rdparty/sentry

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/ExternalProject.cmake:3716 (_ep_add_download_command)
  src/shared/cmake/sentry.cmake:99 (ExternalProject_Add)
  src/shared/sources.cmake:272 (include)
  src/CMakeLists.txt:43 (include)

-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.20.5
Creating library translations_auth_tests
Creating an empty tanslations.completeness file
Creating library translations_template
Creating an empty tanslations.completeness file
Creating library translations_unit_tests
Creating library translations_vpn
Creating an empty tanslations.completeness file
-- Configuring incomplete, errors occurred!
See also "/usr/local/src/mozilla-vpn-client/build/CMakeFiles/CMakeOutput.log".

I can't figure out which dependency might be missing

**VPN version:**
latest from git

**Affected Platforms:**
 x86_64 Tuxedo OS (Ubuntu 22.04 + Kde Neon)

**Prerequisites:**
 get latest source code and install several dependency dev packages

**Steps to reproduce:**

**Expected result:**
 succesful compilation and an runnable installation

**Actual result:**
 compilation fails

**Additional notes:**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5477)

**Comment by tuxmac** [comment]
This is the reason I am trying to build my own version:
mozillavpn: symbol lookup error: mozillavpn: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6

**Comment by strseb** [comment]
>/usr/local/src/mozilla-vpn-client/3rdparty/sentry
is not an existing non-empty directory. Please specify one of [...]

Can you double check that this folder is not empty? If it is, you might need to checkout the submodules. Note also it's recursive, sentry itself has submodules too :)

**Comment by tuxmac** [comment]
Okay it was empty. Found this https://github.com/mozilla-mobile/mozilla-vpn-client/issues/6151
I once tried the pull command which did just nothing new but the other did now 
git submodule update --init --recursive

**Comment by tuxmac** [comment]
Okay.... just found that... https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/docs/dev-setup/index.md
and that https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/docs/dev-setup/linux.md

sorry...

**Comment by tuxmac** [comment]
Misunderstood this "Docs for building the client" as a heading. I don't if it would have helped me on the dependencies. but it helped on getting the full source code and finish the build. I have a running client now!

**Comment by strseb** [comment]
No worries, i'll close this then :) 
Feel free to open another ticket if you encounter something else. (or here if sentry is still the problem)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

.
