### ISSUE TITLE
FVP-02-003 General: Balrog incorrectly verifies certificate chain

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#798]
It was found that Balrog does not properly verify the certificate chain, permitting rogue
root certificates and their fellowship to pass. The attacker-controlled leaf certificate holds
a public key that will be used to verify the update used in Windows and macOS.
This signifies the risk of state-funded attackers who are in charge of a trusted certificate
authority being able to perform Man-in-the-Middle attacks on the TLS connection
initiated by Mozilla VPN to receive updates. Attackers can now replace the binary code
of the update with malicious malware bypassing the Balrog mechanism that intends to
detect those attacks.

**Comment by bakulf** [comment]
@birdsarah can I assign this bug to you?

**Comment by birdsarah** [comment]
Closed via #993
