### ISSUE TITLE
FVP-02-015 General: Verbose logging and leaking of logs to desktop

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#811]
Related to FVP-02-013, the macOS and Windows clients engage in fairly verbose
logging, too. For example, the callback code from the authentication steps and all the
VPN details such as the client’s private key and IPs are logged. Additionally, on macOS
and Linux, requesting the logs via the help menu item will have Mozilla VPN write a copy
of the logfile to the desktop. A user might not notice that these files are created, which
causes privacy concerns.

It is recommended to give users an option to disable logging. Copies of the logs should
not be written into unexpected locations.

**Comment by bakulf** [comment]
To summarize the concern, we should have a setting flag to disable the logging. @jess-cook03 can you help us to add it to the settings view?

**Comment by jess-cook03** [comment]
Is this something we can add next week to the redesigned settings concept we were talking about?
![Scannable Document on Apr 19, 2021 at 5_02_12 PM](https://user-images.githubusercontent.com/54991698/115470811-eaee8080-a204-11eb-9be7-4b1fc5160aa0.png)

@lesleyjanenorton 
cc @bakulf some ideas we have sketched out for redesigning settings UX/UI

**Comment by jess-cook03** [comment]
UX effort here is small-medium I was working with @lesleyjanenorton on this previously and I have proposed near term solution. ^^^^ above
I intend on following up with @lesleyjanenorton to work on rehtinking the settings page -- perhaps I create a separate ticket to track that.

**Comment by bakulf** [comment]
We will fix this in 2.4. This is not a security issue because the logs do not contain any sensitive user data.
In 2.4 we will have an in-app feedback form and we can keep the logs, encrypted, in files.
I close this bug.

**Comment by ValentinaPC** [comment]
Is there a way for QA to check this in 2.4? Thanks!
