### ISSUE TITLE
Linux: DNS Settings screen doesn't always render correctly

### ISSUE THREAD

**Issue by dtl131** [mozilla-mobile/mozilla-vpn-client#8113]
**Describe the bug**
I cannot access the DNS settings with the latest git build under Debian unstable. The window is blank. Furthermore, the GUI reports no connection while it still masks the IP. The log say something about sockets. I have tried Mozilla's DNS servers, Google's, and OpenDNS with the same result.

**VPN version:**
2.18.0 (2.202309231647)

**Affected Platforms:**
Debian Linux, sid/unstable

**Expected result:**
I am tired/frustrated with blank windows and broken functionality on the Linux client while keeping up with the latest git builds. I would try more stable versions, but I cannot get them to build. 
[mozillavpn-2023-9-23.log](https://github.com/mozilla-mobile/mozilla-vpn-client/files/12707599/mozillavpn-2023-9-23.log)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5592)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Valentina Virlics would you mind checking if you can reproduce this on your build?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Thanks Valentina Virlics . Lesley Norton Adrienne Davenport FYI moving this to ‘High’ priority for our next sprint.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Matt Lichtenstein mind checking if this is QT related?

**Comment by dtl131** [comment]
My subscription to mvpn ran out, so I'm just going to close this. Thanks.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Santiago Andrigo Matt Lichtenstein 

This is still repro on both Lunar and Mantic (QT 6.4.2) using Mozilla VPN 2.18 (rc20231024175638).

Reopening the DNS Settings page after entering a custom DNS triggers a white screen instead.

Video below.
