### ISSUE TITLE
UI stopped showing in my Desktop

### ISSUE THREAD

**Issue by hmvago** [mozilla-mobile/mozilla-vpn-client#8246]
**Describe the bug**
The mozillavpn UI stopped showing. 
The VPN still works from terminal with the following message:

$ mozillavpn ui
QDBusArgument: write from a read-only object

**VPN version:**
mozillavpn 2.17.0

**Affected Platforms:**
Ubuntu 20.04.6 LTS   64-bit
Gnome ver. 3.36.8
Windows system X11

**Prerequisites:**
I have already purged and reinstalle the mozillavpn

**Steps to reproduce:**

**Expected result:**
I would like to continue seen the UI where I can activate/deactivate the vpn

**Actual result:**

**Additional notes:**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5682)

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hello,

Thank you for filing this ticket. We are already tracking the issue here: https://mozilla-hub.atlassian.net/browse/VPN-5628 ( https://mozilla-hub.atlassian.net/browse/VPN-5628|smart-link )

**Comment by solsticesurfer** [comment]
That Jira is not publicly accessible. How do users track the issue's progress and contribute feedback without access?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Sorry for the inconvenience. You can try and access the issue through the following link: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8163 ( https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8163|smart-link ). Hope it helps.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Duplicate with VPN-5628
