### ISSUE TITLE
QT6

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#827]
We should support QT6.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-130)

**Comment by strseb** [comment]
From [removed-modules-in-qt-6-0](https://doc.qt.io/qt-6/whatsnew60.html#removed-modules-in-qt-6-0)
Affected: 
websockets
charts

**Comment by data-sync-user** [comment]
➤ Nma-Sie-Anyene Davenport commented:

This is a test comment.

**Comment by birdsarah** [comment]
We initially believed that Qt5.15 was LTS and so there wasn't a rush to update.

However, I have found the following information and I believe it points to us not being on a supported version.

https://www.qt.io/blog/qt-5.15-released

> While Qt 5.15 is supported as usual for all our users, Qt 5.15 will also provide https://www.qt.io/blog/qt-offering-changes-2020?hsLang=en, including the new https://www.qt.io/blog/available-now-qt-for-small-businesses?hsLang=en. Option for extended support is available after the three year support period.

 https://www.qt.io/blog/qt-offering-changes-2020

> Starting with Qt 5.15, long term support (LTS) will only be available to commercial customers. This means open-source users will receive patch-level releases of 5.15 until the next minor release will become available. This means that we will handle Qt 5.15 in the same way as e.g. 5.13 or 5.14 for open source users.

> If there are issues that would prevent the use of the latest release, there will be patches available even if we do not create new full patch releases for that version anymore.We are making this change to encourage open-source users to quickly adopt new versions. This helps maximize the feedback we can get form the community and to emphasize the commercial support available to those with longer product life cycles that rely on a specific Qt version.

https://www.theregister.com/2021/01/05/qt_lts_goes_commercial_only/

> Yesterday senior VP Tuukka Turunen https://lists.qt-project.org/pipermail/development/2021-January/040798.html: "With Qt 6.0.0 released and the first patch release (Qt 6.0.1) coming soon, it is time to enter the commercial-only LTS phase for Qt 5.15 LTS. All the existing 5.15 branches remain publicly visible, but they are closed for new commits (and cherry-picks)... closing happens tomorrow, 5th January 2021. "After this the cherry-picks go to another repository that will be available only for the commercial license holders... first commercial-only Qt 5.15.3 LTS patch release is planned to be released in February."
> **Security**
> The problem is that these releases are in effect no longer maintained. If there is a security issue, or a fix needed to support some change in one of the target operating systems, open-source users will not get that fix other than in the not-ready version 6.0.

https://www.qt.io/blog/commercial-lts-qt-5.15.5-released

> We have released Qt 5.15.5 LTS for **commercial license holders** today. As a patch release, Qt 5.15.5 does not add any new functionality but provides bug fixes and other improvements. Compared to Qt 5.15.4, Qt 5.15.5 contains about 110 bug fixes and security updates. The list of fixes and the overview of all important changes in Qt 5.15.5 can be found from the Qt 5.15.5 release note. It is available via Qt Account: in Downloads, select Product: Qt and Version: 5.15.5.

And this[ FAQ pdf linked](https://cdn2.hubspot.net/hubfs/149513/_Website_Blog/Qt%20offering%20change%20FAQ-2020-01-27.pdf) from the second link:

> What part of the LTS release would be available for everyone and what part is commercial 
only? 
>
> The key diference between a regular and LTS release is that while the regular release only receives
patch releases during the first 6 months until the next feature release is out, a long term supported
release receives patch releases also after the next feature release is available. So when we say that
the LTS becomes commercial only, it means that for open-source users all releases are similar –
receiving patch releaes until the next feature release is out. For commercial users some releases,
such as Qt 5.15, are defined to be long-term supported and receive patch level releases also after the
first 6 months after release.
>
> How many patch releases are done before the “LTS phase” starts? 
>
> This depends upon multiple things, typically 2-3 patch level releases are done during the first 6
months after initial release. Similar level is expected also for Qt 5.15.
---

Based on the above I believe this is a priority as we are not on a supported version of Qt anymore. But I'm not sure. And I don't have a full grasp of what the implications of not being on a supported version are.

**Comment by birdsarah** [comment]
According to qt release notes there have been 4 minor releases of Qt for LTS users, so they are now at 5.15.6. They include over 500 bug fixes and security updates that are included in v6.1+ but I don't know what those security updates are, whether they affect us, or how serious - sorry....i'm also not exactly sure how we'd find out.
