### ISSUE TITLE
Add link to status page on StateBackendFailure.qml

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#834]
Once we have implemented a status page on vpn.mozilla.org, we'll need to link to it from this screen. Is there anywhere else we think we should add a link to the status page?

<img width="363" alt="Screen Shot 2021-04-12 at 10 08 02 AM" src="https://user-images.githubusercontent.com/22355127/114417163-f8599a00-9b76-11eb-9724-e3a5e97d4af8.png">

**Comment by birdsarah** [comment]
blocked by https://github.com/mozilla-services/guardian-website/issues/1012

**Comment by ValentinaPC** [comment]
Verified this on Win 10 VPN build (2.3.0 (2.202105191459)).
The new "status page" link is displayed, but clinking on the link it redirects to FxA account manage page. (https://accounts.stage.mozaws.net/)
![image](https://user-images.githubusercontent.com/15685960/118927787-f9869f80-b94a-11eb-8334-85467b07c9a8.png)

**Comment by ValentinaPC** [comment]
This is the page that loads for me: https://accounts.stage.mozaws.net/ and not https://status.vpn.mozilla.org/ @bakulf
