### ISSUE TITLE
Make the Ring Animation faster/better

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#840]
On a Pixel 4 (Android) our connected/ripple animation does not hit max fps 30~/120 and sometimes even drops to less then 20. 
On the other end, [it's using a lot of power on pc's from reddit: ](https://www.reddit.com/r/firefox/comments/m6a8dp/why_would_a_vpn_need_to_use_gpu/)
>The gpu is a nvidia GTX 1070. The gpu is using 8% of the 3D compute [...] I noticed the cooling fans spin up and become noisey when I basically had nothing demanding open so investigated.

Which all sounds odd to me given we just draw 3 rings on a canvas. Maybe we can find something to improve here :)

**Comment by lesleyjanenorton** [comment]
Closed via #869

**Comment by ValentinaPC** [comment]
Verified this on my Google Pixel 4 device, with Android 10, using the last VPN stage build (2.3.0 - 162902950).
The animation has no UI issues.
