### ISSUE TITLE
Linux: Support Split tunnel

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#842]
We should be able to support this using C-groups :)

**Comment by ValentinaPC** [comment]
@oskirby @strseb can we have some mockups for this? It had a different layout, and now, has changed. We need to know if this will be the final design, so that we can update our Test Cases. Thank you in advance!

**Comment by ValentinaPC** [comment]
Verified this on 2.4.0 (2.202107191711) VPN version on Linux Ubuntu 20.04.
The App Permission feature was introduced with success and works as expected. Some minor issues were logged separately.
Marking this as verified.
