### ISSUE TITLE
Document steps for go modules

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#844]
On linux, I had to run `go mod init balrog` at the top level of the directory for go to compile.

Without running it, I get the error, when running `make` in balrog folder.

```
go build -buildmode c-archive -v
go: cannot find main module, but found .git/config in /home/bird/Dev/mozilla/mozilla-vpn-client
        to create a module there, run:
        cd .. && go mod init
make: *** [Makefile:2: all] Error 1
```

Or I manually can make a go.mod file in the directory.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-132)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This is not well integrated with CMake.
