### ISSUE TITLE
Location leak while VPN is ON on windows and macos

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#850]
We do not have any extra data. As soon as we have logs or an STR, we should prioritize the fix.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-134)
┆author: Data Sync

**Comment by ValentinaPC** [comment]
This happened to me also, but it was because I had installed a secure proxy on the device, and it was a conflict.

**Comment by jr-johnson-support** [comment]
[mozillavpn-2021-4-14.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6318696/mozillavpn-2021-4-14.txt)
Here are some logs pulled from a user experiencing this issue.

**Comment by strseb** [comment]
Do we have info on which pages they visited / How they found out?

**Comment by jr-johnson-support** [comment]
Notes from a frontline agent: "The issue seems to occur sporadically and not specific to a particular URL. The users are only made aware this happens when they check  in websites such as iplocation.net or whatismyipaddress.com"

**Comment by bakulf** [comment]
I wonder if this is a "Firefox" issue when DoH (DNS over HTTP) is enabled.

If Firefox uses DoH, it can be that it keeps the same HTTP2 connection to the DoH provider even after the VPN activation. Because of that, any IP resolution will be done "outside" the VPN tunnel. There is not a way to reset the Firefox HTTP2 connection from the VPN client (yet). In Q3 we will work on it, but so far, leaks can happen (note that this should be a common issue even for other VPN projects).

**Comment by jr-johnson-support** [comment]
32 inbound tickets as of 06/09

**Comment by ValentinaPC** [comment]
What is the status of this for 2.4? Thanks!

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Is this bug still open?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We did not see any location leak on MacOS or Windows 10/11 while testing the 2.10 version;

Please reopen if the case.
