### ISSUE TITLE
Mozilla VPN's MSI installer triggers UAC prompt that shows a gibberish filename like `e3afe72.msi` instead of the actual filename or a more friendly name

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/mozilla-vpn-client#8550]
**Describe the bug**
The Windows installer for Mozilla VPN has a nice human-readable filename, but the UAC prompt that it triggers shows a gibberish filename like `e3afe72.msi`.

**VPN version:**
2.17.0.0

**Affected Platforms:**
Windows 11, probably also Windows 10

**Prerequisites:**
Don't have Mozilla VPN installed yet.  (Uninstall it if you've already got it installed)

**Steps to reproduce:**
1. Download an MSI Installer for [Mozilla VPN](https://www.mozilla.org/en-US/products/vpn/download/windows/thanks/)
2. Double-click the installed MSI, and click to allow the file to execute if prompted.
3. Look at the UAC "User Account Control" prompt that Windows pops up.

**Expected result:**
The UAC prompt identify the application as a familiar/friendly filename -- either whatever filename we use for our installer, or (better yet) a human readable name.  (As an example, Chrome's MSI installer literally says "Google Chrome Installer")
 
**Actual result:**
The UAC prompt shows a random-looking filename like `e3afe72.msi`.

**Additional notes:**
[screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=9360883) from the [bugzilla bug where I originally reported this](https://bugzilla.mozilla.org/show_bug.cgi?id=1861868)
As noted on that bug report, this issue affects Firefox ESR msi-installer too (which is why I reported it over there), but it's lower-priority there since that's not really a user-facing installer; it's intended for enterprise deployments.  So, the VPN team might have a stronger reason to prioritize fixing this (since MSI is the primary installer) as compared to the Firefox folks who works on this code (for whom this isn't really a user-facing installer).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5868)

**Comment by bhearsum** [comment]
I investigated this in the related Gecko ticket, and I _think_ it should be easy to fix by adding an `authenticode_comment` entry to https://github.com/mozilla-mobile/mozilla-vpn-client/blob/fb01c3a9c5021e3d65e9bccdbde6b9ab6b5c0ac3/taskcluster/mozillavpn_taskgraph/transforms/scriptworker.py#L32 for the MSI signing task. (If it works, the value of `authenticode_comment` should be what's shown instead of the random hex string.)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Basti Mind adding points and a fixVersion please? 🙂

**Comment by data-sync-user** [comment]
➤ Basti commented:

This should now be easily testable by pulling the newest signed msi i.e https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/XD9k9cAgSxGyH68nl9HJug/runs/0/artifacts/public/build/MozillaVPN.msi ( https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/XD9k9cAgSxGyH68nl9HJug/runs/0/artifacts/public/build/MozillaVPN.msi )

It should now say “Mozilla VPN installer” 🙂

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this on Mozilla VPN 2.20.0 (2.202312131413) using Windows 10/11.

The UAC prompt for the msi installer now shows the “Mozilla VPN Client installer” filename - Basti, should the “Client” be displayed in the filename or not? Thanks in advance!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Ideally, without “client” please 🙂

**Comment by data-sync-user** [comment]
➤ Daniel Holbert commented:

Looks like the PR that merged did include the word “Client” here: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8787/commits/96114ea30cf48e158d4bfbed19c59d72e200e2f0#diff-6b02ed217741846183c509502de0cc6806652046c0f9dcf9b33735a7b5bbbfd6R50 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8787/commits/96114ea30cf48e158d4bfbed19c59d72e200e2f0#diff-6b02ed217741846183c509502de0cc6806652046c0f9dcf9b33735a7b5bbbfd6R50|smart-link ) . Presumably that just needs a followup to remove that word?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Thanks, Santiago. 

Basti / Santiago Andrigo, as the “Client” is shown in the filename as well, do you prefer to reopen this ticket or file a new one? Thanks!

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

No, it’s fine. We can keep it as is.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Marking this verified as fixed based on previous comments.
