### ISSUE TITLE
When Exporting logs add supportive-debug info. 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#859]
For me at least it would be helpful if we would attach a bit more debug information to the logs when exporting:
Open questions for me usually are: 
-> What OS version is this?
-> What settings are set?

**Comment by jr-johnson-support** [comment]
Adding Mozilla VPN app Version to this list of items collect in logs. 

Nice to haves:
* Firewall/Antivirus details
* alternate VPN application installed
* Manual DNS settings if enabled

Speaking to @strseb  it seems like collecting some of these alternate details would be ok provided the user understands what we are collecting when we ask them to provide logs.

**Comment by ValentinaPC** [comment]
@strseb would this be part of Telemetry feature?

**Comment by strseb** [comment]
No! So this is part of the logs. 
So if you open/export the logs, at the bottom of the file you should see extra information 
about the device and the settings :)

**Comment by ValentinaPC** [comment]
Verified as fixed on Windows 10, Android 10 and Linux Ubuntu 20.04.
At the end of the VPN logs, there are some extra information about the client settings.
