### ISSUE TITLE
Cannot activate Mozilla VPN on Android

### ISSUE THREAD

**Issue by Bianca-O** [mozilla-mobile/mozilla-vpn-client#860]
### Affected versions:
v. 2.1.0 last build;

### Affected Platforms:
- Android 11

### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;
- Have a newly installed VPN app;

### Steps to reproduce:
1. Open VPN app;
2. Turn ON the VPN;

### Expected result:
- The VPN is ON.

### Actual result:
- The VPN is not turned ON.

https://user-images.githubusercontent.com/15685960/115019167-7db7b400-9ec1-11eb-86b5-543065d7eef3.mp4

**Comment by strseb** [comment]
Looking at the logs: 
-> A: Captive portal seems to be enabled 
-> B: The allowed cp-ipv6 is wrong ( we have a bug for that)

But just in general captive-portal may never be enabled on android. 

Relevant parts of the log: 
[2021-04-16T15:05:30.870] [info] - (VPNServiceBinder) - GOT TRANSACTION 1  
[2021-04-16T15:05:30.871] [info] - (VPNServiceBinder) - Activiation Requested, parsing Config  
[2021-04-16T15:05:31.102] [error] - (VPNServiceBinder) - {
    "allowedIPs": [
        "128.0.0.0/2",
        "224.0.0.0/3",
        "208.0.0.0/4",
        "200.0.0.0/5",
        "196.0.0.0/6",
        "194.0.0.0/7",
        "192.0.0.0/8",
        "193.128.0.0/9",
        "193.64.0.0/10",
        "193.0.0.0/11",
        "193.48.0.0/12",
        "193.40.0.0/13",
        "193.36.0.0/14",
        "193.34.0.0/15",
        "193.33.0.0/16",
        "193.32.128.0/17",
        "193.32.0.0/18",
        "193.32.64.0/19",
        "193.32.96.0/20",
        "193.32.112.0/21",
        "193.32.120.0/22",
        "193.32.124.0/23",
        "193.32.127.0/24",
        "193.32.126.128/25",
        "193.32.126.0/26",
        "193.32.126.96/27",
        "193.32.126.80/28",
        "193.32.126.72/29",
        "193.32.126.64/30",
        "193.32.126.68/31",
        "193.32.126.71/32",
        "64.0.0.0/2",
        "0.0.0.0/3",
        "48.0.0.0/4",
        "40.0.0.0/5",
        "36.0.0.0/6",
        "32.0.0.0/7",
        "35.0.0.0/8",
        "34.128.0.0/9",
        "34.0.0.0/10",
        "34.64.0.0/11",
        "34.112.0.0/12",
        "34.96.0.0/13",
        "34.108.0.0/14",
        "34.104.0.0/15",
        "34.106.0.0/16",
        "34.107.0.0/17",
        "34.107.128.0/18",
        "34.107.224.0/19",
        "34.107.192.0/20",
        "34.107.208.0/21",
        "34.107.216.0/22",
        "34.107.222.0/23",
        "34.107.220.0/24",
        "34.107.221.128/25",
        "34.107.221.0/26",
        "34.107.221.96/27",
        "34.107.221.64/28",
        "34.107.221.88/29",
        "34.107.221.84/30",
        "34.107.221.80/31",
        "34.107.221.83/32",
        "10.64.0.1/32",
        "2600:1901:0:38d7::/0"
    ],
    "device": {
        "createdAt": 1618574716364,
        "ipv4Address": "10.65.211.167/32",
        "ipv6Address": "fc00:bbbb:bbbb:bb01::2:d3a6/128",
        "name": "Pixel",
        "publicKey": "IEU0otyIIOXh/yDsNayEQ9tAd1QHHhWBEZVptRajmVo="
    },
    "excludedApps": [
    ],
    "keys": {
        "privateKey": "muchPrivateVeryWow"
    },
    "reason": 0,
    "server": {
        "ipv4AddrIn": "193.32.126.70",
        "ipv4Gateway": "10.64.0.1",
        "ipv6AddrIn": "2a03:1b20:9:f011::a05f",
        "ipv6Gateway": "fc00:bbbb:bbbb:bb01::1",
        "port": 56226,
        "publicKey": "cmqtSjWUa4/0bENQDKxdr0vQqf4nFVDodarHm0Pc0hY="
    }
}
  
[2021-04-16T15:05:31.104] (VPNServiceBinder) - Stored new Tunnel config in Service  
[2021-04-16T15:05:31.129] [info] - (VPNService) - Permission okay  
[2021-04-16T15:05:31.377] [error] - (VPNService) - Exception while enabling the tunnel: Bad address

**Comment by Bianca-O** [comment]
The issue is verified as Fixed on version 2.3.0 (16188100) under Android 11. The VPN is turned ON.
