### ISSUE TITLE
Captcha requests on google searches with VPN turned on

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#866]
Description:
Users are reporting that when doing a Google search they are prompted to verify captcha "I'm not a robot" with the message: Our systems have detected unusual traffic from your computer network

Technical details:
Device: Windows 10
FX product: Mozilla VPN 2.1.0 and Firefox private network browser

Actual Results: 
Captcha request pops up frequently when entering search term into the address bar (google search set to default) with message - "Our systems have detected unusual traffic from your computer network. This page checks to see if it's really you sending the request and not a robot"
![image(1)](https://user-images.githubusercontent.com/58608126/115075163-4694d300-9ec0-11eb-8b9c-bf02885460b3.png)

Expected results: 
Search completes without captcha message populating.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-137)
┆Reporter: Data Sync

**Comment by bakulf** [comment]
There is almost nothing we can do here. Google doesn't "trust" our VPN servers.

**Comment by jr-johnson-support** [comment]
@bakulf  Definitely understand that there is not much we can do here. This is low volume now, though the issue is also on FPN, which there is no real workaround for because you cannot change your IP location via the FPN, unless I am mistaken on that. Not sure if another issue was needed on the FPN repo.

**Comment by paxperscientiam** [comment]
I will just echo the sentiment that it sucks. On the bright side, it may be the prod I needed to try something different.

**Comment by rbillings** [comment]
We are investigating options.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Putting this in product for you Santiago Andrigo . I’m tempted to close this issue. Increased incidence of captchas I feel is a known issue with VPNs. Not sure if you want to think about fixing it.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

I’m not aware of any ways to fix this other than getting into the business of actively avoiding detection, which is not currently part of our strategy. Closing this as “Won’t do”.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Back to cancelled
