### ISSUE TITLE
User is signed out when app closes in certain situations

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#8666]
This happens only when you sign into an account that already has 5 devices, and you remove a device as part of the login flow.

Not sure if this also affects other platforms. Tested on 2 different devices, on the latest `main` build from TestFlight and on the latest 2.19 release branch build. It also apparently happens on 2.18.

1. Sign in on staging
1. Hard quit app
1. Reopen app
1. Note that you’re signed out, which is unexpected

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-5932)
┆Reporter: Matt Cleinman

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hi Matt Cleinman,

Is “hard quit” different than swipe-kill?

While swipe-killing the app, QA is unable to reproduce this while using the 2.19 RC build - #3612 - on iOS 15.7.6/16.5/17.0.

Is there a specific build on which this is reproducing? Thanks!

Attaching a video as well.

!original-B4F90FE8-1A1E-484D-8107-B3C0E2D09031.mp4|width=444,height=960!

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

fwiw I feel like I’ve experienced this here and there for some time now, so maybe it’s intermittent

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Video now attached. This is on a iPhone 13 mini running iOS 17.2. 

While I can’t be 100% confident at all, it’s possible this is related to how various iPhones sometimes look the same in code, based on how iOS reports device names. That’s the first place I’d look when I dig into it, but low confidence that it’s it.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hey Matt Cleinman,

Thank you for attaching the video, it is really helpful. 

We investigated this issue and we are able to reproduce this across platforms, but only after the user removes a device from “Device not added” screen and swipe-kills the app.

We were unable to reproduce this following other steps (quitting the app after a fresh install, after removing a device from “My device” screen).

Also, this is reproducing in 2.18 as well. 

Can we please update the title and description of the issue with our latest findings? 

Thank you in advance!

**Comment by tuxmac** [comment]
Tried v2.18.0 and v2.17.2. All the same. Wasn't before and it worked for some time even with 2FA active.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Was able to repro this, while on Focal, on the latest 2.20 build.

!6thdevsc.mp4|width=1280,height=730!

**Comment by tuxmac** [comment]
Problem persists in v2.19.2 and makes mozilla vpn not usable on my Linux laptop. Going through the 2FA process after every boot results in not using it anymore. Any perspective of a solution? Better understanding of the problem causes?

**Comment by data-sync-user** [comment]
➤ Raluca Monica Ilban commented:

Verified this while using the 2.21.0 (2.202402070521) build across platforms. 

If the user removes a device from “Device not added” screen, then swipe-kill and reopen the app, the user is no longer signed out. We were not able to reproduce the issue without removing a device from “Device not added” screen, so we cannot verify for the other scenarios described in previous comments. 

Matt Cleinman Should we close the ticket and reopen or create a new one if the issue reoccurs? or maybe tuxmac can verify the fix?

**Comment by tuxmac** [comment]
I have canceled my subscription since it was not usable for me. I will eventually consider subscription again and will post if the problem persists. Thanks for the feedback!

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

Raluca Monica Ilban Once it’s verified fixed, we should close it. Future problems could re-open the ticket or create a new one. (And it looks like tuxmac is in agreement on this.)

**Comment by data-sync-user** [comment]
➤ Raluca Monica Ilban commented:

Closing ticket based on previous comments.
