### ISSUE TITLE
Android device shows connected while app shows not connected

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/mozilla-vpn-client#867]
![IMG_20210418_151047.jpg](https://user-images.githubusercontent.com/17863082/115157646-5f37f100-a058-11eb-9d6a-e5971bd8cf1d.jpg)

![IMG_20210418_151153.jpg](https://user-images.githubusercontent.com/17863082/115157656-6f4fd080-a058-11eb-90bb-26eb3b6c7797.jpg)

![Screenshot_20210418-151159.png](https://user-images.githubusercontent.com/17863082/115157662-72e35780-a058-11eb-9dd0-635dfbc9b852.png)

Note that I hide the VPN notification in case that has anything to do with this.

**Comment by strseb** [comment]
Hi, Sorry about that issue! I would need some info to get that reproduceable on my side.
(I only got that situation randomly once, and it seemed that Wireguard.Tunnel.status reported down :(  )
What device, android/vpn version are you running? 
Does this happen every time if you open the app && should be connected?

**Comment by lolrepeatlol** [comment]
I'm on a Pixel 4 XL with a custom ROM (CalyxOS) with Android 11 and the April 5 security patch. This doesn't happen every time, but it seems to happen mostly when I leave the VPN on for a few days.

**Comment by ValentinaPC** [comment]
Verified this on Android 10 (2.3.0 - 16209050) and I was able to reproduce it as follows:
- uninstall the VPN client you have;
- re install the client 
- sign in (do not turn it on)
- check the notification
Reproducibility rate: each time.
![image](https://user-images.githubusercontent.com/15685960/118228301-9dc39e80-b492-11eb-858a-f6c47100f6c0.png)

**Comment by lolrepeatlol** [comment]
> 
> 
> Verified this on Android 10 (2.3.0 - 16209050) and I was able to reproduce it as follows:
> 
>     * uninstall the VPN client you have;
> 
>     * re install the client
> 
>     * sign in (do not turn it on)
> 
>     * check the notification
> 
> 
> Reproducibility rate: each time.
> ![image](https://user-images.githubusercontent.com/15685960/118228301-9dc39e80-b492-11eb-858a-f6c47100f6c0.png)

Interesting, my issue was that the VPN was __on__ while the app was saying that it wasn't on. The issue you're showing is that the VPN was __off__ while a notification was saying it was on. Of course, your screenshot does show that the app says it isn't on under the notification shade, but wouldn't this still be a different issue? Like "notification shows VPN is on when it isn't?" :)

**Comment by ValentinaPC** [comment]
Sorry about the confusion...I looked to your screenshots and saw the VPN app being turned OFF, and above of it, a text mentioning that it is ON, and thought that we are seeing the same issue.
We can track "my issue" in #548 .

Could you retry to see if it still happens to you? I was not able to reproduce it.

**Comment by lolrepeatlol** [comment]
It still happens to me occasionally, but I'm on 2.2.0 since 2.3.0 hasn't released to the public yet, which seems to have the patch :)

**Comment by ValentinaPC** [comment]
I was not able to reproduce it while using the 2.2 version.
