### ISSUE TITLE
Android: Background-Service Shutdown on Swipe Kill 

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#871]
Affected Device: 
OS Android version 10:
-> Samsung Galaxy S9, model SM-G960U 1.1

**Comment by strseb** [comment]
Failed to reproduce this normally. I tried using Devices from Browserstack. 
An S9 with android 8
An S20 ultra with android 10

I was only able to reproduce this on the Android 10 when enabling the powersaving modes - But afaik the customer did exempt the app from that?

**Comment by strseb** [comment]
@ValentinaPC , do you possibly have a device to reproduce this on ? :)

**Comment by ValentinaPC** [comment]
@strseb I've tried to reproduce this on:
- Samsung Galaxy S10 (SM-G973F/DS) with Android 11
- Google Pixel IV with Android 10
and I was not able to duplicate the issue.
On both devices the VPN client (2.2) behaves as expected after swipe-kill.

**Comment by ValentinaPC** [comment]
Verified this with our available resources (see above comment), and we were not able to duplicate the issue.
We will mark this as "verified".
