### ISSUE TITLE
Make the release number copyable or selectable

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#874]
I would like to have a "Copy" button next to the Release version text. But maybe, having the string selectable is a good first step.

**Comment by ValentinaPC** [comment]
Verified this on the last VPN build (2.3.0 -2.202105060955) while using Linux Ubuntu 20.04.
The Build number/ app version si selectable.
![image](https://user-images.githubusercontent.com/15685960/117316010-deb72400-ae90-11eb-8bb8-eedee26eb161.png)
