### ISSUE TITLE
Confusing message in language menu for the System Language feature

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#879]
#### Affected versions:
- v 2.1.2 (2.202104201216);
 
#### Affected Platforms:
- all platforms
 
#### Prerequisites:
- Have a FxA account with an active subscription for Mozilla VPN;
- Have VPN installed;

 
#### Steps to reproduce:
1. Open the VPN app;
2. Open settings - Language menu;
3. Observe the description for the System language feature;
 
#### Expected result:
- When the feature is off the message displayed mentions that after turning the option on will make the app use the system language;
- When the feature is on the message displayed mentions that after turning the option off will make the app stop using the system language;
 
#### Actual result:
- The message is confusing. When the option is off the message is "Mozilla VPN will not use the default system language". The use of future tense here is giving the impression that some further action is needed.

![image](https://user-images.githubusercontent.com/15685441/115542781-4e31ee80-a2a9-11eb-8393-8bb0d44cc916.png)

**Comment by jess-cook03** [comment]
@jess-cook03 to loop in Chris on this for inapp UX writing needs

**Comment by chrisrooneys** [comment]
@lesleyjanenorton We should just keep the strings here static and affirmative no matter whether or not the option is toggled. The "on" switch for this option indicates clearly that the setting applies. Let's use this:

**Header:** "Use system language"
**Descrip text:** "Mozilla VPN will use the default system language."

**Comment by lesleyjanenorton** [comment]
thank you @chrisrooneys  - I will get this updated!

**Comment by madalincm** [comment]
Verified using the latest vpn staging build on Windows 10. Marking the bug as verified fixed.
![image](https://user-images.githubusercontent.com/15685441/117444498-39f51f00-af42-11eb-861e-55243704e6e5.png)
