### ISSUE TITLE
@dotvhs

### ISSUE THREAD

**Issue by RichardValerosoUniverse** [mozilla-mobile/mozilla-vpn-client#8797]
@dotvhs 

_Originally posted by @RichardValerosoUniverse in https://github.com/TGX-Android/Telegram-X/pull/504#pullrequestreview-1777072712_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-6017)

**Comment by oskirby** [comment]
This does not appear to be related to the Mozilla VPN project.
