### ISSUE TITLE
[intermitent] "Remote service error" for an account with expired IAP

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#881]
#### Affected VPN versions:
* 2.2.0 (2.202104201216);

#### Affected Platforms:
* iOS 14.4;

#### Prerequisites:
* Have one FxA account with an IAP subscription for Mozilla VPN made via TestFlight that expired (after 10 minutes);

#### Steps to reproduce:
1. Open VPN app
1. Tap “Get Started”
1. Log in with the account from prerequisites;

#### Expected result:
* User is logged and redirected to the IAP subscription page.

#### Actual result:
* User is not logged and a red banner with the “remote service error” message is displayed;

#### Notes:
* We think that might have something to do with the period immediate after the subscription expiration.
![Skype](https://user-images.githubusercontent.com/15685960/115553455-18dfcd80-a2b6-11eb-98bc-db9015a28341.jpeg)UNITO-UNDERSCORE!Picture!UNITO-UNDERSCORE!2021!UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!21T12!UNITO-UNDERSCORE!27!UNITO-UNDERSCORE!29!UNITO-UNDERSCORE!426Z!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-139)

**Comment by bakulf** [comment]
The app receives a 500 from the guardian-website.

[21.04.2021 15:09:05.451] (networking - NetworkRequest) Network reply received - status: 500 - expected: 201
[21.04.2021 15:09:05.451] (networking - NetworkRequest) Network error: 401 status code: 500 - body: {"message":"https://partner.mullvad.net returned unexpected statusCode=404, body={\"code\":\"ACCOUNT_NOT_FOUND\",\"error\":\"The requested account does not exist\"}, taskType=ADD_DEVICE"}

**Comment by bakulf** [comment]
I saw this issue in the past. It happened when the same account was kind-of blocked by Mullvad. We still need to support this scenario, but right now, it's not so easy to reproduce it. When this happens, I create a new account...

**Comment by ValentinaPC** [comment]
There is another thing happening, that we think has the same root cause as this issue.
If logging in with the same account, after subscription expires, sometimes, user is redirected to the "My devices" page informing the user that max_device_limit was exceeded - witch is not the case as is the first device for that account.
See screenshot below.
![image](https://user-images.githubusercontent.com/15685960/115701872-eba42580-a370-11eb-85f0-122468e297d1.png)

**Comment by rbillings** [comment]
@ValentinaPC does this still repro?

**Comment by ValentinaPC** [comment]
@rbillings Just rechecked this while following the initial steps and seems like, it passed 2 hours and the subscription did not expired, and the VPN still works. Did something changed on iOS regarding subscription expiration?

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Not to my knowledge, but this should be triaged. Pun Lam

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Closing

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I guess we can close this issue. It’s from august and nobody has reported it recently.
