### ISSUE TITLE
KillSwitch Failure - Network Released without user interaction

### ISSUE THREAD

**Issue by Bobinsz** [mozilla-mobile/mozilla-vpn-client#8826]
**Describe the bug**
When a Network connection fails, the KillSwitch works correctly stopping all network traffic, displaying the error: "No Signal - Check Connection"

However if the VPN fails to re-establish a connection to the server choice of the user within a set frame of time the VPN provides the following popup warning: "Server Unavailable - Choose a new Location" & without any user interaction to un-secure the connection, the VPN app completely releases control of the network connections... the KillSwitch no longer functions and all traffic defaults back to un-protected channels, as if the user was not using the VPN in the first place!

**VPN version:**
v2.19.0 (2.202311270624)

**Affected Platforms:**
Edition	Windows 10 Pro
Version	22H2
Installed on	‎25/‎03/‎2023
OS build	19045.3693
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Prerequisites:**
  <Optional: Any special steps taken not related to the app to trigger the bug>

**Steps to reproduce:**
Network Failure, showing error: ""No Signal - Check Connection"
With continued failures to reconnect resulting in the Error popup: "Server Unavailable - Choose a new Location"

**Expected result:**
The KillSwitch works correctly for the initial Network failure. However the VPN completely releases control, without user interaction should the subsequent failure occur ("Server Unavailable - Choose a new Location". allowing unprotected network traffic because of the failure. 

The KillSwitch & VPN should Not release the Network to unprotected traffic, under any circumstance, even with the connection failure popup... without user interaction. There should be no defaulting back to unprotected traffic without user interaction!

**Actual result:**
Once the "Server Unavailable - Choose a new Location" popup occurs - after reconnection attempts have failed - the VPN and KillSwitch stop functioning completely and release all Network traffic back to Unprotected Network traffic as if the VPN wasn't being used in the first place. Without any user interaction.

**Additional notes:**
  <Optional: Any Screenshots, Videos, Logs>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-6033)

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Lesley Norton mentioned that the deactivation is likely happening due to this function:

void Controller::serverUnavailable() {
  logger.error() << "server unavailable";

  m_nextStep = ServerUnavailable;

  if (m_state == StateOn || m_state == StateSwitching ||
      m_state == StateSilentSwitching || m_state == StateConnecting ||
      m_state == StateConfirming || m_state == StateCheckSubscription) {
    deactivate();
    return;
  }
}I don’t think we should be deactivating the VPN if it’s already in StateOn or StateSilentSwitching. We should remain in killswitch for as long as necessary or until user specifically toggles the VPN off.

**Comment by Bobinsz** [comment]
I completely agree with Gela Malek Pour's addition, and was the reason for my raising this issue. I'm thankful Gela has been able to highlight the code which seems to be causing this behavior.

In my mind, the Killswitch & VPN as a whole should Never disengage without user interaction, upon network failure, or any other reason. As it by-passes the protections of a Killswitch.

In my mind when the popup "Server Unavailable - Choose a new Location" occurs; The killswitch should remain active for as long as necessary, the network should Never be released to unprotected traffic without the user choosing to disable the VPN.

Instead, I believe it would be more appropriate that the Killswitch remain active and continue blocking all traffic, until a re-connection to a VPN server is established or user interaction with the VPN occurs. I also think that the user should be able to select an alternative server, if re-connections continue failing, without releasing network traffic back to being unprotected first. (cycling off & on)

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

{quote}Instead, I believe it would be more appropriate that the Killswitch remain active and continue blocking all traffic, until a re-connection to a VPN server is established or user interaction with the VPN occurs.{quote}

Thank you for filing, we are completely aligned on this.

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Santiago Andrigo Should this fix be cherry-picked to the 2.20 branch?

**Comment by data-sync-user** [comment]
➤ Raluca Monica Ilban commented:

Hi Gela Malek Pour ,

Could you please help us with some testing details for verifying this ticket?

Thank you !

**Comment by data-sync-user** [comment]
➤ Gela Malek Pour commented:

Hi Raluca Monica Ilban , yes of course. To verify this, please activate the VPN and when the server location that the VPN is connected to becomes unavailable, ensure that we do not toggle the VPN off.

Per Naomi’s suggestion, here are some ways to replicate the server location becoming unavailable:

To test the NoSignal state in the past I have done things to break the connection to the wireguard server, for example:

  1. Disconnect Wi-Fi/Ethernet and then re-connect after it tries server switching, or
  2. Locate the server's IP and then install a /32 route to drop all packets to it....

  * Linux: ip route add blackhole <server-ip>
  * MacOS: route -v add -net <server-ip>/32 127.0.0.1 -blackhole

**Comment by Bobinsz** [comment]
> ➤ Raluca Monica Ilban commented:
> 
> Hi Gela Malek Pour ,
> 
> Could you please help us with some testing details for verifying this ticket?
> 
> Thank you !

> ➤ Raluca Monica Ilban commented:
> 
> Hi Gela Malek Pour ,
> 
> Could you please help us with some testing details for verifying this ticket?
> 
> Thank you !

Umm... Verifying the Ticket? 

I'm sorry but this IS an issue... It's been highlighted now by a few contributors to your private JIRA sync Workflows... You should be Verifying the Patching of this "Gaping Hole" in the functioning of the VPN, not spending additional time verifying the bug that multiple contributors have agreed is egregious and have highlighted the likely code responsible for the lapse in the Security & Functionality of the KillSwitch & VPN app as a whole!

**Comment by data-sync-user** [comment]
➤ Raluca Monica Ilban commented:

Sorry for the misunderstanding, I was asking for testing details to validate that the issue is fixed.
Gela Malek Pour thank you, we will verify this after regression.

**Comment by strseb** [comment]
> Umm... Verifying the Ticket?
> 
> I'm sorry but this IS an issue... It's been highlighted now by a few contributors to your private JIRA sync Workflows... You should be Verifying the Patching of this "Gaping Hole" in the functioning of the VPN, not spending additional time verifying the bug that multiple contributors have agreed is egregious and have highlighted the likely code responsible for the lapse in the Security & Functionality of the KillSwitch & VPN app as a whole!


Thank you for filing an issue for this. We've already fixed the bug and it should go out in 2.20  - as Raluca already pointed out our QA team is currently validating the fix.  We appreciate your involvement and understand your concerns.
Let's strive to maintain a positive and supportive atmosphere in our conversations while adhering to the [community guidelines.](https://www.mozilla.org/en-US/about/governance/policies/participation/)

**Comment by Bobinsz** [comment]
> > Umm... Verifying the Ticket?
> > I'm sorry but this IS an issue... It's been highlighted now by a few contributors to your private JIRA sync Workflows... You should be Verifying the Patching of this "Gaping Hole" in the functioning of the VPN, not spending additional time verifying the bug that multiple contributors have agreed is egregious and have highlighted the likely code responsible for the lapse in the Security & Functionality of the KillSwitch & VPN app as a whole!
> 
> Thank you for filing an issue for this. We've already fixed the bug and it should go out in 2.20 - as Raluca already pointed out our QA team is currently validating the fix. We appreciate your involvement and understand your concerns. Let's strive to maintain a positive and supportive atmosphere in our conversations while adhering to the [community guidelines.](https://www.mozilla.org/en-US/about/governance/policies/participation/)

I'm unsure as to what I said, that was against community guidelines... I did come across as rather forthright... but none of what I said was offensive or threatening in my mind & as stated, was likely due to the misunderstanding caused by not having access to the other repository linked to the issue I've raised, and only seeing "Snippits" of the automated Syncing responses to the issue.

I'm happy to hear that the issue seems to have been flagged as Urgent, and has been resolved & is just going through testing. 

However, I have to express my concern that people within the team testing this fix appeared not to know how to test the fix initially... I am glad they knew where to ask for guidance, and that they got a prompt response!

As a user of the software, my Only Goal was to improve the software by raising this gaping hole in the security of the VPN. I apologize for my Tone, with regards to misunderstanding of the testing teams questions. 

Kind Regards

Bobs
