### ISSUE TITLE
Win10 "background service error restore" unable to connect

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#886]
Windows 10 users getting an error " background Service Error Restore" and unable to connect to the VPN. Nothing happens when they click on Restore and killing then relaunching the app does not resolve. 

Logs show: The service is not in the right status yet. Failed to run the tunnel service
[mozillavpn-2021-4-12.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6352701/mozillavpn-2021-4-12.txt)
[mozillavpn-2021-3-31.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6352703/mozillavpn-2021-3-31.txt)

Frontline agents unable to reproduce at this time.

**Comment by P-James** [comment]
Windsor user here.
Possibly something to do with Windows Insider build??
Other laptop on normal windows can continue to use

**Comment by tyingq** [comment]
I also had the same issue while running the Windows Insider Build.

A workaround of sorts until this is fixed:

One by one, pick the cities you use in the Mozilla VPN client, and try to turn the VPN on.  Once the button is "on", find the config file at \Windows\System32\config\systemprofile\AppData\local\MozillaVPN\MozillaVPN.conf and rename to <CityName>.conf,  like Paris.conf or NewYork.conf.   The file gets created as soon as you slide that button to the right.

Now, download the generic Windows Wireguard Client at https://www.wireguard.com/install/   Once you have that running, start it and click the "Add Tunnel" button at the bottom left of the window, and select one of the cities.  It will then import that tunnel config and put it in a list of tunnels to choose from.  Mozilla apparently uses a compatible config file, as each city I tried works fine in the generic wireguard client.

**Comment by BrenLaw** [comment]
I can confirm this is an issue when using recent Insider builds of Windows.

I had no issues with Mozilla VPN for many months before entering the Dev channel of Windows Insider to get the new Bluetooth improvements. Everything was normal initially until I shut down my PC and restarted it the next day. Once restarted, Mozilla VPN would try to connect then fail saying "Background service error Restore" . Except clicking restore doesn't do anything. Same as what @jr-johnson-support explained. Meanwhile, my laptop which is not in the Insider program has no issues with Mozilla VPN whatsoever.

After a new build from the Dev channel about two weeks ago. Mozilla VPN worked again. But same as the first time, it would not work after the first shut down and boot up following the update. I just had another Windows update today and was hoping for the best, but Mozilla VPN did not work at all this time. I really hope we don't have to wait until Microsoft's June 24th thing (or longer) for this to get ironed out.

Also just to note, I had already tried the steps Mozilla Support reps recommend. Uninstalling app, deleting the Mozilla stuff within the AppData directories. Restarting.

**Comment by jr-johnson-support** [comment]
66 inbound tickets as of 06/09

**Comment by oskirby** [comment]
I've been able to reproduce this in a VM by installing the Windows Insider Dev Channel with MozillaVPN 2.3.0.

[mozillavpn-2021-6-10.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6635905/mozillavpn-2021-6-10.txt)

**Comment by jr-johnson-support** [comment]
78 tickets submitted to Zendesk with this issue since the issue surfaced.

**Comment by oskirby** [comment]
I think I might have a solution to this one, but I have some cleanup work on it before it will be ready for a PR. I don't really know what the underlying cause of the fault is because it's something inside the Wireguard `tunnel.dll` that is failing with an error message that it was unable to register an NDIS device.

Updating to the latest and greatest code from https://github.com/WireGuard/wireguard-windows seems to get the tunnel up and running again on the Windows 10 dev insider channel, but it pulls in some new dependencies that I still need to integrate into the installer.

**Comment by ChrisJefferson** [comment]
I started getting this today after an update. The older version was working fine. Is there anywhere I can download older releases?

**Comment by jr-johnson-support** [comment]
83 tickets submitted to Zendesk since this issue arose back in April. @bakulf  or @oskirby is there a fix implemented for this? I am confused by the closed status and lack of milestone on this issue.

**Comment by oskirby** [comment]
We have a fix merged into the main branch, which means that it will be included in the next major release, which should be version 2.4 sometime in July.
