### ISSUE TITLE
Firefox + DOH leaking Country of origin

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#892]
Affected versions:
    v. 2.2
Affected Platforms:
    Windows 10;

Steps to reproduce:
    Open Firefox; (make sure doh is enabled)
    Open the VPN;
    Connect to whatever, check ipleak.net. 
    DNS still shows Berlin,Germany.
    IP in this Case is owned by cloudflare

Expected result:
    The DOH resolver IP should be in the right country.

Does work fine when firefox was opened after connecting to vpn. 
So firefox probably keeps the first doh server after launch? 
-> Also doh is on release in US right? 

![grafik](https://user-images.githubusercontent.com/9611612/116072576-8bbebf00-a68f-11eb-99b5-4ca8b530b929.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-142)
┆Reporter: Data Sync

**Comment by bakulf** [comment]
Firefox keeps 1 single http2 connection for DoH. If that connection was opened before the VPN activation, we leak the IP address. We can fix this with a Firefox web-extension or restoring the browser.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Sebastian Streich is this really windows only?

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Santiago Andrigo I’d like to get your take on priority here.

**Comment by data-sync-user** [comment]
➤ Sebastian Streich commented:

Fair to assume this is affecting any firefox desktop version - at that time i only tried this on windows.

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

I launched Firefox, verified it identified me as being in Argentina, connected to Brazil via the VPN and I don’t see that I’m leaking on the DNS side. This is Windows 11, but it seems to go counter to the explanation of Firefox keeping the DoH connection unaltered post-VPN connection. Can anybody reproduce differently?

!image-20221120-022038.png|width=770,height=197!

!image-20221120-021954.png|width=1321,height=821!

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Setting to medium per the other doh bug

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

The traffic is still going through the tunnel. This is working as intended. It's just unfortunate explanation from the DNS probes / Firefox.
Closed during bug squashing.
