### ISSUE TITLE
Error message after installing latest stage build on macOS

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#893]
#### Affected versions:
- v 2.2.0 (20210422018);
 
#### Affected Platforms:
- macOS 10.15.7;
 

#### Steps to reproduce:
1. Install Mozilla VPN using the latest installer (.pkg);
2. Observe the installation window after it is finalized;
 
#### Expected result:
- Success message is displayed in installation window;
 
#### Actual result:
- Installation window displays an error message saying “The installation failed”;
 

#### Note:
- Although the installation window displays the error the application is still installed and can be opened. Upon login the user is redirected to the Waitlist page or the download page(depending on where they’re from);

<img width="622" alt="Screenshot 2021-04-26 at 15 19 57" src="https://user-images.githubusercontent.com/15685441/116081477-f9281b00-a6a2-11eb-8307-fe8ad6f05ec6.png">

**Comment by bakulf** [comment]
This is now fixed!

**Comment by madalincm** [comment]
Verified as fixed in the latest VPN build.
