### ISSUE TITLE
System language feature not working on MacOS for FR and DE languages

### ISSUE THREAD

**Issue by madalincm** [mozilla-mobile/mozilla-vpn-client#894]
#### Affected versions:
- v 2.2.0(2.202104222018);
 
#### Affected Platforms:
- macOS 10.15.7;
 
#### Prerequisites:
- Have a FxA account with an active subscription for Mozilla VPN;
- Have VPN installed;
- Have system language set to German(DE) or French(FR);  
 
#### Steps to reproduce:
1. Open the VPN app;
2. Open settings - Language menu;
3. Turn on the System Language option;
 
#### Expected result:
- The application language is the same as system language(in this case German - Deutch);
 
#### Actual result:
- Application language remains the default one(i.e. English);
 
#### Note:
- The issue is reproducible with other languages as well not just with German;

#### Logs:
[macLogs.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6377299/macLogs.txt)

**Comment by bakulf** [comment]
Fixed

**Comment by madalincm** [comment]
Verified as fixed in the latest VPN build.
