### ISSUE TITLE
A few remaining scaling issues on Windows

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#895]
I've tried to reproduce this, with the last build (2.202104200913) on Windows 10, using the mentioned scales, and I was not able to do it. The size of the VPN app was changing as expected while going back and forth between different scaling.

But some weird things related to scaling, are still happening. Not sure what did I do :D
<img width="394" alt="scaling issues" src="https://user-images.githubusercontent.com/15685960/115400518-0bf9a600-a1f2-11eb-96bc-6ce93686c0d9.png">
 
SysTray icon is having UI issues after few resolution changes.
![icon](https://user-images.githubusercontent.com/15685960/115403368-02257200-a1f5-11eb-9233-8f09e206c3c8.png)

_Originally posted by @ValentinaPC in https://github.com/mozilla-mobile/mozilla-vpn-client/issues/707#issuecomment-823246883_

**Comment by madalincm** [comment]
Verified using the latest vpn staging build on Windows 10. After changing the resolution and the scaling, moving the vpn window between multiple monitors the vpn is scaled correctly. Also the tray icon is no longer blurred. Marking bug as verified fixed.
