### ISSUE TITLE
Windows - Mozilla VPN blocking NAS/network drives

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#8966]
After updating to VPN 2.19, user is unable to access LAN when VPN is turned ON. Tried adding app exclusions to their network controllers, and mapping the drives again. Then tried disabling the VPN, connecting the drives, and then enabling the VPN but the LAN connection ends when the VPN is activated. They have a network drive connected via ethernet and mapped to Z:// that becomes unresponsive the moment VPN is activated and is fine immediately after the VPN is off. Issue does not occur while on V 2.18

Does it impact functionality or aesthetics? No
Does this endanger users? What would be compromised and how likely is the threat? No
How annoying is this for affected users? (Think about how much 'in the way' this is, relative to what the user is trying to do) Annoying for a user since they need to have the VPN Off if they want to access their LAN.
Does it degrade the user experience significantly? No
Is it legally sensitive? No

**Centrality**
Is it on a core user journey or on a secondary one?

* Secondary functionality

**Technical Information**

Platform Windows 11
FX product: Mozilla VPN
Version: 2.19
Region/Languages
Network type: Ethernet

**Steps to Reproduce**

1. Install Mozilla VPN
1. Turn VPN On
1. Attempt to connect to NAS/network drives

**Actual Results**

What happens when following the steps above

**Expected Results**

VPN should allow access to local network

[^mozillavpn-2023-12-22(1).log]

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-6107)
┆Reporter: Juan Zapata

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

We managed to find a NAS device and tried to reproduce this issue, but without any luck. We were able to connect to the NAS device while VPN was ON and vice-versa.

Tested on:

  * Windows 11 Pro v22H2
  * NAS device - Seagate Lyve Mobile Shuttle 8TB (SSD)
  * NAS transfer protocol: SMB
  * Network configuration: PC + NAS connected to same router, LAN config .10 Gbps

Juan Zapata maybe we can find out what Lan/NAS configuration has the user?

Attaching logs as well.

[^mozillavpn-2024-1-22.log]

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

Valentina Virlics thank you for checking this. I’ll follow up with the user asking for their LAN/NAS configuration

**Comment by data-sync-user** [comment]
➤ Juan Zapata commented:

The only user affected came back reporting that after updating to V 2.20 they no longer have this issue. We can cancel this Jira since we have not received any further user reports.

**Comment by edflyer** [comment]
I am having this issue on 2.21.

Windows 10 Version 10.0.19045.4291

I have an SMB share with a QNAP NAS that disconnects when the VP is running, but as soon as the VPN stops it comes back. Both devices are connected to the same network switch. QNAP has a static IP.
