### ISSUE TITLE
Localize the MacOS installer pkg

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#911]

**Comment by ValentinaPC** [comment]
Verified this on Mac OS 10.15 VPN build 2.3.0 (2.202105201517).
The installed is not localized entirely - French and all good for German.
Reopening.

**Comment by ValentinaPC** [comment]
Verified as fixed on Mac OS 10.15 using the last VPN build (2.202105230622).
All steps of the installer are localized. (verified "de" and "fr")
