### ISSUE TITLE
Scripts all do remote update of submodules

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#913]
I just noticed that the scripts:

* scripts/linux_script.sh
* scripts/apple_compile.sh
* scripts/windows_compile.bat

and maybe more, all run `git submodule update --remote --depth 1`. 

This means that versions we build could be different from versions we're dev-ing with.

Dev install instructions say to just update https://github.com/mozilla-mobile/mozilla-vpn-client/#initialize-submodules

Should we change these to update remote and then we should all include PRs that update submodules.

Alternatively, we could have a submodule update PR at the start of each fresh release cycle and then not do remote updates in these scripts?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-149)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

We do not commit submodules updates anymore.
