### ISSUE TITLE
Message: New Update to VPN 2.20 - the message is from 2023, but was published in Feb. 2024

### ISSUE THREAD

**Issue by math-GH** [mozilla-mobile/mozilla-vpn-client#9157]
**Describe the bug**
It is not the first time, that the date of the message is very wrong.

Here the date of the message about VPN 2.20

![grafik](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/1645099/ed718f46-b5fa-4922-ae52-dd1429d3a648)

![grafik](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/1645099/b3e8e2f9-a7b2-426d-970b-81f9ca29423e)

**VPN version:**
I stuck on 2.16, but I cannot update it..... I thought that I had updated accordingly to 2.19 already

2.16.0 (2.202307282008)
![grafik](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/1645099/164dbbc0-fd96-4a25-8656-5cf46193f4ba)

**Expected result:**
The correct publishing date of the news

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-6219)

**Comment by data-sync-user** [comment]
➤ Matt Cleinman commented:

This was an error in not updating a date stamp in the addons manifest. We've done this for recent updates (thanks to QA pointing it out), and it's not worth fixing for an addon released several months ago that few users still see.
