### ISSUE TITLE
Need content and UX for turning telemetry on/off

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#916]
We need UX and content for:
- How telemetry gets turned on and off. 
- How and when users will be informed about telemetry (if we need to do that). Probably need legal to weigh in if they haven't already.

**Comment by jess-cook03** [comment]
UX effort Medium-Large
This has a dependency on #765 and how we move forward with Telemetry in general - esp. in this upcoming release.
cc Chris @dianahorn

**Comment by jess-cook03** [comment]
Update after design checkin 4/4:
Design to assess feasibility and commitment and circle back with team to understand priority for this release.

**Comment by jess-cook03** [comment]
Met with legal 4/6 to discuss -- need data review - submission.
Need to outline UX needs -- will be working with Nicole S from legal team to help us establish the right UX/UI pattern.
Diana - Chris - Jess to work with her.
**High level:**
Create ideal flow

- [ ] new users vs. existing users

- [ ] figure out onboarding opt in - opt out in settings

**Comment by dianahorn** [comment]
Workflow for opting in/out are in [Telemetry Figma](https://www.figma.com/file/V24ybQi40Jk3vQyExFtRzc/Telemetry?node-id=0%3A1)

**Comment by dianahorn** [comment]
@jess-cook03 @lesleyjanenorton
Updated the following per feedback from today's design review:
 - Modified the button labels to allow/not allow with new wording
 - Removed the banner flow

@chrisrooneys recommend we proceed with the suggested confirmation text because it aligns with the format that Firefox currently uses. We can meet tomorrow to confirm with legal and Nicole S.

**Comment by lesleyjanenorton** [comment]
Thank you @dianahorn , @jess-cook03  and @chrisrooneys !

**Comment by jess-cook03** [comment]
@lesleyjanenorton design and copy finalized can be found here: https://www.figma.com/file/V24ybQi40Jk3vQyExFtRzc/Telemetry?node-id=79%3A0
✅

**Comment by bakulf** [comment]
This has been fully implemented. Closing the bug.

**Comment by ValentinaPC** [comment]
Verified this across platforms using the last VPN 2.3.0 build.
The telemetry screen was added before authentication.
Some issues were found, but are tracked separately.
We can mark this as verified.
