### ISSUE TITLE
Mozilla

### ISSUE THREAD

**Issue by K8AmeenAE** [mozilla-mobile/mozilla-vpn-client#9171]
**Describe the bug**

**VPN version:**
  <Please fill this in>

**Affected Platforms:**
  <Please fill this in>

**Prerequisites:**
  <Optional: Any special steps taken not related to the app to trigger the bug>

**Steps to reproduce:**
   <Please fill this in>

**Expected result:**
  <Please fill this in>

**Actual result:**
  <Please fill this in>

**Additional notes:**
  <Optional: Any Screenshots, Videos, Logs>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-6225)

**Comment by data-sync-user** [comment]
➤ Adrienne Davenport commented:

Invalid Jira issue. All fields blank.
