### ISSUE TITLE
Need UX to support new DNS setting

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#920]
#902

**Comment by jess-cook03** [comment]
@lesleyjanenorton @strseb Can either of you provide a bit more context here as to what is needed from UX/UI to support this? Thanks!

**Comment by jess-cook03** [comment]
Based on investigation for requirements yesterday it sounds like there is only a UI need for this --- we need a spec for a form field component which we have provided, but I will also link the figma file here: https://www.figma.com/file/39hmjdjZcKRg8pC1LWbTBK/Components?node-id=154%3A325 

Please let @peterbenvenuto and/or myself know if there is anything else needed from design.

We know this is in the settings section.... if @strseb or @lesleyjanenorton could provide a screenshot for context that would be extra helpful, thanks!

**Comment by strseb** [comment]
Helloo! Here's a screenshot of the current pr. I would probably need some help with the copy, not sure if it's okay like this :) 
![Unbenannt](https://user-images.githubusercontent.com/9611612/121704950-83ea9b00-cad4-11eb-93b0-7ab36df1cf87.PNG)

**Comment by chrisrooneys** [comment]
@strseb I have a couple of questions and will set up time with you!

**Comment by jess-cook03** [comment]
✅ designs have been completed and delivered for this ticket/feature for v2.4 and v2.5
cc @peterbenvenuto

**Comment by lesleyjanenorton** [comment]
Done!

**Comment by data-sync-user** [comment]
➤ Peter Benvenuto commented:

Jessica Cook Here
