### ISSUE TITLE
Consider reworking Settings flows and Settings screen

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla-mobile/mozilla-vpn-client#921]
We know that our current Settings flow is less than ideal. For instance:

- The VPN must be off to change some settings but the user doesn't find this out until they're already a few clicks deep into a Settings sub-page and see the error message. To update the setting, the user has to back out of sub-page, close out of the Settings menu screen, turn off the VPN, then navigate back to where they were.
- It's also not easy to update unrelated settings without doing a lot of clicking around.
- We're giving the avatar, display name, email, and Manage Account button a lot of real estate at the top of the screen and the user has to scroll past them to get to the settings. It's a paper-cut but one that becomes particularly apparent when going through the flow described in the first bullet.

It would be great if we could rework these flows to save the user some clicks, prevent an annoying experience, and make settings easier to manage.

![IMG_5922](https://user-images.githubusercontent.com/22355127/116593063-4f38d080-a8e6-11eb-81ba-691e0f52f5e1.PNG)

Related: 
#930 #929 #916 #920 #882 #864

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-152)

**Comment by jess-cook03** [comment]
Adding #811 into this umbrella here as we can shuffle it into larger settings task.

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

https://mozilla-hub.atlassian.net/browse/VPN-42 ( https://mozilla-hub.atlassian.net/browse/VPN-42|smart-link )

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Refactor settings spec: https://www.figma.com/file/iBkvpAPTSMQHeRxIrCynQi/Settings-Redesign?node-id=99%3A1696 ( https://www.figma.com/file/iBkvpAPTSMQHeRxIrCynQi/Settings-Redesign?node-id=99%3A1696|smart-link )

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on the last VPN 2.50 release builds on all platform and observed the following:

  1. Option from "Get Help" menu have different order
  2. "App permissions" are listed in the Figma file for IOS - but the feature should not be shown on iOS (we do not have yet a build with these changes to check)
  3. Now that we have a "Preference" option in Settings, should we update the "Preference" string from VPN tray menu?
  4. The "Give feedback" option is not listed in the VPN tray menu, under Get Help

Jessica Cook Florian Zia Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as it has already been verified.

Thank you.

Valentina Virlics
