### ISSUE TITLE
Android: Enable Use of Kernel-Wireguard Implementation

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#924]
Supposed to be added in android 12 and we should use it if available :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-154)
┆author: Data Sync

**Comment by data-sync-user** [comment]
➤ Basti (Sebastian) Streich commented:

The Android API does not allow us to acces the kernel implementation without root. 
So this is nothing we would do.
