### ISSUE TITLE
Add ability to Bookmark servers

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#926]
From Support feedback: Add ability to Bookmark servers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-156)

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Now that we have multi hop and we have added a recent section to the servers list – I do not think this feature request still holds water ---- Brian Yee Adrienne Davenport I think we could cancel this ticket IMO
