### ISSUE TITLE
Connect VPN on startup button missing on iPhone 7

### ISSUE THREAD

**Issue by Abiologist** [mozilla-mobile/mozilla-vpn-client#9278]
**Describe the bug**
The "Connect VPN on startup" button is missing from IPhone 7
**VPN version:**
VPN 2.20

**Affected Platforms:**
iPhone 7

**Prerequisites:**
<Optional: Any special steps taken not related to the app to trigger the bug>

**Steps to reproduce:**
Open App Preferences and look at the space above "Data collection and use"

**Expected result:**
I expect to see a button labelled "Connect VPN on startup" - which I can see on my Mac version.

**Actual result:**
There is no such button

**Additional notes:**
<Optional: Any Screenshots, Videos, Logs>

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-6270)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

This functionality is not enabled on iOS nor on Android.
