### ISSUE TITLE
Website vague about subscription vs one time purchase

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#933]
From user feedback: The website makes almost no reference that this is a subscription. Only the button which redirects to the payments process mentiones it ("Abo").while "X Monat(e)" ("X month(s)") could be interpreted as a one-time purchase for this timeframe.

**Comment by birdsarah** [comment]
Moved to https://github.com/mozilla/bedrock/issues/10189
