### ISSUE TITLE
Question if having a Hong Kong server is secure

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#935]
From user feedback: There is a proxy in Hong Kong. Does it belong into a product offered as safe and protection against snooping?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-162)

**Comment by bfyee** [comment]
most major competitors have servers in hong kong, including nord, express, surfshark.  a number of other us and canada based vpn services have shut down their servers there, as per [this article](https://www.cnbc.com/2020/07/17/vpn-firms-shut-down-hong-kong-servers-over-security-law-concerns.html).  Best to keep an eye on this and leave in the parking lot.
