### ISSUE TITLE
Crash caused by being offline

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#938]
From user feedback: Calling "Get Started" ("Erste Schritte") while the phone is offline crashes the VPN app.

platform: Android 10

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-165)

**Comment by rbillings** [comment]
Note: I was unable to repro this using Android 11.

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This issue is old and nobody else has reported similar bugs recently.
Closing.
