### ISSUE TITLE
Connection issue removing device

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#943]
From user feedback: Removing a different device from the list in the client shows the throbber and eventually claims a connection issue and won't remove it visually from the device list. Quitting the list and reopening it shows it has been removed.

**Comment by ValentinaPC** [comment]
There are a bunch of issues on this part: #183 , #189 , #501; We can track this in any of them.
Thanks!

**Comment by bakulf** [comment]
This should be fixed in the latest versions. I would close this issue. If the issue is still reproducible, let's reopen this bug.
