### ISSUE TITLE
Connection time label moves

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#944]
From user feedback: The connection time label moves horizontally because it's centered and the numbers have variable width (e.g. HH:MM:S0 to HH:MM:S1 will move the start left)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-168)

**Comment by lesleyjanenorton** [comment]
Thanks for filing! If I'm understanding this correctly we should be able to solve this by using a mono-spaced font for these numbers. @jess-cook03 what do you think?

**Comment by ValentinaPC** [comment]
Would this be fixed for 2.4? Thanks!

**Comment by lesleyjanenorton** [comment]
@ValentinaPC This won't be fixed for 2.4 but possibly in time for 2.5
