### ISSUE TITLE
Payment email marked as spam

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#946]
From user feedback: Payment confirmation email got delivered into Spam folder (Email provider: GMX / United Internet)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-169)
┆Reporter: Data Sync

**Comment by rbillings** [comment]
Note: I was unable to repro this issue.

**Comment by data-sync-user** [comment]
➤ Nma-Sie-Anyene Davenport commented:

Unable to reproduce
