### ISSUE TITLE
PayPal payment shown in English

### ISSUE THREAD

**Issue by rbillings** [mozilla-mobile/mozilla-vpn-client#948]
From user feedback: English product details shown in Paypal after payment in the right sidebar
Country and city names in English. (edit: at least on Android switching to a different language and back to German switch the country and cities list to German)
<img width="483" alt="Screen Shot 2021-04-30 at 11 23 07 AM" src="https://user-images.githubusercontent.com/737878/116737749-735be680-a9a6-11eb-824b-c42ce14c61ac.png">

**Comment by ValentinaPC** [comment]
1. "English product details shown in Paypal after payment in the right sidebar"

- reproducible for both German and French - but **ONLY on Stage** - production site shows VPN details in the correct language;
![Screenshot 2021-05-04 at 14 39 49](https://user-images.githubusercontent.com/15685960/116998634-3023af80-ace7-11eb-83fe-67ecc8f7d88c.png)

2. "Country and city names in English" - this is from the VPN client, yes?
- if "yes", I can reproduce this as follows: 
---- if VPN client has system language ON and device is on German/French => Cities and countries listed in English;
---- if VPN client has system language OFF and the language set to German/Franch => Cities and countries listed in German/French;

https://user-images.githubusercontent.com/15685960/117001964-a6c2ac00-aceb-11eb-8ed0-223ac3c03134.mp4

Verified this on VPN 2.2.0 (16190310) and 2.2.0 (2.202104281453) while using Android 10 and Linux Ubuntu 20.04;

**Comment by birdsarah** [comment]
Issue (1) is only on stage and is an FXA issue

Issue (2) is fixed in v2.3
