### ISSUE TITLE
Linux debian background service error

### ISSUE THREAD

**Issue by gillesMioni** [mozilla-mobile/mozilla-vpn-client#953]
Mozillavpn compiled & installed from source on linux debian 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 

When mozillavpn launched, vpn start on fails with background service error.
Restore did not fix the problem.
Log joined.
Also tested a mozillavpn build on ubuntu 20 and copied to debian device. Same error.
[mozillavpn-2021-5-3_1.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6416334/mozillavpn-2021-5-3_1.txt)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-171)

**Comment by bakulf** [comment]
@gillesMioni is the mozillavpn dbus daemon running? Usually the mozillavpn dbus daemon runs because of the `org.mozilla.vpn.dbus.service` file, installed in `/usr/share/dbus-1/system-services`. If this doesn't happen, you can see this error.

Try to run the daemon in this way: `sudo mozillavpn linuxdaemon` and then run `mozillavpn`.

**Comment by gillesMioni** [comment]
@bakulf bakulf
> Try to run the daemon in this way: `sudo mozillavpn linuxdaemon` and then run `mozillavpn`.
Thanks for the answer. Alas, I tried this way without success. Same message error occurred.
The file org.mozilla.vpn.dbus.service is installed in /usr/share/dbus-1/system-services.

I would like to know some details about wireguard. I’ve not found docs about the configuration if it needed with mozillavpn.

**Comment by gillesMioni** [comment]
Something new about  mozillavpn failed at start on :
Journalctl -xe output :+1: mai 13 20:14:37  NetworkManager[1221]: <info>  [1620929677.9266] device (moz0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
mai 13 20:14:37  NetworkManager[1221]: <info>  [1620929677.9268] device (moz0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
mai 13 20:14:37  NetworkManager[1221]: <info>  [1620929677.9276] device (moz0): Activation: successful, device activated.
mai 13 20:14:37  NetworkManager[1221]: <info>  [1620929677.9389] **device (moz0): state change: activated -> unmanaged (reason 'unmanaged', sys-iface-state: 'removed')**
mai 13 20:14:37  gnome-shell[3280]: **Removing a network device that was not added**
mai 13 20:14:38  goa-daemon[3049]: **secret_password_lookup_sync() returned NULL**
mai 13 20:14:38  goa-daemon[3049]: secret_password_lookup_sync() returned NULL
mai 13 20:14:39  goa-daemon[3049]: secret_password_lookup_sync() returned NULL
mai 13 20:14:39  goa-daemon[3049]: secret_password_lookup_sync() returned NULL

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

A lot of things have changed in the latest releases. Can you please try again?
If the bug is still there, reopen the issue. Thank you!

**Comment by KeakaR** [comment]
I have the the same issue on Debian, have uninstalled and reinstalled. no change,, activated the process and then tried to add a server. crashed. same error code. Mozilla has no information on their website. 05/09/22

**Comment by oskirby** [comment]
This is a fairly old issue and there has been some significant code changes since it was initially filed. @KeakaR would you be able to provide logs and open a new issue so that we can attempt to diagnose the issue for you?
