### ISSUE TITLE
Issue building on Linux Debian 9

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla-mobile/mozilla-vpn-client#955]
Hello,

Following the posted build steps in order to build `mozilla-vpn-clinet`, `main` branch, on Linux Debian 9, results in a build error:

```
In file included from commands/commandlogout.cpp:5:
In file included from commands/commandlogout.h:8:
In file included from ./command.h:9:
In file included from ../../qt/qt/include/QtCore/QObject:1:
In file included from ../../qt/qt/include/QtCore/qobject.h:47:
../../qt/qt/include/QtCore/qstring.h:1554:29: error: cannot initialize a parameter of type 'wchar_t *' with an rvalue of type 'const wchar_t *'
    str.resize(toWCharArray(str.data()));
                            ^~~~~~~~~~
../../qt/qt/include/QtCore/qstring.h:1153:43: note: passing argument to parameter 'array' here
inline int QString::toWCharArray(wchar_t *array) const
```

The compiler used is clang-11:
```
Debian clang version 11.1.0-++20210204123133+1fdec59bffc1-1~exp1~20210203233800.162
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bakulf** [comment]
@abpostelnicu, thanks for this bug report. Can you share more logs? I would like to know the QT version you are using.

**Comment by abpostelnicu** [comment]
I’m using qt-everywhere-src-5.15.1.tar.xz
I want to be able to build it in order to run some static analysis on the build.

**Comment by abpostelnicu** [comment]
I'm using the reference READ.me file as guidance.

**Comment by abpostelnicu** [comment]
I've fired up another VM, this time an ubuntu-20.04 and I'm following step by step what I see in this [yml](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/.github/workflows/linux.yaml#L13), let's see how it does.

**Comment by abpostelnicu** [comment]
Using ubuntu-20.04 works and following the guide from the yml file, @bakulf I think we should update the README in order to be more friendly with other linux distributions and the steps that need to be performed to have a sane build.

**Comment by oskirby** [comment]
I think the problem is due to the version of `libstdc++6` that ships with Debian 9 (version 6.3.0), which has incomplete support for C++17. We can work around it by dropping down to C+14 in `src/src.pro` by changing `CONFIG += c++1z` to `CONFIG += c++14`

**Comment by abpostelnicu** [comment]
@oskirby I did a PR on this matter.
