### ISSUE TITLE
Drop support for iOS 13 (QT 6.6 does not support iOS 13) 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#9553]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-6385)
┆Reporter: Lesley Norton

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Naomi Kirby The changes to the SUMO articles (https://bugzilla.mozilla.org/show_bug.cgi?id=1892746 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1892746|smart-link ) ) and to SubPlat pages (https://mozilla-hub.atlassian.net/browse/VPN-6331 ( https://mozilla-hub.atlassian.net/browse/VPN-6331|smart-link )) are already done. We are missing changing the VPN Downloads page, but that should happen hopefully soon (https://mozilla-hub.atlassian.net/browse/VPN-6337 ( https://mozilla-hub.atlassian.net/browse/VPN-6337|smart-link )).

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Santiago Andrigo Will these changes happen together with the 2.23 release?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Yes, this is because QT 6.6 is shipping in 2.23 → https://mozilla-hub.atlassian.net/browse/VPN-6369 ( https://mozilla-hub.atlassian.net/browse/VPN-6369|smart-link )

**Comment by data-sync-user** [comment]
➤ Lesley Norton commented:

This ticket was fulfilled by VPN-6453

**Comment by oskirby** [comment]
Closed by #9656
