### ISSUE TITLE
Android: IAP Support

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#961]
Might be become mandatory

https://support.google.com/googleplay/android-developer/answer/9858738

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-173)

**Comment by birdsarah** [comment]
Mandatory for Sep 30, 2021 - so probably v2.5.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

This has been reopened by Data Sync but the Github ticket is still closed, as of 08/25 . Changing it back to Done.

Thank you.
