### ISSUE TITLE
UI displays disproportionate to screen size

### ISSUE THREAD

**Issue by jr-johnson-support** [mozilla-mobile/mozilla-vpn-client#964]
After updating to version 2.1.0 users are reporting VPN app is UI is disproportionate in size, making it much bigger, making it almost unusable, and cannot adjust the app size. 

<img width="960" alt="Mozilla_VPN_at_150_scale" src="https://user-images.githubusercontent.com/58608126/117067609-dd022a80-acef-11eb-8ced-f2c10d3862e7.png">
<img width="960" alt="Mozilla_VPN_at_125_scale" src="https://user-images.githubusercontent.com/58608126/117067614-decbee00-acef-11eb-8c5c-6d0df5cd60f3.png">
[mozillavpn-2021-5-3.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/6423836/mozillavpn-2021-5-3.txt)

**Comment by bakulf** [comment]
This should be fixed already. @lesleyjanenorton can you confirm?

**Comment by lesleyjanenorton** [comment]
Fixed as of #954
