### ISSUE TITLE
Square VPN logo in menu bar for Linux

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/mozilla-vpn-client#967]
#### Affected version:
* 2.2.0 (2.202104281453);

#### Affected Platforms:
* Linux Ubuntu 20.04;

#### Prerequisites:
* Have one FxA account without subscription;

#### Steps to reproduce:
1. Open VPN app;
1. See the VPN icon from the menu bar on the left corner;

#### Expected result:
* VPN logo has no UI issues;

#### Actual result:
* VPN logo has edges.
![Screenshot 2021-05-05 11 03 07](https://user-images.githubusercontent.com/15685960/117112335-96650c80-ad91-11eb-81a0-dfb753222b6b.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-177)

**Comment by ValentinaPC** [comment]
What is the status of this, for 2.4? Thanks!

**Comment by jswinarton** [comment]
Hey @ValentinaPC, could you please clarify what the desired result of this fix is? At the moment the logo in the dock and the logo in the menu bar both have a black background with rounded corners. Is the idea that the black background should be gone and only the white logomark itself remain? And to clarify, we only want this change made to the menu bar logo?

![screen1](https://user-images.githubusercontent.com/1616117/129625368-ae3bf9ef-ac2a-4949-8c12-24aa6dd2ce1a.png)
![screen2](https://user-images.githubusercontent.com/1616117/129625372-39b0be9a-a29b-4662-aaf7-739f60587cd2.png)

**Comment by jswinarton** [comment]
Hey, I think I've figured out what's going on here. The [GNOME User Interface Guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html#symbolic-app-icons) allows for the creation of a "Symbolic Icon" which is a monochrome SVG, independent from the standard icon set. If it exists, it's rendered out in places like menu and task bars and also responds programmatically to accessibility features like high-contrast themes, etc. Below is what the Firefox app looks like the the GNOME taskbar and the corresponding icon. I think this is what we want.

cc @lesleyjanenorton 

![screen](https://user-images.githubusercontent.com/1616117/129734143-f007e697-5a7d-4c31-aa67-922d7de69801.png)
![screen](https://user-images.githubusercontent.com/1616117/129734211-d5c711d6-2878-4512-b173-d1afb89344d2.png)

**Comment by ValentinaPC** [comment]
@jswinarton yes, that is the thing that happens, probably.
![image](https://user-images.githubusercontent.com/15685960/129901804-9e70852b-22fe-4821-9119-f0143d08fbb9.png)

**Comment by ValentinaPC** [comment]
Verified this using VPN 2.5 (2.202108191036) and the monochrome icon looks ok, but the one from activities has UI issues now.
![icon](https://user-images.githubusercontent.com/15685960/130209681-4c168294-c730-4265-bb01-e6c338b9f79d.png)

**Comment by ValentinaPC** [comment]
Verified this on the last VPN build 2.5.0. (2.202109011948)
The VPN app icon, when VPN is opened and shown, has a very small logo pixelation. Same as in above screenshot.
The icon for which this issue was logged is fixed. We can close this.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Closing this as Valentina reported it was fixed, on the 2nd of September (see above comment).

Thank you.
