### ISSUE TITLE
 SystemTray icon should be visible in Dark Mode on Linux 

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#97]
On Linux, we need a better systray icon or a way to detect which icon should be used:

![](https://user-images.githubusercontent.com/1796208/96359390-19659480-10d8-11eb-9d82-a9c3bba6576c.png)

See #83

**Comment by jess-cook03** [comment]
@bakulf @lesleyjanenorton @birdsarah 
Hi folks! I found the specs for the [Linux app icons](https://www.figma.com/file/COmhUpSznZjUlBiB5OJCJS/Dock-Icons?node-id=0%3A1) -- this should resolve the issue -- treating the icons similarly to Mac as well 👍 

Let me know if this works!

**Comment by ValentinaPC** [comment]
Verified as fixed on Linux Ubuntu 20.04, while using the VPN cross-plat build v. 2.202011301350.
The VPN SystemTray icon is visible.
![systray](https://user-images.githubusercontent.com/15685960/100874957-ffc4b480-34ad-11eb-81b7-fc54e6e35265.png)
