### ISSUE TITLE
Warning: qrc:/ui/components/VPNButtonBase.qml:47: ReferenceError: vpnFlickable is not defined (VPNButtonBase.qml:47)

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#975]
[06.05.2021 08:40:37.352] Warning: qrc:/ui/components/VPNButtonBase.qml:47: ReferenceError: vpnFlickable is not defined (VPNButtonBase.qml:47)

**Comment by lesleyjanenorton** [comment]
closed via #980

**Comment by ValentinaPC** [comment]
@lesleyjanenorton Is there a way for QA to verify this? Thanks!

**Comment by lesleyjanenorton** [comment]
@ValentinaPC No, this isn't a user-facing error so there really isn't a way for QA to verify. Thank you for checking in on this though!
