### ISSUE TITLE
Android: AAB Bundle Pipeline

### ISSUE THREAD

**Issue by strseb** [mozilla-mobile/mozilla-vpn-client#978]
... i know we had that. Just opening a bug here as it will become mandatory.
from Google play: 
>From August 2021, new apps will be required to publish with the Android App Bundle on Google Play. .

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-179)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Can we close this?
