### ISSUE TITLE
Replace balrog cert verification code with Rust crate

### ISSUE THREAD

**Issue by birdsarah** [mozilla-mobile/mozilla-vpn-client#984]
Mozilla is updating nss to have an api for cert verification ([https://bugzilla.mozilla.org/show_bug.cgi?id=1709291](https://bugzilla.mozilla.org/show_bug.cgi?id=1709291) ).

There's a rust crate, rc-crypto, that mozilla maintains, that wraps nss which is probably the easiest thing to use to embed this new code.

We should also use a mozilla standardized cert verification library so that we're all using the same code as much as possible,

Bugs that probably track our blocked path:

* [https://bugzilla.mozilla.org/show_bug.cgi?id=1709291](https://bugzilla.mozilla.org/show_bug.cgi?id=1709291) 
* [https://github.com/mozilla/application-services/issues/3766](https://github.com/mozilla/application-services/issues/3766)

cc @leplatrem (feel free to correct this where I've got it wrong).

The opportunity here is to get rid of go code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-181)
┆Reporter: Data Sync

**Comment by birdsarah** [comment]
nss implementation is in - https://bugzilla.mozilla.org/show_bug.cgi?id=1709291

**Comment by leplatrem** [comment]
The signature verification on top of NSS/rc_crypto [was released at last](https://github.com/mozilla/application-services/releases/tag/v82.0.0)!

In order to use it, you'll have to follow these steps roughly:

* Compile NSS (I use [this hack](https://github.com/mozilla-services/remote-settings-client/blob/b819c041076f2cbd6e49ba37a51c70c509d727ac/.circleci/config.yml#L22-L47), but there are other ways)
* Indicate NSS folder in environment variable:
```
export NSS_DIR=$(pwd)/libs/desktop/linux-x86-64/nss
export NSS_STATIC=1
```
* Add `rc_crypto` to `Cargo.toml`:
``` 
rc_crypto = { git = "https://github.com/mozilla/application-services", rev = "v82.0.0"
``` 
* Enjoy :)
```rust
use rc_crypto::{contentsignature, ErrorKind as RcErrorKind};
use std::time::{SystemTime, UNIX_EPOCH};

let epoch_seconds = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap() // Time won't go backwards.
        .as_secs();
// hash of cert chain root
let root_hash: &str = "3C:01:44:6A:BE:90:36:CE:A9:A0:9A:CA:A3:A5:20:AC:62:8F:20:A7:AE:32:CE:86:1C:B2:EF:B7:0F:A0:C7:45";
// message with prefix 
let message: &[u8] =
        b"Content-Signature:\x00{\"data\":[],\"last_modified\":\"1603992731957\"}";
// base64 signature obtained from Autograph
let signature: &[u8] = b"fJJcOpwdnkjEWFeHXfdOJN6GaGLuDTPGzQOxA2jn6ldIleIk6KqMhZcy2GZv2uYiGwl6DERWwpaoUfQFLyCAOcVjck1qlaaEFZGY1BQba9p99xEc9FNQ3YPPfvSSZqsw";
// Autograph signer name
let subject_cn: &str = "remote-settings.content-signature.mozilla.org";

contentsignature::verify(
    &message,
    &signature,
    &pem_bytes,
    epoch_seconds,
    &root_hash,
    &subject_cn,
)?;
```

**Comment by birdsarah** [comment]
@leplatrem does the crate bundle NSS or do we need to link it / bundle it with VPN?

**Comment by leplatrem** [comment]
With the current setup, you'd have to bundle it.

I'm not sure how it would be possible to publish a compiled crate with NSS statically linked. Maybe there is a way!

**Comment by birdsarah** [comment]
This is no longer blocked we have the pieces of the puzzle from other teams it just needs to get put on the roadmap.

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

During development of this feature, it became clear that the rc_crypto crate wasn’t really fit for the task due to its dependency on NSS for the cryptographic components which would have been an extremely large task to integrate with the VPN project. Instead I felt it would be more fruitful to make use of the x509-parser ( https://docs.rs/x509-parser/latest/x509_parser/ ) crate.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Naomi Kirby Could you please add some testing instructions for this fix? Thank you!

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Copy-pasting the instructions from slack:

“naomi  3 days ago ( https://mozilla.slack.com/archives/C01DCUKG95E/p1697222197781399?thread_ts=1697046500.073039&cid=C01DCUKG95E )
I merged the PR last night into main, and it seems like balrog stage has been reactivated, so this should be testable now on stage by using the force_update_check inspector command. I think this is how you currently test the update mechanism, but if not....

Install a recent build of the main branch onto an M1/M2 Mac

  * any build after commit 3206e02e69e43eb0c556a8ca0335ca0d558fe5ab on October 12th should do.
  * Run force_update_check 2.14.0 via the inspector.
  * The app should not crash, there should be no scary certificate warnings in the logs.
  * Navigate to the About Us page and click Check for Updates
  * A screen should display informing the user that an update is available.
  * Click on the Update button and wait
  * A copy of the VPN installer for MacOS should download in the background and launch within a few minutes.”

**Comment by data-sync-user** [comment]
➤ Naomi Kirby commented:

Hey Valentina Virlics 

Past

I think your test procedure for the past update flow is fine, and you should continue to use that in the future once we are clear of this balrog crash. But as long as one of the builds being tested includes the crash (2.16 on an M1) we will need a different procedure.

Present

I believe the steps you have listed here are correct. We still expect 2.16 to crash on stage for the time being as we have not taken steps to specifically exclude 2.16 from receiving update data on staging (yet).

Understanding

Our plan for prod users on 2.16 is that we will serve them a message through the messaging centre informing them of the new release (2.18, once we release it), but the check for updates button will never do anything.
