### ISSUE TITLE
Surveys per platform

### ISSUE THREAD

**Issue by bakulf** [mozilla-mobile/mozilla-vpn-client#988]
Currently, the app fetches a list of the surveys from the guardian website REST API. We should extend the REST API to expose the list of platforms for each survey. In this way, we can have surveys for IOS, for Android and so on.

The API is this: `/api/v1/vpn/surveys` and the response is:

```
[{
  "id":"unique_id"
  "url":"http://vpn.mozilla.org",
  "trigger_time":4
  },{
  "id":"unique_id2",
  "url":"http://vpn.mozilla.org",
  "trigger_time":10
}]
```

I would suggest to add a `platforms` attribute for each survey object. The value can be an array with the list of platform for that survey. Something like:

```
[{
  "id":"unique_id"
  "url":"http://vpn.mozilla.org",
  "trigger_time":4
  // This is for each platform.
  },{
  "id":"unique_id2",
  "url":"http://vpn.mozilla.org",
  "trigger_time":10
 "platforms": [ "windows", "ios" ],
}]
```

**Comment by ValentinaPC** [comment]
Is there a way for QA to verify this? Thanks!
