### ISSUE TITLE
[Android][iOS] Locale fallback issue: zh-CN is displayed when OS is in zh-TW

### ISSUE THREAD

**Issue by petercpg** [mozilla-mobile/mozilla-vpn-client#9899]
**Describe the bug**
The app launches in zh-CN in a zh-TW device on fresh install. Probably a locale fallback issue?

**VPN version:**
* Android: 2.25.0 (2.202409190619)
* iOS: 2.23.0 (2.202406241838)

**Affected Platforms:**
* Android: Google Pixel 6 Pro / Android 14
* iOS: Apple iPhone 7 / iOS 15.8.3

**Prerequisites:**
None.

**Steps to reproduce:**
1. Set OS to Traditional Chinese (zh-TW)
2. Clean install VPN app and launch
3. Observe UI messages

--- OR ---

1. Set OS to Traditional Chinese (zh-TW)
2. Set VPN locale to match OS system language
3. Observe UI messages

**Expected result:**
UI should display in Traditional Chinese (zh-TW)

**Actual result:**
UI displays in Simplified Chinese

**Additional notes:**
[MozillaVPN_Logs_2024-58-23-16-58-48.txt](https://github.com/user-attachments/files/17099229/MozillaVPN_Logs_2024-58-23-16-58-48.txt)

This will be a blocker if the App is going to launch in Taiwan / Hong Kong market.

**Comment by flodolo** [comment]
Looks like this was fixed a couple of weeks ago but the ticket wasn't updated
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9933

Are you still seeing the issue in a recent nightly?

**Comment by petercpg** [comment]
I can confirm that the issue is not reproducible anymore on 2.25.0 (2.202410150633) on Android. I'm not sure how to test nightly on iOS, do we use TestFlight or so?

**Comment by flodolo** [comment]
@mcleinman
Can you confirm if this was tested by QA on iOS and we can close it?

**Comment by mcleinman** [comment]
Apologies for not closing the ticket here on GitHub earlier. @petercpg - A deep thank you for bringing this to our attention.

Yes, this was tested by QA on both iOS and Android. There is no public iOS TestFlight build unfortunately.
