### ISSUE TITLE
Android: Missing applications on app permissions page

### ISSUE THREAD

**Issue by Domilopment** [mozilla-mobile/mozilla-vpn-client#994]
On some devices, there are preinstalled applications that normally are installed by users.

For example, the Galaxy S21 (SM-G991B/DS) with preinstalled Netflix and OneDrive.

These applications are not listed in the app permissions page, cause there are classified as "system apps" and so the user can't add them to unprotected.

Possible solutions could be:
<ul>
<li>Add apps to whitelist</li>
<li>Include "updated system apps" in list</li>
<li>Let user choose what app types to show in list</li>
<li>Add apps manually to list from "system apps"</li>
</ul>

**Comment by ValentinaPC** [comment]
Was this fixed with the implementation of "+Add application" button? Thanks!

**Comment by strseb** [comment]
Hi! No, the "+Add button " is not yet coming to android as we need supporting qml ui here, which does not exist. We're now more permissive with filtering which apps we show, e.g once they had an update or can have an icon on the homescreen we put them there :)

**Comment by ValentinaPC** [comment]
Verified as fixed on the last VPN 2.4 (16269380) version on Android 10.
Once an app is installed, it gets automatically added to the App Permissions list.
